### ISSUE TITLE
Name collision issue/question

### ISSUE THREAD

**Issue by Linwood-F** [yadayada/acd_cli#100]
I'm uploading images in a loop, and because of performance issues I am doing them in batches anywhere from a few to thousands.  Because I am not doing one file at a time, and might not know if I had errors, I am doing the upload with overwrite, specifically the command is:

/usr/local/bin/acd_cli upload --max-connections=3 --overwrite folder1 folder2

I then check for an error (just a $? check) after it runs, and if zero I remove the files in preparation for the next round.

This generally works, but occasionally I see this error: 

```
Processing /home/ferguson/ToUpload/stage_2015-07-27
15-07-28 13:34:15.097 [WARNING] [acd_cli] - Folder "2015-07-27" already exists.
15-07-28 13:34:15.857 [ERROR] [acd_cli] - Uploading "2015-07-27-23-15-00-420165_Garage_Periodic.jpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-07-28 13:34:16.739 [ERROR] [acd_cli] - Uploading "2015-07-27-23-20-00-171146_Southside_Periodic.jpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-07-28 13:34:19.507 [ERROR] [acd_cli] - Uploading "2015-07-27-23-20-00-300907_Lanai_Periodic.jpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
[#################################] 100.0% of   10MiB  62/62  463.8KB/s
3 file(s) failed.
```

Note that the warning on already exists is intended -- I can't find a way to tell if a folder already exists (in script) so I just create it and let it fail if present.

Despite the failed message, I do not seem to be getting a non-zero error response.  I say "seem" as I am still a bit bash-weak, but the test is immediately following and it is being treated as zero.

Should this error cause a failure?

Perhaps more to the point -- what does this failure mean?   is it really an overwrite (and if so why not just overwrite)?  Should it return a failure status? 

A sync was done at the beginning of the run by the way.

**Comment by yadayada** [comment]
I'm not yet sure why the CACHE_ASYNC flag doesn't get returned.
Do these errors occur after database locked errors (https://github.com/yadayada/acd_cli/issues/99)?

PS: you can check a folder's existence using ``acdcli ls /mydir | wc -l``. A non-existing folder will return 0 lines and an existing one >=1.

**Comment by Linwood-F** [comment]
No, I have never received any database locked errors.  I left this running over night and this error did not recur -- I've seen it now 3-4 times, but I cannot figure out a cause.

Thanks for the command to test folder existence.

I'll leave this running and see if I can pin down the circumstances.

**Comment by Linwood-F** [comment]
I've been running this for several days in a loop, and it has happened only one more time.

[ERROR] [acd_cli] - Uploading "2015-07-31-01-05-00-238375_NorthFront_Periodic.jpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.

It gave that error, then as soon as it was run again (the loop does not sync) it worked fine.  More importantly the actual error did not seem to return an error code to bash.

The file was uploaded.  The file was not in the cache (I did an ls, it was absent, did a synch and it was present).  I am about 99% sure there is no path through the code that could have previously uploaded it, I think this error appeared in the same upload command that uploaded it.

But it is clearly infrequent.

**Comment by yadayada** [comment]
I forgot to tell you initially that the sync action may not give all current data.

**Comment by keithah** [comment]
So I am having this same issue, but it doesn't correct itself upon restart, it displays the same issues.

Here's a snippet:
```
15-11-08 04:57:29.417 [ERROR] [acd_cli] - Uploading "Justified.S06E06.Alive Day.SD.TV-thumb.jpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-11-08 04:57:40.553 [ERROR] [acd_cli] - Uploading "Justified.S06E06.Alive Day.SD.TV.mp4" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-11-08 04:57:43.770 [ERROR] [acd_cli] - Uploading "Justified.S06E06.Alive Day.SD.TV.nfo" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-11-08 04:57:46.160 [ERROR] [acd_cli] - Uploading "Justified.S06E06.Alive Day.SD.TV.tbn" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-11-08 04:57:46.193 [WARNING] [acdcli.api.backoff_req] - Waiting 13.119336s because of error(s).
15-11-08 04:57:59.762 [ERROR] [acd_cli] - Uploading "Justified.S06E07.The Hunt.SD.TV-thumb.jpg" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-11-08 04:57:59.776 [WARNING] [acdcli.api.backoff_req] - Waiting 7.985797s because of error(s).
15-11-08 04:58:20.816 [ERROR] [acd_cli] - Uploading "Justified.S06E07.The Hunt.SD.TV.mp4" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-11-08 04:58:20.826 [WARNING] [acdcli.api.backoff_req] - Waiting 14.699991s because of error(s).
15-11-08 04:58:36.038 [ERROR] [acd_cli] - Uploading "Justified.S06E07.The Hunt.SD.TV.nfo" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-11-08 04:58:36.047 [WARNING] [acdcli.api.backoff_req] - Waiting 101.448131s because of error(s).
15-11-08 05:00:18.160 [ERROR] [acd_cli] - Uploading "Justified.S06E07.The Hunt.SD.TV.tbn" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-11-08 05:00:18.277 [WARNING] [acdcli.api.backoff_req] - Waiting 57.400117s because of error(s).
```

This happens with quite a few files, any more info I provide?

**Comment by yadayada** [comment]
Did you sync before restarting?

**Comment by keithah** [comment]
Yes, I sync before running upload every time.

Here's the log: https://www.dropbox.com/s/sfvlt1x9nao3pc6/acd_cli.log.gz?dl=0

**Comment by Rufflewind** [comment]
> I'm not yet sure why the CACHE_ASYNC flag doesn't get returned.

Using exit codes higher than 255 is unportable.  For example, on Linux it doesn't work at all:

    $ python
    >>> import subprocess
    >>> subprocess.run(["python", "-c", "exit(0xffff)"]).returncode
    255

Notice that `0xffff` (65535) got truncated to `0xff` (255).
