### ISSUE TITLE
Problems understanding if I'm doing first sync correctly...

### ISSUE THREAD

**Issue by keithb119** [yadayada/acd_cli#103]
Hi, 

I'm afraid I'm slightly confused at sadly quite a basic level with the installation instructions.  What is more worrying is that no-one else seems to be. :-( 

I'm using a Raspberry Pi and installed acd_cli using:

sudo pip-3.2 install --upgrade git+https://github.com/yadayada/acd_cli.git

after first installing:

sudo apt-get install python3-pip

I am uncertain from your instructions as to whether the initial setup (initial run of acd_cli sync) can be done from the command line or whether it is necessary to do this from X-windows?  Your references to a browser tab makes it sound as though it should be within X?  I also find it unclear if the file oauth_data is created automatically, or whether a copy-and-paste operation is necessary?

Ideally, I want to be able to do this entirely from the command line.

When I perform the command:

acd_cli sync 

Lynx (I thought) is invoked.  I enter my Amazon u/n and password and select 'Sign in using out secure server'.

I then select 'Okay'.

I am then presented with the JSON '{ "access_token": ' etc string on the display (at the top), with a highlighted OK 'button' at the bottom left and flashing cursor to the bottom right.  Nothing further happens.  The OK button is unreachable.  The only thing I am able to do is type 'Q' which asks me if I want to exit 'Link's.  Interestingly, it is not colour-coded like Lynx (proper).  If I type www-browser, which is what appears to be the command/utility it is using according to 'ps x', this also refers to 'Links', so I guess that is what is being used.  If I choose 'Yes', the following is displayed:

A browser tab will have/be opened at https://tensioe-runway-92512.appspot.com/.
Please accept the request and save the response data into a file called "oauth_data" in the directory "/home/pi/.cache/acd_cli".
Then press a key to continue.

Again nothing further happens. Pressing a key results in an error saying File "oauth_data" not found.

If I run this from an SSL session from PC and copy-and-paste the JSON '{ "access_token": ' etc string into .cache/acd_cli/oauth_data using nano it gives different errors.

So, my first question is: is this supposed to work entirely from the command line?  Secondly, is it supposed to create and populate the oauth_data and client_data files in .cache or am I supposed to copy-and-paste anything?  Currently, no files have been created.

Before starting this I had already uploaded a large number of photos (14,500) via the Windows interface.  Should I expect to wait on the page with the JSON text for some considerable time?  I tried leaving it for at least 12 hours, but no joy.  One would expect that if that were the case it would create the oauth_data file immediately, but as I say no file is created.

Regards,
Keith

**Comment by Linwood-F** [comment]
This confused me as well, I'll give you the simple way.  Take your favorite web browser on any computer (doesn't have to be the Pi).  GO to https://tensile-runway-92512.appspot.com/

Do the login there it downloads an oauth file.

Copy it here: ~/.cache/acd_cli/oauth_data       on the Pi (set protections as appropriate).

I tried it once with the text based browser that pops up if you do it on the terminal interface, not fun, but I think possible.  But it's easy with a regular browser.

**Comment by hongkongkiwi** [comment]
Although using Lynx is a bit broken, I found using w3m was just fine for
terminal.

Getting the file using a desktop browser is much much easier though.

**Comment by keithb119** [comment]
Ah!  Excellent!  Thank you both so much, especially Linwood-F.  I went the desktop browser route in the end - as you say, much easier.  It appears to be working now.  The problem with Lynx and www-browser is that they don't do an automatic file download.
