### ISSUE TITLE
Upload reporting errors after each file uploaded...

### ISSUE THREAD

**Issue by keithb119** [yadayada/acd_cli#104]
Hi,

This is my first attempt at an upload.  I installed acd_cli on a Raspberry Pi yesterday using:

sudo pip-3.2 install --upgrade git+https://github.com/yadayada/acd_cli.git

I'm getting the following errors, although it did upload some files and create all the directories.  It reports that I'm trying to upload 24GiB and 12289 files.  Apologies for the formatting, it took a slightly convoluted route:

It appears, although I am by no means certain, that the error is being generated after the upload of each file since the number of files uploaded count is incrementing.  However, it then states it is waiting for approximately 60 / 16 / 148 (148.019707) / 244 seconds because of errors!

15-08-03 04:26:20.760 [ERROR] [acd_cli] - Traceback (most recent call last)7h:   
File "/usr/lib/python3.2/http/client.py", line 780, in send                      self.sock.sendall(data)                                                      File "/usr/lib/python3.2/ssl.py", line 368, in sendall                           amount = len(data)                                                         TypeError: object of type 'MultipartEncoder' has no len()                                                                                                     During handling of the above exception, another exception occurred:                                                                                           Traceback (most recent call last):                                               
File "/usr/local/bin/acd_cli.py", line 169, in wrapped                           ret_val = f(*args, **kwargs)                                                 File "/usr/local/bin/acd_cli.py", line 294, in upload_file                       deduplication=dedup)                                                         File "/usr/local/lib/python3.2/dist-packages/acdcli/api/content.py", line 118, in upload_file                                                                   stream=True, headers={'Content-Type': m.content_type})                       File "/usr/local/lib/python3.2/dist-packages/acdcli/api/common.py", line 236, in post                                                                           return cls._request('POST', url, acc_codes, **kwargs)                        File "/usr/local/lib/python3.2/dist-packages/acdcli/api/common.py", line 139, in decorated                                                                      return func(*args, **kwargs)                                                 File "/usr/local/lib/python3.2/dist-packages/acdcli/api/common.py", line 222, in _request                                                                       r = cls.__session.request(type_, url, headers=headers, timeout=timeout, **kwargs)                                                                           File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 465, in request                                                                        resp = self.send(prep, **send_kwargs)                                        File "/usr/local/lib/python3.2/dist-packages/requests/sessions.py", line 573, in send                                                                           r = adapter.send(request, **kwargs)                                          File "/usr/local/lib/python3.2/dist-packages/requests/adapters.py", line 370, in send                                                                           timeout=timeout                                                              File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen                                                 body=body, headers=headers)                                                  File "/usr/local/lib/python3.2/dist-packages/requests/packages/urllib3/connectionpool.py", line 349, in _make_request                                           conn.request(method, url, **httplib_request_kw)                              File "/usr/lib/python3.2/http/client.py", line 970, in request                   self._send_request(method, url, body, headers)                               File "/usr/lib/python3.2/http/client.py", line 1008, in _send_request            self.endheaders(body)                                                        File "/usr/lib/python3.2/http/client.py", line 966, in endheaders                self._send_output(message_body)                                              File "/usr/lib/python3.2/http/client.py", line 815, in _send_output              self.send(message_body)                                                      File "/usr/lib/python3.2/http/client.py", line 787, in send                      "or an iterable, got %r" % type(data))                                     TypeError: data should be a bytes-like object or an iterable, got <class 'requests_toolbelt.multipart.encoder.MultipartEncoder'>   

Regards,
Keith

One point to note.  I originally removed the '7h' from the end of the Traceback line thinking it was an artifact of the copy-and-paste between devices, so I think I am correct putting back!  Another run has shown 4h, 1h or 6h.

**Comment by Linwood-F** [comment]
I know nothing about the error or internals, I just use this software, but I will offer the observation that is a LOT of files and size to be uploading in one go.  Just the vagaries of the internet/amazon/pi would seem to make it likely to hiccup somewhere during that large of a transfer, and you then do not have a really good way to restart.  You might want to consider scripting so you do it in smaller chunks.  It's definitely more efficient to do more than one file at a time, but it is not noticeably more efficient to do, say, 2000 than 1000.  Or if they are decent sizes maybe even 100 vs 200.

**Comment by yadayada** [comment]
Did you check in the Web interface that any files actually got uploaded?

What does
``python3 -c "import sys; print(sys.version_info[:3] in [(3, 2, 3), (3, 3, 0), (3, 3, 1)])"``
output?

**Comment by keithb119** [comment]
Hi yadayada,

python3 -c "import sys; print(sys.version_info[:3] in [(3, 2, 3), (3, 3, 0), (3, 3, 1)])"

Returns True

**Comment by keithb119** [comment]
Ah!  Known issues!  Is there an easy work-around?

I did check via the web interface and it is successfully uploading files despite the errors, although with added delays between each.  According to the Amazon Photo iOS app, it has uploaded 335 files so far, and they all appear normal/uncorrupted.  This has taken about 12 hours.

What I cannot be sure of is whether every file that should have been uploaded, has been uploaded, or whether any have been skipped.  It appears it is uploading every file successfully but I need to think of a an easy way of confirming that.

**Comment by yadayada** [comment]
Well, known issue, yes (https://github.com/yadayada/acd_cli/issues/61). The "work-around" is not using Python 3.2.3 or 3.3.0 or 3.3.1.

To check whether your files got uploaded, sync and use the ls action. Or use the Web interface https://www.amazon.com/clouddrive/.

**Comment by keithb119** [comment]
Hi Linwood-F,

You make a fair point.  At the time I didn't really have a directory with a small number of files to try and didn't want to reorganise things unnecessarily.  I had already, over the past couple of days, uploaded most of the smaller candidates via Windows.  This had already taken forever, and I needed to upload this larger/largest, set so I was keen to offload this to a Pi if possible to avoid the PC being tied up and running for several days straight.

I am not overly familiar with Python, but the errors didn't appear to me superficially to be what I might expect for blowing a boundary condition due to an excessive number of files.  However; you're right, I should have tried a smaller number to see if that made any difference.  

At the time I started this I was already very tired and it was very late, so I thought I'd just try anyway, figuring it would either work, or not.  Since I was needing to go to bed anyway, I didn't want to waste time on a smaller upload if it would work anyway.  In the end, it kind of simultaneously worked and didn't, and so I spent longer trying to diagnose or at least report the error to see if anyone had any advice/suggestions.  For a time I thought it was completely failing, but discovered that it was successfully uploading the files (apparently intact) to Amazon.  They all view normally via both the web interface and the iOS app.  So I have left it running for now.  With the additional 'waits' it may take some considerable time, and the errors are a little annoying in terms of screen-space, but it's better than tying up my PC for extended periods.

So some reason it is actually rather satisfying to watch the iOS app (for a time) and see each new file appear momentarily after being uploaded.

**Comment by yadayada** [comment]
I recommend you use your Windows machine and use multiple connections for the upload. It should also be possible to abort an upload process and continue later (using the same command as before) without any complications.

**Comment by keithb119** [comment]
Unfortunately, those were the versions I got with 'apt-get install python3-pip' and 'pip-3.2 install'.  However, I'm not so sure this is the issue after all, see below.

What are the recommended or working versions?  I installed pip-3.2 in the first place because pip wouldn't work.

By work-around I was wondering if there was a way of installing or overriding with working versions of the necessary dependencies and if you knew how on the Raspberry Pi?

Is the delay being implemented within the Python or is this just being reported back from Amazon?  Do you know if these look like errors being returned by Amazon and simply reported back or are they exceptions raised with Python or supporting modules locally?


Interestingly: python -c "import sys; print(sys.version_info[:3])" reports (2, 7, 3).  Which is the same on another Pi on which I installed Python some time ago.

python -c "import sys; print(sys.version_info[:3]) in [(2, 7, 3)]" returns True.

Tested individually:

python -c "import sys; print(sys.version_info[:3]) in [(2, 7, 3)]", 
python -c "import sys; print(sys.version_info[:3]) in [(2, 7, 3)]"
python -c "import sys; print(sys.version_info[:3]) in [(2, 7, 3)]"

all return False!

**Comment by keithb119** [comment]
Personally, a slightly crippled/imperfect acd_cli uploading from a Pi is vastly preferable than using a PC for this purpose.  As I say, it does appear to be working, albeit slowly and reporting (possibly false) errors.  Now up to 380 files.  Even with the issues it isn't necessarily that much slower than using a PC.

For the current upload session, started about 14 hours ago, I didn't specify the number of connections having previously specified 2.  This was because I wondered of this might be an issue.  

If I abort the current (acd_cli) run and restart, will it start again from scratch or pick up from where it left off?  Do you know what might be the optimum number of connections for a Raspberry Pi?

**Comment by keithb119** [comment]
Oops!  My mistake, I see what I did wrong now:

python3 -c "import sys; print(sys.version_info[:3])" 

Actually returns (3, 2, 3)

I was using 'python -c' etc!  Sorry.  I thought that was weird!

**Comment by keithb119** [comment]
Well it's still plodding away in the background successfully uploading the files to ACD.  1022 thus far.  I eventually used debug to repoint stderr and stdout to null so that the terminal session was usable.  

With my max 1mbps upstream speed, my current (very approximate) estimate is that it will take a further 18 days to complete!  It is still only on older lower-resolution photos, once it gets to more recent photos it will take even longer for each image.

So does anyone know if I abort and restart this and try a higher number of connections, whether it will resume from where it left off?  I wasn't sure whether yadayada's comment about restarting referred to the Amazon Windows upload app?

I am also keen to know if anyone has tried multiple connections on a Raspberry Pi and if they have found an optimum/max workable value?

**Comment by Linwood-F** [comment]
I can't answer your first question (I do smaller bunches for this reason), but as to the last part, it is probably more a function of the speed and latency in your internet connection than the Pi.  While not a heavy duty processor, I don't think it will be the limiting factor with those internet speeds.  My guess (emphasis on guess) is that more streams will help, HOWEVER, more streams will saturate your line more and make it harder to work yourself.  One possibility if you do it in chucks is schedule so you use more streams at night when you are alseep, etc.

At those speeds, finding a starbucks or some other site with fast internet might be a good alternative. :)

**Comment by keithb119** [comment]
It hardly seems to be using much bandwith or CPU so I don't think the Pi or internet connection are much of an issue.  One definite impact is the random (?) imposed wait of 30-300 seconds after each error.  When uploading via Windows it was using hardly any bandwidth either.  Windows seemed quicker but it clearly wasn't going full-pelt.  I suspect it may be throttled from the Amazon end.  Smaller uploads seemed to go much faster - larger uploads seemed to go much more slowly.  

I'm content to leave it slowly chugging away in the background - it will (hopefully) get there eventually - and it's not causing any inconvenience.  Although obviously it would be preferable to eliminate the errors (and associated wait), and if I knew for certain I could cancel it and it would restart from where it left off, I could experiment with different numbers of connections to see if that helped.

**Comment by Linwood-F** [comment]
It's not amazon throttling it, not at that rate; I get about 8 megabits of upload with the program, which is a bit less than half my upstream bandwidth.  Do the math, and if you aren't hitting somewhere near 50-70% of your upstream bandwidth (real bandwidth -- measure it somewhere first, like www.speakeasy.net/speedtest) then you are being somehow limited on your end most likely. Errors (using wifi?), latency, bad network tuning (most is automatic but doesn't mean it is good), competition on your link... all can affect it.  Maybe it is the pi.

My experience in lots of file transfer applications is that one stream is rarely the most efficient use of the link (OTOH if it's a shared link you might not want it saturated).

**Comment by yadayada** [comment]
It seems you are correct: files get uploaded despite the error messages.

The upload process should resume correctly (skip remotely existing files). The only thing you need to pay attention to is that a sync is necessary prior to resuming if errors occurred before.

**Comment by keithb119** [comment]
OK, thanks.

Does Python 3.4 (3.4.3) work correctly without errors?  What is the highest version below 3.2.3 that works?

**Comment by yadayada** [comment]
Yes, requests-toolbelt works with 3.4.2 and 3.4.3. I think it also works with 3.2.6 and 3.3.2+.

**Comment by keithb119** [comment]
Thanks.  Hmmm... It seems that currently the only way to install Python 3.4 (or even 3.2.6) on Rapbian/Debian Wheezy on the Pi is to build from source.

I guess building from source would be the way to go, especially since nothing else on that Pi relies upon Python3.

**Comment by yadayada** [comment]
The stable Debian release should include Python 3.4 as seen in http://archive.raspbian.org/raspbian/dists/stable/main/binary-armhf/Packages.xz.

**Comment by tomwitt2** [comment]
On 08/05/2015 02:04 PM, keithb119 wrote:
>
> Thanks. Hmmm... It seems that currently the only way to install Python 
> 3.4 (or even 3.2.6) on Rapbian/Debian Wheezy on the Pi is to build 
> from source.
>
> I guess building from source would be the way to go, especially since 
> nothing else on that Pi relies upon Python3.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/yadayada/acd_cli/issues/104#issuecomment-128093557>.
>
I'm also seeing this behaviour (upload reporting errors after multi-file 
upload but only at end, not during).  I'm on Kubuntu 14.04.2, Python 
3.4.0, acd_cli 0.3.0a1

**Comment by yadayada** [comment]
@tomwitt2 Please provide some error logs.

**Comment by keithb119** [comment]
> The stable Debian release should include Python 3.4 as seen in 
> http://archive.raspbian.org/raspbian/dists/stable/main/binary-armhf/Packages.xz.

Well, yes, kind of...

As I understand it, that is true for RPi model 2 which is using the next version of Raspbian (called something else not Wheezy).  The original Model B that I'm using is currently stuck with Python 3.2.3 in the repository.  Whilst it is possible to upgrade an original Model B to the next version of Raspbian, a number of people have reported issues with it concerning booting.

**Comment by yadayada** [comment]
I suggest to simply back up your SD card, upgrade Raspbian and see for yourself.

**Comment by yadayada** [comment]
I don't think I'll be able to do anything about this because it's an idiosyncratic behavior of a specific Python version.

**Comment by keithb119** [comment]
> - added startup python version check (#104)

What does that mean exactly?  Does it mean it will prevebt running unless an 'approved' version?

I stopped, sync'd and restarted the upload with -x 10.  This appears to be working very well.   The errors still occur, but it consistently appears that 8 files are being uploaded at any give time.  My assuption is that two are continually held waiting after an error leaving the other connections to do their thing.  It utilises around 60-70% CPU during the actually uploading phase.

I also tried -x 15, but this errored immiately.  Once the current upload completes, I shall try -x 12 to see if that is successful.

**Comment by keithb119** [comment]
Hmm...  -x 10 and -x 12 result in the same number of files open, namely 8.  So I'm not sure how number of connections relates to simultaneously open files, if at all.  Originally I thought it wouldn't and instead related to https streams until I noticed it was uploading multiple files simultaneously..  Maybe it is fixed at 8?  -x 12 didn't appear to provide any benefit over -x 10, if anything it seemed slower, although it is difficult to be certain and I was uploading a different set of files.

So far, for a Raspberry Pi, -x 10 seems optimum; but my tests have hardly been exhaustive.

**Comment by keithb119** [comment]
To answer my previous question:

+    if sys.version_info[:3] in [(3, 2, 3), (3, 3, 0), (3, 3, 1)]:
+        logger.warning('Your Python version is known to cause issues. Uploading might not work.')

**Comment by resipsa2917** [comment]
"-x 8" is hard-coded as the limit. so "-x 999" will mean "-x 8".

**Comment by keithb119** [comment]
Aha, so I should probably use -x 8, then.  :-)
