### ISSUE TITLE
Share support [create/list/delete]

### ISSUE THREAD

**Issue by PythonicNinja** [yadayada/acd_cli#108]
What about developing support of share functionality?

I have done some initial work but 
RequestError: 403, {"message":"Insufficient permissions granted for operation: listSharedNodes"}

We need to add new scope of app in 
OAUTH_ST1 = {'client_id': CLIENT_ID,
             'response_type': 'code',
             'scope': 'clouddrive:read clouddrive:write',
             REDIRECT_URI_KEY: None}

**Comment by yadayada** [comment]
This was already discussed in #39. Amazon considers sharing by external applications a security risk.

There is no known way to whitelist a security profile for sharing or purging. Requesting a non-whitelisted scope permission will not work. This means it will not be possible to do anything related to sharing.
