### ISSUE TITLE
inotify support

### ISSUE THREAD

**Issue by msh100** [yadayada/acd_cli#109]
Whenever the nodes change on Amazon Cloud Drive, it would be nice if acd_cli could utilise inotify.

I am not too sure if this is possible with FUSE, but who knows :smile:

**Comment by hongkongkiwi** [comment]
In theory this would only show up the changes when you do a node refresh right?

**Comment by msh100** [comment]
That would be fine in my opinion as the node refresh can be done on interval. The tasks which are triggered by an inotify event may be substantially more expensive to run on interval.

**Comment by yadayada** [comment]
Do you just need a cache synchronization or do you really need to trigger inotify events?

If you do need the events, that would necessitate a lot of database querying and altering the FUSE class. I am definitely not going to implement this.

**Comment by msh100** [comment]
I guess more precisely I'd like to know when the contents change - how ever that is achieved doesn't really matter

**Comment by hongkongkiwi** [comment]
An easy way to imement this is have the sync command get a list of changes
from last sync. Then you could have an extra command flag to run a script
to receive the list of changes. E.g. You could have a bash script receiving
the changes and process how you like.

So for example:
acd_cli sync --change-script "handle-changes.sh"

It could send something like this to the script
$1 node
$2 change_type

On Thursday, August 13, 2015, Marcus Stewart Hughes <
notifications@github.com> wrote:

> I guess more precisely I'd like to know when the contents change - how
> ever that is achieved doesn't really matter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yadayada/acd_cli/issues/109#issuecomment-130377737>.
>


-- 
Sent from Gmail Mobile

**Comment by yadayada** [comment]
I'm still not sure if I got what you meant. Can you give me an example of what you actually want to do with this?
