### ISSUE TITLE
Problem with sqlalchemy dependence

### ISSUE THREAD

**Issue by grostim** [yadayada/acd_cli#11]
uname -a
Linux OMV 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux

pip install sqlalchemy
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy in /usr/local/lib/python2.7/dist-packages

./acd_cli.py sync
Traceback (most recent call last):
  File "./acd_cli.py", line 11, in <module>
    from cache import sync, query, db
  File "/root/acd_cli/cache/sync.py", line 6, in <module>
    from sqlalchemy.exc import *
ImportError: No module named sqlalchemy.exc

**Comment by procmail** [comment]
Experienced the same. Solution was to use Python 3 instead of 2.

**Comment by yadayada** [comment]
@procmail Yup.
I think it's pip3 on Debian. If you want to use the official packages, you need
python3-dateutil python3-pycurl python3-requests python3-sqlalchemy
(I'm using Debian testing)
