### ISSUE TITLE
Install acd_cli

### ISSUE THREAD

**Issue by kelna** [yadayada/acd_cli#111]
I couldn't install acd_cli with the method described in readme.md. I got some sort of python error (cannot look up now), so I had to figure out how to resolve the problem. I have to admit that I have **absolutely no idea** what the following lines do or why they are needed, but they work.
`virtualenv` might need to be installed with `sudo apt-get install virtualenv`.
```
virtualenv -p /usr/bin/python3 py3env
source py3env/bin/activate
```
[(ref)](https://stackoverflow.com/questions/10763440/how-to-install-python3-version-of-package-via-pip-on-ubuntu)
Then I used the git repository to install from, as described in readme.md:
```
pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git
```

After this acd_cli is up and running. From now on follow the initial guide in readme.md.
After every reboot you need to restart acd_cli and remount ACD, so tell your computah:
```
source py3env/bin/activate
acd_cli mount /path/to/mount/point
```
You probably can do this in about a hundred ways automatically in boot-time, but I couldn't achieve this so far.
![d690cbb35e4b2d522bdda7e5c8322f0f1edbf0ddb778bd3f273b6dfe0743824a](https://cloud.githubusercontent.com/assets/10761790/9386437/c71398bc-475b-11e5-8261-8672c5d325f0.jpg)

I'm using Kubuntu 15.04 in case anyone is interested.

Sorry if this is not really an issue or not relevant but I thought, if I ran into this, others can, too.

**Comment by HazCod** [comment]
Shouldn't be necessary, but thanks for sharing!
I did;

```
git clone HTTPS://github.com/yadayada/acd_cli && cd acd_cli && sudo python3 setup.py install
```

**Comment by cpare** [comment]
HazCod - What distro are you on?

**Comment by HazCod** [comment]
I am running Ubuntu 14.04

**Comment by chrisidefix** [comment]
@kelna maybe you didn't have pip installed or more likely your system was not configured for `python 3.x`, but with `$PYTHONPATH` pointing to python 2.x directories. By sourcing that  `py3env/bin/activate` path you probably setup the correct `python 3.x` environment and thus it works for you now.

**Comment by yadayada** [comment]
Not sure exactly what to do with your information, since you can't provide the installation error message.
Anyway, I added a short hint for virtualenv to the setup guide.
