### ISSUE TITLE
Question about vmware and windows

### ISSUE THREAD

**Issue by Neodark7** [yadayada/acd_cli#114]
Hello, i have an windows dedi with an ubuntu VM using vmware workstation, and on it i've setup acd_cli + plex and everything works fine on your side... but apparently even if i allocate all the cores to the VM, plex cannot use all the cpu for transcoding correctly... So my question is, is there any way to mount the drive in an shared folder to access it directly with windows and then use plex on the "real" machine ?

i tried and it's not working, when you link an mounted shared folder and an mounted ACD it show an empty folder on windows...

any idea please :( ? <3

**Comment by yadayada** [comment]
Have you tried the `--alow-other` argument?

**Comment by Neodark7** [comment]
Hmm.. Like "acd_cli mount --allow-other /home/plex/amazon" ?

**Comment by Neodark7** [comment]
So I've tried "sudo acdcli mount --allow-other /mnt/hgfs/Amazon/TEST" which is the mount point for the shared folder but same thing, i can see my ACD files on the vm but the TEST folder on the dedi is empty...

**Comment by yadayada** [comment]
Ok, then. I was able to successfully mount a remote ACDFuse directory using sshfs. Try win-sshfs instead of a shared folder.

**Comment by Neodark7** [comment]
okay i'll try that now, thx for your help, do you think that'll work with plex ?

**Comment by msh100** [comment]
Why don't you run the mount single threaded and run Plex from Linux? Making a VM just for handling files seems a bit crazy to me.

**Comment by Neodark7** [comment]
Okay so i can access the files from windows with sshfs and read them in plex but even with that it seems plex don't want to use all the cpu, he stay at 30/40% and tell me that the server is not powerful enough ( with an "local" file everything works fine and it use all the cpu ) 

I've tried to mount single threaded too but acd_cli still use like 60/80% of the VM cpu.

I really don't know what to do...
It's not possible to use acd_cli directly on windows right ?
maybe acd_cli is not quick enough to deliver the file to the windows plex ?

**Comment by Neodark7** [comment]
For more informations i use for the test a 37mbps video ( 58m5s - 11GB )
And i have an Intel Xeon E3-1225V2 3.20ghz / 16GB ram / 100mbps connexion
And the VM have the 4 cores allocated with 2GB ram and all the connexion
Maybe it's an "disk speed" issue ?

**Comment by Neodark7** [comment]
ooh it """seems"""" to work for now when single threaded mounted... i close this for now

**Comment by Neodark7** [comment]
Ok finally VM + Plex + acd_cli seems to work great... there is just a big buffer/lag/cpu usage from plex and acd_cli when plex refresh the libraries but when everything is idle, the stream take 5/10sec to start and no buffer issue. i hope there is no other issue on that.
Thanks @yadayada and @msh100 :) for the help
