### ISSUE TITLE
Unable to create an encrypted acd_cli mount

### ISSUE THREAD

**Issue by seppi91** [yadayada/acd_cli#115]
I mounted the acd via 'acd_cli mount /mnt/.acd/'. After creation of the mount I encrypted the directory via encfs ('encfs /mnt/.acd/ /mnt/acd/').

If I now try to copy (cp) files from any directory to /mnt/acd (encrypted dir) i'm getting error messages:
cp: error writing ‘/mnt/acd/ubuntu-15.04-desktop-i386.iso’: Input/output error
cp: failed to extend ‘/mnt/acd/ubuntu-15.04-desktop-i386.iso’: Input/output error

Is there anything I'm missing or did wrong?

**Comment by HazCod** [comment]
Don't you have to copy files to /mnt/.acd ?

`encfs <output> <input>`

**Comment by seppi91** [comment]
@HazCod You're right, but I just wrote the wrong command in my post. I corrected the first post. Thanks for mentioning

**Comment by yadayada** [comment]
It looks like encfs needs non-sequential write access, which is not possible.

**Comment by HazCod** [comment]
Hmm. Any suggestions on what we could use as an alternative @yadayada ?
I might look at implementing this myself in acdcli.

**Comment by msh100** [comment]
It's object storage. You shouldn't expect this kind of functionality.

If you want to use encfs, what you could do is mount it to the local host filesystem and then run `acd_cli ul` with the files you have generated in the encrypted directory, or copy them to the acd_cli FUSE mointpoint. `encfs` ultimately just generates plain files anyway.

**Comment by seppi91** [comment]
@msh100 you are probably right. I've found a very detailed guide for this here https://amc.ovh/2015/08/14/mounting-uploading-amazon-cloud-drive-encrypted.html

**Comment by yadayada** [comment]
Encfs needs to encrypt full blocks at a size of 1024. You can use ``dd bs=1024 if=myfile of=/mnt/acd/myfile``, but I think that's not really an improvement.
https://github.com/vgough/encfs/issues/108

**Comment by ShapeShifter499** [comment]
I was able to make it work here just fine, you have to calculate the bytes. Encfs encrypts using a block size of 1024 by default BUT if you turn on all the extra features it adds bytes on to the end of the 1024 making it fail.

**Comment by HazCod** [comment]
@ShapeShifter499 care to share your command?

**Comment by ShapeShifter499** [comment]
I used the setup prompts and skipped all the extra features. Below is my encfs6.xml configuration.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="12">
<cfg class_id="0" tracking_level="0" version="20">
	<version>20100713</version>
	<creator>EncFS 1.8.1</creator>
	<cipherAlg class_id="1" tracking_level="0" version="0">
		<name>ssl/aes</name>
		<major>3</major>
		<minor>0</minor>
	</cipherAlg>
	<nameAlg>
		<name>nameio/block</name>
		<major>4</major>
		<minor>0</minor>
	</nameAlg>
	<keySize>256</keySize>
	<blockSize>1024</blockSize>
	<uniqueIV>0</uniqueIV>
	<chainedNameIV>1</chainedNameIV>
	<externalIVChaining>0</externalIVChaining>
	<blockMACBytes>0</blockMACBytes>
	<blockMACRandBytes>0</blockMACRandBytes>
	<allowHoles>0</allowHoles>
	<encodedKeySize>52</encodedKeySize>
	<encodedKeyData>
REMOVEDkeyPrivacy
        </encodedKeyData>
	<saltLen>20</saltLen>
	<saltData>
REMOVEDsaltPrivacy
	</saltData>
	<kdfIterations>83949</kdfIterations>
	<desiredKDFDuration>500</desiredKDFDuration>
</cfg>
</boost_serialization>

```

**Comment by ShapeShifter499** [comment]
So basically I mounted the same,   'acd_cli mount /mnt/.acd/'   then   'encfs /mnt/.acd/ /mnt/acd/', but I chose different options in the prompt which resulted in the above config.

**Comment by ShapeShifter499** [comment]
@yadayada is 1024 a hard requirement for all types of writes? I'm not a security expert but it seems like security may or may not be reduced if you have to limit features of encfs so it only writes/encrypts 1024 bytes at a time.

**Comment by yadayada** [comment]
I have added a footnote to the [FUSE doc](../tree/master/docs/FUSE.rst) about writes at random addresses.
