### ISSUE TITLE
Lost name updates using rsync

### ISSUE THREAD

**Issue by mattwood-okta** [yadayada/acd_cli#116]
Wondering if this is PEBKAC or a current issue. After mounting the remote ACD (did not use the -ro option), I can create paths and filenames but the content of the target files will not go beyond zero bytes. At first I thought this might be a conflict with rsync, so I tried 'cp -r' and got the same result:
```
[mwood@flux ~]$ cp -r testup local_mount/
cp: writing `local_mount/testup/02-06. The Haunting of Hill House - Disc02-Track06.mp3': Read-only file system
```
I can mount and browse the ACD tree and the other non-fuse acd_cli functions seem to work well.  I am using python 3.4.3, fuse libs/utils 2.8.3 (CentOS 6 pkgs), fusepy-2.0.2, and acd_cli 0.3.0a1. Any ideas for troubleshooting? thanks!

**Comment by cpare** [comment]
I am also getting this message on my first attempt to rsync - I can however do a "acd_cli upload -x 8 /source /destination" without issue. 

Linux 3.16.0-46-generic #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yadayada** [comment]
>acd_cli 0.3.0a1

And there is your problem. Please try again with a recent version (>=0.3.0a5).

@cpare Please mount with ``acdcli -d mount -fg -i0`` and provide log messages.

**Comment by cpare** [comment]
Updated my version as well and now I am able to mount and rsync fine - thanks!

**Comment by mattwood-okta** [comment]
ok done thx for the tip, yadayada. I upgraded via pip and the github path.  Now I don't get read/write issues but there seems to be sporadic and/or timeout issues with rsync finishing a file by moving the dot-version filename to the final version after the syncing.  In one folder test I did, with 4 files, 1 of the 4 was moved into the proper final filename but 3 remained as rsync intermediate files (with dot-names and the random suffix).  Gist link with debug and foreground output snippet of a file that didn't get renamed properly:  https://gist.github.com/mattwood-okta/bca798f41b4e6cd7c402#file-track21-log-txt

The reason I'm trying to get rsync to work is that the acdcli upload function works great but I'd like the ability to have a tree of directories where I can make changes on the source side and then send the changes only (i.e. an rsync-like operation) to ACD.

Perhaps this is an issue with the FUSE libraries on my system?  I can try from a more modern distro version like Debian 8 (?)

**Comment by cpare** [comment]
@mattwood-okta - I was also noticing this behavior after upgrading to the latest version, I thought it was due to the command-line options I was handing to rsync.  I noticed some suggestions to use a few options I had omitted, I will try those tonight and let you know if I see an improvement.

**Comment by yadayada** [comment]
I've also encountered this while using rsync. Not sure yet if it's the renaming that fails (despite the 200 status code) or the cache update is faulty or something else is amiss.

**Comment by mattwood-okta** [comment]
oh ok well however we can help test, let us know!  I'm a fan of acd_cli! :)  Should I rename the title of this issue?

**Comment by SimmonsTech** [comment]
Hi, where did you find the missing rsync options? I'm seeing this issue too (I think). Could the ideal rsync command be documented somewhere?

**Comment by cpare** [comment]
@HazCod suggested a few command line options in a prior thread, but I can't find it now - hopefully he sees this and adds his prior suggestions here.  Specifically I believe it had to do with sending chunks of data and file matching on size, not date (as the dates are not retained).

**Comment by HazCod** [comment]
@cpare; rsync --whole-file will not use deltas but transfer whole files

**Comment by 2marshall** [comment]
Are these timeouts I'm having related? I ran an acdcli upload -x 8 /local /acd

![image](https://cloud.githubusercontent.com/assets/13956848/9596398/1a1a7140-5029-11e5-9d7d-c3a4cb6dda6d.png)

**Comment by yadayada** [comment]
@2marshall Nope. You might want to try using fewer connections.

**Comment by yadayada** [comment]
Has anyone still got this problem?

**Comment by mattwood-okta** [comment]
Hi @yadayada I must say with the latest version (acd_cli 0.3.1, api 0.8.7) I don't see any more rsync timeouts. It's not exactly fast but this is AWS we're talking about :)

One thing that does occur is that repeated rsync invocations on the same tree of data seems to result in resending each file every time.  I assume this is some odd interaction between how rsync does its delta computations and some interaction with FUSE (?)  Manual checksums of files shows them to be the same.  I'll keep experimenting with rsync flags but as far as this bug is concerned, I think we can close it out.  thanks for all your work on acd_cli!
