### ISSUE TITLE
Cannot remove file in FUSE mount: file exists

### ISSUE THREAD

**Issue by HazCod** [yadayada/acd_cli#118]
Steps to reproduce:
--------------------------
`mkdir acd && acdcli mount acd`
`rm -rf acd/*`
`rm: cannot remove ‘acd/StableBit CloudDrive/CloudPart-57528dfc-0fa7-4aa7-a76e-89e5a0ac3171/57528dfc-0fa7-4aa7-a76e-89e5a0ac3171-chunk-1425’: File exists
rm: cannot remove ‘acd/StableBit CloudDrive/CloudPart-57528dfc-0fa7-4aa7-a76e-89e5a0ac3171/57528dfc-0fa7-4aa7-a76e-89e5a0ac3171-chunk-751’: File exists
rm: cannot remove ‘acd/StableBit CloudDrive/CloudPart-57528dfc-0fa7-4aa7-a76e-89e5a0ac3171/57528dfc-0fa7-4aa7-a76e-89e5a0ac3171-chunk-224’: File exists`

These were files created with Stablebit Clouddrive.

**Comment by yadayada** [comment]
This happens if a file is already trashed. May be a cache problem. 
If you do a full sync, the trashed files should disappear.

**Comment by HazCod** [comment]
Nope :/

```
hazcod@laptop:~/NoBackup/Source/infrared$ acdcli old-sync
Syncing...
Done.
hazcod@laptop:~/NoBackup/Source/infrared$ acdcli ls
[rpy0g9gsTueZvKHR_3EJyw] [A] StableBit CloudDrive/
[rvAEyGM8TLK9MYOh1VkBLQ] [A] .DS_Store
[0-bl7zEUQ3eV5r2AjjbvtQ] [A] .encfs6.xml
hazcod@laptop:~/NoBackup/Source/infrared$ acdcli sync
Syncing...
Done.
hazcod@laptop:~/NoBackup/Source/infrared$ acdcli clear-cache
hazcod@laptop:~/NoBackup/Source/infrared$ acdcli sync
Syncing...
Done.
hazcod@laptop:~/NoBackup/Source/infrared$ acdcli ls
[rpy0g9gsTueZvKHR_3EJyw] [A] StableBit CloudDrive/
[rvAEyGM8TLK9MYOh1VkBLQ] [A] .DS_Store
[0-bl7zEUQ3eV5r2AjjbvtQ] [A] .encfs6.xml
```
