### ISSUE TITLE
Cannot copy file to FUSE mount: bad address

### ISSUE THREAD

**Issue by HazCod** [yadayada/acd_cli#119]
It seems I am attracting these problems :)

```
hazcod@DG12:~$ acdcli sync
15-08-26 13:22:12.424 [WARNING] [acd_cli] - Your Python version is known to cause issues. Uploading might not work.
Syncing...
Done.
hazcod@DG12:~$ acdcli mount .cloud
15-08-26 13:22:18.230 [WARNING] [acd_cli] - Your Python version is known to cause issues. Uploading might not work.
hazcod@DG12:~$ encfs /home/hazcod/.cloud/ /home/hazcod/cloud/
EncFS Password: 
hazcod@DG12:~$ ls cloud/
hazcod@DG12:~$ ls .cloud/
hazcod@DG12:~$ cp big_buck_bunny_1080p_h264.mov cloud/bunny.mov
cp: cannot create regular file 'cloud/bunny.mov': Bad address
```

Edit: And now it worked after unmounting and re-mounting with `-d`.. what..

And say again it doesn't consume a lot of CPU; this was on a Xeon 1230v2!  

![cpu onsumption acd_cli on Xeon 1230v2](https://i.imgur.com/rbjecIM.png)

**Comment by yadayada** [comment]
Is this related to #115? If your regular CLI upload works and your unencrypted writes work, it may be.

The upload block queue isn't implemented very efficiently. Your CPU load may be high if your block size is small (512B) or when encfs has to write incomplete blocks, effectivly doubling the block count. I usually get a block size of 4K.

I get intermttend errors with encfs, too.

It would be helpful if you could reproduce this while in debug mode. It's not clear if cp fails when creating the empty file or uploading the content...

**Comment by yadayada** [comment]
I'm closing this for now. Please reopen if this reoccurs and you can provide a log.
