### ISSUE TITLE
Filea uploaded as 0 bytes

### ISSUE THREAD

**Issue by SimmonsTech** [yadayada/acd_cli#121]
Hi,
I'm seeing files uploaded through fuse as 0 bytes (they upload fine, I see hundreds of MB leave my system through the network). However, in both the web viewer and acd_cli they are appearing as 0 bytes long. I'm using the latest GIT version.
Any ideas?

**Comment by SimmonsTech** [comment]
Note: I have tried cp and rsync. It sometimes works...

**Comment by SimmonsTech** [comment]
Ah, RSync throws an error when it fails with the rename.
Rsync: Rename "blah.jpg.heiffhjw" to "blah.jpg": Remote I/O Error (121)

**Comment by cpare** [comment]
this is a known bug (#116)
https://github.com/yadayada/acd_cli/issues/116

**Comment by yadayada** [comment]
For the time being, I recommend using the `--inplace` argument for rsync.

**Comment by SimmonsTech** [comment]
For what it's worth, I now use the comand:
rsync -avvvh -st --inplace --size-only --whole-file SRC DST

Sometimes it fails, so I run again. Note, if a file is changed (but it';s size is not) then it will be missed (because of size-only) which stops checksums

**Comment by yadayada** [comment]
If there really was an existing file "blah.jpg", the Remote I/O error might have been an error trashing the existing file. Otherwise, there was an error renaming.

If you want me to investigate this, I need a debug log of a failed renaming operation.
