### ISSUE TITLE
Question - Synching Lots of data

### ISSUE THREAD

**Issue by cpare** [yadayada/acd_cli#122]
I have about 1TB that I would like to keep synchronized with ACD - Until the rsynch bug is addressed is there a way I can run ACD_CLI using native commands for a few hours each night to (slowly) upload the entire volume, or would I end up overwriting the same files each night?

For those wondering why I don't just start a copy and let it roll, the copy estimates are 30+ days, and while ACD is running its using so much bandwidth that streaming media and online gaming is impacted.

My end state solution will be to write a shell script that will run every 10 minutes to ping my ChromeCast and see if its up, if the ChromeCast isn't found the script will check to see if ACD_CLI is in memory, and kick off a new session - in the event the ChromeCast is found and ACD_CLI is in memory it will try to kill the process, and if the ChromeCast is found and ACD_CLI isn't found it will just exit.

**Comment by chrisidefix** [comment]
The easy answer is, yes, you can. Already uploaded files will not be uploaded and overwritten again. acd_cli keeps track of which files are in the cloud.

A few things to look out for:

1 - makes sure that your files are smaller than the 40 GB limit (if you have larger files you won't be able to upload them).

2 - if you also want to download changes from ACD (and on your local client add / change / delete files, etc), then things become a little difficult

3 - to just upload your files you can call:
`acd_cli sync`
`acd_cli upload -x 2 /path/to/local/folder /remote/parent/folder`
Please check the [README](https://github.com/yadayada/acd_cli/blob/master/README.rst) for more details on this.

Regarding the scripting:

From what I understand you want to basically interrupt the upload whenever ChromeCast is running and restart it when it is not found. That sounds pretty reasonable to me, but since I don't have/use ChromeCast I am not sure how you would really check if "ChromeCast is found". I assume it's always on the network and would always respond to a ping or do you manually switch it on/off?

I would probably schedule a `cron` job [Cron](http://www.unixgeeks.org/security/newbie/unix/cron-1.html) for your script (available on most unix systems, including OS X) and make the script handle running `acd_cli`. I would also store the process-id in a tmp file somewhere to avoid starting acd_cli multiple times.

**PSEUDO-CODE:**
```python
# check if acd_cli has already been started
path_to_tmp_process_id = '/path/to/tmp/process_id_file'
acd_cli_process_id = read_from_file(path_to_tmp_process_id)

IF (is_running(acd_cli_process_id)):
    # check if acd_cli is still allowed to be running, if not, kill it
    IF (is_running(ChomeCast)):
        kill(acd_cli_process_id)
    # in either case exit script here, since acd_cli won't need to be running
    return exit()

# now check if acd_cli is allowed to run and start it
IF (NOT is_running(ChomeCast)):
    acd_cli_process_id  = run(acd_cli)

# overwrite the process-id for acd_cli in a tmp file
write_to_file(acd_cli_process_id, path_to_tmp_process_id)

# exit the script
return exit()
```

**Comment by cpare** [comment]
thanks for the excellent response, this was a great push in the right direction, I now have a working sample I want to share here for others.  In my code I check for two devices "Chromecast" and "glasd0s".

    #!/bin/bash
    
    if (ping -c 3 Chromecast &> /dev/null)||(ping -c 3 glasd0s &> /dev/null) ; then
      echo "Devices are online"
      if ( pgrep acd_cli ) ; then
        echo " acd_cli is currently running"
        # Attempt to kill acd_cli
        ps -ef | grep acd_cli | awk '{print $2}' | xargs kill
      else
        echo "acd_cli is not currently running"
      fi
    else
      echo "Devices are all offline"
      # Check to see if acd_cli is already in memory
      if ( pgrep acd_cli ) ; then
        echo " acd_cli is currently running"
      else
        echo " acd_cli is not running, starting it now"
        sudo acd_cli sync
        sudo acd_cli upload -x 2 /media/cpare/NewData/ / 2> >(tee /home/cpare/acd.log >&2) &
      fi
    fi

**Comment by cpare** [comment]
hmmm, for some reason it works fine from the command line, but it's not working in cron, perhaps because there isn't a tty to send the % complete and other output to?

**Comment by SimmonsTech** [comment]
Would it be possible to rate limit the acd_cli upload? I know trickle could limit python.. but that would limit all python bandwidth. Perhaps a rate limiter could be added to acd_cli upload inside the python code?

**Comment by chrisidefix** [comment]
@cpare thanks for sharing - you could of course increase `acd_cli upload -x 2` to whatever you would like (in case you have many small files it could speed up the upload)

@SimmonsTech check out the discussion about rate limiting for `acd_cli` here: #55 
the short answer is, yes, this is possible, but unless you implement it, it doesn't look like it is going to happen ;)

The slightly longer answer is - in case you are really doing many python tasks in parallel that require the additional bandwidth - you could run acd_cli as a separate user and just limit the bandwidth for that specific user - problem solved :dart:

**Comment by Stapper** [comment]
I have following 2 scripts cronned. One starts AmazonTransfer at midnight the other stops it at noon.
AmazonTransfer(starts at midnight)
```bash
#!/bin/bash
#Variables
LOG="/home/stapper/log/AmazonTransfer"
MAIL="My@email.Internet,My@email.local"
Amazondir="/media/Data/DropBox/AmazonTransfer"
#Save pid
echo $$ > /tmp/AmazonTransfer.pid;
#Sync
/usr/local/bin/acd_cli sync> "$LOG/current.log";
#Write selected Dirs to log
echo -e "Followin Directories will be uploaded:\n$(ls $Amazondir|grep)">>"$LOG/current.log";
#Start upload
/usr/local/bin/acd_cli ul "$Amazondir"/* / 1>"$LOG/acd.log" 2>"$LOG/error.log";
#Write logs
sed 's/\r/\n/g' "$LOG/acd.log" | tail -3 >>"$LOG/current.log";
echo -e "Completed with following errors:\n$(cat "$LOG/error.log")">>"$LOG/current.log";
#Surepress name collisions (Case issues) in logs
sed -i '/Name collision with non-cached file/d' "$LOG/current.log"
#Sync again
/usr/local/bin/acd_cli sync>> "$LOG/current.log";
#Send mail
cat "$LOG/current.log"|mail -aFrom:AmazonTransfer -s "Job completed $(date +"%a %d %b %H:%M")" $MAIL;
#Archive log
echo -e "$(date +"%a %d %b %H:%M")\n=================\n$(cat "$LOG/current.log")\n************">>"$LOG/previous.log"
rm /tmp/AmazonTransfer.pid;
```
Kills Job if still running by noon
```bash
#!/bin/bash
LOG="/home/stapper/log/AmazonTransfer"
MAIL="My@email.Internet,My@email.local"
if [ -e /tmp/AmazonTransfer.pid ]
then
    kill $(cat /tmp/AmazonTransfer.pid);
    #and just to be sure
    pkill acd_cli;
    rm /tmp/AmazonTransfer.pid;
    echo "Cron killed job on  $(date +"%a %d %b") at ">"$LOG/current.log";
    sed 's/\r/\n/g' "$LOG/acd.log"|tail -1 >>"$LOG/current.log";
    echo -e "Found Errors:\n$(cat "$LOG/error.log")">>"$LOG/current.log";
    /usr/local/bin/acd_cli sync >>"$LOG/current.log";
    cat "$LOG/current.log" |mail -aFrom:AmazonTransfer -s "Job Killed $(date +"%a %d %b") " $MAIL;
    echo -e "$(date +"%a %d %b %H:%M")\n=================\n$(cat "$LOG/current.log")\n***********">>"$LOG/previous.log";
fi
```

**Comment by chrisidefix** [comment]
Maybe these scripts could go as actual examples (with a little documentation how to edit them) into the actual repository ?
