### ISSUE TITLE
OS X Finder "The application cannot be found" - Accented non-standard characters

### ISSUE THREAD

**Issue by Slennox** [yadayada/acd_cli#125]
Hi.

Some of my files have accented non-standard characters (written in Spanish).

It looks like when I use acd_cli mount to mount ACD through FUSE an additional mount option:

-o modules=iconv,from_code=UTF-8 

Should be passed to prevent errors. The problem is that Finder and other desktop applications cannot open the files, although they can be seen trough terminal (i.e. ls).

Related post to the problem:

https://github.com/osxfuse/osxfuse/issues/71

Any suggestion to workaround this problem? 

Rest of files with standard characters works well in the same mount point.

Thank you.

**Comment by yadayada** [comment]
```diff
diff --git a/acdcli/fuse.py b/acdcli/fuse.py
index 1aeda3e..54050e7 100644
--- a/acdcli/fuse.py
+++ b/acdcli/fuse.py
@@ -471,6 +471,7 @@ def mount(path: str, args: dict, **kwargs):
     FUSE(ACDFuse(**args), path, entry_timeout=60, attr_timeout=60, auto_cache=True,
          uid=os.getuid(), gid=os.getgid(),
          subtype=ACDFuse.__name__,
+         modules='iconv,from_code=UTF-8',
          **kwargs
          )
```

**Comment by Slennox** [comment]
Thank you. Finally got it working for me with:

modules='iconv,to_code=UTF-8-MAC'

**Comment by Slennox** [comment]
Another (aesthetic) problem I found is that every file shows up in Finder as 0 bytes of size. Although in terminal you can see the actual size.

Any ideas?

Thank you.

**Comment by Timdawson264** [comment]
could be finder is using the readdir() `` struct stat ``  which contains file size and type etc .
`` ls `` will aslo call getattr.
can u please give a log one from finder and one from terminal.

`` acd_cli -d mount -fg -i0 2>&1 | tee finder.log ``
and
`` acd_cli -d mount -fg -i0 2>&1 | tee terminal.log ``

**Comment by Slennox** [comment]
Hi, Tim.

Hope it helps to track it down.

**finder.log**
https://gist.github.com/Slennox/2818f485dd418cec9226

**terminal.log**
https://gist.github.com/Slennox/b30182485373647554fd

**Comment by Timdawson264** [comment]
this seems pretty weird ive looked at the logs and both finder and the terminal are calling getattr.
so it looks like it might just be finder doing something weird with readir. that just a guess.

**Comment by yadayada** [comment]
I've added a ``--modules`` argument in 6c9b1be629a4b9d664eb8e302f86f3ba534b7905.

I might look into the Finder issue at some later time.
