### ISSUE TITLE
Any way to overwrite changed files (and only changed)?

### ISSUE THREAD

**Issue by SimmonsTech** [yadayada/acd_cli#126]
Perhaps with an md5sum check?
Ideally something like --chk-md5 on acd_cli overwrite to allow checking before uploading each file. That way, only changed files would be transferred (putting load on CPU over network).
Another option would be a bash script around acd_cli, checking hashes and using find_md5.. but that seems overkill for something like 'acd_cli overwrite --chk-md5' which would enable keeping two directories in perfect sync.
Thoughts?

**Comment by yadayada** [comment]
``acdcli ul -o`` will overwrite (update) remote files if a) the local mtime is higher or b) the local ctime is higher and the file sizes don't match.

**Comment by SimmonsTech** [comment]
I was just reading the code and came across that - I managed to miss the --overwrite option when looking at the output of -h. Closed!
