### ISSUE TITLE
"Invalid ID format" error after making oauth_data file

### ISSUE THREAD

**Issue by clb92** [yadayada/acd_cli#13]
### Description

After accepting the auth request, I saved the text to a "oauth_data" file in the application directory. I've also tried converting it to UTF-8 instead of the default ANSI, but that just crashes the JSON decoder completely (comment if you want a stacktrace of that).

### Console output

	C:\acd_cli-master>python acd_cli.py upload C:\test.txt
	Invalid ID format.

Neither `--verbose` nor `--debug` seem to print any additional info.

### Contents of oauth_data

The text is valid JSON format:

	{
		"access_token": "<REMOVED FOR SECURITY REASONS>",
		"exp_time": 1430170624.685374,
		"expires_in": 3600,
		"refresh_token": "<REMOVED FOR SECURITY REASONS>",
		"token_type": "bearer"
	}

In my Amazon account I can see that **acd_cli_oa** is successfully authorized, so I'm not exactly sure what's wrong.

**Comment by clb92** [comment]
Ah, I feel stupid now. I was simply missing arguments, and it had nothing to do with the oauth...

**Comment by yadayada** [comment]
There was an error in the argument processing. I will make a change to have argparse print a proper error message.
