### ISSUE TITLE
Install fails due to SSL verification error 

### ISSUE THREAD

**Issue by tophee** [yadayada/acd_cli#131]
I am trying to use acd_cli with Python 2.7.10. But the install process fails because of an SSL certificate error. I am not sure whether this is a problem with acd_cli or something else, but I'm posting this here because when I was googling for a solution, I found several people with the same problem and the solution for them seemed to be that the app they were trying to install needed some fixing in order to deal with python 2.7 or something.

So here is what I get:

```
NAS:~# easy_install-2.7 acdcli
Searching for acdcli
Reading http://pypi.python.org/simple/acdcli/
Download error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'acdcli' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
Download error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for acdcli
Best match: None
Traceback (most recent call last):
  File "/usr/local/bin/easy_install-2.7", line 8, in <module>
    load_entry_point('setuptools==0.6c11', 'console_scripts', 'easy_install-2.7')()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1712, in main
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1700, in with_ei_usage
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 1716, in <lambda>
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 211, in run
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 434, in easy_install
  File "build/bdist.linux-i686/egg/setuptools/package_index.py", line 475, in fetch_distribution
AttributeError: 'NoneType' object has no attribute 'clone'
NAS:~#
```

In case you are wondering why I'm not using pip, it's because I just can't get it installed...

**Comment by yadayada** [comment]
I don't know if your NAS has enough RAM.

First off, you'll need Python 3. For the last step below, you may need to have root privileges.
```
git clone https://github.com/yadayada/acd_cli.git
python3 acd_cli/setup.py install
```

**Comment by msh100** [comment]
I'd focus on 

```
Download error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
```

I don't even think it tried to download the file due to SSL issues. Check here: http://stackoverflow.com/questions/21265616/python-easy-install-fails-with-ssl-certificate-error-for-all-packages

**Comment by tophee** [comment]
My NAS has 2GB RAM and I have root privileges. If I absolutely need Python 3, it would be good to state this somewhere in the instructions. I'm not sure whether P3 is available for my NAS (runnig on a variant of Debian Etch). I guess not, because otherwise I would probably have installed it back then when I decided to install Python.

I agree with @msh100: it probably didn't even download all the files but I'm not sure whether it's worthwhile for me to pursue this further, since it seems I won't be able to run acd_cli anyway...

**Comment by yadayada** [comment]
Let's see. There is a shield io shield, a hint in the installation guide, there also is a mention of 'pip3'.
