### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by FromScratchGDN** [yadayada/acd_cli#132]
Hi,

For the maintainers: Is it possible to also upload Windows versions? That would be great :).

**Comment by yadayada** [comment]
What do you mean, exactly?

![install](https://cloud.githubusercontent.com/assets/4608955/9740740/987826b2-5656-11e5-925c-775b1a46bb0d.png)
![running](https://cloud.githubusercontent.com/assets/4608955/9740739/9876ed1a-5656-11e5-9ad9-44290b335ad1.png)

**Comment by msh100** [comment]
I suspect he means for FUSE. In which case the answer is no; Windows has no way of mounting FUSE filesystems.

**Comment by yadayada** [comment]
If you mean if I plan to develop a free/libre Netdrive equivalent, the answer is no.
Unless you get a Kickstarter campaign going, that is.
