### ISSUE TITLE
truncate function not implemented

### ISSUE THREAD

**Issue by fling-** [yadayada/acd_cli#133]
fling@studio ~/mnt/acd $ LANG=C truncate --size=100M sketch.pdf 
truncate: failed to truncate 'sketch.pdf' at 104857600 bytes: Function not implemented

**Comment by msh100** [comment]
I have lost count of how many times I have said this. Running these kinds of functions (especially truncate) requires you to be able to write over specific blocks. `acd_cli` would have to download the file (or the part you don't want to truncate at least) and then re-upload a new object in order to achieve this. Amazon Cloud Drive is **object storage**.

**Comment by fling-** [comment]
@msh100 do you think truncate should not implemented because of the need of reuploading?
I'm not shrinking in the example btw, I'm increasing file size…

**Comment by msh100** [comment]
I believe you're treating Amazon Cloud Drive in ways which it was not designed to be treated, ergo I believe it to be out of scope for `acd_cli`. Maybe others disagree.

Maybe you want to check [this](https://amc.ovh/2015/08/15/uniting-encrypted-encfs-filesystems.html) for a potential method to handling changing data. At least treat the Amazon data as read only until you have an "object" to upload.

**Comment by fling-** [comment]
Is it atleast possible to read huge files at an offset without downloading the whole file?

**Comment by msh100** [comment]
Yep

**Comment by fling-** [comment]
> At least treat the Amazon data as read only until you have an "object" to upload.
I'd like this to be implemented in acd_cli itself.
And talking about unionfs setup I don't get how to delete files properly in this case.

**Comment by yadayada** [comment]
Trucate operations are simply not supported by the Amazon API.
I will change the truncate method to actually clear files if length 0 is requested. Truncation to the total current file size will also work.

Like msh100 said in https://github.com/yadayada/acd_cli/issues/133#issuecomment-138945437, I would have to implement a compound operation that downloads the whole file, trucate it on harddisk and re-upload it.

**Comment by yadayada** [comment]
Closing this. You can request a truncate operation for ACD in the developer forum at https://forums.developer.amazon.com/forums/forum.jspa?forumID=74.

>>At least treat the Amazon data as read only until you have an "object" to upload.

>I'd like this to be implemented in acd_cli itself.

Please clarify.
