### ISSUE TITLE
rm is broken

### ISSUE THREAD

**Issue by fling-** [yadayada/acd_cli#134]
fling@studio ~/mnt/acd $ LANG=C rm sketch.pdf 
rm: cannot remove 'sketch.pdf': Bad address

**Comment by msh100** [comment]
I saw you were also using the C wrapper, just to confirm, this is by using standalone `acd_cli`?

**Comment by fling-** [comment]
@msh100 yes.

**Comment by yadayada** [comment]
Could you provide a debug log, e.g. run ``acdcli -d mount -fg -i0 /mount/path`` and paste the relevant output? I think 'Bad address' may be the error description for all uncaught exceptions.

**Comment by yadayada** [comment]
I think this was fixed in a recent commit. Please re-open if the error persists.
