### ISSUE TITLE
'write error: Bad address' on append

### ISSUE THREAD

**Issue by fling-** [yadayada/acd_cli#135]
```
fling@studio ~/mnt/acd $ echo > new data
fling@studio ~/mnt/acd $ LANG=C echo >> new more data
-bash: echo: write error: Bad address
```

**Comment by msh100** [comment]
https://github.com/yadayada/acd_cli/issues/133#issuecomment-138945437

Please check my reply there, I believe the same applies.

**Comment by yadayada** [comment]
Currently, you cannot append to files, see the [FUSE doc](https://github.com/yadayada/acd_cli/blob/master/docs/FUSE.rst). Amazon is working on resumeable uploads, maybe it'll be possible then.
