### ISSUE TITLE
Append to empty files fails silently

### ISSUE THREAD

**Issue by fling-** [yadayada/acd_cli#136]
fling@studio ~/mnt/acd $ touch empty
fling@studio ~/mnt/acd $ echo >> empty data
fling@studio ~/mnt/acd $ cat empty

**Comment by yadayada** [comment]
I get
```
~/Desktop/acdfuse % touch foobar 
~/Desktop/acdfuse % echo >> foobar
~/Desktop/acdfuse % wc foobar
1 0 1 foobar
```

**Comment by yadayada** [comment]
Appending to an empty file should work, appending to a non-empty file should result in a 'bad address' error.
