### ISSUE TITLE
Question: How to see the buckets?

### ISSUE THREAD

**Issue by fling-** [yadayada/acd_cli#137]
I don't see the buckets in my s3 after the creation procedure -> http://docs.aws.amazon.com/AmazonS3/latest/gsg/CreatingABucket.html
I not it possible with acd_cli?

**Comment by msh100** [comment]
Amazon Cloud Drive is **not** Amazon S3. 

(it may be in the backend, but they're separate APIs)

**Comment by fling-** [comment]
Is not it possible to access my cloud drive from aws?

**Comment by fling-** [comment]
Another question: How to determine/change the region of where my data is stored in cloud drive?

**Comment by msh100** [comment]
No. They're different services.

You have no choice over it's location. I assume it's dependant on your registration data.
