### ISSUE TITLE
invalid_client when refreshing token

### ISSUE THREAD

**Issue by temple** [yadayada/acd_cli#138]
I'm sorry if isn't really a bug, but, how could I get a my client id?
I'm not so familiarized with ACD API, but I've purchased an account and give a try to acd_cli.

After an hour working the refresh_token toke place but the amazon response looks like

> RequestError: 1004, Error refreshing authentication token: {"error_description":"Client authentication failed","error":"invalid_client"}

**Comment by yadayada** [comment]
If you tried to create you own security profile, have a look at
https://developer.amazon.com/public/apis/experience/cloud-drive/content/getting-started on how to get your own client_id and client_secret.

If you have completed the appspot authentication prior to this, simply delete your oauth_data file and restart.

If you don't know what I'm talking about, run ``acdcli delete-everything`` and redo the init steps.
