### ISSUE TITLE
Question - Determining progress with many empty folders

### ISSUE THREAD

**Issue by cpare** [yadayada/acd_cli#144]
When acd_cli runs it appears to create the entire folder structure first, and then circle back to upload files into the folders - is this correct?  If so, is there an easy way for me to see what file(s) are currently being uploaded so I can verify them when completed on the ACD website?  I have hundreds of folders (Photos organized by year/month, albums by artist/album) and at this point most are still empty due to my tiny 310k upload rate.

It's not that I don't trust acd_cli, I just want to check in on things to see how it's going...

Thanks in advance - please flag as a question.

**Comment by cpare** [comment]
Just realized I may be able to get this through strace - I will check and post my findings.

**Comment by yadayada** [comment]
The verbose argument (among other things) will log the current files.
