### ISSUE TITLE
Please implement mkdir -p /this/is/long/remote/path

### ISSUE THREAD

**Issue by amaxcz** [yadayada/acd_cli#146]
man mkdir says:

<pre>
-p      Create intermediate directories as required.  If this option is not specified, the full path prefix of each operand must already exist.  On the other hand, with this
             option specified, no error will be reported if a directory given as an operand already exists.  Intermediate directories are created with permission bits of
             rwxrwxrwx (0777) as modified by the current umask, plus write and search permission for the owner.
</pre>

But, currently its not comfortable works with ACD paths from bash scripts.. so

<pre>
REMOTE_PATH="/Backup/somedir"
</pre>

and next

<pre>
if [ ! -z $REMOTE_PATH ]; then
REMOTE_DIRS=$(echo $REMOTE_PATH | sed 's#/$##' | awk -F "/" '{$1 = ""; print $0}' | xargs)
RPATH=""
for i in $REMOTE_DIRS; do
RPATH="$RPATH/$i"
acdcli --utf mkdir $RPATH  &> /dev/null
done
</pre>

Please implement true way to make remote dirs with -p switch.
Thanks.

**Comment by AlexCzar** [comment]
+1
