### ISSUE TITLE
I would like the option to output the date and time of each file transfer...

### ISSUE THREAD

**Issue by kylehayes** [yadayada/acd_cli#15]
I'm in the process of uploading 100s of GB to ACD which takes some time. Sometimes, when I check on the progress, I notice that it appears to have stalled or is waiting for something. It would be nice if I could have the option to show a date and time of each operation (similar to a log file) so that I can see how long the operation has been sitting idle.

**Comment by yadayada** [comment]
This is not exactly what you asked for, but I've added stalling detection, i.e. lower timeouts (60s), for both libraries (requests and pycurl).

**Comment by yadayada** [comment]
I think the verbose log prints should suffice for this. They're less noisy now. The hasher messages and last sqlite insertion logs should indicate as to when the current upload started or the last upload ended.
