### ISSUE TITLE
autosync not working

### ISSUE THREAD

**Issue by saqebakhter** [yadayada/acd_cli#155]
if you have acd_cli mount - used to mount acd using fuse , and files are uploaded from web drive, or another system - the fuse mount is out of sync .

Two things:

1) implement the the changes api - https://developer.amazon.com/public/apis/experience/cloud-drive/content/changes

2) acd_cli sync - should also sync the cache for the fuse mount as well.

**Comment by yadayada** [comment]
1) It already is implemented.
2) There is a background _autosync process for FUSE. It must have stopped working some time ago. 

Does your ``acd_cli sync`` really not sync?

**Comment by saqebakhter** [comment]
It syncs - ie) acd_cli ls - works - but fuse does not reflect it until a 
remount.

For example if you follow this:

1) mount fuse
2) acd-cli clear cache
  (fuse still has directory structure, but acdcli ls does not )
3) acd-cli sync ( acdcli  ls is updated )


yadayada wrote:
>
> 1) It already is implemented.
> 2) There is a background _autosync process for FUSE. It must have 
> stopped working some time ago.
>
> Does your |acd_cli sync| really not sync?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/yadayada/acd_cli/issues/155#issuecomment-143401744>.
>

-- 
--Saqeb

**Comment by yadayada** [comment]
What happens here is

1) the sqlite3 database nodes.db gets opened in the mount process
2) ``clear-cache`` removes nodes.db from harddisk
3) ``sync`` will create a new nodes.db

I know, ``clear-cache`` is a bit of a misnomer.

**Comment by saqebakhter** [comment]
Okay - so is clear-cache usually needed or not ?

yadayada wrote:
>
> What happens here is
>
> 1) the sqlite3 database nodes.db gets opened in the mount process
> 2) |clear-cache| removes nodes.db from harddisk
> 3) |sync| will create a new nodes.db
>
> I know, |clear-cache| is a bit of a misnomer.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/yadayada/acd_cli/issues/155#issuecomment-143403639>.
>

-- 
--Saqeb

**Comment by yadayada** [comment]
There is an automatic syncing mechanism for FUSE that should sync every 60 seconds. That's broken now.

Usually, clear-cache is not needed. A simple sync will propagate updates to the mount as well.

**Comment by saqebakhter** [comment]
Ah okay - so the auto sync to fuse is broken.

But doing a acdcli sync should work....I'll give that a shot.


yadayada wrote:
>
> There is an automatic syncing mechanism for FUSE that should sync 
> every 60 seconds. That's broken now.
>
> Usually, clear-cache is not needed. A simple sync will propagate 
> updates to the mount as well.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/yadayada/acd_cli/issues/155#issuecomment-143404282>.
>

-- 
--Saqeb

**Comment by saqebakhter** [comment]
Cool thanks !

**Comment by saqebakhter** [comment]
I tried the dev branch - and it still does not seem to be auto syncing ? 

Does acdcli automatically pull changes happening in acd ? I uploaded a file - waited 5 minutes - and on my system acdcli ls is still not showing that new file.

**Comment by yadayada** [comment]
If I 
1) run ``acdcli mount acdfuse``,
2) create a folder in the web interface,
3) wait a minute and ``ls acdfuse``,

the folder is there. The standard sync interval is 60 seconds.

**Comment by tobyboreham** [comment]
My mistake was putting sync in the cron, not thinking it did it automatically. Now the mount point and the push of new files are playing happily together. Thanks for the clarification!
