### ISSUE TITLE
Sync % Rising but Storage GB not Increasing

### ISSUE THREAD

**Issue by 2marshall** [yadayada/acd_cli#158]
any idea why for two days I have the overall % of this upload increasing but if I login to https://www.amazon.com/clouddrive/ and click on manage storage I see the same amount in GB?

![image](https://cloud.githubusercontent.com/assets/13956848/10124820/4ccc24b2-6514-11e5-9b2d-d29c30ec8917.png)

**Comment by yadayada** [comment]
Please edit your message to reflect
- what command(s) you are running,
- what "the same amount" is and at which times you recorded this data,
- what the web interface shows currently and what ``acdcli u`` prints currently,
- what the web interface showed and what ``acdcli u`` output at a specific point in the recent past,
- that you have checked that files actually were and are being successfully uploaded or not

and, most importantly, why I should care. 
Please close this issue if you cannot answer all of the questions.

**Comment by jonas5** [comment]
you have to sync again after upload, then check space
