### ISSUE TITLE
Invalid Syntax on fname: str

### ISSUE THREAD

**Issue by neurobomber** [yadayada/acd_cli#159]
I'm unable to upgrade acdcli when installing from pip3. Here's my output:    

    Collecting acdcli
      Downloading acdcli-0.3.0a6.tar.gz (59kB)
        100% |████████████████████████████████| 61kB 788kB/s 
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-T1hFIt/acdcli/setup.py", line 7
            def read(fname: str) -> str:
                          ^
        SyntaxError: invalid syntax
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-T1hFIt/acdcli

**Comment by yadayada** [comment]
Is this pip3?

**Comment by jtaylor991** [comment]
I had this issue on Fedora 22. I discovered, after trying to update pip (from 6.0.8 to 7.1.2), the "pip3" command went away. "pip" by itself was running for Python 2.7. I searched around, and to run pip3, I had to use "python3 -m pip" (or reinstall pip3 somehow, but that worked fine).

So, running "python3 -m pip install --upgrade git+https://github.com/yadayada/acd_cli.git" worked successfully!

**Comment by UnklAdM** [comment]
This worked for me on Centos 7.  Thanks!
