### ISSUE TITLE
Error when trying to sync

### ISSUE THREAD

**Issue by jurecotic** [yadayada/acd_cli#16]
I'm getting a new error with the latest master. When I sync I get the following:

```
Syncing... 
Traceback (most recent call last):
  File "./acd_cli.py", line 606, in <module>
    main()
  File "./acd_cli.py", line 602, in main
    args.func(args)
  File "./acd_cli.py", line 265, in sync_action
    sync_node_list(full=args.full)
  File "./acd_cli.py", line 52, in sync_node_list
    r = metadata.get_changes(checkpoint=cp)
  File "/home/ssitcm/acd_cli/acd/metadata.py", line 51, in get_changes
    if not status['end']:
KeyError: 'end'
```

This happens on Raspbian with Python 3.4.

**Comment by yadayada** [comment]
Could you please put the following code into a file in the main directory, run it and tell me what the output looks like.

```python
#!/usr/bin/env python3

import os
from acd.common import *

init(os.path.dirname(os.path.realpath(__file__)))
r = BackOffRequest.post(get_metadata_url() + 'changes')
print(r.text)
```

The output should include all nodes and an end tag. That's what it looks for me:
```
{
    "checkpoint": "...",
    "nodes": [
        ...
    ],
    "reset": true,
    "statusCode": 200
}
{'end':true}
```

**Comment by jurecotic** [comment]
Yeah, I get a list of a lot of nodes and the end tag is also there

```
{"end":true}
```

**Comment by yadayada** [comment]
And if you invoke the above script like `python3 foo.py | wc -l`, what does it output?

**Comment by jurecotic** [comment]
I get 12.

**Comment by yadayada** [comment]
Hmm... I was expecting two lines in the response with all data on the first line and the end tag on the last line. (My example above was pretty printed.)

Would you try to replace the last lines in `acd/metadata.py` with
```
    status = json.loads(ro[-1])
    if not status['end']:
        logger.warning('End of change request not reached.')

    return json.loads(' '.join(ro[:-1]))
```

If that doesn't work, I will need a more detailed description of the response text you get.

**Comment by sasotepina** [comment]
I'm having the same issue.
The response I get looks like this:
```
{"checkpoint": "...","nodes": [ ... ],"reset": true,"statusCode": 200}
{"checkpoint": "...","nodes": [ ... ],"reset": false,"statusCode": 200}
{"checkpoint": "...","nodes": [ ... ],"reset": false,"statusCode": 200}
{"checkpoint": "...","nodes": [ ... ],"reset": false,"statusCode": 200}
{"end":true}
```

**Comment by yadayada** [comment]
Might work with 0b7c00db04897f3fdd28bccf1aa560a365eb8a42.

**Comment by sasotepina** [comment]
It works fine now.
Thanks!
