### ISSUE TITLE
Please implement --remove-source-files on upload complete

### ISSUE THREAD

**Issue by cfoucher** [yadayada/acd_cli#160]
It would be great to have to have the option to automatically remove the source files after a successful acd_cli upload call.

**Comment by AlexCzar** [comment]
+1

**Comment by HazCod** [comment]
I just do a
```
if acd_cli upload -o "$file" "/$root"; then
   rm "$file
fi
```

**Comment by hongkongkiwi** [comment]
This would be fantastic, I'm using rsync for this, but it's definitely not as good as using acd_cli upload (due to the multi connection option in acd_cli upload)

**Comment by hongkongkiwi** [comment]
Hi there, I saw this was added! It's really awesome. I've found a bug though, when a file already exists the upload is skipped (as it should be), however the file is not actually removed on the local machine.

**Comment by hongkongkiwi** [comment]
I found these IPs from a quick DNS check, if we can specify it somewhere with a flag, maybe you could try these for a better speed:

```
54.88.171.177
54.88.163.153
54.88.116.165
54.85.103.237
54.86.242.151
54.86.244.224
54.165.88.192
54.88.196.111
```

**Comment by Linwood-F** [comment]
When a file is skipped on upload by being a duplicate, I'm not sure it really should remove it on the source, as there's a chance it is not REALLY a duplicate just a match, and someone may want to deal with it manually?   I could argue either way, but just wanted to throw that thought out there.

**Comment by acornspaul** [comment]
I agree with @Linwood-F .  I would prefer to see the app support both behaviors with the chosen behavior being toggled by a command line flag and the default behavior being not to delete the file.

**Comment by hongkongkiwi** [comment]
Makes perfect sense, what about if we have
--remove-source-files (will remove only when uploaded successfully)
and --remove-source-duplicates (when a duplicate is detected it will remove the source file)

So you can use one option, or both.

**Comment by yadayada** [comment]
Note to self: check symlink behaviour, add option to download as well.
