### ISSUE TITLE
Root node not found

### ISSUE THREAD

**Issue by kelna** [yadayada/acd_cli#161]
When I try to launch acd_cli I get this error:
`[CRITICAL] [acd_cli] - Root node not found. Please sync.`
What is this? What should I do?

**Comment by yadayada** [comment]
What do you mean by 'launch'?
This is a critical error, meaning the root node ('/') was not found. Maybe you should try a (full) sync.

**Comment by kelna** [comment]
I've been using this script to mount my ACD. It worked until recently. Now I get the above mentioned message.
```
source py3env/bin/activate
acd_cli mount /home/kelna/ACD/
```

**Comment by kelna** [comment]
>Maybe you should try a (full) sync.

How do I do that?

**Comment by jayachandranm** [comment]
If people are still looking for the solution, running sync again did remove this error.

acd_cli sync

The first time the above command is run, the browser window opens to download the oauth key. After setting up the key, run the command again to do the sync. This step seems missing from the documentation.
