### ISSUE TITLE
OSError: Unable to find libfuse

### ISSUE THREAD

**Issue by vertigo235** [yadayada/acd_cli#165]
I'm getting this error, but I have verified the packages and files are available in the referenced folder.  I installed using pip

```
ds415plus> python3 acd_cli mount /volume1/amazoncloud
Traceback (most recent call last):
  File "acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a6', 'console_scripts', 'acd_cli')()
  File "/volume1/@appstore/py3k/usr/local/bin/acd_cli.py", line 1361, in main
    sys.exit(args.func(args))
  File "/volume1/@appstore/py3k/usr/local/bin/acd_cli.py", line 899, in mount_action
    import acdcli.acd_fuse
  File "/volume1/@appstore/py3k/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 15, in <module>
    from acdcli.bundled.fuse import FUSE, FuseOSError as FuseError, Operations
  File "/volume1/@appstore/py3k/usr/local/lib/python3.4/site-packages/acdcli/bundled/fuse.py", line 74, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse
ds415plus>
```

**Comment by vertigo235** [comment]
It doesn't appear that the find_library utility is working properly, but libfuse is located in /lib

**Comment by vertigo235** [comment]
I was able to get working by modifying the source to map directly to my libfuse.so file and not use find_library

**Comment by yadayada** [comment]
Which OS version are you using?

**Comment by vertigo235** [comment]
Synology DSM 5.2-5592 Update 4, on a DS415+

**Comment by yadayada** [comment]
Does it work if you
```bash
acdcli umount
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH":/lib/"
```
and mount again?

**Comment by vertigo235** [comment]
no that does not work

**Comment by vertigo235** [comment]
Recommend modifying the bundled fuse.py to include ability to set path (and optionally file name) with environment variables. 

...
try:
    _libfuse_root = environ['FUSE_LIBRARY_PATH']
except KeyError:
    if _system == 'Darwin':
        _libiconv = CDLL(find_library('iconv'), RTLD_GLOBAL) # libfuse dependency
        _libfuse_path = (find_library('fuse4x') or find_library('osxfuse') or
                         find_library('fuse'))
    else:
        _libfuse_path = find_library('fuse')
else:
    _lib_filename = environ.get('FUSE_LIBRARY_FILENAME', 'libfuse.so.2')
    _libfuse_path = join(_libfuse_root, _lib_filename)

    if exists(_libfuse_path) is False:
        raise EnvironmentError("libfuse not found at prescribed place: %s" % (_libfuse_path))
...

**Comment by yadayada** [comment]
I got the same idea from the fusepy issue tracker
https://github.com/terencehonles/fusepy/issues/35#issuecomment-147133806

I'll put it in one of the next commits.
