### ISSUE TITLE
Fuse: Remote I/O error

### ISSUE THREAD

**Issue by HazCod** [yadayada/acd_cli#166]
Trying to download subtitles with subliminal for media directly on my fuse mount.
Exits with a `IOError: [Errno 121] Remote I/O error`

File is created but empty. `-rw-rw-rw- 1 media media          0 Oct 12 13:01 Fried Green Tomatoes.nl.srt`

What is the correct debug parameter set to look at this?

```
...
  File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py", line 405, in save_subtitles
    f.write(subtitle.content)
IOError: [Errno 121] Remote I/O error

```

**Comment by yadayada** [comment]
>File "/usr/local/lib/python2.7/dist-packages/subliminal/api.py"

You know that's an external application, right? There is no exception handling in subliminal.
What do you think should happen instead?

>File is created but empty.

That's supposed to happen if the upload fails.
>What is the correct debug parameter set to look at this?

Oh, come on. That's documented.
If you're using a recent version, you might find some logs in your cache path.
