### ISSUE TITLE
Non-ascii characters in filenames cause a UnicodeEncodeError

### ISSUE THREAD

**Issue by elonen** [yadayada/acd_cli#168]
Listing ACD files that have non-ascii characters (e.g. 'ä') in their names cause a UnicodeEncodeError. ACD web UI handles them gracefully, so my guess is they are encoded in UTF-8, but acd_cli assumes ascii. Here's a stack trace:

```python
(acd_cli) panda:~/.cache/acd_cli$ acdcli tree
/
    Documents/
    My Send-to-Kindle Docs/
Traceback (most recent call last):
  File "/home/jarno/bin/acd_cli/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.0a2', 'console_scripts', 'acdcli')()
  File "/home/jarno/bin/acd_cli/bin/acd_cli.py", line 1096, in main
    sys.exit(args.func(args))
  File "/home/jarno/bin/acd_cli/bin/acd_cli.py", line 524, in tree_action
    print(node)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 14: ordinal not in range(128)
```

**Comment by elonen** [comment]
Hmm. Issuing `export LC_ALL="en_US.UTF-8"` on the shell seems to fix / work around the problem. Not sure what would be the ideal way to handle this. Catch UnicodeEncodeError and print out a more descriptive error for the user (suggest changing locale)? Force ascii encode with placeholder characters?

**Comment by yadayada** [comment]
Python 3's print function uses ASCII if the system locale is not set.
There's a global utf flag for this very issue. ``acdcli --utf tree`` should do.

**Comment by elonen** [comment]
I see, guess this is more of a Python problem/issue. Thank you.

**Comment by yadayada** [comment]
TODO: Add excepthook and print a hint for this.
