### ISSUE TITLE
All files show size of 0

### ISSUE THREAD

**Issue by vertigo235** [yadayada/acd_cli#169]
I'm not sure what the deal is, but all files show size of 0 for mounted folder.  I was able to upload a file to cloud drive by copying to the mounted folder but still says file size 0.

**Comment by yadayada** [comment]
There is nothing I can say or do about this without a debug log of the upload.

>all files show size of 0 for mounted folder.

Were (some of) these files successfully uploaded before? What happens if you do a upload via CLI (``acdcli ul``)? 

>I was able to upload a file to cloud drive by copying to the mounted folder but still says file size 0.

Did you check whether the file was present in the Web interface?

**Comment by vertigo235** [comment]
It was all files (previously uploaded and the new one I uploaded), not just the ones uploaded via the mount.  So it's not related to the upload, appears to be an issue with the read functionality of the FUSE mount I would guess?  Yes the file I uploaded did make it to the cloud drive and was able to see it using the web form.  

How should I make a debug log?  I'm not a linux master but I would like to help with this.  I'm not sure if there are many Synology users using this cool tool that you have made.

**Comment by vertigo235** [comment]
OK so it appears that the mount only shows the files and folders but they are empty if I try to view them or copy them to another folder.  

So it does appear to be an issue with the fuse reader?

**Comment by yadayada** [comment]
It's very hard to understand what you are trying to say.
There are intact files that you can download via the Web interface but they are displayed as being 0byte in the mountpoint?

Please also compare the output of ``acdcli ls -l /some/path`` and ``ls -l mountpoint/some/path``, especially the file sizes.

There should be log files in the cache path (the path should be stated in the output of ``acdcli -v init``). Alternatively, you'll get the logs by unmounting and running ``acd_cli -d mount -i0 -fg path/to/mountpoint``

Please upload a small file (a few kilobytes) via FUSE and see what it logs.

I would also like the output of one getattr call, like

```
15-10-12 20:12:43.587 [DEBUG] [acdcli.acd_fuse] - -> getattr /CDDA/Kante - Die Tiere sind unruhig.cue (None,)
15-10-12 20:12:43.595 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_atime': 1444673563.5944877, 'st_mode': 33206, 'st_mtime': 1435245406.14, 'st_nlink': 1, 'st_size': 915, 'st_ctime': 1433764138.966}
```

**Comment by vertigo235** [comment]
yes, that's what I'm saying also if I copy the files from the mountpoint to another folder the file will still be 0byte in the new folder so it copies a blank file to the new folder from the mountpoint.

attached is one of the log files I have generated while testing, it doesn't appear there is any st_size value being returned in the JSON? hmm

**Comment by vertigo235** [comment]
actually my mistake it does have st_size for the files.

15-10-12 14:09:41.560 [DEBUG] [acdcli.acd_fuse] - -> getattr /iPhonePhotos/photo 1.JPG (None,)
15-10-12 14:09:41.593 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_mtime': 1444522487.7950001, 'st_size': 2338942, 'st_atime': 1444673381.5905855, 'st_mode': 33206, 'st_ctime': 1444522484.346, 'st_nlink': 1}
15-10-12 14:09:41.594 [DEBUG] [acdcli.acd_fuse] - -> getattr /iPhonePhotos/2013-07-19 (None,)
15-10-12 14:09:41.624 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_atime': 1444673381.624794, 'st

**Comment by vertigo235** [comment]
Please also compare the output of acdcli ls -l /some/path and ls -l mountpoint/some/path, especially the file sizes.

.... doing this does show the correct file sizes, which indicates that it is an issue with the fuse mount no?

**Comment by yadayada** [comment]
Did you get correct sizes with both commands?
Which program did you use that displays the wrong file sizes?

**Comment by vertigo235** [comment]
sorry I understand your question now, the acdcli method displays the correct file sizes, the fuse mount does not

**Comment by yadayada** [comment]
Sorry, you don't seem to put in a minimum amount of effort and this conversation is going nowhere.

**Comment by vertigo235** [comment]
I thought I already made it clear that the fuse mount displayed the incorrect file sizes, I was confirming that the other method showed the correct file sizes.  Anyhow, I'm sorry my understanding was not up to par, good luck with the tool. I really like what you have done already I'll check back later after someone more worthy of your time provides you with info on this issue.

**Comment by vertigo235** [comment]
OK so i modified my fuse.py to force it to fallback to i686 and it appears to be working now, odd machine reports x86_64s
