### ISSUE TITLE
PyPi publication / Release version (Milestone management)

### ISSUE THREAD

**Issue by chrisidefix** [yadayada/acd_cli#17]
Hi @yadayada,

great work from what I can see. Have you thought about publishing this through [PyPi](https://pypi.python.org/pypi) - once there is a "stable" version available? It may make sense to create release versions for this purpose and since your `README.md` already contains a list of features and planned work, this should be fairly straight forward.

Cheers!

**Comment by yadayada** [comment]
I might publish it eventually, but not in the near future.

**Comment by yadayada** [comment]
I guess this can be closed now.

**Comment by chrisidefix** [comment]
I added you as owner, so sure can close this now :+1:

**Comment by yadayada** [comment]
Thanks.
