### ISSUE TITLE
Support -o like FUSE mounting

### ISSUE THREAD

**Issue by ratherDashing** [yadayada/acd_cli#173]
I have multiple users on my Linux box who would like to access the ACD mountpoint.  It would be beneficial to support a -o like FUSE mounting so multiple users can access the mount point.

**Comment by HazCod** [comment]
`--allow_other` or `--allow-other` is supported.

**Comment by ratherDashing** [comment]
didn't see that thanks

**Comment by yadayada** [comment]
I've seen most FUSE filesystems support the passing of options via ``-o``. Is there any advantage to it?

**Comment by ratherDashing** [comment]
I've just used sshfs before and I'm just accustomed to passing the -o

http://linux.die.net/man/1/sshfs

you can see that sshfs supports a lot more options than the ACD cli supports

**Comment by HazCod** [comment]
not having to hardcofr multiple ones I suppose

**Comment by huseynli** [comment]
Guys, I used "mount -ao" to test it. Now my mount directory shows permission 777. I can't seem to change it. remounting without -ao doesn't affect it. I really don't want to leave permissions like this. What can I do ?
