### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by bardamatic** [yadayada/acd_cli#177]
Since I have updated to the latest release (0.3.1) when syncing I get:

RequestError: 1003, [acd_api] reading changes terminated prematurely.

I have lots of files online it is timing out after ~5 minutes.  If 5 minutes is the timeout it may be insufficient.  Can this be adjusted?

**Comment by bardamatic** [comment]
I saw that my nodes.db continued growing after every 'acd_cli sync' even after the failure.

After 20 separate tries that all timed out with the above message, it finally reported a successful sync.

Not sure what this issue is, but I will not do a 'and_cli cc' again until this is sorted out.

**Comment by yadayada** [comment]
The ability to continue a failed sync and the verrry nice error message you see now were added recently.

5 minutes is a bit high, the timeout should be 30 or 60 seconds.

There is a relates issue, #156.

**Comment by bardamatic** [comment]
My nodes.db file grew to around 220mb before it finally said 'success'. About 10mb per 'acd_cli sync' repeated after every timeout failure.

I would assume that I can't make this size of db from scratch in 30-60 seconds especially if I have many, many small files stored on the ACD.

I guess if Amazon is throttling outbound bandwidth it would make sense that it takes a long time to receive the metadata on all these files, hence the timeout.

I won't 'acd_cli cc' or 'acd_cli sync -f'  in the future (unless required) as this would make me go through this process again.
