### ISSUE TITLE
Backoff and I/O throughput plunge

### ISSUE THREAD

**Issue by Slennox** [yadayada/acd_cli#178]
Certain file access patterns to ACD give me those backoff messages that can be seen in the log. Are those messages related to ACD throttling my requests? When that happens, I/O throughput of ACD plunges.

Is there something I can tweak on my application to just keep under ACD maximum request rate? Which are those rates?

```
15-10-23 18:27:45.270 [DEBUG] [acdcli.acd_fuse] - <- read ''
15-10-23 18:27:45.272 [DEBUG] [acdcli.acd_fuse] - -> read /file (131072, 374882304, 2)
15-10-23 18:27:45.280 [DEBUG] [acdcli.acd_fuse] - s: 374882304-385533859; r: 374882304-375013375
15-10-23 18:27:45.786 [DEBUG] [acdcli.acd_fuse] - <- read ''
15-10-23 18:27:45.787 [DEBUG] [acdcli.acd_fuse] - -> rad /file (114688, 375013376, 2)
15-10-23 18:27:45.799 [DEBUG] [acdcli.acd_fuse] - s: 375013376-385533859; r: 375013376-375128063
15-10-23 18:27:45.930 [DEBUG] [acdcli.acd_fuse] - <- read ''
15-10-23 18:27:45.931 [DEBUG] [acdcli.acd_fuse] - -> read /file (16384, 310378496, 2)
15-10-23 18:27:45.939 [DEBUG] [acdcli.acd_fuse] - s: 375128064-385533859; r: 310378496-310394879
15-10-23 18:27:45.939 [DEBUG] [acdcli.acd_fuse] - s: 14385152-385533859; r: 310378496-310394879
15-10-23 18:27:45.940 [DEBUG] [acdcli.acd_fuse] - s: 335036416-385533859; r: 310378496-310394879
15-10-23 18:27:45.940 [DEBUG] [acdcli.acd_fuse] - s: 353632256-385533859; r: 310378496-310394879
15-10-23 18:27:45.940 [DEBUG] [acdcli.acd_fuse] - s: 297533440-385533859; r: 310378496-310394879
15-10-23 18:27:45.940 [DEBUG] [acdcli.acd_fuse] - s: 2097152-385533859; r: 310378496-310394879
15-10-23 18:27:45.940 [DEBUG] [acdcli.acd_fuse] - s: 66584576-385533859; r: 310378496-310394879
15-10-23 18:27:45.941 [DEBUG] [acdcli.acd_fuse] - s: 123994112-385533859; r: 310378496-310394879
15-10-23 18:27:45.941 [DEBUG] [acdcli.acd_fuse] - s: 130023424-385533859; r: 310378496-310394879
15-10-23 18:27:45.941 [DEBUG] [acdcli.acd_fuse] - s: 118751232-385533859; r: 310378496-310394879
15-10-23 18:27:45.941 [DEBUG] [acdcli.acd_fuse] - s: 260161536-385533859; r: 310378496-310394879
15-10-23 18:27:45.941 [DEBUG] [acdcli.acd_fuse] - s: 68157440-385533859; r: 310378496-310394879
15-10-23 18:27:45.942 [DEBUG] [acdcli.acd_fuse] - s: 233570304-385533859; r: 310378496-310394879
15-10-23 18:27:45.942 [DEBUG] [acdcli.acd_fuse] - s: 84934656-385533859; r: 310378496-310394879
15-10-23 18:27:45.942 [DEBUG] [acdcli.acd_fuse] - s: 380633088-385533859; r: 310378496-310394879
15-10-23 18:27:45.942 [DEBUG] [acdcli.api.content] - chunk o 310378496 l 524288000
15-10-23 18:27:45.942 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.411346s
```

**Comment by yadayada** [comment]
If you get a negative waiting time, you're not waiting at all. 
Ordinarily, there is a random waiting time from 0 to 1 second. If errors occur, the waiting time is in the interval of 0 to 2^no_of_errors seconds (max. 2^8).

**Comment by Slennox** [comment]
But what is the meaning of these [acdcli.api.backoff_req] messages that I can see on the log? Because I do know ACD can saturate my link when reading a file sequentially for example, but with this other access pattern of random reads of the same file from different connections the throughput is very poor.

**Comment by yadayada** [comment]
>But what is the meaning of these [acdcli.api.backoff_req] messages that I can see on the log? 

I just told you. See the [ACD API Best Practices](https://developer.amazon.com/public/apis/experience/cloud-drive/content/restful-api-best-practices) for further information on the required backoff algorithm.

>Because I do know ACD can saturate my link when reading a file sequentially for example, but with this other access pattern of random reads of the same file from different connections the throughput is very poor.

Your question is the answer. Non-sequential access is slower. Take your read on file handle 2 at address 310378496, for example. There is no open chunk that you can continue reading from for this address. So a new chunk must be requested, which takes time.
