### ISSUE TITLE
Amazon Throttling

### ISSUE THREAD

**Issue by aus** [yadayada/acd_cli#181]
I'd like to start a discussion on how Amazon throttles its connections. It's my understanding that Amazon may classify, at will, any application ID as "Development" or "Production". Applications classified as Development get their connections throttled, while Production applications get much better speeds. I've also seen [occurrences](http://community.covecube.com/index.php?/topic/1519-amazon-cloud-drive-near-future/?p=10680) from other applications where Amazon downgrades the application status from Production to Developer without warning. In this case, a user was pushing 400 Mbps which triggered their application ID to be downgraded. 

Currently, with `acd_cli`, I get a steady 9 Mbps down and 1 Mbps up on a 300 Mbps up/down connection.

My questions would be:

1. What is the current application status for `acd_cli` when OAuth'd from `tensile-runway-92512.appspot.com`? Development or Production? My money is on Development.
2. To distribute the load between application IDs, would it be better to individually register our own application ID and OAuth against our own service? Then, if we behave nicely, maybe our own application ID gets promoted to production? And if someone triggers a downgrade to Development, we don't affect others.
3. How have speeds been for other people with `tensile-runway-92512.appspot.com`? Has anyone tested with their own application ID? I should have some time this weekend to post my own results.

Even more frustrating, I have not seen any of this information officially documented by Amazon. We may be grasping at straws, but perhaps a discussion of our own experiences can help us better understand how Amazon expects us to behave. StableBit said it took months to get promoted to Production with no indication of when they will get promoted again.

I also realize that @yadayada does not have any control of these factors and we are all at the mercy of Amazon. So please remember to direct your :fire:ing towards Amazon.

**Comment by msh100** [comment]
I use my own application ID and I do not download that slowly.

**Comment by sjfer** [comment]
I'm using yadayada's but I'm able to upload and download a lot quicker than that. I have a gig connection but can reach between 100 and 200 mbit/s when uploading files overnight.

**Comment by yadayada** [comment]
I applied for review at the end of March and got assured the app was approved at the end of August (it may have been approved earlier).
>Your app has been reviewed and approved. We have adjusted your throttling limits to production levels.

>Best regards,
>Amazon Cloud Drive 3P Support

The "app" in question is acd_cli_oa at [tensile-runway-92512.appspot.com](https://acd_cli_oa at tensile-runway-92512.appspot.com)

I, personally, haven't noticed a difference between the speeds with my (development rate) private security profiles and the appspot one, but I can't base this on extensive benchmarking. 

Other people seem to be complaining about a decline in speed, too:
https://forums.developer.amazon.com/forums/thread.jspa?threadID=9178&tstart=0

I suspect Amazon may throttle based on geolocation and possibly other factors. That's because I get different speeds with/without VPN using acd_cli (same with the Web interface).

**Comment by jmoriau** [comment]
In the last days I have also seen my upload speed go from 24MB/s to ~2MB/s.
Didn't change anything on my side, so I was thinking Amazon may be throttling too.

**Comment by tyauvil** [comment]
I can max out my upload on a 1Gb/s connection. I think it's entirely dependent on your ISP.

**Comment by HazCod** [comment]
A few notes or suggestions on the best choices regarding peering/providers would be cool

**Comment by cyrilboh** [comment]
When I download, I can initially get a few hundred megabits per second. But it very quickly drops to about half a megabyte per second.

I am using fuse though, don't know if that is a factor.

**Comment by maplesyrupcloud** [comment]
How do we sign up for our own app ID?

**Comment by tuapuikia** [comment]
It actually depend on which Amazon Cloud Drive endpoint (content-na.drive.amazonaws.com) you connected to. I manage to archive 25MB/s upload when I connected to specific IP.

**Comment by cyrilboh** [comment]
Is it possible to specify which end point to use in acdcli?

**Comment by hongkongkiwi** [comment]
I found these IPs from a quick DNS check, if we can specify it somewhere with a flag, maybe you could try these for a better speed:

```
54.88.171.177
54.88.163.153
54.88.116.165
54.85.103.237
54.86.242.151
54.86.244.224
54.165.88.192
54.88.196.111
```

**Comment by yadayada** [comment]
@cyrilboh The contentUrl that's used for file transfer may be manually set in the endpoint_data file in the cache path. You can also increase the exp_time value to have that change stick for longer than 3 (or 5?) days?

**Comment by bobloadmire** [comment]
I'm on 150/150 fiber and I'm getting much better speeds. I was able to stream 6 8Mbps shows on Plex this morning as a test, and even though initial playback took 10 seconds to start, it never hiccuped once streaming. Also I was uploading to ACD simultaneously at 25 Mbps. Really impressed.

**Comment by Sunako** [comment]
I've noticed this recently too, using my own application profile, not the supplied one from yadayada. I would be downloading a 5GiB file and speeds range from a few hundred KB/s to 20MB/s, it seems to happen pretty consistently when downloading a large file. I wonder if I can get my application profile changed to "production" if it is just for me. Anyone tried this?

**Comment by marcelowa** [comment]
Is there a list of endpoints somewhere?

**Comment by yadayada** [comment]
AFAIK, the endpoints are North America, Europe and Japan and you get locked in to an endpoint when you sign up.
https://content-{na|eu|jp}.drive.amazonaws.com/cdproxy/

**Comment by marcelowa** [comment]
When did it lock it when I signed up to your amazon app or when I signed up to amazon cloud drive?

**Comment by yadayada** [comment]
I think you get assigned to an endpoint when you sign up for Cloud Drive. How one's endpoint is determined is not entirely transparent for me; I first got an American account and then an European one on Amazon's Black Friday sale.

**Comment by Neodark7** [comment]
I'm using a server in france and by default acd_cli can upload at 3MB/s using https://content-na.drive.amazonaws.com/cdproxy/ . I just switched to "eu" and now i can upload at 25MB/s so really a good solution

**Comment by bobloadmire** [comment]
Noice! Where do you change the server address?

**Comment by Neodark7** [comment]
in the .cache/acd_cli/endpoint_data file

**Comment by Neodark7** [comment]
aaand it's not working anymore... now i have 5-10mBps...

**Comment by pmwoodward3** [comment]
I went to endpoint_data to change the domain to a direct IP and I got this interesting error message:

 hostname '54.210.220.185' doesn't match either of 'cnt-00.content-na-gamma.drive.amazonaws.com', 'cnt-00.content-na.drive.amazonaws.com', 'cnt-01.content-na-gamma.drive.amazonaws.com', 'cnt-01.content-na.drive.amazonaws.com', 'cnt-02.content-na-gamma.drive.amazonaws.com', 'cnt-02.content-na.drive.amazonaws.com', 'cnt-03.content-na-gamma.drive.amazonaws.com', 'cnt-03.content-na.drive.amazonaws.com', 'cnt-04.content-na-gamma.drive.amazonaws.com', 'cnt-04.content-na.drive.amazonaws.com', 'cnt-05.content-na-gamma.drive.amazonaws.com', 'cnt-05.content-na.drive.amazonaws.com', 'cnt-06.content-na-gamma.drive.amazonaws.com', 'cnt-06.content-na.drive.amazonaws.com', 'cnt-07.content-na-gamma.drive.amazonaws.com', 'cnt-07.content-na.drive.amazonaws.com', 'content-na-gamma.drive.amazonaws.com', 'content-na.drive.amazonaws.com', 'cosmo.content-na.drive.amazonaws.com'.

Would it be possible to make acdcli switch between all these different hosts to avoid throttling?

**Comment by pmwoodward3** [comment]
Also, would it be possible to release the acdcli Amazon app so people could make and upload their own? Maybe if we spread out the load to many different apps each one will be able to perform better?

**Comment by tuapuikia** [comment]
I can reach 25MB/s by using the "high speed" IP.  :+1:

**Comment by Neodark7** [comment]
what do you mean by the "high speed" ip ?

**Comment by hjone72** [comment]
I tried what Neodark7 suggested, in the .cache/acd_cli/endpoint_data file
but am also getting an error:
 " failed. Code: 403, msg: {"logref":"b65fd6a6-bd47-11e5-9d8a-b1e15d68d892","message":"Account not found","code":"ACCOUNT_NOT_FOUND"}"

I also have a server in France which i'm using it with. Getting very slow uploads.

I was looking at trying to use a VPN for acd only...

**Comment by pmwoodward3** [comment]
Today im getting particularly slow speed, less than 15MB/s down from 60MB/s.

**Comment by dellipse** [comment]
I am getting the same thing as hjone72 and Neodark when I change from 
    "contentUrl": "https://content-us.drive.amazonaws.com/cdproxy/",
to
    "contentUrl": "https://content-eu.drive.amazonaws.com/cdproxy/",

It looks like it is uploading great, but then I get the ACCOUNT_NOT_FOUND error and when I look at the web base ACD interface, the file is not there.  Is there something else that needs to be done, or are we locked to the regions we originally signed up in (US/EU/JP)?  Does Amazon allow you to change regions with a support ticket?

**Comment by Neodark7** [comment]
what do you mean by "regions we originally signed up" ? cause i've buy my account on amazon.us but with a FR ip. and it does not work with the "eu url" ...
And i don't want to risk to do a ticket to change my region cause in france it cost approx. 440$/year for just 1to of storage... so if they change the prices too... x)

**Comment by dellipse** [comment]
I see your point on that, too.
I signed up in the US, but use it with my computers in France, Canada, and the US.  The "us" endpoint is slower than the "eu" endpoint but it does work. I can get equivalent speeds when I use multiple connections, but it appears that only works with multiple files.

Sorry for what may be a beginner type of question, but is there a way to have multiple connections for a single file? How about within the FUSE side of things? If so, that might be a way to solve the connection speed issues many are seeing these days.

If you are using a VPN to change geolocation detection, what are people using that seems to help?

**Comment by Neodark7** [comment]
the probleme with vpn is that i don't think many of them can handle a 1gbps connexion :/ and if it cause slow upload too it's not a solution... idk with proxys but i think it's the same problem... there might be a solution ? a different endpoint url ? or ip ? a setting or something ? @yadayada

**Comment by dellipse** [comment]
When I use the -x command to send multiple files, life is "in the fast lane" of ~22-25MB/s, but without it or if it is just a single file upload is is back to the "slow lane" of around 2-4 MB/s (on a 250Mbps link for reference.)  I don't know how to replicate that test within a FUSE mount though.

When on the "eu" endpoint, a single file does just fine at ~22-25MB/s, but fails since that is not where my account "lives" so it isn't a solution.

**Comment by msh100** [comment]
You can use `HTTPS_PROXY` if you really care. You can not use an EU endpoint for an NA account, check the price difference/terms and stop being ridiculous. Using a proxy may increase your speed if you connect from the US (as you should per terms anyway).

@pmwoodward3 do you really feel the need to inform us that you're **only** getting 15MB/s? It's personal cloud storage, not EBS - completely unrealistic expectations (the same applies to multiple people here).

Muting this issue now. Please think this through for 30 seconds before posting, this nonsense is notifying a lot of people.

**Comment by dellipse** [comment]
@msh100 Please don't consider this a complaint, but more of looking for a way to optimize the connections based on what can and cannot be done. I realize the limitations and that this is _personal _storage and not _enterprise class_ storage, nor do I expect it to work as such. If there is a way to performance tune the connections while still following the T&C of the service, shouldn't that be a worthy goal? For reference, the current speeds are fine for me and many others, but just because some do not find it working for them doesn't mean they are unrealistic. It wasn't too long ago that the FCC thought that 4/1 Mbps was what they called "broadband" but they have raised it to 25/3 Mbps, so times and usage change, just as they have since I became a 'Netizen in the 1980s.

If there is a better forum to work on this issue than within the issue itself, please suggest it and I would be happy to move it there, providing there is a way to keep history and allow others to learn from what is being discussed.

**Comment by yadayada** [comment]
Ok, I think everything has been said. 

Just changing the endpoint URL won't work. If someone needs to change your cloud drive's storage location, contact the customer support, see https://forums.developer.amazon.com/forums/thread.jspa?threadID=10440&tstart=0

Please move your conversions to Gitter or Amazon's Developer forum.

**Comment by 5YHgB** [comment]
Changing cloud storage location means they cancel your original subscription and then you register again at your desired Amazon location. 

I changed from Amazon.com to Amazon.de and it was kind an annoyance. They dont transfer your files and it took more than a few contacts with the helpdesk. Also I didnt receive a refund from Amazon.com yet either.  

Also I got this email now all of a sudden after all the work:

> Thank you for the nice conversation last week.
> 
> I am glad, that your Amazon Drive works fine now! Your Amazon drive account is now set to Amazon.de.
> 
> After you free trial ends, you will not longer be able to use Amazon Drive from Amazon.de. As you live in the Netherlands you must use Amazon Drive from Amazon.com
> We cannot transfer your data to another country, which means, that you need to backup your files - we transfer your account to Amazon.com - and then you can upload them again.
> This is a very important information, as you store more and more files in the cloud, the more you'll have to backup.
> 
> As we want to help you the best way, it would be the best to transfer your account as soon as possible.
> 
> Have a nice day
> 
> Freundliche Grüße
