### ISSUE TITLE
What's the proper way to use acd_cli on CentOS 7.1?

### ISSUE THREAD

**Issue by jsrober** [yadayada/acd_cli#183]
I have python and python3.4 installed, but can't seem to get acd_cli to run.

How do I add 'setuptools' to Python 3.4? I don't see an RPM for it.

Thanks!
John

```
johnr@conroe(~/git/acd_cli) 394$ python setup.py
  File "setup.py", line 8
    def read(fname: str) -> str:
                  ^
SyntaxError: invalid syntax
johnr@conroe(~/git/acd_cli) 395$ python3.4 setup.py
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
johnr@conroe(~/git/acd_cli) 396$

johnr@conroe(~/git/acd_cli) 392$ rpm -qa | grep python | sort
dbus-python-1.1.1-9.el7.x86_64
fuse-python-0.2.1-10.el7.x86_64
libselinux-python-2.2.2-6.el7.x86_64
newt-python-0.52.15-4.el7.x86_64
python-2.7.5-18.el7_1.1.x86_64
python34-3.4.3-2.el7.x86_64
python34-libs-3.4.3-2.el7.x86_64
python3-pkgversion-macros-1-3.el7.noarch
python-backports-1.0-8.el7.x86_64
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
python-configobj-4.7.2-7.el7.noarch
python-decorator-3.4.0-3.el7.noarch
python-iniparse-0.4-9.el7.noarch
python-libs-2.7.5-18.el7_1.1.x86_64
python-pip-7.1.0-1.el7.noarch
python-pycurl-7.19.0-17.el7.x86_64
python-pyudev-0.15-6.el7.noarch
python-setuptools-0.9.8-3.el7.noarch
python-slip-0.4.0-2.el7.noarch
python-slip-dbus-0.4.0-2.el7.noarch
python-urlgrabber-3.10-6.el7.noarch
rpm-python-4.11.1-25.el7.x86_64
johnr@conroe(~/git/acd_cli) 393$
```

**Comment by yadayada** [comment]
CentOS provides mostly Python 2.x packages, it seems. I'm sure there must be detailled guides for setting up Python 3 for CentOS. But if you ask me, I would start with getting setuptools [from PyPI](https://pypi.python.org/pypi/setuptools). Maybe somebody else can provide some extra information.

**Comment by jsrober** [comment]
Thank you. That's what I did and it's working wonderfully right now.

I built Python 3.5.0 from src. I had to install various lib/devel rpms (readline, bzip2, openssl) to get Python to build completely.

I was able to 'sync' and 'mount' and now I'm pushing files into ACD! I'm so thrilled with this. 

THANK YOU SO MUCH for building this software!

John
