### ISSUE TITLE
ONLINE_PROXY_FLEET_FAILURE

### ISSUE THREAD

**Issue by a5m0** [yadayada/acd_cli#186]
I am getting this error + sync failed

15-11-03 20:23:56.072 [ERROR] [acd_cli] - Uploading "example." failed. RequestError: 503, {"logref":"","message":"OPF (Online Proxy Fleet) unavailable","code":"ONLINE_PROXY_FLEET_FAILURE"}.
RequestError: 503, [acd_api] no body received.  8409/14452    9.1MB/s   03:09m
15-11-03 20:24:28.720 [CRITICAL] [acd_cli] - Sync failed.

**Comment by aus** [comment]
I got the same error. I tried resetting my my oauth against `tensile-runway-92512.appspot.com` and Amazon responds with a `500 Service Unavailable`. I searched Twitter and it looks like other applications were affected. I'd pin this one on Amazon.

**Comment by a5m0** [comment]
Yeah I was getting errors when trying to check in the webui, I'll check again tomorrow just to ensure everything is ironed out.

**Comment by yadayada** [comment]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
