### ISSUE TITLE
Deleting a node with a name starting with `-`

### ISSUE THREAD

**Issue by jmoriau** [yadayada/acd_cli#187]
I ran into this issue today, consider this:

    $ acd_cli ls /BUCKET | grep filename
    [-JgLhSg2SyqbPHEQZmcKNZ] [A] filename

    $ acd_cli trash -JgLhSg2SyqbPHEQZmcKNZ
    usage: acd_cli trash [-h] node
    acd_cli trash: error: the following arguments are required: node

    $ acd_cli trash '-JgLhSg2SyqbPHEQZmcKNZ'
    usage: acd_cli trash [-h] node
    acd_cli trash: error: the following arguments are required: node

    $ acd_cli trash \-JgLhSg2SyqbPHEQZmcKNZ
    usage: acd_cli trash [-h] node
    acd_cli trash: error: the following arguments are required: node

    $ acd_cli trash "-JgLhSg2SyqbPHEQZmcKNZ"
    usage: acd_cli trash [-h] node
    acd_cli trash: error: the following arguments are required: node

I tried everything I could think of but `acd_cli` is convinced that the node name is an option, I see why but I don't see how to fix this :/

Any idea ?

**Comment by HazCod** [comment]
Tried `acd_cli trash "-JgLhSg2SyqbPHEQZmcKNZ"` ?

**Comment by jmoriau** [comment]
It's the last one I tried see the examples I pasted before.

**Comment by yadayada** [comment]
See #30 or ``acd_cli -h``.
