### ISSUE TITLE
Copying files via encfs exceedingly slow

### ISSUE THREAD

**Issue by FallingSnow** [yadayada/acd_cli#189]
Copying files into an encfs directory which encrypts them into my Amazon cloud mount point is incredibly slow. Encfs by itself is fast, so is acd, but when you put the two together, acd_cli hits 100% cpu usage and bottlenecks at about 73 KB/s.

If you can tell me how to profile acd during my transfer, I would love to profile it for you.

**Comment by yadayada** [comment]
Please define 'fast' and tell me what speed you get with a non-FUSE upload.

**Comment by FallingSnow** [comment]
With a non-encfs, non-FUSE upload via `acd_cli upload` my upload bandwidth is completely saturated at 2.5MB/s and cpu usage doesn't move about 1%.

**Comment by breunigs** [comment]
also see Siennox comments in another ticket, regarding the same issue:
https://github.com/yadayada/acd_cli/issues/97#issuecomment-148186902
https://github.com/yadayada/acd_cli/issues/97#issuecomment-148509262

**Comment by dellipse** [comment]
I also see this issue, and referenced it in another issue (just not by number to make sure the were not linked since separate issues, of course.)

However, @yadayada made the following comment in the other post
```
dellipse: ...until the acd_cli/encfs combination speed issues are fixed
yadayada: Not going to happen.
```
Now I am curious to know if it is an issue that cannot be fixed or will not be fixed. If it cannot be fixed using the combination, would it be a possible enhancement to integrate the functionality of the encryption/decryption within acd_cli?  I am sure there are many people who would like to have cloud based storage that held the provider to a "zero knowledge" standard by encrypting the data before it was event sent to the provider.

**Comment by HazCod** [comment]
I also wonder if the issues would be the same if using ecryptfs

**Comment by FallingSnow** [comment]
ecryptfs didn't even work for me when I tried it, kept getting IO errors/invalid address.

**Comment by yadayada** [comment]
>Now I am curious to know if it is an issue that cannot be fixed or will not be fixed.

If you tell me what the cause is, I'll tell you whether I can and will fix 'it'.

**Comment by FallingSnow** [comment]
> If you tell me what the cause is, I'll tell you whether I can and will fix 'it'.

I don't know python, is there a basic way to try to profile `acd_cli` while trying to run encfs so I can attempt to find the section that is boosting cpu usage to 100%?

I already tried `python -m cProfile -s time -o /tmp/acd_cli.profile acd_cli mount /mnt/.AmazonCloudRaw/`

**Comment by HazCod** [comment]
@FallingSnow Maybe you should wait for https://github.com/yadayada/acd_cli/issues/171 then?

**Comment by yadayada** [comment]
@FallingSnow I don't think it's a problem caused by excessive CPU usage.

@HazCod Changing the default consts does nothing for me. I tried fiddling with the buffer size, but the encfs write didn't get any faster.

**Comment by FallingSnow** [comment]
I just find it suspect because it hits 100-102% (out of 800% possible) cpu usage, almost like it's hitting a n imposed ceiling. When I first ran into this problem and I saw the (what appear to be limited) cpu usage I thought something within acd_cli was bottlenecking every time encfs was writing a chunk. Like a function that was detecting file system changes.

Oh well though, maybe encfs just isn't got to happen.

**Comment by egyptianbman** [comment]
I'm running into this as well.  I've got encfs unmounted, leaving me with the encrypted directory that I'm trying to sync to ACD.  I'm running:

```
acdcli upload --max-connections=8 /path/to/encrypted-dir/* /.private
```

One of my cores is running at 100% and upload is considerably slow.  Is this caused by the files being encrypted somehow?

**Comment by ratherDashing** [comment]
@egyptianbman just do a reverse encfs mount and create a cron script to upload the encrypted files every so often.  you can use a mkdir on a lock dir to make sure you don't run two uploads at once:

if mkdir ~/mylock; then

**Comment by egyptianbman** [comment]
Actually, I was trying to upload 100gb.  What I found out is that it took a long time to actually start.  I'm guessing directory creation or something of the sort.  After a while, it ended up being threaded, uploading at a much faster rate.

**Comment by HazCod** [comment]
@egyptianbman Yeah, acdcli first recursively creates the directories

**Comment by beam** [comment]
Same issue here, enc-fuse and acd-fuse is slow.
Now i use encfs --reverse and then encrypted directory upload via acd_cli and this works well. Fill 100% of my upload.

**Comment by b-rockx** [comment]
Hopefully this can get resolved soon. I've been trying to use different methods to upload my 2TB but I don't have enough space to encrypt everything first then upload the entire directory. However, the using the reverse option seems to work for now.

**Comment by yadayada** [comment]
I enabled the big_writes flag in the last commit. I.e. the the write block size should be 128K instead of 4K.

My write throughput is 10Mbit/s either way (without encfs). Could anyone with a faster uplink comment about their before/after throughput with encfs?

**Comment by ratherDashing** [comment]
I have a 75 megabit upload and it pegged a cpu core before I got to fill up my bandwidth.  I was getting around 15 megabit before i pegged a core.  I do have an old pentium g3220 though so people with newer chips with better single thread performance could possibly fill up their uplink.

**Comment by Sytanek** [comment]
Hitting 100Mbit+ without, about 20Mbit with encfs.

**Comment by rizjuan1** [comment]
Just wanted to add that this was an awesome addition! In my tests with an an older version of acd_cli from PyPI I get about 5MB/s (40mbps) for FUSE uploads but with the new version I max out my line speed at 40MB/s (320mbps). You rock!

**Comment by ianling** [comment]
This is not fixed.

**Comment by Thinkscape** [comment]
Confirming this. There's some kind of weird performance leak that happens only when copying to a encfs path. Notice that it's the `acd_cli` process that's eating all the CPU, not the encfs. This results in extremely slow uploads. It doesn't behave the same when copying the other way around (i.e. download from encfs to local drive)

![image](https://cloud.githubusercontent.com/assets/270528/17565161/8bd570ba-5f36-11e6-9e75-9b448d1f3689.png)

**Comment by mescon** [comment]
Same problem here - extreme CPU usage when doing uploads of encrypted files.
I'm using the latest acd_cli from git and encfs 1.8.1. 

This is how I mount it:
```
sudo -u mescon acd_cli mount --allow-other /mnt/.acd
ENCFS6_CONFIG='/etc/encfs.xml' encfs --extpass=/sbin/pass_acd.sh /mnt/.acd/ /mnt/acd/ -- -o allow_other,gid=1000,uid=1000
```

![image](https://cloud.githubusercontent.com/assets/5875228/18023067/fae6725e-6bf4-11e6-97f7-cf1f4c94416e.png)

**Comment by nDiVinEx** [comment]
Why is this still closed? The problem still persists.. I'm having the exact same problem, haven't managed to find a fix yet.

**Comment by vnpavanelli** [comment]
Hi,
It seems the problem is still there, with default settings my CPU was limiting on 100% and got about 20mbps upload.
I'm running acd_cli 0.3.2, api 0.9.0 and looked acd_fuse.py and it haves the big_writes option, but in the log file it was sending 1024 bytes per call when under encfs.

I changed the encfs blocksize from 1024 to 4096 and it seems to improve a lot.
Normal copy into the ACD_fuse was using 128k blocks and worked very well here.

How to force it to use a 128k block size under encfs?

**Comment by yadayada** [comment]
>How to force it to use a 128k block size under encfs?

I think you've hit the limit with 4k blocks.

**Comment by mwoelfer** [comment]
@vnpavanelli if I understood you correctly, you were able to improve this behavior by changing the blocksize from 1024 to 4096.

Can you tell me how? :)

Thanks

**Comment by Thinkscape** [comment]
4k is the limit. It doesn't improve much, though. I've tried it and with `100%` cpu load it went from something like 2Mbps to maybe 10Mbps, while `acd_cli upload` easily saturates 100Mbps with around 2% cpu usage.

You can select block size during encfs config - just `encfs /some/acd/folder /some/mount/point` and it runs the config process - select manual and one of the first questions will be block size.

**Comment by mwoelfer** [comment]
ok I can confirn this.
I changed blocksize in encfs.xml to 4096.
The speed has been improved from 2MB/s to 8MB/s. :)
