### ISSUE TITLE
Invalid ID in cache

### ISSUE THREAD

**Issue by honeygrahams** [yadayada/acd_cli#192]
```
[ERROR] [acd_cli] - Uploading "XXXXXXXXXXXXXXXXX.flv" failed. RequestError: 400, {"logref":"ed4e936d-8d39-11e5-ae6e-5b0fd460fd0c","message":"One of the parentId doesn\u0027t exists","code":""}
```

I have deleted and reset my ID's multiple times. 
I always get the same error code. I have also reinstalled the acd_cli system but nothing works.

**Comment by yadayada** [comment]
Which upload command did you use to get this error?

Also, please resolve the upload path to the ID, and try get the metadata for that ID and post the result.

>I have deleted and reset my ID's multiple times. 

What do you mean by this?
