### ISSUE TITLE
Logging...?

### ISSUE THREAD

**Issue by 2marshall** [yadayada/acd_cli#196]
I see that you have automatic logging enabled as a new feature. where is the logging file stored and does it display like an rsync transfer would? I would love to see the files that upload each time.

thanks

**Comment by yadayada** [comment]
There are logging files in your cache path. Execute ``acdcli -v init`` to find out what it is.

**Comment by 2marshall** [comment]
thanks, this is just what I needed.

**Comment by acornspaul** [comment]
I think this is another good candidate for a FAQ.
