### ISSUE TITLE
Exclude filter on upload [feature request]

### ISSUE THREAD

**Issue by StefanUG** [yadayada/acd_cli#20]
Hi there.

Fantastic work. Thanks!

I have a request for being able to specify exclude filters for the upload command.
I have a large photo library which also contain video files, but I only want to upload the photos so that the video files don't take up my quota on the Amazon Drive.

For the moment I have simply added these lines to the upload_file function:

    # Test to not upload mov and mp4 files
    if short_nm.lower().endswith('.mov') or short_nm.lower().endswith('.mp4'):
        print('Skipping "%s" because it\'s a movie.' % short_nm)
        return 0

And while this is of course not an ideal long term fix, it solves my immediate problem.

Keep up the good work.

Thanks,
Stefan

**Comment by yadayada** [comment]
It's now possible to exclude a file ending when uploading or downloading by providing an extra argument. For your above use case, this would be "-xe mov -xe mp4".
