### ISSUE TITLE
Upload throttle?

### ISSUE THREAD

**Issue by dmb247** [yadayada/acd_cli#203]
Hi. I am using my Ubuntu VPS to uload files to Amazon. 

My connection is 1gbps up/down, but it seems that my uploads are being throttled at abour 10Mb/s.

This doesn't happen for Google Drive at all. It nearly maxes out uploading at 1gbps. I have tried using -x 4 and -x 8 for more upload connections, but it doesn't seem to make a difference in the speeds. 

Any ideas are appreciated.

**Comment by yadayada** [comment]
See #181.
