### ISSUE TITLE
Option for .cache/acd_cli

### ISSUE THREAD

**Issue by xswqaz** [yadayada/acd_cli#204]
Failed to execute in crontab or atd for failed to search .cache/acd_cli
It would be better add if option for .cache/acd_cli added

**Comment by yadayada** [comment]
Your message is very unclear.

The cache path may be overriden manually, see https://acd-cli.readthedocs.org/en/latest/setup.html#environment-variables.

**Comment by xswqaz** [comment]
Thank you
It was misunderstood
