### ISSUE TITLE
RFE: automatic sync for 10GB+ files

### ISSUE THREAD

**Issue by mattdm** [yadayada/acd_cli#209]
As per issue #8, files over 10GB may succeed but give a timeout error. It would be slick if acd_cli would automatically sync and verify when timeout errors are received when uploading large files, and only return an error if that fails.

**Comment by zmwangx** [comment]
Sync could be an expensive operation though.

**Comment by breunigs** [comment]
I tested manually if this approach _always_ works, and that doesn't seem to be the case. When the upload receives a timeout error, the file is most likely still processed by the server -- it doesn’t show up in the official web interface and `acdcli sync && acdcli metadata <file>` does not return anything. The file sizes I tried were 20 GB and 15 GB.

**Comment by yadayada** [comment]
I think the idea was to wait until the uploaded file is hashed. The parent folder's list of children could be retrieved in an interval of maybe 1 minute 

Since my connection has a meager 50Mbit/s, it would be nice if someone could find out how long the processing takes approximately for large files.

**Comment by yadayada** [comment]
@mattdm I've put together something in the dev branch if you want to test it.

**Comment by zmwangx** [comment]
:+1:

**Comment by zmwangx** [comment]
Nitpick: I think the commit message is a little bit confusing.

> Wait 10 minutes for metadata (update) when an upload/overwrite request fails with timeout error.

When I first read this I thought we'll just sit for ten minutes... The doubt was cleared once I read the code.
