### ISSUE TITLE
Slow transfers when using acd_cli via FUSE mount

### ISSUE THREAD

**Issue by dellipse** [yadayada/acd_cli#212]
I am getting anywhere from 1/2 to 1/10th the average speed when using rsync with data that originates on ACD that I am accessing via acd_cli's FUSE mount.

What would you suggest is the best way to attempt to troubleshoot this to determine where the issue is?

(CPU is minimal, network bandwidth is not an issue, disk I/O is not an issue on the receiving side of the files)

**Comment by pmwoodward3** [comment]
I'm having the same slow performance.

Down from ~110mb/s to 2.2mb/s with fuse.

**Comment by JigSawFr** [comment]
Confirmed

**Comment by Yol250** [comment]
I'm having the same behaviour here. On a 30MB file : 

- "acd_cli dl" reports 6.8MB/s
- rsync reports 260kB/s
- cp takes roughly the same time as rsync

I've got a small VPS, and the CPU is actually under medium to heavy load (it's an Atom 230, 1.6GHz) using acd_cli mount during the copy. On the other hand acd_cli download does not even show up in htop, so I guess that there is *a lot* more happening with fuse.

**Comment by jheredianet** [comment]
Same problem here, I have a 200/200mbps fiber internet connection:
- "acd_cli dl" reports 24 MB/s
- cp, rsync or any other native linux tools report  5.5MB/s

**Comment by nphil** [comment]
Having the same issue, reading from the mounted drive is pretty slow causing plex to buffer constantly.

**Comment by dellipse** [comment]
I am having slow performance using the FUSE mount, too.  However, the
download function outside of the FUSE system is working at full speed.

**Comment by nphil** [comment]
Can confirm, using the acd_cli download option maxes out my vps connection. I used rsync to test the speed by copying from cloud drive to local hdd, and the speed was around 1-2 MB/s with very sporadic bursts to 20-30.

**Comment by nphil** [comment]
Using the acd_cli download option maxes out my vps connection. I used rsync to test the speed by copying from cloud drive to local hdd, and the speed was around 1-2 MB/s with very sporadic bursts to 20-30.

Read somewhere that amazon can throttle downloads on unauthorized applications, but I'm not sure why it would only affect fuse

**Comment by jheredianet** [comment]
@nphil you are right I've read about amazon too, but in this case it seems to be something just related to fuse. I'm was wondering if it depends on the version of fuse.
I'm using version 2.9.5 (get it by  fusermount -V)

**Comment by dellipse** [comment]
FUSE performance has continued to get worse, down to a range of 1/10-1/100 of the same file downloaded with the _acd_cli dl_ command.

Any ideas where to look or what would be needed for troubleshoot this issue with acd_cli and FUSE?

For reference:
acd_cli commit 02c1120d3e307c0a8d877d67e534e54b990eacd1 (latest)
Python 3.4.3
Linux-3.14.32-xxxx-grs-ipv6-64-x86_64-with-Ubuntu-14.04-trusty
fusermount version: 2.9.2

**Comment by yadayada** [comment]
Any changes with https://github.com/yadayada/acd_cli/commit/87287cefb70adb2183023c0271a2027c92b88761?

**Comment by pmwoodward3** [comment]
acdcli fuse is still getting 4-6mb/s for me using rsync.

**Comment by dellipse** [comment]
It did improve a bit, however it is still MUCH slower (avg. 1/3) the transfer rate I get with the download command.

Test Transfer via FUSE using _pv_
347MB 0:02:33 [avg 2.26MB/s / hi 5.22MB/s / low 543KB/s]

Test Transfer via _acd_cli dl_
[#########################] 100.0% of  348MiB  1/1    6.7MB/s       0s

**Comment by saqebakhter** [comment]
I get about 4-6MB/s with Fuse and 50MB/s without so huge difference.  


-Saqeb 






On Sun, Feb 7, 2016 at 11:30 AM -0800, "dellipse" <notifications@github.com> wrote:












It did improve a bit, however it is still MUCH slower (avg. 1/3) the transfer rate I get with the download command.



Test Transfer via FUSE using pv

347MB 0:02:33 [avg 2.26MB/s / hi 5.22MB/s / low 543KB/s]



Test Transfer via acd_cli dl

[#########################] 100.0% of  348MiB  1/1    6.7MB/s       0s
