### ISSUE TITLE
frequent "error refreshing authentication token" errors

### ISSUE THREAD

**Issue by mattdm** [yadayada/acd_cli#214]
I have acd_cli set up with the "easy auth" method. I'm using the command-line upload (not fuse) for directories with about 1000 image files each (in a loop, one at a time).

This mostly works, but after a while, I get something like

    15-12-03 11:41:00.588 [ERROR] [acd_cli] - Uploading "20060308_c5060wz_p3082624.jpg" failed. RequestError: 1004, Error refreshing authentication token: {"error_description":"Not authorized for requested operation","error":"unauthorized_client"}.

and it keeps doing the back-off timeout thing for increasing intervals but it fails each new time too
hitting ctrl-c and then restarting, though — no problem.

    $ python3 -c 'import platform as p; print("%s\n%s" % (p.python_version(), p.platform()))'
    3.4.3
    Linux-4.2.6-301.fc23.x86_64-x86_64-with-fedora-23-Twenty_Three

**Comment by yadayada** [comment]
Please run acdcli in debug mode and have a look at the output of http.client.

**Comment by mattdm** [comment]
Here you go (with secret and token strings replaced with XXX.)

    15-12-05 15:00:43.494 [INFO] [acd_cli] - Uploading rejected-offline-045/20071228_k10d_imgp2964.jpg
    15-12-05 15:00:43.499 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.262054s
    [#####################    ]  86.5% of    2GiB   909/1043  712.1KB/s   05:36mESC[K^M
    15-12-05 15:00:43.762 [INFO] [acdcli.api.oauth] - Token expired at 2015-12-05 15:00:43.513166.
    15-12-05 15:00:43.762 [INFO] [acdcli.api.oauth] - Refreshing authentication token.
    15-12-05 15:00:43.763 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): api.amazon.com
    send: b'POST /auth/o2/token HTTP/1.1\r\nHost: api.amazon.com\r\nContent-Type: application/x-www-form-urlencoded\r\nUser-Agent: acd_cli/0.3.1 python-requests/2.7.0 CPython/3.4.3 Linux/4.2.6-301.fc23.x86_64\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\nContent-Length: 687\r\n\r\nclient_secret=XXX&client_id=amzn1.application-oa2-client.XXX&refresh_token=XXX&redirect_uri=http%3A%2F%2Flocalhost&grant_type=refresh_token'
    reply: 'HTTP/1.1 400 Bad Request\r\n'
    header: Date header: Server header: x-amzn-RequestId header: X-Amz-Date header: x-amzn-ErrorType header: Content-Type header: Vary header: Content-Encoding header: Content-Length header: Cneonction
    15-12-05 15:00:43.956 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST /auth/o2/token HTTP/1.1" 400 94
    15-12-05 15:00:43.967 [ERROR] [acd_cli] - Uploading "20071228_k10d_imgp2964.jpg" failed. RequestError: 1004, Error refreshing authentication token: {"error_description":"Not authorized for requested operation","error":"unauthorized_client"}.
    15-12-05 15:00:43.985 [INFO] [acd_cli] - Uploading rejected-offline-045/20071228_k10d_imgp2964.jpg.caption
    15-12-05 15:00:43.989 [DEBUG] [acdcli.api.backoff_req] - Retry 1, waiting 1.599924s
    [#####################    ]  86.5% of    2GiB   909/1043  711.8KB/s   05:37mESC[K^M[#####################    ]  86.5% of    2GiB   909/1043  711.8KB/s   05:37mESC[K^M[#####################    ]  86.5% of    2GiB   909/1043  711.8KB/s   05:37mESC[K^M[#####################    ]  86.5% of    2GiB   909/1043  537.5KB/s   07:26mESC[K^M[#####################    ]  86.5% of    2GiB   909/1043  363.2KB/s   11:00mESC[K^M[#####################    ]  86.5% of    2GiB   909/1043  188.7KB/s   21:11mESC[K^M
    15-12-05 15:00:45.591 [INFO] [acdcli.api.oauth] - Token expired at 2015-12-05 15:00:43.513166.
    15-12-05 15:00:45.591 [INFO] [acdcli.api.oauth] - Refreshing authentication token.
    15-12-05 15:00:45.593 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): api.amazon.com
    send: b'POST /auth/o2/token HTTP/1.1\r\nHost: api.amazon.com\r\nContent-Type: application/x-www-form-urlencoded\r\nUser-Agent: acd_cli/0.3.1 python-requests/2.7.0 CPython/3.4.3 Linux/4.2.6-301.fc23.x86_64\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\nContent-Length: 687\r\n\r\nclient_secret=xxx&client_id=amzn1.application-oa2-client.XXX&refresh_token=XXX&redirect_uri=http%3A%2F%2Flocalhost&grant_type=refresh_token'
    reply: 'HTTP/1.1 400 Bad Request\r\n'
    header: Date header: Server header: x-amzn-RequestId header: X-Amz-Date header: x-amzn-ErrorType header: Content-Type header: Vary header: Content-Encoding header: Content-Length header: Cneonction
    15-12-05 15:00:45.769 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST /auth/o2/token HTTP/1.1" 400 94
    15-12-05 15:00:45.771 [ERROR] [acd_cli] - Uploading "20071228_k10d_imgp2964.jpg.caption" failed. RequestError: 1004, Error refreshing authentication token: {"error_description":"Not authorized for requested operation","error":"unauthorized_client"}.
    15-12-05 15:00:45.789 [INFO] [acd_cli] - Uploading rejected-offline-045/20071228_k10d_imgp2965.jpg
    15-12-05 15:00:45.795 [DEBUG] [acdcli.api.backoff_req] - Retry 2, waiting 0.036004s
    15-12-05 15:00:45.831 [INFO] [acdcli.api.oauth] - Token expired at 2015-12-05 15:00:43.513166.
    15-12-05 15:00:45.831 [INFO] [acdcli.api.oauth] - Refreshing authentication token.

**Comment by yadayada** [comment]
>I have acd_cli set up with the "easy auth" method. 

But then, there is a POST request to api.amazon.com with a client_id and client_secret...
>send: b'POST /auth/o2/token HTTP/1.1\r\nHost: api.amazon.com\r\nContent-Type: application/x-www-form-urlencoded\r\nUser-Agent: acd_cli/0.3.1 python-requests/2.7.0 CPython/3.4.3 Linux/4.2.6-301.fc23.x86_64\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\nContent-Length: 687\r\n\r\nclient_secret=XXX&client_id=amzn1.application-oa2-client.XXX&refresh_token=XXX&redirect_uri=http%3A%2F%2Flocalhost&grant_type=refresh_token'
reply: 'HTTP/1.1 400 Bad Request\r\n'

Can you spot a difference between the failed requests and a successful request after you restarted?

**Comment by mattdm** [comment]
Doh! I had a client_data file lingering from switching to that method and then back. I assumed it wasn't a problem because of how things _mostly_ work. PEBKAC!
