### ISSUE TITLE
Cache re-implementation

### ISSUE THREAD

**Issue by yadayada** [yadayada/acd_cli#216]
Task: Rewrite the node cache without SQLAlchemy to improve FUSE path resolution speed (by at least one order of magnitude) and possibly fix threading/multiprocessing issues.

Some related issues:
- [x] #97 
- [x] #208

threading/multiprocessing issues
- [ ] #124  --> same thing #231
- [x] #215 

TODO:
- [x] rewrite tests

[getattr branch](https://github.com/yadayada/acd_cli/tree/getattr) now merged into master branch.

**Comment by ratherDashing** [comment]
I love this new update.  For me it works great for directories with not many subdirectories.

I see it hitting Amazon and taking about 1 second of timeout before hitting Amazon again for files which is slowed some things for me down to a crawl:

15-12-16 15:54:21.669 [DEBUG] [acdcli.acd_fuse] - <- read 32768
15-12-16 15:54:21.670 [DEBUG] [acdcli.acd_fuse] - -> read /Plex/1oPlYii2vCyMRVQdwYrS9Kle/0rxiwc7lcoVuPFQ8TOyDVZGlbrPdJ3KoUoT2ySIFGGFUS,/IiMrDahDwE6skimFrcN45ZrDzrkqHJo5dgnxvj8Q2E4kUywBgH1W5H3GQNVUhFti0Nmc3zruv8OseJuedosDDWk- (4096, 540672, 571)
15-12-16 15:54:21.671 [DEBUG] [acdcli.acd_fuse] - s: 49152-310753257; r: 540672-544767
15-12-16 15:54:21.671 [DEBUG] [acdcli.acd_fuse] - s: 310753258-310753257; r: 540672-544767
15-12-16 15:54:21.671 [DEBUG] [acdcli.api.content] - chunk o 540672 l 524288000
15-12-16 15:54:21.671 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.420634s
15-12-16 15:54:22.092 [INFO] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/BJ1FtBu_QvmFh9rThTx55Q/content"
15-12-16 15:54:22.093 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): content-na.drive.amazonaws.com
15-12-16 15:54:22.364 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/BJ1FtBu_QvmFh9rThTx55Q/content HTTP/1.1" 206 310212586
15-12-16 15:54:22.365 [DEBUG] [acdcli.acd_fuse] - <- read 4096
15-12-16 15:54:22.366 [DEBUG] [acdcli.acd_fuse] - -> read /Plex/1oPlYii2vCyMRVQdwYrS9Kle/0rxiwc7lcoVuPFQ8TOyDVZGlbrPdJ3KoUoT2ySIFGGFUS,/IiMrDahDwE6skimFrcN45ZrDzrkqHJo5dgnxvj8Q2E4kUywBgH1W5H3GQNVUhFti0Nmc3zruv8OseJuedosDDWk- (4096, 1269760, 571)
15-12-16 15:54:22.367 [DEBUG] [acdcli.acd_fuse] - s: 544768-310753257; r: 1269760-1273855
15-12-16 15:54:22.367 [DEBUG] [acdcli.acd_fuse] - s: 49152-310753257; r: 1269760-1273855
15-12-16 15:54:22.367 [DEBUG] [acdcli.acd_fuse] - s: 310753258-310753257; r: 1269760-1273855
15-12-16 15:54:22.367 [DEBUG] [acdcli.api.content] - chunk o 1269760 l 524288000

Here is an example of a ~1s wait:

15-12-16 15:54:22.367 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.944432s

15-12-16 15:54:23.313 [INFO] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/BJ1FtBu_QvmFh9rThTx55Q/content"
15-12-16 15:54:23.314 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): content-na.drive.amazonaws.com
15-12-16 15:54:23.713 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/BJ1FtBu_QvmFh9rThTx55Q/content HTTP/1.1" 206 309483498
15-12-16 15:54:23.728 [DEBUG] [acdcli.acd_fuse] - <- read 4096
15-12-16 15:54:23.729 [DEBUG] [acdcli.acd_fuse] - -> getattr /Plex (None,)
15-12-16 15:54:23.729 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_atime': 1450299263.729667, 'st_nlink': 1, 'st_mtime': 1449643860.635, 'st_ctime': 1444943743.339, 'st_mode': 16895}
15-12-16 15:54:23.729 [DEBUG] [acdcli.acd_fuse] - -> getattr /Plex/1oPlYii2vCyMRVQdwYrS9Kle (None,)
15-12-16 15:54:23.730 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_atime': 1450299263.7304585, 'st_nlink': 1, 'st_mtime': 1446238931.006, 'st_ctime': 1444944504.083, 'st_mode': 16895}
15-12-16 15:54:23.730 [DEBUG] [acdcli.acd_fuse] - -> getattr /Plex/1oPlYii2vCyMRVQdwYrS9Kle/0rxiwc7lcoVuPFQ8TOyDVZGlbrPdJ3KoUoT2ySIFGGFUS, (None,)
15-12-16 15:54:23.731 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_atime': 1450299263.731223, 'st_nlink': 1, 'st_mtime': 1444948567.477, 'st_ctime': 1444944506.202, 'st_mode': 16895}
15-12-16 15:54:23.731 [DEBUG] [acdcli.acd_fuse] - -> getattr /Plex/1oPlYii2vCyMRVQdwYrS9Kle/0rxiwc7lcoVuPFQ8TOyDVZGlbrPdJ3KoUoT2ySIFGGFUS,/IiMrDahDwE6skimFrcN45ZrDzrkqHJo5dgnxvj8Q2E4kUywBgH1W5H3GQNVUhFti0Nmc3zruv8OseJuedosDDWk- (None,)

**Comment by saqebakhter** [comment]
is the getattr branch stable enough to use or do you think it will be merged into master soon ?

**Comment by ratherDashing** [comment]
I use it as my daily driver.  It's realllly slow the first time you scan a directory with multiple sub directories (like your legally purchased music).  After the first time its fast so if you purchase an additional album and want to scan that directory for updates, it's almost as fast as ext4 natively
