### ISSUE TITLE
Could not resolve path when using Unix style dir

### ISSUE THREAD

**Issue by ultimoamore** [yadayada/acd_cli#218]
`acd_cli.exe upload /c/ADATA_NOBACKUP/DSC00860.JPG /Immagini`
gives: 
`Could not resolve path "C:/Program Files/Git/Immagini"`
    
`acd_cli.exe upload /c/ADATA_NOBACKUP/DSC00860.JPG Immagini`
gives:
` Invalid ID format: "Immagini".`

While using the ID (found using find) everything works:
`acd_cli.exe upload /c/ADATA_NOBACKUP/DSC00860.JPG YACn_PLrSICKWqmS7Nl-iw`
`[#########################] 100.0% of  178KiB  1/1   60.8KB/s       0s`

How am I supposed to pass the output path?

Thank you

**Comment by yadayada** [comment]
If "/Immagini" is a valid absolute remote path, that's the correct way to specify the parent path.

>``Could not resolve path "C:/Program Files/Git/Immagini"``

Your shell seems to expand the path you specified (to a local directory). Please see if you can quote the path. Which OS and shell are you using?

**Comment by ultimoamore** [comment]
Yes I was using git bash, the additional leading slash worked

Thank you very much
