### ISSUE TITLE
After installed, I type acdcli or acd_cli in terminal and I don't get to run the program

### ISSUE THREAD

**Issue by bunset** [yadayada/acd_cli#220]
Hello!
Thanks for the program.
I have installed in my mac el capitan having installed python 3.5 and following the steps. It shows succesfully installed acd_cli-0.3.1. All fine without errors. But when I try to type acdcli or acd_cli, it shows command not found.
I don't get to find where is the executable file. Where is it installed please? or How can I do to have the acdcli command available in terminal?

Thank you very much and kind regards.

**Comment by yadayada** [comment]
``pip3 uninstall acdcli <<< "n" | grep bin`` should show you where `acd_cli.py` and its two console scripts are. You might want to add this bin path to your $PATH (please consult a search engine on how to do this).

**Comment by bunset** [comment]
Your are a phenomeno!, awesome, located!, there it was. Thank you very much yadayada! :)

**Comment by bunset** [comment]
Mine was in /Library/Frameworks/Python.framework/Versions/3.5/bin/
