### ISSUE TITLE
Help with fuse module.

### ISSUE THREAD

**Issue by BanterJSmoke** [yadayada/acd_cli#222]
I'm fairly new to all of this, and I have been looking for days. I don't know how to fix this. I get everything installed and I try to mount but fuse is not found. At one point, I had compiled fuse myself, pointed directly to the lib files, and got the error "/dev/fuse/ not allowed". Starting over, I am back at square one. 

I had this working on one install of Ubuntu Server 14.04, but I had to switch to a different vps provider. This build of ubuntu server 14.04 seems to have nothing preinstalled, i.e. manually installing, via apt-get, nano git fuse etc... and thus I have issues mounting.

```
acd_cli mount -ao --modules="subdir,subdir=/TV" /media/Amazon/TV
fuse: device not found, try 'modprobe fuse' first
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1437, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 959, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/acd_fuse.py", line 686, in mount
    **kwargs
  File "/usr/local/lib/python3.4/dist-packages/acdcli/bundled/fuse.py", line 416, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

**Comment by BanterJSmoke** [comment]
I updated to Ubuntu server 15.10, to try having everything installed and updated, same issue

**Comment by JigSawFr** [comment]
I can confirm ou that acd_cli is working perfectly on Ubuntu Server 15.10 :+1: 
If you try whitout modules, it is working ?

**Comment by maran** [comment]
Can you confirm fuse is loaded with `lsmod | grep fuse` ?

**Comment by BanterJSmoke** [comment]
entering lsmod | grep fuse does not show any output when i enter it

**Comment by yadayada** [comment]
>``fuse: device not found, try 'modprobe fuse' first``

**Comment by msh100** [comment]
> but I had to switch to a different vps provider

By any chance... OpenVZ? :smile:

**Comment by BanterJSmoke** [comment]
modprobe fuse
modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab108.8/modules.builtin.bin'
modprobe: FATAL: Module fuse not found.

**Comment by msh100** [comment]
Yep, fairly sure that's OpenVZ. If that's the case, ask your host to enable the kernel module for FUSE.

**Comment by BanterJSmoke** [comment]
I've also done `export LIBFUSE_PATH="/lib/x86_64-linux-gnu/libfuse.so.2"` after checking to see that libfuse.so.2 is in there. I rebuilt the vps with ubuntu server 14.04 and started over, done `sudo apt-get update` and `sudo apt-get upgrade`

**Comment by BanterJSmoke** [comment]
Yep, it's OpenVZ, thanks.
