### ISSUE TITLE
stream fails with "TypeError: get_child() missing 1 required positional argument: 'child_name'"

### ISSUE THREAD

**Issue by pendor** [yadayada/acd_cli#226]
Attempting to use the 'stream' command always fails with the following stack:

> 15-12-24 19:15:11.484 [ERROR] [acd_cli] - Traceback (most recent call last):
>   File "/usr/lib64/python3.4/site-packages/acdcli-0.3.1-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line  201, in wrapped
>     ret_val = f(*args, **kwargs)
>   File "/usr/lib64/python3.4/site-packages/acdcli-0.3.1-py3.4.egg/EGG-INFO/scripts/acd_cli.py", line  448, in upload_stream
>    child = cache.get_child(file_name)
> TypeError: get_child() missing 1 required positional argument: 'child_name'

(Pull request in-bound w/ one-line fix)

**Comment by yadayada** [comment]
Thanks.
