### ISSUE TITLE
Unable to mount with latest version

### ISSUE THREAD

**Issue by seppi91** [yadayada/acd_cli#233]
Hi,
since upgrading my acdcli revision today, I can't mount acd anymore. Seems like this issue is related with the latest commit (adding read-only support).

/usr/local/bin/acdcli -d mount /mnt/.acd-remote-enc
15-12-26 11:31:27.523 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
15-12-26 11:31:27.524 [INFO] [acd_cli] - TestPlugin attached.
15-12-26 11:31:27.524 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
15-12-26 11:31:27.524 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
15-12-26 11:31:27.525 [INFO] [acdcli.cache.schema] - DB schema version is 2.
15-12-26 11:31:27.579 [INFO] [acd_cli] - Last sync at 2015-12-26 10:26:19.005789.
15-12-26 11:31:27.580 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x7f60c3a35080>, action='mount', allow_other=False, allow_root=False, cache=<acdcli.cache.db.NodeCache object at 0x7f60c3a2ea20>, check=0, color=2, debug=1, foreground=False, func=<function mount_action at 0x7f60c3a0d1e0>, interval=60, log=True, modules='', nlinks=False, no_wait=False, nonempty=False, path='/mnt/.acd-remote-enc', read_only=False, single_threaded=False, utf=False, verbose=None)
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1432, in main
    sys.exit(args.func(args))
  File "/usr/local/bin/acd_cli.py", line 951, in mount_action
    ro=args.ro, foreground=args.foreground, nothreads=args.single_threaded,
AttributeError: 'Namespace' object has no attribute 'ro'

----------------------------------------------

python3 --version
Python 3.4.3

uname -a
Linux xxxxxxx 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**Comment by yadayada** [comment]
Fixed in  a468759.
