### ISSUE TITLE
Security profile initialization fails

### ISSUE THREAD

**Issue by anijap** [yadayada/acd_cli#240]
Setting up a security profile fails to generate a valid redirect URL: **[14924:14953:0105/170140:ERROR:nss_util.cc(839)] After loading Root Certs, loaded==false: NSS error code: -8018**

I have installed acd_cli via **pip3 install --upgrade --pre acdcli** and placed the appropriate security profile values in the cache file at **/home/anijap/.cache/acd_cli/client_data**

Initializing acd_cli via **acd_cli -v init** produces the output shown below (redacted to omit my real amazon client id).

>anijap@mesa:~$ acdcli -v init
>16-01-05 17:01:40.160 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin, ClementinePlugin, TestPlugin, TermsOfUsePlugin
>16-01-05 17:01:40.160 [INFO] [acd_cli] - TestPlugin attached.
>16-01-05 17:01:40.160 [INFO] [acd_cli] - Clementine executable not found.
>16-01-05 17:01:40.160 [INFO] [acd_cli] - TestPlugin attached.
>16-01-05 17:01:40.160 [INFO] [acd_cli] - TermsOfUsePlugin attached.
>16-01-05 17:01:40.161 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/anijap/.cache/acd_cli".
>A window will have opened at https://amazon.com/ap/oa?client_id=amzn1.application-oa2-client.**real_client_id_was_here**&response_type=code&scope=clouddrive%3Aread_all+clouddrive%3Awrite&redirect_uri=http%3A%2F%2Flocalhost
>Please log in or accept and enter the URL you have been redirected to: [14924:14953:0105/170140:ERROR:nss_util.cc(839)] After loading Root Certs, loaded==false: NSS error code: -8018
>Created new window in existing browser session.
>Fontconfig error: Cannot load default config file

**Comment by yadayada** [comment]
>[14924:14953:0105/170140:ERROR:nss_util.cc(839)] After loading Root Certs, loaded==false: NSS error code: -8018

I think that's an error/a warning your browser emitted. You can still enter the redirect URL.

**Comment by anijap** [comment]
The amazon.com redirect URL?
Going to that URL redirects me to **http://localhost/?error_description=lwa-invalid-parameter-bad-scope&error=invalid_scope**

That's why I assumed that the redirect URL would have been in the place where I have the nss_util.cc error.

Have you seen the lwa-invalid-parameter error before?

**Comment by yadayada** [comment]
That will happen if a) your security profile was created prior to June 2015 or b) the wrong permission level was chosen when whitelisting the security profile.

**Comment by anijap** [comment]
The security profile was created a few days ago, but what is this about choosing a permission level and whitelisting the profile?

When I created the profile, the only thing I had to set was the return URL.
I went back and there doesn't seem to be any place to set permission levels or to whitelist it. Am I missing something? Can you point me to a place where this is documented?

**Comment by yadayada** [comment]
... or c) you didn't whitelist your profile.

>The security profile was created a few days ago, but what is this about choosing a permission level and whitelisting the profile?

:-|

> Can you point me to a place where this is documented?

I could, but it's rather annoying that you would open an invalid issue before researching yourself. I am not your nanny.

**Comment by anijap** [comment]
My bad -- just found the link, I thought I had scoured all your documentation but I missed it earlier. My apologies.

**Comment by doegox** [comment]
Just in case someone like me comes across this ticket when looking for how to whitelist its profile and feels bad about asking where it's documented, see https://github.com/yadayada/acd_cli/issues/392
