### ISSUE TITLE
acdcli as root

### ISSUE THREAD

**Issue by calisro** [yadayada/acd_cli#243]
I am running for various reasons a acdcli mount owned by root.  The fuse module is presenting the data owned by root:root with a permission of 777 (because I specify  "--allow-other").  Fuse itself has options to allow us to specify a permission/ownership for a fuse FS but that is lacking in acdcli as far as I can tell.  Is there a way to specify similarly to regular fuse the options "umask=$umase,gid=$gid,uid=$uid" so that I can mount that FS as root yet the presentation of that mount pount would be owned by specific user along with specific permissions? 

I am assuming this would just be a passthrough set of commands to the fuse layer.

If this doesn't yet exist, can this be considered an improvement request?

**Comment by yadayada** [comment]
The uid and gid that may be passed to FUSE mounts seem have no effect. I've also checked that with sshfs.
If you absolutely must be running acd_cli as root, I suggest `sudo -u myuser ...`

I haven't implemented permission checks; there is only read-only and read+write. Which umask would you want to use and what's the intended purpose?

**Comment by calisro** [comment]
When a fuse volume is mounted as root, the directory structure looks like this:

drwxrwxrwx  1 root root    0 Jan 17 14:39 .
drwxr-xr-x 35 root root 4096 Dec 21  2012 ..
drwxrwxrwx  1 root root    0 Jan 17 14:44 cloude
drwxrwxrwx 1 root root 0 Jan  7 16:11 MJZrm2lkXekJAk8H1H-B7Ymy
drwxrwxrwx 1 root root 0 Jan 15 11:29 TPJw1mFD3OZ,6QNoeIKrN-wo

The objects are all set as root:root permission.  I am passing the '--allow-other' flag which makes the permissions look like this:  rwxrwxrwx (777).  This sort of works for me since it allows other users to read/write from it.  But what I am looking to do is run fuse as root but force the owner to be someuser:somegroup with a permission of 775.  Fuse allows for this.  

With fuse, you can specify these flags:
-o allow_other -o umask=775,gid=1005,uid=1010

When those are passed and the executing user is root, the volume would be presented and mounted AS user 1005:1010 with rwxrwxrw- permissions thus keeping security in check (not open to the world).

I'm not looking for acd_cli to actually manage any more permissions or anything but at the fuse layer, a root user can force what permissions/owner/group is assigned at the mount.

**Comment by yadayada** [comment]
First off, to quote myself
>The uid and gid that may be passed to FUSE mounts seem have no effect.

Secondly, what's wrong with using sudo?

>at the fuse layer, a root user can force what permissions/owner/group is assigned at the mount.

That doesn't work for me at least. Any user can set any uid/gid with no effect whatsoever on (group) ownership. [I even made fuse set the mounting user's uid and gid because it defaults to root's uid/gid.]

Umask only seems to affect execution permission. `--allow-other` will allow everyone to read/write.

Have you tried modifying acd_fuse.py yet? Which OS are you using?

**Comment by calisro** [comment]
They do have an effect outside of acd_cli.  I use this same functionality for other fuse mounts.  In this example I am using encfs mounted as a fuse volume:

This is the example using the uid/umask/gid options.  You will see the files are 'presented' as 'deluge:mediashare' with 772 permission as I intend.
```
-># cd /home/robert/ft
root@HS: /home/robert/ft
-># ENCFS6_CONFIG=/home/robert/encfs.xml /usr/local/bin/encfs  -o allow_other -o umask=002,gid=1002,uid=118  -S /cloudu/cloude /home/robert/ft/cloud
root@HS: /home/robert/ft
-># cd cloud
root@HS: /home/robert/ft/cloud
-># ls -l
total 2
drwxrwxr-x 1 deluge mediashare    0 Jan 15 11:29 Documents
drwxrwxr-x 1 deluge mediashare    0 Jan  7 16:11 Media
root@HS: /home/robert/ft/cloud
-># cd ..
```

This is the same example omiting the gid/uid/umask options. This will be presented as root:root with 777.  This is the same thing that acd_cli does.
```
root@HS: /home/robert/ft
-># umount /home/robert/ft/cloud
root@HS: /home/robert/ft
-># ENCFS6_CONFIG=/home/robert/encfs.xml /usr/local/bin/encfs -o allow_other  -S /cloudu/cloude /home/robert/ft/cloud
root@HS: /home/robert/ft
-># cd cloud
root@HS: /home/robert/ft/cloud
-># ls -l
total 0
drwxrwxrwx 1 root root 0 Jan 15 11:29 Documents
drwxrwxrwx 1 root root 0 Jan  7 16:11 Media
root@HS: /home/robert/ft/cloud
-># 
```

sudo has nothing to do with this.  Using sudo and running directly from root is the same thing.

**Comment by yadayada** [comment]
You know, there always is the possibility that a difference between appearance and actuality exists. 

I had implemented the ability to pass uid/gid. SETTING THEM HAS NO EFFECT. It's just the labels that change. There is no security gain. Using `--allow-other` opens your FUSE mount to the world, regardless of permissions.

>sudo has nothing to do with this. Using sudo and running directly from root is the same thing.

I meant you should run e.g. `sudo -u deluge ...` *as root*, not run it to get root.

**Comment by calisro** [comment]
> You know, there always is the possibility that a difference between appearance and actuality exists.

>I had implemented the ability to pass uid/gid. SETTING THEM HAS NO EFFECT. It's just the labels that change. There is no security gain. Using --allow-other opens your FUSE mount to the world, regardless of permissions.

That isn't true.  Setting those values lets a user specify the global permissions and ownership for that file system.  This only matters when running the fuse mount as root. (i'll get to why I do that at the end).  

Here I mount that file system with 'allow_other' yet I restrict the permissions and the ownership.  It doesn't just label them...  It sets owner:group and permissions for that file system at a global level for that file system.   Here I know get permission denied because group permissions are OFF and it is owned by a different owner as well.  Had I logged in as debian-deluged (owner of that file system that was marked in fuse) then that user can access it.
```
->  sudo -i
root@HS: ~
-># ENCFS6_CONFIG=/home/robert/encfs.xml /usr/local/bin/encfs -o allow_other -o umask=077,gid=1009,uid=119 /cloudu/cloude /home/robert/ft/cloud
EncFS Password: 
root@HS: ~
-># exit
logout
 robert [~/ft/cloud] $
-> cd /home/robert/ft/cloud
bash: cd: /home/robert/ft/cloud: Permission denied
robert [~/ft/cloud] $
->  ls -l /home/robert/ft/
total 0
drwx------ 1 debian-deluged 1009 0 Jan 17 14:44 cloud
```

> I meant you should run e.g. sudo -u deluge ... as root, not run it to get root.

Unfortunately, I cannot do that.  I really didn't want to confuse this issue with 'why' I am doing this but let me try to explain.  When fuse is run as root, then it can do things it simply cannot do in userspace.  For example, I have a 'chmod 2755' assigned to my file system which allows for sticky group permissions assigned to any file that gets created on that file system.  I then have that file system JOINED using union-fs with my amazon cloud file system.  If I do not run that file system as root, 'deluge' doesn't have the permissions neccessary to follow a sticky bit.  If I run it as root, then I can assign ownership as deluge and I also get the benefit of getting group ownership assigned to new files because of that sticky bit. Really this is way beyond this issue and it may confuse things but I'll summarize it to say that if I use sudo to deluge and run it as deluge, it won't work with my use case.  I MUST run as root so that fuse runs with the neccessary root permissions to act as any user.

**Comment by calisro** [comment]
I ran a test myself.  I modified the acd_fuse.py and hardcoded the gid,uid and added a umask and it works perfectly.  I can execute the mount as root and since I am root, it will modify the mount to the user specified.  To be honest, I am not good enough at coding python to initiate a pull request and code this all myself but what I am asking for as an enhancement is the ability to SPECIFY the uid,gid,umask as mount parameters to the acdcli which would pass that down to the acd_fuse.

Changed made to acd_fuse.py
```
    FUSE(ACDFuse(**args), path,
         auto_cache=True, sync_read=True,
         #uid=os.getuid(), gid=os.getgid(),
         uid='118', gid='1002',umask='002',
         subtype=ACDFuse.__name__,
         **kwargs
         )


```

results are correct.  The mount is now running with ROOT but are presented as the user specified with the correct mask.
```
┌[ ✓ robert [~/acd_cli] $
└─> sudo ACD_CLI_CACHE_PATH="/home/robert/.cache/acd_cli" ./acd_cli.py mount --allow-other -i 0 /home/robert/ft/cloud
┌[ ✓ robert [~/acd_cli] $
└─> cd /home/robert/ft/cloud
┌[ ✓ robert [~/ft/cloud] $
└─> ls -l
total 0
drwxrwxr-x 1 deluge mediashare 0 Jan 17 14:44 cloude

```

**Comment by calisro** [comment]
I've made a patch to add this functionality in my fork and i'd like to submit a pull request for the same.  I saw in the contributing guidlines to add to contributers and such but I wanted to confirm that you are happy to add this functionality before I submit a pull request.

**Comment by yadayada** [comment]
>I wanted to confirm that you are happy to add this functionality before I submit a pull request.

Indifferent is the word. I was going to add the functionality just to end this discussion.
