### ISSUE TITLE
QUESTION: sync interval

### ISSUE THREAD

**Issue by calisro** [yadayada/acd_cli#244]
Can you explain what impact the sync interval has on the acd mount?  I've reduced my sync interval to every 6 hours because I was getting lots of errors on my mounts and this seems to have completely stopped the errors (there were other inssues opened around this).  I perform a manually sync now after the data gets updated on the drive which is twice a day.  I am trying to understand what the sync actually does and what the ramifications are to delaying it like I have done.  THanks!!

**Comment by yadayada** [comment]
The automatic sync is for external updates, e.g. when changes occur by using the ACD Web interface or acd_cli on another machine. These external changes are not visible in your mount until the cache is synced. That's what the autosync is for.

If you don't have any external updates, you should completely disable autosync by specifying `-i0`.
