### ISSUE TITLE
problem with metadata function

### ISSUE THREAD

**Issue by francescofusco** [yadayada/acd_cli#248]
Great library before all.
I have a problem when a node start with the "-" char. Example:

C:\Users\me>acd_cli children GX7XnmAEQN2SVnXxZhwCHA
[bqXp-_PTTHiHDhQz02ckgA] [A] TWAIN107.BMP
[tcKA0MwcSoqK_J5pVYT4Rg] [A] TWAIN108.BMP
[Ez1oJc09Sua0yVw5l5ZUSA] [A] TWAIN109.BMP
[_FYoj576T_yWaUq31q77jA] [A] TWAIN110.BMP    <------- Start with '-'

Then if I try 
C:\Users\me>acd_cli children _FYoj576T_yWaUq31q77jA
I obtain an error.

I tried to enclosure the _F... string with " or ' but same error.

Thanks a lot
francesco

**Comment by francescofusco** [comment]
Sorry the example was wrong. The correct example is 

C:\Users\me>acd_cli children GX7XnmAEQN2SVnXxZhwCHA
[bqXp-_PTTHiHDhQz02ckgA] [A] TWAIN107.BMP
...
[_FYoj576T_yWaUq31q77jA] [A] TWAIN110.BMP   <---- OK becpuse start with '_'
[Hrns0iVuS8Kjh9WJ1MOryg] [A] TWAIN138.BMP
...
[-tMu7aTJSA-0KIJzqjVCFQ] [A] TWAIN141.BMP     <---- KO becpuse start with '-'

So, error if I try    "acd_cli metadata -tMu7aTJSA-0KIJzqjVCFQ"
The '-' char is interpreted as an option of the metadata command.

thanks a lot
francesco

**Comment by yadayada** [comment]
http://acd-cli.readthedocs.org/en/latest/FAQ.html
