### ISSUE TITLE
Database directory should be configurable.

### ISSUE THREAD

**Issue by chrisidefix** [yadayada/acd_cli#25]
Right now the source code directory hosts all data. It would be great to allow the user to configure a *data directory*, where she would place the `oauth_data` file. At least it should be the current working directory by default and not the source code directory in my opinion.

**Comment by yadayada** [comment]
I was planning to use [appdirs](https://github.com/ActiveState/appdirs) to put 'oauth_data', 'endpoint_data' and 'nodes.db' into the user's cache directory, which is `/home/<user>/.cache/`.

**Comment by chrisidefix** [comment]
Sounds like a decent way to solve this, but it may not be very convenient for the user to find that directory and manually have to copy `oauth_data` there. Maybe you need an import function for `oauth_data`..?

**Comment by yadayada** [comment]
The cache path may now be set manually by the environment variable `ACD_CLI_CACHE_PATH`.
