### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'modified'

### ISSUE THREAD

**Issue by vena** [yadayada/acd_cli#252]
Getting the following error on 0.3.1 when uploading a 15gb file in ubuntu 16.04, python 3.5.1+, using the cli client's basic upload with debug output:

```
16-01-20 20:24:19.403 [INFO] [acdcli.cache.sync] - Inserted/updated 1 file(s).
16-01-20 20:24:19.419 [INFO] [acdcli.cache.sync] - Parented 1 node(s).
16-01-20 20:24:19.420 [DEBUG] [acd_cli] - Local and remote hashes match for "/mnt/storage-encrypted/xnnsA,azIOklxxxx7ycX9yjL/ezacbvOh1jG8UjQKprxxxxx/60YFl39Ax1crrSz6K-S7Sq1Lp-7vro9VxxxxxxxvKR0A0lZGdma-pEkFH000QUev6D".
16-01-20 20:24:19.420 [DEBUG] [acd_cli] - Local and remote sizes match for "/mnt/storage-encrypted/xnnsA,azIOklxxxx7ycX9yjL/ezacbvOh1jG8UjQKprxxxxx/60YFl39Ax1crrSz6K-S7Sq1Lp-7vro9VxxxxxxxvKR0A0lZGdma-pEkFH000QUev6D".
16-01-20 20:24:19.427 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 201, in wrapped
    ret_val = f(*args, **kwargs)
  File "/usr/local/bin/acd_cli.py", line 440, in upload_file
    rmod = datetime_to_timestamp(conflicting_node.modified)
AttributeError: 'NoneType' object has no attribute 'modified'
```

file seems to upload fine in the end, it just errors out during the check.

**Comment by yadayada** [comment]
I had a look at the source yesterday and didn't find an execution path that would produce this error. 
Are you using the latest version?

**Comment by vena** [comment]
yes, i use the recommended master branch install method and keep it up to date, and at the time this error occurred i would have been around f7a863543ccad792951273cbb186bc70c07ef982

haven't seen another error like it since, but i also haven't been uploading 15gb files since then either.
