### ISSUE TITLE
Can't exclude files by ending or regex

### ISSUE THREAD

**Issue by triplike1do** [yadayada/acd_cli#254]
I'm trying to skip certain type of files on upload, and -xe is working, but only for one extension
tried to use regex, but it doesn't working, `-xr '\.(thm|mov|mp4)$'`

maybe something is wrong with my regex? or maybe I can combine multiple endings somehow, e.g. `-xe 'thm' -xe 'mov' -xe 'mp4'`

**Comment by yadayada** [comment]
Yes, you may specify multiple endings for exclusion using multiple `xe` statements. With `xr`, you need to match the beginning of the file name, eg `-xr '^.*?\.(foo|bar)$'`.

**Comment by triplike1do** [comment]
hm, my fault, `xe` is working, it was some issue with web interface
and thanks for help with regex
