### ISSUE TITLE
Incorrect upload speed summary

### ISSUE THREAD

**Issue by wdenx** [yadayada/acd_cli#255]
I'm observing strange output for the summary upload speed report once an upload has (successfuly) completed.

When uploading a single big file I see for example after completion:
```
[#########################] 100.0% of    5GiB  1/1     0.0B/s       0s
```
During the upload, the speed was between 2.2 ... 5.1 MB/s.

Similar when uploading whole directories. Here is an example that shows a few snapshots during the upload, then then the summary report after completion:
```
[####################     ]  83.8% of    4GiB  22/24    3.3MB/s   03:49m
[#####################    ]  86.3% of    4GiB  22/24    4.3MB/s   02:28m
[######################   ]  89.9% of    4GiB  22/24    4.1MB/s   01:55m
[######################   ]  91.7% of    4GiB  22/24    4.3MB/s   01:29m
[#######################  ]  95.6% of    4GiB  22/24    4.4MB/s      46s
[#########################] 100.0% of    4GiB  24/24    33.9B/s       0s
```
For other directory uploads (which all run at 3...5 MB/s), I see this:
```
[#########################] 100.0% of    4GiB  24/24    34.3B/s       0s
[#########################] 100.0% of    4GiB  24/24    34.6B/s       0s
[#########################] 100.0% of    4GiB  24/24    33.9B/s       0s
[#########################] 100.0% of    4GiB  24/24    34.3B/s       0s
[#########################] 100.0% of    4GiB  24/24    35.3B/s       0s
[#########################] 100.0% of    6GiB  40/40    1.3KB/s       0s
[#########################] 100.0% of    6GiB  40/40    1.3KB/s       0s
[#########################] 100.0% of    5GiB  34/34    1.1KB/s       0s
[#########################] 100.0% of    3GiB  20/20   637.3B/s       0s
```
There seems to be some bug in the summary calculation?

**Comment by yadayada** [comment]
What you see isn't really a summary, but the last progress that's printed. It's always displaying the 'current' speed determined by how many bytes were read locally. IIRC, it's an average over 20 samples taken in 0.3s intervals.

After a whole file has been read (i.e. sent), there is a period of waiting time until Amazon sends its response (e.g. hashing large files takes a while). That lowers your throughput.
Also, there may be a <0.3s wait after all files are completed. That may further decrease the value.

**Comment by wdenx** [comment]
OH, I see. I was expecting to see the average upload speed for the whole transfer, similar to what other programs show after completion.

Sorry for the misunderstanding.

And thanks a lot for all your help.
