### ISSUE TITLE
Request:Get all files on a shared folder without authentication

### ISSUE THREAD

**Issue by phdcoder** [yadayada/acd_cli#257]
I dont know if the API allow it , but it would be nice do download all files , or at least generate the Templinks, of a shared folder. So a user without an amazon account could download all files ina a shared folder without have to click on the files when the limit of 1000files/5GB  is applied.  I made this script to generate the links on the browser.  Its pretty efficient. 
```
var templinks= $x('//*[@id="dashboard-container"]/div[2]/div/div/div[3]/div[3]/div[1]/div/@data-templink')
var text=""
for ( i=templinks.length;i--;)
{
    text  =  text + templinks[i].value + "?download=true\r\n"
}
console.log(text)
```

**Comment by yadayada** [comment]
The API doesn't allow it.

If you have a look at the shared folder's static page source, you'll see that there are no links included. That means a Javascript-enabled webscraping framework is necessary to get the links.

Your script works in my browser *inside a folder* if I replace `mano.length` by `templinks.length`. Don't you want to start a small project for this yourself? A browser plugin maybe or a command-line tool?

**Comment by phdcoder** [comment]
My bad, i renamed the vars to english after i run the script and forgot to test.  Well, since there is no way to attach this behavior in acd_cli, i will develop a small extension to chrome.  It would be fun.
