### ISSUE TITLE
sync fails with RequestError: 1000

### ISSUE THREAD

**Issue by procmail** [yadayada/acd_cli#259]
Hi,

Running with --debug, I get:

> 16-02-06 16:29:23.884 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-06 16:29:23.884 [INFO] [acd_cli] - TestPlugin attached.
16-02-06 16:29:23.884 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/eric/Library/Caches/acd_cli".
16-02-06 16:29:23.884 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-06 16:29:23.891 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-02-06 16:29:23.891 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x104a46d68>, action='sync', cache=<acdcli.cache.db.NodeCache object at 0x104a5ccf8>, check=0, color=2, debug=1, full=False, func=<function sync_action at 0x104a1eae8>, log=True, no_wait=False, utf=False, verbose=None)
16-02-06 16:29:23.891 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
16-02-06 16:29:23.892 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.001848s
16-02-06 16:29:23.892 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
16-02-06 16:29:23.892 [DEBUG] [acdcli.api.backoff_req] - {}
16-02-06 16:29:23.907 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
send: b'POST /drive/v1/changes HTTP/1.1\r\nHost: cdws.us-east-1.amazonaws.com\r\nAuthorization: Bearer Atza|IQEBLjAsAhRRew66Y8wbbl08z9gl9LoPEP6KmwIUf-EUI57CPo1fsgdfhdfghdfgfasfghdfhjfdghdf_VoIrECHTnghdfghrhjfdghdghdfghdfghfgdhzs6XL7B_qupBQU39oy9Qmr2cGsX7bL0rsaGt9z9BPff8HxflQSLCYHEhxUPSvAdZ-Q9RM-UjU-B_YUZNAtNy2-hOCdUfghdfghdfghdfghykBDGeLnv-E5oeDlfepqgJqghdghdfgh0WJ5ll_GdBmOLAtJNN_iXH8uH7aNUXdfghdgfhdfghdfghfdghcEbzr24S-6hcdghdghdfgh6_hg1vdfghdgfhdfghcj_g0GsfdghdfghdgfhcWV_eVUdfghdgfhdfghdgfB4\r\nConnection: keep-alive\r\nContent-Length: 2\r\nUser-Agent: acdcli.api/0.8.8 python-requests/2.6.2 CPython/3.4.3 Darwin/15.3.0\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\n\r\n{}'
16-02-06 16:30:25.699 [CRITICAL] [acd_cli] - Sync failed.
Syncing...
RequestError: 1000, HTTPSConnectionPool(host='cdws.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)

I've even removed the cache and received a new oauth_data.

>(acd_cli) ➜  acd_cli git:(master) ✗ python acd_cli.py version  
acd_cli 0.3.1, api 0.8.8

**Comment by yadayada** [comment]
I assume this error may occur from time to time no matter what, but you may try the [sync_tempfile branch](https://github.com/yadayada/acd_cli/tree/sync_tempfile) nonethelesss.

**Comment by procmail** [comment]
Sorry, missed out on the reply. The sync-tempfile branch link isn't working anymore. Any other suggestions?

**Comment by procmail** [comment]
Just to add, using both sync and old-sync gives the same error.

**Comment by swvajanyatek** [comment]
I think i'm seeing the same, but 'm 

> [root@c7t ~]# acd_cli -d sync
> 16-04-03 13:33:36.099 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
> 16-04-03 13:33:36.100 [INFO] [acd_cli] - TestPlugin attached.
> 16-04-03 13:33:36.100 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
> 16-04-03 13:33:36.100 [INFO] [acdcli.api.oauth] - Token expired at 2016-04-02 21:46:10.083482.
> 16-04-03 13:33:36.100 [INFO] [acdcli.api.oauth] - Refreshing authentication token.
> 16-04-03 13:33:36.111 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): tensile-runway-92512.appspot.com
> send: b'POST / HTTP/1.1\r\nHost: tensile-runway-92512.appspot.com\r\nContent-Type: application/x-www-form-urlencoded\r\nAccept-Encoding: gzip, deflate\r\nContent-Length: 603\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nConnection: keep-alive\r\nAccept: */*\r\n\r\nrefresh_token=geTnPOetrc6JNzeDEqWcPqQuqZKng8rszIWDUvN8kw0h_5JZAM9ZB0QR9TvU_hImEFVB4Y4-MDZYzxsJ1mt-EoeYlKxT0pWGpBX-7LU73PK8R5OPo_RMwx5brxq5qcthUgDyDXnExgP3HXEBAFUTg2cUn8exYpyCTHKOFiQ7kxzlZLMwavm__g2pD7FjryQf39mXvt0k7yJI38f3MbZ1BdgyjJp1nYfqWRjuNiZy_LKlUnsiP7lLOfX4dvD7bc1DJusUkmiCITCD6zb4DTfAHDPlxHfN5P0vURw76dZFAAyYtD5zCZcLNr11UfnnfSAvR4pAWMpnF8KMRBdE7Uo35UMxxQPC-heOstBzUz8rKU0ckreIk4_SYg88--2RTwx9bHUWqtNRRcEKQ'
> reply: 'HTTP/1.1 200 OK\r\n'
> header: Content-Type header: Cache-Control header: Date header: Server header: Content-Length header: Alternate-Protocol header: Alt-Svc 16-04-03 13:33:36.499 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST / HTTP/1.1" 200 1300
> 16-04-03 13:33:36.502 [INFO] [acdcli.api.oauth] - New token expires at 2016-04-03 14:31:36.101068.
> 16-04-03 13:33:36.518 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
> 16-04-03 13:33:36.519 [INFO] [acdcli.cache.schema] - DB schema version is 2.
> 16-04-03 13:33:36.519 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x7f00fb69b208>, action='sync', cache=<acdcli.cache.db.NodeCache object at 0x7f00fb6ae4e0>, check=0, color=2, debug=1, full=False, func=<function sync_action at 0x7f00fb715620>, log=True, no_wait=False, utf=False, verbose=None)
> Getting changes16-04-03 13:33:36.519 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
> 16-04-03 13:33:36.520 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.001252s
> 16-04-03 13:33:36.520 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
> 16-04-03 13:33:36.520 [DEBUG] [acdcli.api.backoff_req] - {}
> 16-04-03 13:33:36.522 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
> send: b'POST /drive/v1/changes HTTP/1.1\r\nHost: cdws.us-east-1.amazonaws.com\r\nAuthorization: Bearer jfemhNLQog5XbVRXl1KkHhge5ODSJ0LMZmDehyHUDCpNYAs_oALYMhiC539OaFZThCv_Jr3Kjt1Z1_TtL1cWyxzRSZ0hbFuJ-yLJqNhzU8NpZVy7sjF_7cS0cqnYSwdo4gO6Qc5YqJ92eHnA_eBjQJyU3OIAkD7QwmLW2kzwESw1UM1hof_OA8c4YupMD7U0eYOFWo7iegft4dlIxInMfm1gxaN67nOO2QrQwilZdfgCZ76zt_noG1DVHS0ZbJ77JbM2PH-vevPH6oFupNW19V7-_2RyzgN_ujsP2d1r8lGzoa6YK0eQlN7fL8pfTmxhg9wsIhWlpZNU-d8z-dS-CmcD0tJ2P7ecFXqzvyrFaEKhHF0gwyGly0efWB0WBAPKKxbCx8XfyHO-UkmWl8mXnp-XSA2qXZDVinPVsLoGlVVF9mWpk5sDpaIEM25mtDYQ8FvPVRoIEI793k2Vd6wtUxJ-Z6AuT0WD_B0AJYBzBHDwNobLr_9Ta8oMIXmPw\r\nAccept-Encoding: gzip, deflate\r\nContent-Length: 2\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nConnection: keep-alive\r\nAccept: */*\r\n\r\n{}'
> reply: 'HTTP/1.1 504 Gateway Time-out\r\n'
> header: Server header: Date header: Content-Type header: Content-Length header: Connection header: Last-Modified header: ETag header: Accept-Ranges header: Vary header: Content-Encoding 16-04-03 13:34:36.690 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST /drive/v1/changes HTTP/1.1" 504 437
> RequestError: 504, [acd_api] no body received.
> 16-04-03 13:34:36.691 [CRITICAL] [acd_cli] - Sync failed.

**Comment by yadayada** [comment]
>Just to add, using both sync and old-sync gives the same error.

 &
 
>I think i'm seeing the same with both sync and old-sync. 

I cannot do anything about either of your timeout issues.

**Comment by swvajanyatek** [comment]
so is there something specific to my setup or account that prevents this from working, or should this be temporal and work at some random point in the future?

**Comment by andymcblane** [comment]
Hi, I am interested in setting my own timeout, and not being restricted to the 60 secs. Have looked around the issue tracker and in the source code however was unable to locate. I also am having this issue as above.

**Comment by nbonfire** [comment]
@yadayada I'm also getting this when I try to sync. Does this sound like a reasonable workaround?

acdcli ls /
for each item in that output:
acdcli psync -r /{item}
if failed, recursively acdcli ls the item and psync its nodes
