### ISSUE TITLE
acd_cli does not sync

### ISSUE THREAD

**Issue by sHaggYcaT** [yadayada/acd_cli#260]
I have two hosts with centos 7. On first acd_cli works, but on second not.

I have acd_cli installed from git (/usr/bin/python3-pip install --upgrade git+https://github.com/yadayada/acd_cli.git)

python3-pip-1.3.1-4.el7.nux.noarch

head -1 /bin/acd_cli
#!/usr/bin/python3

rpm -qf /usr/bin/python3
python3-3.3.2-12.el7.nux.x86_64

Also, I tried 
rpm -qf /bin/python3.4
python34-3.4.3-2.el7.x86_64

On the first centos 7 box (where acd_cli works fine) I have python3-3.3.2-12.el7.nux.x86_64
and also pip3 from nux repo.

[acd_cli@xvs ~]$ acd_cli -v sync
16-02-07 18:45:13.799 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-07 18:45:13.800 [INFO] [acd_cli] - TestPlugin attached.
16-02-07 18:45:13.800 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/acd_cli/.cache/acd_cli".
16-02-07 18:45:13.801 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-07 18:45:13.822 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): drive.amazonaws.com
16-02-07 18:45:15.345 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Syncing...
16-02-07 18:45:15.352 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
16-02-07 18:45:15.356 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
16-02-07 18:45:15.374 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
16-02-07 18:45:17.572 [INFO] [acdcli.api.metadata] - Found "reset" tag in changes.
16-02-07 18:45:18.031 [INFO] [acdcli.cache.schema] - Dropped all tables.
16-02-07 18:45:18.572 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-02-07 18:45:19.014 [INFO] [acdcli.cache.sync] - Inserted/updated 152 folder(s).
16-02-07 18:45:21.289 [INFO] [acdcli.cache.sync] - Inserted/updated 1705 file(s).
16-02-07 18:45:21.440 [INFO] [acdcli.cache.sync] - Parented 1857 node(s).
16-02-07 18:45:22.101 [INFO] [acdcli.cache.sync] - Inserted/updated 24 folder(s).
16-02-07 18:45:24.706 [INFO] [acdcli.cache.sync] - Inserted/updated 1965 file(s).
16-02-07 18:45:25.006 [INFO] [acdcli.cache.sync] - Parented 1989 node(s).
16-02-07 18:45:25.658 [INFO] [acdcli.cache.sync] - Inserted/updated 19 folder(s).
16-02-07 18:45:28.284 [INFO] [acdcli.cache.sync] - Inserted/updated 1978 file(s).
16-02-07 18:45:28.535 [INFO] [acdcli.cache.sync] - Parented 1997 node(s).
16-02-07 18:45:29.162 [INFO] [acdcli.cache.sync] - Inserted/updated 17 folder(s).
16-02-07 18:45:31.862 [INFO] [acdcli.cache.sync] - Inserted/updated 1957 file(s).
16-02-07 18:45:32.029 [INFO] [acdcli.cache.sync] - Parented 1974 node(s).
16-02-07 18:45:32.798 [INFO] [acdcli.cache.sync] - Inserted/updated 20 folder(s).
16-02-07 18:45:35.687 [INFO] [acdcli.cache.sync] - Inserted/updated 1973 file(s).
16-02-07 18:45:35.899 [INFO] [acdcli.cache.sync] - Parented 1993 node(s).
16-02-07 18:45:36.563 [INFO] [acdcli.cache.sync] - Inserted/updated 15 folder(s).
16-02-07 18:45:39.872 [INFO] [acdcli.cache.sync] - Inserted/updated 1984 file(s).
16-02-07 18:45:40.106 [INFO] [acdcli.cache.sync] - Parented 1999 node(s).
16-02-07 18:45:40.729 [INFO] [acdcli.cache.sync] - Inserted/updated 6 folder(s).
16-02-07 18:45:43.568 [INFO] [acdcli.cache.sync] - Inserted/updated 1993 file(s).
16-02-07 18:45:43.874 [INFO] [acdcli.cache.sync] - Parented 1999 node(s).
16-02-07 18:45:44.533 [INFO] [acdcli.cache.sync] - Inserted/updated 8 folder(s).
16-02-07 18:45:47.438 [INFO] [acdcli.cache.sync] - Inserted/updated 1992 file(s).
16-02-07 18:45:47.699 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:45:48.260 [INFO] [acdcli.cache.sync] - Inserted/updated 10 folder(s).
16-02-07 18:45:51.616 [INFO] [acdcli.cache.sync] - Inserted/updated 1989 file(s).
16-02-07 18:45:51.953 [INFO] [acdcli.cache.sync] - Parented 1999 node(s).
16-02-07 18:45:52.581 [INFO] [acdcli.cache.sync] - Inserted/updated 4 folder(s).
16-02-07 18:45:55.557 [INFO] [acdcli.cache.sync] - Inserted/updated 1995 file(s).
16-02-07 18:45:55.799 [INFO] [acdcli.cache.sync] - Parented 1999 node(s).
16-02-07 18:45:56.271 [INFO] [acdcli.cache.sync] - Inserted/updated 10 folder(s).
16-02-07 18:45:59.784 [INFO] [acdcli.cache.sync] - Inserted/updated 1989 file(s).
16-02-07 18:45:59.980 [INFO] [acdcli.cache.sync] - Parented 1999 node(s).
16-02-07 18:46:00.473 [INFO] [acdcli.cache.sync] - Inserted/updated 26 folder(s).
16-02-07 18:46:03.658 [INFO] [acdcli.cache.sync] - Inserted/updated 1970 file(s).
16-02-07 18:46:03.907 [INFO] [acdcli.cache.sync] - Parented 1996 node(s).
16-02-07 18:46:04.425 [INFO] [acdcli.cache.sync] - Inserted/updated 17 folder(s).
16-02-07 18:46:07.778 [INFO] [acdcli.cache.sync] - Inserted/updated 1975 file(s).
16-02-07 18:46:07.999 [INFO] [acdcli.cache.sync] - Parented 1992 node(s).
16-02-07 18:46:11.479 [INFO] [acdcli.cache.sync] - Inserted/updated 2000 file(s).
16-02-07 18:46:11.702 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:46:12.245 [INFO] [acdcli.cache.sync] - Inserted/updated 2 folder(s).
16-02-07 18:46:15.589 [INFO] [acdcli.cache.sync] - Inserted/updated 1997 file(s).
16-02-07 18:46:15.858 [INFO] [acdcli.cache.sync] - Parented 1999 node(s).
16-02-07 18:46:16.363 [INFO] [acdcli.cache.sync] - Inserted/updated 17 folder(s).
16-02-07 18:46:19.880 [INFO] [acdcli.cache.sync] - Inserted/updated 1955 file(s).
16-02-07 18:46:20.081 [INFO] [acdcli.cache.sync] - Parented 1972 node(s).
16-02-07 18:46:20.665 [INFO] [acdcli.cache.sync] - Inserted/updated 12 folder(s).
16-02-07 18:46:23.753 [INFO] [acdcli.cache.sync] - Inserted/updated 1986 file(s).
16-02-07 18:46:24.027 [INFO] [acdcli.cache.sync] - Parented 1998 node(s).
16-02-07 18:46:24.766 [INFO] [acdcli.cache.sync] - Inserted/updated 26 folder(s).
16-02-07 18:46:27.959 [INFO] [acdcli.cache.sync] - Inserted/updated 1963 file(s).
16-02-07 18:46:28.225 [INFO] [acdcli.cache.sync] - Parented 1989 node(s).
16-02-07 18:46:28.634 [INFO] [acdcli.cache.sync] - Inserted/updated 14 folder(s).
16-02-07 18:46:32.090 [INFO] [acdcli.cache.sync] - Inserted/updated 1985 file(s).
16-02-07 18:46:32.364 [INFO] [acdcli.cache.sync] - Parented 1999 node(s).
16-02-07 18:46:32.849 [INFO] [acdcli.cache.sync] - Inserted/updated 6 folder(s).
16-02-07 18:46:36.094 [INFO] [acdcli.cache.sync] - Inserted/updated 1992 file(s).
16-02-07 18:46:36.351 [INFO] [acdcli.cache.sync] - Parented 1998 node(s).
16-02-07 18:46:36.786 [INFO] [acdcli.cache.sync] - Inserted/updated 21 folder(s).
16-02-07 18:46:39.877 [INFO] [acdcli.cache.sync] - Inserted/updated 1977 file(s).
16-02-07 18:46:40.240 [INFO] [acdcli.cache.sync] - Parented 1998 node(s).
16-02-07 18:46:40.835 [INFO] [acdcli.cache.sync] - Inserted/updated 13 folder(s).
16-02-07 18:46:43.969 [INFO] [acdcli.cache.sync] - Inserted/updated 1974 file(s).
16-02-07 18:46:44.247 [INFO] [acdcli.cache.sync] - Parented 1987 node(s).
16-02-07 18:46:44.939 [INFO] [acdcli.cache.sync] - Inserted/updated 47 folder(s).
16-02-07 18:46:48.041 [INFO] [acdcli.cache.sync] - Inserted/updated 1889 file(s).
16-02-07 18:46:48.357 [INFO] [acdcli.cache.sync] - Parented 1936 node(s).
16-02-07 18:46:48.994 [INFO] [acdcli.cache.sync] - Inserted/updated 18 folder(s).
16-02-07 18:46:52.325 [INFO] [acdcli.cache.sync] - Inserted/updated 1876 file(s).
16-02-07 18:46:52.638 [INFO] [acdcli.cache.sync] - Parented 1894 node(s).
16-02-07 18:46:53.550 [INFO] [acdcli.cache.sync] - Inserted/updated 147 folder(s).
16-02-07 18:46:57.044 [INFO] [acdcli.cache.sync] - Inserted/updated 1847 file(s).
16-02-07 18:46:57.452 [INFO] [acdcli.cache.sync] - Parented 1994 node(s).
16-02-07 18:47:00.642 [INFO] [acdcli.cache.sync] - Inserted/updated 1933 folder(s).
16-02-07 18:47:01.017 [INFO] [acdcli.cache.sync] - Inserted/updated 67 file(s).
16-02-07 18:47:01.310 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:47:04.706 [INFO] [acdcli.cache.sync] - Inserted/updated 2000 folder(s).
16-02-07 18:47:05.171 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:47:09.082 [INFO] [acdcli.cache.sync] - Inserted/updated 2000 folder(s).
16-02-07 18:47:09.478 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:47:13.139 [INFO] [acdcli.cache.sync] - Inserted/updated 2000 folder(s).
16-02-07 18:47:13.540 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:47:16.933 [INFO] [acdcli.cache.sync] - Inserted/updated 2000 folder(s).
16-02-07 18:47:17.300 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:47:20.856 [INFO] [acdcli.cache.sync] - Inserted/updated 2000 folder(s).
16-02-07 18:47:21.259 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:47:24.869 [INFO] [acdcli.cache.sync] - Inserted/updated 2000 folder(s).
16-02-07 18:47:25.344 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:47:27.778 [INFO] [acdcli.cache.sync] - Inserted/updated 1351 folder(s).
16-02-07 18:47:28.664 [INFO] [acdcli.cache.sync] - Inserted/updated 327 file(s).
16-02-07 18:47:29.055 [INFO] [acdcli.cache.sync] - Parented 1678 node(s).
16-02-07 18:47:29.703 [INFO] [acdcli.cache.sync] - Inserted/updated 45 folder(s).
16-02-07 18:47:32.166 [INFO] [acdcli.cache.sync] - Inserted/updated 1083 file(s).
16-02-07 18:47:32.505 [INFO] [acdcli.cache.sync] - Parented 1128 node(s).
16-02-07 18:47:33.022 [INFO] [acdcli.cache.sync] - Inserted/updated 8 folder(s).
16-02-07 18:47:36.471 [INFO] [acdcli.cache.sync] - Inserted/updated 1992 file(s).
16-02-07 18:47:36.773 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:47:37.577 [INFO] [acdcli.cache.sync] - Inserted/updated 24 folder(s).
16-02-07 18:47:40.963 [INFO] [acdcli.cache.sync] - Inserted/updated 1907 file(s).
16-02-07 18:47:41.334 [INFO] [acdcli.cache.sync] - Parented 1931 node(s).
16-02-07 18:47:41.701 [INFO] [acdcli.cache.sync] - Inserted/updated 2 folder(s).
16-02-07 18:47:44.246 [INFO] [acdcli.cache.sync] - Inserted/updated 999 file(s).
16-02-07 18:47:44.486 [INFO] [acdcli.cache.sync] - Parented 1001 node(s).
16-02-07 18:47:46.880 [INFO] [acdcli.cache.sync] - Inserted/updated 1003 file(s).
16-02-07 18:47:47.037 [INFO] [acdcli.cache.sync] - Parented 1003 node(s).
16-02-07 18:47:49.614 [INFO] [acdcli.cache.sync] - Inserted/updated 1001 file(s).
16-02-07 18:47:49.830 [INFO] [acdcli.cache.sync] - Parented 1001 node(s).
16-02-07 18:47:50.197 [INFO] [acdcli.cache.sync] - Inserted/updated 5 folder(s).
16-02-07 18:47:53.007 [INFO] [acdcli.cache.sync] - Inserted/updated 1167 file(s).
16-02-07 18:47:53.206 [INFO] [acdcli.cache.sync] - Parented 1172 node(s).
16-02-07 18:47:53.766 [INFO] [acdcli.cache.sync] - Inserted/updated 61 folder(s).
16-02-07 18:47:56.603 [INFO] [acdcli.cache.sync] - Inserted/updated 1235 file(s).
16-02-07 18:47:56.975 [INFO] [acdcli.cache.sync] - Parented 1296 node(s).
16-02-07 18:47:57.443 [INFO] [acdcli.cache.sync] - Inserted/updated 16 folder(s).
16-02-07 18:48:00.554 [INFO] [acdcli.cache.sync] - Inserted/updated 1634 file(s).
16-02-07 18:48:00.859 [INFO] [acdcli.cache.sync] - Parented 1650 node(s).
16-02-07 18:48:01.443 [INFO] [acdcli.cache.sync] - Inserted/updated 19 folder(s).
16-02-07 18:48:05.037 [INFO] [acdcli.cache.sync] - Inserted/updated 1981 file(s).
16-02-07 18:48:05.353 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:48:05.804 [INFO] [acdcli.cache.sync] - Inserted/updated 8 folder(s).
16-02-07 18:48:08.734 [INFO] [acdcli.cache.sync] - Inserted/updated 1236 file(s).
16-02-07 18:48:09.057 [INFO] [acdcli.cache.sync] - Parented 1244 node(s).
16-02-07 18:48:11.766 [INFO] [acdcli.cache.sync] - Inserted/updated 1004 file(s).
16-02-07 18:48:11.997 [INFO] [acdcli.cache.sync] - Parented 1004 node(s).
16-02-07 18:48:12.600 [INFO] [acdcli.cache.sync] - Inserted/updated 21 folder(s).
16-02-07 18:48:15.587 [INFO] [acdcli.cache.sync] - Inserted/updated 1292 file(s).
16-02-07 18:48:15.984 [INFO] [acdcli.cache.sync] - Parented 1313 node(s).
16-02-07 18:48:18.967 [INFO] [acdcli.cache.sync] - Inserted/updated 1599 folder(s).
16-02-07 18:48:20.018 [INFO] [acdcli.cache.sync] - Inserted/updated 370 file(s).
16-02-07 18:48:20.680 [INFO] [acdcli.cache.sync] - Parented 1969 node(s).
16-02-07 18:48:24.262 [INFO] [acdcli.cache.sync] - Inserted/updated 1816 folder(s).
16-02-07 18:48:25.072 [INFO] [acdcli.cache.sync] - Inserted/updated 184 file(s).
16-02-07 18:48:25.763 [INFO] [acdcli.cache.sync] - Parented 2000 node(s).
16-02-07 18:48:26.965 [INFO] [acdcli.cache.sync] - Inserted/updated 312 folder(s).
16-02-07 18:48:30.825 [INFO] [acdcli.cache.sync] - Inserted/updated 1684 file(s).
16-02-07 18:48:31.361 [INFO] [acdcli.cache.sync] - Parented 1996 node(s).
16-02-07 18:48:32.346 [INFO] [acdcli.cache.sync] - Inserted/updated 244 folder(s).
16-02-07 18:48:36.080 [INFO] [acdcli.cache.sync] - Inserted/updated 1733 file(s).
16-02-07 18:48:36.742 [INFO] [acdcli.cache.sync] - Parented 1977 node(s).
16-02-07 18:48:38.110 [INFO] [acdcli.cache.sync] - Inserted/updated 446 folder(s).
16-02-07 18:48:41.135 [INFO] [acdcli.cache.sync] - Inserted/updated 1379 file(s).
16-02-07 18:48:41.564 [INFO] [acdcli.cache.sync] - Parented 1825 node(s).
16-02-07 18:48:42.425 [INFO] [acdcli.cache.sync] - Inserted/updated 138 folder(s).
16-02-07 18:48:45.486 [INFO] [acdcli.cache.sync] - Inserted/updated 1444 file(s).
16-02-07 18:48:45.963 [INFO] [acdcli.cache.sync] - Parented 1582 node(s).
16-02-07 18:48:46.185 [INFO] [acdcli.api.metadata] - ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
RequestError: 1003, [acd_api] reading changes terminated prematurely.
16-02-07 18:48:46.189 [CRITICAL] [acd_cli] - Sync failed.

**Comment by yadayada** [comment]
Please see if the [sync_tempfile](https://github.com/yadayada/acd_cli/tree/sync_tempfile branch) fixes your problem.

What's the hardware setup on your two machines?

**Comment by sHaggYcaT** [comment]
Thank you for helping. 

Your link is broken (404 error)

First box is my home workstation: Core2Quard, 8Gb RAM, 2xSATA 10k RPM raptors 250Gb raid1, 1x250 SSD 120G
Second box is home "server":

new-voltage(5Watt) CPU: Intel(R) Celeron(R) CPU  N3150
8Gb RAM,
4 x 1Tb SATA in raidz1 (I use zfs-on-linux project).

1 month ago this raidz1 located in my workstation. Today it mounted by NFSv4 on my station, and another PC in our small home LAN

acd_cli sync, running on my PC, download and upload works to the local drives and to the NFSv4 storage too. But if I run it on home "server", it doesn't.

**Comment by yadayada** [comment]
Could you try again, I updated the link.

**Comment by chesterdkat** [comment]
I also get errors when I sync. The first question is: do you think a Raspberry Pi 2 (the single core, 512 MB RAM variety) can hack acd_cli? I have even dumped all files on Amazon Cloud Drive so trying to sync an empty instance.

When I try syncing the cpu hovers around 100%
RAM usage is usually only around 40 MB

The latest Debian Jessie
python3 3.4.2

Error:
Syncing...
RequestError: 1003, [acd_api] reading changes terminated prematurely.
16-02-16 10:56:29.915 [CRITICAL] [acd_cli] - Sync failed.

**Comment by yadayada** [comment]
Please test the sync_tempfile branch, i.e. install it by running ``pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git@sync_tempfile``, and report back.

**Comment by sHaggYcaT** [comment]
Thank you, I've installed from new branch. Here is some changes - sync complied, but by fact, acd_cli doesn't work too:

```
[root@xvs shaggycat]# rpm -e python3-setuptools python3-pip

SKIP

[root@xvs shaggycat]# rpm -Uvh python3-setuptools-0.6.49-1.el7.nux.noarch.rpm
warning: python3-setuptools-0.6.49-1.el7.nux.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 85c6cd8a: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:python3-setuptools-0.6.49-1.el7.n################################# [100%]
[root@xvs shaggycat]# rpm -Uvh python3-pip-1.3.1-4.el7.nux.noarch.rpm
warning: python3-pip-1.3.1-4.el7.nux.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID 85c6cd8a: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:python3-pip-1.3.1-4.el7.nux      ################################# [100%]
[root@xvs shaggycat]# /usr/bin/python3-pip list
appdirs (1.4.0)
distribute (0.6.49)   
python-dateutil (2.4.2)
requests (2.9.1)
requests-toolbelt (0.6.0)
six (1.10.0)
```

```
[root@xvs shaggycat]# /usr/bin/python3-pip install --upgrade git+https://github.com/yadayada/acd_cli.git@sync_tempfile
Downloading/unpacking git+https://github.com/yadayada/acd_cli.git@sync_tempfile
  Cloning https://github.com/yadayada/acd_cli.git (to sync_tempfile) to /tmp/pip-8u_h4k-build
  Running setup.py egg_info for package from git+https://github.com/yadayada/acd_cli.git@sync_tempfile

Requirement already up-to-date: appdirs in /usr/lib/python3.3/site-packages (from acdcli==0.3.1)
Downloading/unpacking colorama (from acdcli==0.3.1)
  Running setup.py egg_info for package colorama

Requirement already up-to-date: python-dateutil in /usr/lib/python3.3/site-packages (from acdcli==0.3.1)
Requirement already up-to-date: requests>=2.1.0,!=2.9.0 in /usr/lib/python3.3/site-packages (from acdcli==0.3.1)
Requirement already up-to-date: requests-toolbelt in /usr/lib/python3.3/site-packages (from acdcli==0.3.1)
Requirement already up-to-date: six>=1.5 in /usr/lib/python3.3/site-packages (from python-dateutil->acdcli==0.3.1)
Installing collected packages: colorama, acdcli
  Running setup.py install for colorama

  Running setup.py install for acdcli
    changing mode of build/scripts-3.3/acd_cli.py from 644 to 755

    changing mode of /usr/bin/acd_cli.py to 755
    Installing acd_cli script to /usr/bin
    Installing acdcli script to /usr/bin
Successfully installed colorama acdcli
Cleaning up...
[root@xvs shaggycat]# 

[acd_cli@xvs ~]$ rm -rf .cache/acd_cli
[acd_cli@xvs ~]$ acd_cli init
For the one-time authentication a browser (tab) will be opened at https://tensile-runway-92512.appspot.com/.
Please accept the request and save the plaintext response data into a file called "oauth_data" in the directory "/home/acd_cli/.cache/acd_cli".
Press a key to open a browser.

Press a key if you have saved the "oauth_data" file into "/home/acd_cli/.cache/acd_cli".

16-02-16 14:44:24.889 [CRITICAL] [acd_cli] - Root node not found. Please sync.
[acd_cli@xvs ~]$ acd_cli sync
Syncing...

Done.
[acd_cli@xvs ~]$ 
[acd_cli@xvs ~]$ 
[acd_cli@xvs ~]$ 
[acd_cli@xvs ~]$ 
[acd_cli@xvs ~]$ acd_cli mount /mnt/amazon/
Traceback (most recent call last):
  File "/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/bin/acd_cli.py", line 1465, in main
    cache = db.NodeCache(CACHE_PATH, args.check)
  File "/usr/lib/python3.3/site-packages/acdcli/cache/db.py", line 62, in __init__
    raise IntegrityError('Could not uniquely identify root node.')
acdcli.cache.db.IntegrityError: 'Could not uniquely identify root node.'
```

**Comment by chesterdkat** [comment]
Sync Completed, albeit about 2 hours.

**Comment by yadayada** [comment]
@sHaggYcaT acdcli determines the root node by looking for a folder with no name. Unfortunately, you've got more than one folder with a NULL name.

Please open the sqlite CLI  by issuing
``sqlite3 /home/acd_cli/.cache/acd_cli/nodes.db``
, search for NULL-named folders by entering 
``SELECT id, created FROM nodes WHERE type IS 'folder' AND name is NULL;``
you should get multiple result lines like this
``PHwiEv53QOKoGFGqYNl8pw|2013-03-23 11:13:44.673000+00:00``

As a quick workaround you may issue SQL commands to rename all but the oldest NULL-name folder. Or you can find them in the web interface.

**Comment by sHaggYcaT** [comment]
Thank you for answer. I login in sqlite shell, and did following commands:

1) get list
`SELECT *, created FROM nodes WHERE type IS 'folder' AND name is NULL;`

here was 3 positions

2) made update:

`UPDATE nodes SET Name='1' WHERE Id='HERE WAS A SECOND ID';`

3) again:

`UPDATE nodes SET Name='2' WHERE Id='HERE WAS A THIRD ID';`

Now I can run commands (for example, acd_cli ls /) and mount with fuse:

`acd_cli mount /mnt/amazon/`

It works!

But new problem: I see in this folder files and dirs, but it's not my files!

On my PC I also can operate with my fiiles. Probably no broken.

**Comment by yadayada** [comment]
You can switch back to the master branch now. I also pushed a commit that filters out unnamed nodes.

>But new problem: I see in this folder files and dirs, but it's not my files!

What do you mean by that?

**Comment by vampywiz17** [comment]
Hello,

It is the same problem, it is only sync one way (if i made a changes in PC) but if i do simeting in Amazon web interace, it is dont sync. I use the latest master branch. (it was work some days ago)
