### ISSUE TITLE
Verify consistency of remote files

### ISSUE THREAD

**Issue by MattPark** [yadayada/acd_cli#263]
It seems that errors get thrown quite a bit so it follows that you would want to check your local file hierarchy against the remote one.  You would also want to make sure that the entire file made it and not just a portion of it.

So I looked through the usage guide and issues for a bit... can't find a good answer.
_How would you verify that the remote file was successfully uploaded before deleting the local file?_

**For a small file you could:**
1. md5sum the local file
2. md5sum downloaded file
3. compare md5sum (maybe rsync with rolling checksum instead)

**For a non-trivial file like 20GB you would:**
1. md5sum the local file
2. `acd_cli find-md5 [local md5 hash]`
3. check for a match

For a file tree containing 5000 trivial and 1000 non-trivial files, how would you check to make sure they all uploaded correctly?  Just script `acd_cli find-md5` into a loop?  Delete and re-upload the broken ones?

Is there a better way to do this, or is it already taken care of somewhere?

**Comment by yadayada** [comment]
>It seems that errors get thrown quite a bit 

Which errors? I also don't quite get what you're trying to accomplish in your first example.

Generally, continuing or "checking" of an upload of a local directory hierarchy is done by simply re-executing the initial upload command. Files that already exist remotely will be skipped automatically.

> You would also want to make sure that the entire file made it and not just a portion of it.

It's not usual for files to get "partially uploaded", they're either fully uploaded or not.
If you get errors uploading files larger than 10GB, you should wait a few minutes after the last error before continuing. You should then sync to get the metadata of timed-out uploads before re-executing your upload command.

>How would you verify that the remote file was successfully uploaded before deleting the local file?

`acdcli ul -h` will tell you there's an argument`  --remove-source-files` which `removes local files on successful upload`. That includes a successful MD5 sum check.

**Comment by MattPark** [comment]
Thanks for the quick response.

> Which errors?

I've been getting a lot of 
Error 500: Error creating remote folder / Internal server error
and 
Error 1000: Uploading failed / Read timed out (known Amazon error)

> It's not usual for files to get "partially uploaded", they're either fully uploaded or not.

I saw plenty of stories that error 1000 meant nothing was wrong, but the first one I tested would say input/output error whenever I did an `ls` on the directory.  The one file had none of the inode metadata and seemed totally borked, while the other file in the directory were fine.  I synced, waited a day, re-synced, etc.

> before re-executing your upload command

So according to the docs I could just upload the file tree again with `acdcli ul -o [path] [parent]` and it would find any partial files and reupload them.  OR would it just skip them because local mod and ctime would be older?

Anyway, I think your last example is basically what I should have done from the start.  Thanks again.

**Comment by yadayada** [comment]
>Error 500: Error creating remote folder / Internal server error

There's nothing to worry about those errors, the local directory will be skipped.

>I saw plenty of stories that error 1000 meant nothing was wrong, but the first one I tested would say input/output error whenever I did an ls on the directory.

Did you get the I/O error with FUSE? I'd like to see the debug log, if possible.
[If you upload with FUSE, you will get empty files on error!]

>The one file had none of the inode metadata and seemed totally borked

Could you provide more info on that?

>So according to the docs I could just upload the file tree again with acdcli ul -o [path] [parent] and it would find any partial files and reupload them. OR would it just skip them because local mod and ctime would be older?

`-o` would skip them [unfortunately, there is currently no mechanism to copy the local mtime], `-of` would always overwrite. Do you *really* have partially uploaded files?

I'd also like to point you to https://github.com/ncw/rclone, which seems to do directory synchronization quite well.

**Comment by MattPark** [comment]
>Did you get the I/O error with FUSE? 

I'm using the fuse mount but I didn't think you could upload that way.  I've been using `acdcli upload`.  I guess it was on the changelog that you enabled write...

>Could you provide more info on that? I'd like to see the debug log, if possible.

So in the process of trying to fix it I deleted the file-- I didn't remount with debug on, so I don't think I have good logs anywhere.  Here is the old termcap though--
```
plex@nas:~$ ls -la acd-sorted/Folder/Filename\ \(2004\)/
ls: cannot access acd-sorted/Folder/Filename (2004)/Filename.mkv: Input/output error
total 4141719550801648390
drwxrwxrw- 0 plex plex 0 Feb 10  2016 .
drwxrwxrw- 0 plex plex 0 Feb 10  2016 ..
-rwxrwxrw- 0 plex plex 0 Feb 10  2016 Filename-fanart.jpg
?????????? ? ?    ?    ?            ? Filename.mkv
-rwxrwxrw- 0 plex plex 0 Feb 10  2016 Filename.nfo
-rwxrwxrw- 0 plex plex 0 Feb 10  2016 Filename.tbn
```
It's expected behavior that all of the file are 0 byte, correct?


>I'd also like to point you to https://github.com/ncw/rclone

Seems cool, may be good for the initial sync, or verify all the files.  I still want to use your fuse module though.

**Comment by canonlp** [comment]
Currently I have it set up like this

```
acd_cli upload $file /

while true; do
        if [[ $(acd_cli find $file) ]]; then
                   echo "File is in Amazon"
                   break
        else
                   echo "No Files Found"
                   acd_cli upload -o $file /
                   acd_cli sync
        fi
done
```

It will upload the file first, check if it is in ACD, if not then reupload. Mind you, this only checks for the file name exists on ACD. You could probably also do a MD5 checksum as well.

**Comment by yadayada** [comment]
>`total 4141719550801648390`

>```
?????????? ? ?    ?    ?            ? Filename.mkv
```

That's odd. If that's recent enough, you may find logs for that in your cache path (see `acdcli -v init`).

>It's expected behavior that all of the file are 0 byte, correct?

If they are empty, yes. Otherwise, no. Which operating system are you using?

**Comment by MattPark** [comment]
>Which operating system are you using?
Debian Jessie -- (but a weird nas kernel)

>If they are empty, yes. Otherwise, no.
Haha, great.  See now my verification questions are starting to come into context.  Lemme investigate further...

Your recommendation for rclone seems to be working for uploads.  I want the fuse mount to work so I will check on that again.

**Comment by MattPark** [comment]
So I went through and removed as many things as possible that could be interfering (encfs)--
When I run an `ls -la` all the files come back as 0 byte (they are not).

This prints `getxattr '[Errno 61] No data available'` to the log for each file.  (similar to #185?) 

So this could be a weird edge case, because I have a Synology DSM OS, but a chrooted Debian Jessie running on top of it. (it has access to /dev, /proc, etc.)  The fuse kernel module actually resides on the SynoOS because that's where the kernel is.

I didn't think I would be able to get acd_cli running on the base OS, but this problem is likely due to how it is running... sigh.
```
plex@nas:~$ ls -la /mnt/media/.Files-acd/Filename\ \(2001\)/
total 7072402941362676371
drwxrwxrw- 0 plex plex 0 Feb 10 05:14 .
drwxrwxrw- 0 plex plex 0 Feb 10 04:33 ..
-rwxrwxrw- 0 plex plex 0 Feb 18 01:24 Filename-fanart.jpg
-rwxrwxrw- 0 plex plex 0 Feb 15 09:48 Filename.nfo
-rwxrwxrw- 0 plex plex 0 Feb 19 12:31 Filename.orig.nfo
-rwxrwxrw- 0 plex plex 0 Feb 12 18:39 Filename.tbn
plex@nas:~$ ls -la /mnt/media/.Files-acd/Filename\ \(2001\)/
total 5101750782782973225
drwxrwxrw- 0 plex plex 0 Feb 10 05:14 .
drwxrwxrw- 0 plex plex 0 Feb 10 04:33 ..
-rwxrwxrw- 0 plex plex 0 Feb 18 01:24 Filename-fanart.jpg
-rwxrwxrw- 0 plex plex 0 Feb 15 09:48 Filename.nfo
-rwxrwxrw- 0 plex plex 0 Feb 19 12:31 Filename.orig.nfo
-rwxrwxrw- 0 plex plex 0 Feb 12 18:39 Filename.tbn
```
Printed to the log:
```
plex@nas:~$ acd_cli -d -nl mount -i0 -fg -ao --modules="subdir,subdir=/NAS/Files" /mnt/media/.Files-acd
16-02-20 10:54:33.907 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-20 10:54:33.907 [INFO] [acd_cli] - TestPlugin attached.
16-02-20 10:54:33.908 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/plex/.cache/acd_cli".
16-02-20 10:54:33.928 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-20 10:54:33.950 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-02-20 10:54:34.449 [INFO] [acd_cli] - Last sync at 2016-02-20 15:34:20.180660.
16-02-20 10:54:34.449 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0xf693a9ec>, action='mount', allow_other=True, allow_root=False, cache=<acdcli.cache.db.NodeCache object at 0xf694a72c>, check=0, color=2, debug=1, foreground=True, func=<function mount_action at 0xf69a5fa4>, gid=1002, interval=0, log=False, modules='subdir,subdir=/NAS/Files', nlinks=False, no_wait=False, nonempty=False, path='/mnt/media/.Files-acd', read_only=False, single_threaded=False, uid=1002, umask=18, utf=False, verbose=None)
16-02-20 10:54:34.652 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.705057s
16-02-20 10:54:34.660 [INFO] [acdcli.api.backoff_req] - GET "https://cdws.us-east-1.amazonaws.com/drive/v1/account/quota"
16-02-20 10:54:34.713 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
send: b'GET /drive/v1/account/quota HTTP/1.1\r\nHost: cdws.us-east-1.amazonaws.com\r\nUser-Agent: acdcli.api/0.8.8 python-requests/2.9.1\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\nAuthorization: Bearer Atza|IQE<snip>9ozAP-woCuwB6ERc\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: x-amzn-RequestId header: Content-Encoding header: Cache-Control header: Pragma header: Vary 16-02-20 10:54:37.700 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /drive/v1/account/quota HTTP/1.1" 200 174
16-02-20 10:54:38.130 [DEBUG] [acdcli.acd_fuse] - -> init / ()
16-02-20 10:54:38.133 [DEBUG] [acdcli.acd_fuse] - <- init None
16-02-20 10:55:15.132 [DEBUG] [acdcli.acd_fuse] - -> getattr /NAS/Files/Filename (2001) (None,)
16-02-20 10:55:15.197 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_mtime': 1455903081.529, 'st_ctime': 1455099272.445, 'st_atime': 1455983715.1712797, 'st_nlink': 1, 'st_mode': 16895}
16-02-20 10:55:15.199 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001) ('security.selinux',)
16-02-20 10:55:15.224 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.225 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001) ('system.posix_acl_access',)
16-02-20 10:55:15.226 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.227 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001) ('system.posix_acl_default',)
16-02-20 10:55:15.229 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.230 [DEBUG] [acdcli.acd_fuse] - -> opendir /NAS/Files/Filename (2001) ()
16-02-20 10:55:15.231 [DEBUG] [acdcli.acd_fuse] - <- opendir 0
16-02-20 10:55:15.231 [DEBUG] [acdcli.acd_fuse] - -> readdir /NAS/Files/Filename (2001) (0,)
16-02-20 10:55:15.271 [DEBUG] [acdcli.acd_fuse] - <- readdir ['.', '..', 'Filename-fanart.jpg', 'Filename.nfo', 'Filename.orig.nfo', 'Filename.tbn']
16-02-20 10:55:15.273 [DEBUG] [acdcli.acd_fuse] - -> getattr /NAS/Files/Filename (2001) (None,)
16-02-20 10:55:15.310 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_mtime': 1455903081.529, 'st_ctime': 1455099272.445, 'st_atime': 1455983715.3099618, 'st_nlink': 1, 'st_mode': 16895}
16-02-20 10:55:15.312 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001) ('security.selinux',)
16-02-20 10:55:15.313 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.314 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001) ('system.posix_acl_access',)
16-02-20 10:55:15.315 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.315 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001) ('system.posix_acl_default',)
16-02-20 10:55:15.316 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.317 [DEBUG] [acdcli.acd_fuse] - -> getattr /NAS/Files/ (None,)
16-02-20 10:55:15.320 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_mtime': 1455872679.641, 'st_ctime': 1455096830.628, 'st_atime': 1455983715.320099, 'st_nlink': 1, 'st_mode': 16895}
16-02-20 10:55:15.321 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/ ('security.selinux',)
16-02-20 10:55:15.322 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.323 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/ ('system.posix_acl_access',)
16-02-20 10:55:15.324 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.324 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/ ('system.posix_acl_default',)
16-02-20 10:55:15.325 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.326 [DEBUG] [acdcli.acd_fuse] - -> getattr /NAS/Files/Filename (2001)/Filename-fanart.jpg (None,)
16-02-20 10:55:15.364 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_mtime': 1455776659.68, 'st_ctime': 1455776659.327, 'st_size': 198760, 'st_atime': 1455983715.3636134, 'st_nlink': 1, 'st_mode': 33206}
16-02-20 10:55:15.366 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename-fanart.jpg ('security.selinux',)
16-02-20 10:55:15.367 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.367 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename-fanart.jpg ('system.posix_acl_access',)
16-02-20 10:55:15.368 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.369 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename-fanart.jpg ('system.posix_acl_default',)
16-02-20 10:55:15.370 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.371 [DEBUG] [acdcli.acd_fuse] - -> getattr /NAS/Files/Filename (2001)/Filename.nfo (None,
16-02-20 10:55:15.409 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_mtime': 1455547705.333, 'st_ctime': 1455547704.972, 'st_size': 9802, 'st_atime': 1455983715.4090228, 'st_nlink': 1, 'st_mode': 33206}
16-02-20 10:55:15.411 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.nfo ('security.selinux',)
16-02-20 10:55:15.412 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.413 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.nfo ('system.posix_acl_access',)
16-02-20 10:55:15.413 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.414 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.nfo ('system.posix_acl_default',)
16-02-20 10:55:15.415 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.416 [DEBUG] [acdcli.acd_fuse] - -> getattr /NAS/Files/Filename (2001)/Filename.orig.nfo (None,)
16-02-20 10:55:15.455 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_mtime': 1455903081.562, 'st_ctime': 1455903081.296, 'st_size': 1015, 'st_atime': 1455983715.4546, 'st_nlink': 1, 'st_mode': 33206}
16-02-20 10:55:15.457 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.orig.nfo ('security.selinux',)
16-02-20 10:55:15.458 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.458 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.orig.nfo ('system.posix_acl_access',)
16-02-20 10:55:15.459 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.461 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.orig.nfo ('system.posix_acl_default',)
16-02-20 10:55:15.462 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.481 [DEBUG] [acdcli.acd_fuse] - -> getattr /NAS/Files/Filename (2001)/Filename.tbn (None,
16-02-20 10:55:15.518 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_mtime': 1455320390.817, 'st_ctime': 1455320390.44, 'st_size': 174945, 'st_atime': 1455983715.5183907, 'st_nlink': 1, 'st_mode': 33206}
16-02-20 10:55:15.521 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.tbn ('security.selinux',)
16-02-20 10:55:15.522 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.522 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.tbn ('system.posix_acl_access',)
16-02-20 10:55:15.524 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.525 [DEBUG] [acdcli.acd_fuse] - -> getxattr /NAS/Files/Filename (2001)/Filename.tbn ('system.posix_acl_default',)
16-02-20 10:55:15.526 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 61] No data available'
16-02-20 10:55:15.526 [DEBUG] [acdcli.acd_fuse] - -> releasedir /NAS/Files/Filename (2001) (0,)
16-02-20 10:55:15.527 [DEBUG] [acdcli.acd_fuse] - <- releasedir 0
```

**Comment by yadayada** [comment]
>This prints `getxattr '[Errno 61] No data available'`

That's not an error, merely missing extended attributes on each file.

There was something similar (i.e. exactly the same) in #172. Synology OS seems to be using a 32bit fuse module with a 64bit kernel, making fusepy use the wrong file stat struct.

**Comment by MattPark** [comment]
Hmm... I'll take a look, but kernel and hardware are both 32 bit

**Comment by yadayada** [comment]
Would you mind modifying acd_fuse.py like so

```diff
diff --git a/acdcli/acd_fuse.py b/acdcli/acd_fuse.py
index 5ae5cea..e4881b6 100644
--- a/acdcli/acd_fuse.py
+++ b/acdcli/acd_fuse.py
@@ -438,7 +438,7 @@ class ACDFuse(LoggingMixIn, Operations):
         elif node.is_file:
             return dict(st_mode=stat.S_IFREG | 0o0666,
                         st_nlink=self.cache.num_parents(node.id) if self.nlinks else 1,
-                        st_size=node.size,
+                        st_size=node.size, st_blocks=node.size//512,
                         **times)
 
     def listxattr(self, path) -> 'List[str]':
````

and see if it does something?

**Comment by MattPark** [comment]
Made the change, unmounted and remounted.  No difference as far as I could tell.

**Comment by yadayada** [comment]
Ok. Well, the size seems to be reported correctly in the getattr calls, so it must be in the wrong stat struct format.

Have you checked the fuse.ko and the system's architecture? Which DiskStation are you using?

**Comment by MattPark** [comment]
I have the 1812+ which is a Atom 2700 architecture "cedarview" ---

Now I could have sworn it was a 32 bit processor... but according to intel http://ark.intel.com/products/59683 it's 64-bit.

Chrooted Debian Jessie
```
plex@nas[chroot]:~$ file /lib/i386-linux-gnu/libfuse.so.2.9.3
/lib/i386-linux-gnu/libfuse.so.2.9.3: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=89bfe6e2224bafac779dcd68ea08b42fbe0718b1, stripped
plex@nas:~$ uname -a
Linux nas 3.10.35 #5592 SMP Mon Jun 29 17:28:12 CST 2015 x86_64 GNU/Linux
```

Base SynoOS:
```
OSError: /lib/libfuse.so.2.9.3: wrong ELF class: ELFCLASS32
bash-4.3$ uname -a
Linux nas 3.10.35 #5592 SMP Mon Jun 29 17:28:12 CST 2015 x86_64 GNU/Linux synology_cedarview_1812+
bash-4.3$ file /lib/libfuse.so.2.9.3
/lib/libfuse.so.2.9.3: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped
```

In the SynoOS there is also a /lib64 directory:
```
nas> ls /lib64
ld-linux-x86-64.so.2  libe2p.so             libgmp.so.10.0.1      libncurses.so.5.9     librt.so.1
ld.so.1               libe2p.so.2           libiw.so              libncursesw.so        libss.so
libattr.so            libe2p.so.2.3         libiw.so.29           libncursesw.so.5      libss.so.2
libattr.so.1          libext2fs.so          liblzo2.so.2          libncursesw.so.5.9    libss.so.2.0
libattr.so.1.1.0      libext2fs.so.2        libm.so.6             libnsl.so.1           libstdc++.so.6
libblkid.so           libext2fs.so.2.4      libmenu.so            libnss_dns.so.2       libutil.so.1
libblkid.so.1         libform.so            libmenu.so.5          libnss_files.so.2     libuuid.so
libblkid.so.1.1.0     libform.so.5          libmenu.so.5.9        libpanel.so           libuuid.so.1
libc.so.6             libform.so.5.9        libmenuw.so           libpanel.so.5         libuuid.so.1.3.0
libcom_err.so.2       libformw.so           libmenuw.so.5         libpanel.so.5.9       libz.so
libcom_err.so.2.1     libformw.so.5         libmenuw.so.5.9       libpanelw.so          libz.so.1
libcrypt.so.1         libformw.so.5.9       libmount.so.1         libpanelw.so.5        libz.so.1.2.8
libcurses.so          libgcc_s.so.1         libmount.so.1.1.0     libpanelw.so.5.9      terminfo
libcursesw.so         libgmp.so             libncurses.so         libpthread.so.0
libdl.so.2            libgmp.so.10          libncurses.so.5       libresolv.so.2

nas> file /lib64/libstdc++.so.6
/lib64/libstdc++.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
```

Do I need to try to build a libfuse 64 bit from source or something?

**Comment by yadayada** [comment]
Unfortunately, there is no easy way to check the `.so`'s word size from within Python without knowing its absolute path.

Would you kindly run

```bash
python3 <<EOF
with open('/lib/libfuse.so.2.9.3', 'rb') as libfuse:
    libfuse.seek(4)
    arch = 32 if libfuse.read(1) == b'1' else 64     
    print(arch)
EOF
```

and see if it outputs 32?

**Comment by MattPark** [comment]
```
EOF> with open('/lib/libfuse.so.2.9.3', 'rb') as libfuse:
>     libfuse.seek(4)
>     arch = 32 if libfuse.read(1) == b'1' else 64
>     print(arch)
> EOF
64

$: file /lib/libfuse.so.2.9.3
/lib/libfuse.so.2.9.3: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped
```

Was able to install a totally separate 64-bit arch in /opt and by setting `LIBFUSE_PATH=/opt/lib/libfuse.so.2` I was able to get it to work.

```
$: file /opt/lib/libfuse.so.2.9.3
/opt/lib/libfuse.so.2.9.3: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
```

**Comment by yadayada** [comment]
Closing this because the original question has been answered.

I'm not putting in an architecture check into fusepy because it's non-trivial to obtain the path of the shared library from within python.

**Comment by kkasberg** [comment]
Is there a way to implement an MD5 check when uploading files.   I sometimes will have the same file name but the file was replaced by a higher quality video.   I would like to have acd_cli overwrite the existing file with the new file when the MD5 sum has changed.   Is this possible (like with rsync setting it to check MD5 sums).

**Comment by MattPark** [comment]
yeah so I think that works already.  But you can use rclone, (which is basically rsync for ACD) just to be sure.

**Comment by yadayada** [comment]
@kkasberg Using the `--overwrite` flag will overwrite existing remote files if the local modification time is higher or the local creation time is higher than the remote modification time AND the file sizes do not match.

**Comment by soakes** [comment]
@MattPark Sorry for the disturbence but I have the exact same issue as you.

I am trying to run acd_cli mount within the debian chroot on the Synology NAS and like you I have a 32bit OS but 64bit kernel.

I would like to ask, how did you obtain/get the new /opt you made so you can use the env var?

Did you use debian bootstrap? or could you please tell me how you created it? 

Thanks in advance.

**Comment by MattPark** [comment]
@soakes Yeah so basically I did the opkg bootstrap and then changed the environment variables instead of hacking fuse.py or whatever.  It also enabled me to do logs of cool stuff like actually compile code which usually failed before.  I thought that in DSM 6.0 they were fixing the 32 bit OS issue.  I haven't upgraded yet because I think it will break some stuff.

**Comment by soakes** [comment]
@MattPark thanks very much for the info.  

Yeah, I am still using 5.2 if I recall due to lots of custom stuff which I know will break when I upgrade and as the NAS is not on the internet, theres little reason to upgrade it right now.

Anyway, thanks again for the trick/tips and I will have a play shortly as I would idealy not have to mess with fuse.py for various reasons.  

Thanks again.

**Comment by MattPark** [comment]
@soakes Good luck Simon, here are the best instructions -- super easy and they have links to all the advanced stuff as well. https://github.com/Entware-ng/Entware-ng/wiki/Install-on-Synology-NAS

**Comment by soakes** [comment]
@MattPark your a super star, thank you very much for the information.  This is just what I need.  Thanks again.
