### ISSUE TITLE
mount on boot, not login

### ISSUE THREAD

**Issue by TerrorFactor** [yadayada/acd_cli#264]
I am using acd_cli on a debian jessie based system (systemd), but I cannot get acd_cli to run on boot, without logging in first. 
When trying to run a modified version in a system context, it doesn't seem to be able to find the oauth file, even though the parameter "User" was specified. Starting the script from the console manually does seem to work though :/

This is the most recent try that works when started from the console (sudo systemctl start amazon-cloud-drive.service)
```
[Unit]
Description=user Amazon Cloud Drive FUSE mount
Documentation=https://acd-cli.readthedocs.org/en/latest/
AssertPathIsDirectory=/home/osmc/.acd-sorted
After=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/acd_cli mount --foreground /home/osmc/.acd-sorted -ao
ExecStop=/usr/local/bin/acd_cli -v -nl umount /home/osmc/.acd-sorted
User=osmc

[Install]
WantedBy=multi-user.target


```

I've also tried to autologon to a virtual console. The loging on seems to work (service is active), but it doesn't trigger the user-level service.

What is the proper way to get it to run on boot, without having to log in?

**Comment by yadayada** [comment]
You  may need to set the environment variable `ACD_CLI_CACHE_PATH` in the `[Service]` section, e.g. 
`Environment=ACD_CLI_CACHE_PATH=/home/osmc/.cache/acd_cli`.

**Comment by TerrorFactor** [comment]
That made sense, but it doesn't seem to fix the problem:
```
osmc@osmc:~$ sudo systemctl status amazon-cloud-drive.service -l
* amazon-cloud-drive.service - user Amazon Cloud Drive FUSE mount
   Loaded: loaded (/etc/systemd/system/amazon-cloud-drive.service; enabled)
   Active: failed (Result: exit-code) since Thu 2016-02-11 23:40:20 CET; 2min 17s ago
     Docs: https://acd-cli.readthedocs.org/en/latest/
  Process: 465 ExecStop=/usr/local/bin/acd_cli -v -nl umount /home/osmc/.acd-sorted (code=exited, status=1/FAILURE)
  Process: 292 ExecStart=/usr/local/bin/acd_cli mount --foreground /home/osmc/.acd-sorted -ao (code=exited, status=1/FAIL                                                                    URE)
 Main PID: 292 (code=exited, status=1/FAILURE)

Feb 11 23:40:17 osmc acd_cli[292]: return self._request('GET', url, acc_codes, **kwargs)
Feb 11 23:40:17 osmc acd_cli[292]: File "/usr/local/lib/python3.4/dist-packages/acdcli/api/common.py", line 50, in decora                                                                    ted
Feb 11 23:40:17 osmc acd_cli[292]: raise RequestError(RequestError.CODE.CONN_EXCEPTION, e.__str__())
Feb 11 23:40:17 osmc acd_cli[292]: acdcli.api.common.RequestError: RequestError: 1000, HTTPSConnectionPool(host='cdws.eu-                                                                    west-1.amazonaws.com', port=443): Max retries exceeded with url: /drive/v1/account/quota (Caused by NewConnectionError('<                                                                    requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x76296c90>: Failed to establish a new connection:                                                                     [Errno -2] Name or service not known',))
Feb 11 23:40:17 osmc systemd[1]: amazon-cloud-drive.service: main process exited, code=exited, status=1/FAILURE
Feb 11 23:40:20 osmc acd_cli[465]: 16-02-11 23:40:20.349 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
Feb 11 23:40:20 osmc acd_cli[465]: 16-02-11 23:40:20.352 [INFO] [acd_cli] - TestPlugin attached.
Feb 11 23:40:20 osmc acd_cli[465]: fusermount: entry for /home/osmc/.acd-sorted not found in /etc/mtab
Feb 11 23:40:20 osmc systemd[1]: amazon-cloud-drive.service: control process exited, code=exited status=1
Feb 11 23:40:20 osmc systemd[1]: Unit amazon-cloud-drive.service entered failed state.

```

**Comment by yadayada** [comment]
>acdcli.api.common.RequestError: RequestError: 1000, HTTPSConnectionPool(host='cdws.eu-                                                                    west-1.amazonaws.com', port=443): Max retries exceeded with url: /drive/v1/account/quota (Caused by NewConnectionError('<                                                                    requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x76296c90>: Failed to establish a new connection:                                                                     [Errno -2] Name or service not known',))

Well....

**Comment by TerrorFactor** [comment]
Does that mean that the network isn't up yet when it runs, even though this is set?
```
[Unit]
After=network-online.target
```

**Comment by yadayada** [comment]
Maybe `After=NetworkManager-wait-online.service` will work if you use networkmanager.

**Comment by TerrorFactor** [comment]
That didn't help either :( 
"Solved" it by adding a timer unit that starts the service.

**amazon-cloud-drive.timer**
```
[Unit]
Description=Runs ACD on boot

[Timer]
# Time to wait after booting before we run first time
OnBootSec=1min
Unit=amazon-cloud-drive.service

[Install]
WantedBy=multi-user.target

```
