### ISSUE TITLE
Authorization through terminal?

### ISSUE THREAD

**Issue by pkasarski** [yadayada/acd_cli#268]
I would like to authorize in a virtual machine that does not have a graphical display.

I first tried the "simple" authorization method. It did open lynx, but I think some of the JavaScript threw it off, and I couldn't download the `oauth_data` file.

I was going to try the other method, but I'm unclear as to what this means:

> Just copy the URL (e.g. http://localhost/?code=AbCdEfGhIjKlMnOpQrSt&scope=clouddrive%3Aread_all+clouddrive%3Awrite) into the console.

Which console is that referring to?

Is there a way to authorize on a different machine than the one acd_cli is running on?

Thanks for any help.

**Comment by yadayada** [comment]
I just tried to initialize with lynx and (after accepting a few dozen cookies) it worked for me, but I
suggest using elinks, if at all possible. It may be necessary to set the BROWSER environment variable to override the default text browser. 

> >Just copy the URL (e.g. http://localhost/?code=AbCdEfGhIjKlMnOpQrSt&scope=clouddrive%3Aread_all+clouddrive%3Awrite) into the console.

>Which console is that referring to?

The prompt when the client_data file is created, you run `acdcli init` for the first time.

> Is there a way to authorize on a different machine than the one acd_cli is running on?

Yes. Just navigate to https://tensile-runway-92512.appspot.com, get your oauth_data file from there and scp it to your cache path (it's output when you turn verbose mode on).

**Comment by pkasarski** [comment]
That worked -- thanks!
