### ISSUE TITLE
Auto create directories on single upload

### ISSUE THREAD

**Issue by TerrorFactor** [yadayada/acd_cli#272]
An issue that I ran into:
When you upload a single file (acd_cli upload /path/to/file /path/to/) and the remote folder structure (/path/to/) doesn't exist yet, it fails.

The documents mention " If remote folder hierarchies or local directory hierarchies need to be created, this will be done prior to the file transfers.", but this doesn't seem to happen.

**Comment by yadayada** [comment]
It should fail if the destination is non-existent. The passage about hierarchy creation only applies to subfolders/subdirectories.

**Comment by TerrorFactor** [comment]
Could you maybe add a --force option for this?
