### ISSUE TITLE
End of change request not reached

### ISSUE THREAD

**Issue by nphowe** [yadayada/acd_cli#274]
Hi there!  I've researched and can't find any instances of this.  Below is my verbose output when trying to perform initial sync.  Running as root just to rule things out.  Running as sudo user gave me the same result though. /shrug

Also of note, I have purged my entire ACD to ensure that nothing there could be causing the issue.  It's a clean slate at this point.
```
root@localhost:~# acdcli -v sync
16-02-21 14:25:50.337 [INFO] [acd_cli] - Plugin leaf classes: TermsOfUsePlugin, TestPlugin, ClementinePlugin, TestPlugin
16-02-21 14:25:50.350 [INFO] [acd_cli] - TermsOfUsePlugin attached.
16-02-21 14:25:50.350 [INFO] [acd_cli] - TestPlugin attached.
16-02-21 14:25:50.351 [INFO] [acd_cli] - Clementine executable not found.
16-02-21 14:25:50.351 [INFO] [acd_cli] - TestPlugin attached.
16-02-21 14:25:50.351 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-02-21 14:25:50.352 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-21 14:25:50.352 [INFO] [acdcli.cache.db] - Initializing cache with path "/root/.cache/acd_cli".
16-02-21 14:25:50.524 [INFO] [acdcli.cache.db] - Cache is initialized.
16-02-21 14:25:50.526 [INFO] [acdcli.cache.db] - DB schema version is 1.
Syncing...
16-02-21 14:25:50.535 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "CNmz-basKRoA".
16-02-21 14:25:50.535 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
16-02-21 14:25:50.540 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
16-02-21 14:25:52.559 [INFO] [acdcli.cache.sync] - Purged 2 node(s).
16-02-21 14:25:52.833 [INFO] [acdcli.cache.sync] - Inserted/updated 23 folder(s).
16-02-21 14:25:54.285 [INFO] [acdcli.cache.sync] - Inserted/updated 1937 file(s).
16-02-21 14:25:54.893 [INFO] [acdcli.cache.sync] - Parented 1960 node(s).
16-02-21 14:25:55.472 [INFO] [acdcli.cache.sync] - Purged 1 node(s).
16-02-21 14:25:56.445 [INFO] [acdcli.cache.sync] - Inserted/updated 1627 file(s).
16-02-21 14:25:56.878 [INFO] [acdcli.cache.sync] - Parented 1627 node(s).
16-02-21 14:25:58.697 [INFO] [acdcli.cache.sync] - Inserted/updated 1654 file(s).
16-02-21 14:25:59.580 [INFO] [acdcli.cache.sync] - Parented 1654 node(s).
16-02-21 14:26:00.874 [INFO] [acdcli.cache.sync] - Inserted/updated 1452 file(s).
16-02-21 14:26:01.566 [INFO] [acdcli.cache.sync] - Parented 1452 node(s).
16-02-21 14:26:03.685 [INFO] [acdcli.cache.sync] - Inserted/updated 1687 file(s).
16-02-21 14:26:04.210 [INFO] [acdcli.cache.sync] - Parented 1687 node(s).
16-02-21 14:26:04.471 [INFO] [acdcli.api.metadata] - 4 page(s) in changes.
16-02-21 14:26:04.471 [WARNING] [acdcli.api.metadata] - End of change request not reached.
Done.
```
Thanks for your help!

**Comment by yadayada** [comment]
> I've researched and can't find any instances of this.

I find that very hard to believe.

Please upgrade.

**Comment by nphowe** [comment]
I did find instances of this error message, but under different circumstances.  One guy had a corrupt file in ACD, which is why I chose to purge my ACD.

This was a fresh install I did yesterday, but all the same I just upgraded with:
pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git

I then ran acdcli delete-everything and tried syncing again, generating a fresh oauth_data.  Output below.

16-02-21 14:41:42.849 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-21 14:41:42.850 [INFO] [acd_cli] - TestPlugin attached.
16-02-21 14:41:42.850 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-02-21 14:41:42.851 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-21 14:41:42.852 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Getting changes16-02-21 14:41:42.853 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "None".
16-02-21 14:41:42.853 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
16-02-21 14:41:42.857 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com

16-02-21 14:41:43.243 [INFO] [acdcli.api.metadata] - -1 page(s) in changes.
16-02-21 14:41:43.244 [WARNING] [acdcli.api.metadata] - End of change request not reached.

**Comment by yadayada** [comment]
>This was a fresh install I did yesterday

Be that as it may, the PyPI versions is a few months old.

>[WARNING] [acdcli.api.metadata] - End of change request not reached.

If you get that, you can continue syncing later.

**Comment by nphowe** [comment]
I should just keep trying then, even though the results have been static for a couple hours now?  There is nothing I could do in the meantime to correct this situation?  Thanks!

**Comment by nphowe** [comment]
Just to follow up, I spun up a different VPS with a different provider running Ubuntu 15.10 (last VPS was 14.04).  When performing initial acdcli sync on the new VPS, I get the same exact result as before.  Bear in mind that acdcli old-sync works on both machines.

Any idea if this could be something tied to my Amazon account?  Not that I'm asking you to troubleshoot my account.  Just not sure if you've run across this before.

Thanks.
