### ISSUE TITLE
Slow uploads, without FUSE

### ISSUE THREAD

**Issue by TerrorFactor** [yadayada/acd_cli#276]
Hi,

I noticed acd_cli is limites to ~750 KB/s upload ("acd_cli upload file /").
If I upload with the webbrowser, or with "expandrive" (windows tool that allows you to mount your amazon drive), I get way higher speeds. On a 3GB file, I got 30MB/s with expandrive (gigabit network, though only got 350/150 mbps on speedtest).

I tried with acd_cli on a raspberry pi, Ubuntu VM, and my Windows host. Weirdly, in Windows I only got 250 KB/s.
For comparison, I get about 17MB/s upload to a (slow, raid6) smb nas with the ubuntu VM, and 1-2MB higher directly from my Windows host.

**Comment by yadayada** [comment]
Could you compare the transfer speeds of the current version the ones you get with 17c0407ca2f2668c7a34e3945bf45483548ee858?

**Comment by TerrorFactor** [comment]
In the understanding that I installed it correctly, it doesn't seem to make any difference.

`sudo pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git@17c0407ca2f2668c7a34e3945bf45483548ee858`
```
Downloading/unpacking git+https://github.com/yadayada/acd_cli.git@17c0407ca2f2668c7a34e3945bf45483548ee858
  Cloning https://github.com/yadayada/acd_cli.git (to 17c0407ca2f2668c7a34e3945bf45483548ee858) to /tmp/pip-is_8r6op-build
  Could not find a tag or branch '17c0407ca2f2668c7a34e3945bf45483548ee858', assuming commit.
  Running setup.py (path:/tmp/pip-is_8r6op-build/setup.py) egg_info for package from git+https://github.com/yadayada/acd_cli.git@17c0407ca2f2668c7a34e3945bf45483548ee858

```
cut out a bunch of stuff
 ```
Found existing installation: acdcli 0.3.1
    Uninstalling acdcli:
      Successfully uninstalled acdcli
  Running setup.py install for acdcli
    changing mode of build/scripts-3.4/acd_cli.py from 644 to 755
    
    changing mode of /usr/local/bin/acd_cli.py to 755
    Installing acd_cli script to /usr/local/bin
    Installing acdcli script to /usr/local/bin
Successfully installed pycurl acdcli
```

**Comment by yadayada** [comment]
This is out of my sphere of influence.
