### ISSUE TITLE
Cannot access file: Bad Address

### ISSUE THREAD

**Issue by adamdilibero** [yadayada/acd_cli#279]
I've mounted and some files in the folder I'm getting the following error when trying to list the directory or do anything with the files: 

ls: cannot access FILENAME: Bad address 

I am seeing this error for half the files in this folder but the other half are fine

When I check manually they are all listed on Amazon Cloud Drive I'm running latest version of acd_cli 

Any suggestions? 

Thanks, 

Adam

**Comment by yadayada** [comment]
Please mount in debug mode and give me an *excerpt* of the log where this happens.

**Comment by adamdilibero** [comment]
`acd_cli -d mount /home/plex/amazon --allow-other
16-02-23 08:22:18.429 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-23 08:22:18.429 [INFO] [acd_cli] - TestPlugin attached.
16-02-23 08:22:18.429 [INFO] [acdcli.api.client] - Initializing ACD with path "/var/lib/plexmediaserver/.cache/acd_cli".
16-02-23 08:22:18.430 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-23 08:22:18.431 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-02-23 08:22:18.483 [INFO] [acd_cli] - Last sync at 2016-02-23 07:22:01.722270.
16-02-23 08:22:18.484 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x6df906f03b00>, action='mount', allow_other=True, allow_root=False, cache=<acdcli.cache.db.NodeCache object at 0x6df906f12860>, check=0, color=2, debug=1, foreground=False, func=<function mount_action at 0x6df9071560d0>, gid=123, interval=0, log=True, modules='', nlinks=False, no_wait=False, nonempty=False, path='/home/plex/amazon', read_only=False, single_threaded=False, uid=111, umask=2, utf=False, verbose=None)
16-02-23 08:22:18.491 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.060932s
16-02-23 08:22:18.491 [INFO] [acdcli.api.backoff_req] - GET "https://cdws.us-east-1.amazonaws.com/drive/v1/account/quota"
16-02-23 08:22:18.494 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
send: b'GET /drive/v1/account/quota HTTP/1.1\r\nHost: cdws.us-east-1.amazonaws.com\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nAccept: */*\r\nAccept-Encoding: gzip, deflate\r\nConnection: keep-alive\r\nAuthorization: Bearer Atza|IQEBLjAsAhQkJwfWd9v-r-9lG3obfkNs9P45MQIUdnTf5M-uNkVSSEkar0m_nhbZaKqw2qvIkhFRlSWiX__OiLJuBcWG62jZFZO-PbkYlH5uHa9QwKK5RC63-2nBitjmk-zbt34HN3AUEf7jklDmVVhwtMj1k7fEwn5kTV9ShHhygNlxorh-WGA43hjN-T-3eZ5V5ZxO_ckAItljiVIMHAiVBgTPx_Y4J1dIozocYUDXIJ7qR_t852AYozlJdtdQ1qjJVgL_5cBvmF4WFmJFshIpwXVJCZB1yIjNCG3q0xwePZOoYm6XVACoTv1pwgX1uk5Lh3eKqZVxVowC3kkq6vxSvPOGEWgG_VqsLFYBjCxGwKeagdMwJBOCvhhZbfO811T4tevrdFisXquzgFRR3JS8fAqCRo2BGcngI6qbJMyDrSP7UUgPrcvi7Nc6N3v5_Rkh\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: x-amzn-RequestId header: Content-Encoding header: Cache-Control header: Pragma header: Vary 16-02-23 08:22:18.999 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /drive/v1/account/quota HTTP/1.1" 200 136
plex@media1:/root$ cd /home/plex/amazon 
plex@media1:/home/plex/amazon$ ls
Movies	TV-Shows
plex@media1:/home/plex/amazon$ cd TV-Shows/
plex@media1:/home/plex/amazon/TV-Shows$ ls -latr
ls: cannot access ..: Bad address
ls: cannot access Band of Brothers: Bad address
`

I'm unsure how to get a debug log of the bad address part?

**Comment by adamdilibero** [comment]
Also this: 

plex@media1:/home$ acd_cli sync
Getting changes..
Inserting nodes.
plex@media1:/home$ acd_cli -d sync
16-02-23 13:57:27.653 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-23 13:57:27.653 [INFO] [acd_cli] - TestPlugin attached.
16-02-23 13:57:27.653 [INFO] [acdcli.api.client] - Initializing ACD with path "/var/lib/plexmediaserver/.cache/acd_cli".
16-02-23 13:57:27.654 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-23 13:57:27.654 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-02-23 13:57:27.699 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x66c554767b00>, action='sync', cache=<acdcli.cache.db.NodeCache object at 0x66c554777860>, check=0, color=2, debug=1, full=False, func=<function sync_action at 0x66c5549be0d0>, log=True, no_wait=False, utf=False, verbose=None)
Getting changes16-02-23 13:57:27.699 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "CLCmmvGwKhoaCAQaFgEUAAAAAp8QRO_iJWPmbsV5XYi-qJk=".
16-02-23 13:57:27.699 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.045214s
16-02-23 13:57:27.699 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
16-02-23 13:57:27.699 [DEBUG] [acdcli.api.backoff_req] - {"includePurged": "true", "checkpoint": "CLCmmvGwKhoaCAQaFgEUAAAAAp8QRO_iJWPmbsV5XYi-qJk="}
16-02-23 13:57:27.702 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
send: b'POST /drive/v1/changes HTTP/1.1\r\nHost: cdws.us-east-1.amazonaws.com\r\nAccept-Encoding: gzip, deflate\r\nAuthorization: Bearer Atza|IQEBLjAsAhQ-JxiT8i_1wJcnDu1t_YPIrq0MvgIUAfc2Nqel3BEIynqEwP7HKbcBQ9GADi0befP94dOtn-kS0IuihqCx2Poi103013asbdUXRY6-Mr8MxkgugknE4G45Uhre07UvTK9XcPrfTPnoLrWcEAo1vBostDRFi4cGKxoW_V0BtRDh8CmjbdS64mnvYR3M6dlqTGy9pT_WuoRfXDHixptdNkG3mE507Lwq-_Axz_s_rbGP6-9kYxdPqbf9CkXDtODDEgruFTk6d-45Sd1jKKnh-M8YR5vEQmfRwZAbgT2-2_KJalg0aAEiJC39fxJMkW_EQkCBnhQqk_7XLXGv1uiePIIsA62GWJByTsupqtCMLT6Kubd74lTjXRIenng3othhpSej2H6sAQy2Om0e1IRqWMnuM6_cn2jZyGs_sSBC6psK2oPMfo-TvXHwg4PeJa3rGdZ2ai70Hc9HA2uwSg\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nContent-Length: 91\r\nConnection: keep-alive\r\nAccept: */*\r\n\r\n{"includePurged": "true", "checkpoint": "CLCmmvGwKhoaCAQaFgEUAAAAAp8QRO_iJWPmbsV5XYi-qJk="}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server header: Date header: Content-Type header: Transfer-Encoding header: Connection header: x-amzn-RequestId header: Content-Encoding header: Cache-Control header: Pragma header: Vary 16-02-23 13:57:28.076 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST /drive/v1/changes HTTP/1.1" 200 None
..
16-02-23 13:57:28.078 [DEBUG] [acdcli.api.metadata] - Checkpoint: CLjVqvGwKhoA
Inserting nodes.16-02-23 13:57:28.147 [INFO] [acdcli.api.metadata] - 1 page(s) in changes.

**Comment by yadayada** [comment]
>I'm unsure how to get a debug log of the bad address part?

Please reply with a log snippet if you figure it out.

>Also this:
[...]

Seriously? What's your problem?

**Comment by adamdilibero** [comment]
Fixed by clearing the cache of acd
