### ISSUE TITLE
API Backoff Req

### ISSUE THREAD

**Issue by dany20mh** [yadayada/acd_cli#283]
Most of the time, this cause my FUSE mount get discount and I'm not sure if I'm doing something wrong here, or it's something else.

16-02-28 09:06:46.706 [DEBUG] [acdcli.api.content] - chunk o 0 l 524288000
16-02-28 09:06:46.706 [WARNING] [acdcli.api.backoff_req] - Waiting 244.183154s because of error(s).
16-02-28 09:06:46.706 [DEBUG] [acdcli.api.backoff_req] - Retry 8, waiting 244.183154s
16-02-28 09:07:09.598 [DEBUG] [acdcli.acd_fuse] - -> access / (0,)
16-02-28 09:07:09.598 [DEBUG] [acdcli.acd_fuse] - <- access 0
16-02-28 09:07:09.598 [DEBUG] [acdcli.acd_fuse] - -> getattr / (None,)
16-02-28 09:07:09.598 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_atime': 1456668429.598734, 'st_nlink': 1, 'st_ctime': 1301403574.027, 'st_mtime': 1456661131.759, 'st_mode': 16895}
16-02-28 09:07:09.598 [DEBUG] [acdcli.acd_fuse] - -> getxattr / ('com.apple.FinderInfo', 0)
16-02-28 09:07:09.599 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 96] No message available on STREAM'
16-02-28 09:07:39.654 [DEBUG] [acdcli.acd_fuse] - -> access / (0,)
16-02-28 09:07:39.654 [DEBUG] [acdcli.acd_fuse] - <- access 0
16-02-28 09:07:39.654 [DEBUG] [acdcli.acd_fuse] - -> getattr / (None,)
16-02-28 09:07:39.655 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_atime': 1456668459.655392, 'st_nlink': 1, 'st_ctime': 1301403574.027, 'st_mtime': 1456661131.759, 'st_mode': 16895}
16-02-28 09:07:39.655 [DEBUG] [acdcli.acd_fuse] - -> getxattr / ('com.apple.FinderInfo', 0)
16-02-28 09:07:39.655 [DEBUG] [acdcli.acd_fuse] - <- getxattr '[Errno 96] No message available on STREAM'
16-02-28 09:07:46.715 [DEBUG] [acdcli.acd_fuse] - -> destroy / ()
16-02-28 09:07:46.715 [DEBUG] [acdcli.acd_fuse] - <- destroy None

**Comment by yadayada** [comment]
The relevant portion of the log is missing. I think it's still the same as #270.

**Comment by dany20mh** [comment]
The log is really big and I couldn't copy all of it here and I don't know which part exactly you need, so I copy it in a text file and uploaded here https://infinit.io/_/C7CBkYb

This is from the time I start the service and it get shutdown.

My test script is nothing special, if you see it in the code, it's just automatic process that make the acdcli running again if it close the mount, so those top and end note is for me.

I'm using this for mounting 
`acd_cli -d -nl mount -fg /Users/Danial/amazon `

Let me know if you need anything else.

**Comment by yadayada** [comment]
I guess the sleep initiated by the back-off algorithm triggers a daemon timeout in osxfuse.

**Comment by dany20mh** [comment]
@yadayada I kind of don't get what you said, do you need me to test something or is there a way to fix it ?

**Comment by dany20mh** [comment]
For example, this past Saturday, it shut down and unmount 15 times during the day.
I don't mind it that much because I have it running in the loop, so anytime it shut down and unmount, it will automatically re-run again, but I don't what is the problem that causing it.

**Comment by yadayada** [comment]
What I meant was 
 - you get 500 errors when trying to read e.g. /Movie/Crank_ High Voltage.mkv
 - the requests to ACD are delayed incrementally, up to 256 seconds
 - if enough consecutive errors occur, finally the delay is so high that oxsfuse's daemon_timeout is triggered
- then the filesystem gets destroyed (unmounted)

Please check that the files that cause these 500 errors are accessible, e.g. try `acdcli -d dl /Movie/Crank_ High Voltage.mkv`.

PS: Please delete your debug log that you uploaded to infinit.io!

**Comment by dany20mh** [comment]
Ok, so I was thinking about something else.
So this is working on the coding and it won't recognize the space because we don't have space in the machine and if we want to use it we have to put \ after the file name, can it be cause the problem?
Because if you see in the name, It's **Crank_High** and then space **Voltage**, so if I run that code, won't do anything.

Danials-iMac:~ Danial$ acdcli -d dl /Movie/Crank_ High Voltage.mkv
usage: acd_cli [-h] [-v | -d] [-nl] [-c {auto,always,never}]
               [-i {full,quick,none}] [-u]
               {version,v,sync,s,old-sync,clear-cache,cc,tree,t,children,ls,dir,find,f,find-md5,fh,find-regex,fr,upload,ul,overwrite,ov,stream,st,download,dl,cat,create,c,mkdir,list-trash,lt,trash,rm,restore,re,move,mv,rename,rn,resolve,rs,add-child,ac,remove-child,rc,usage,u,quota,q,metadata,m,mount,umount,delete-everything,init,i,test}
               ...
acd_cli: error: unrecognized arguments: Voltage.mkv

Even if we run it with \ , it won't work 

Danials-iMac:~ Danial$ acdcli -d dl /Movie/Crank_ High\ Voltage.mkv
16-02-29 14:44:49.285 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-29 14:44:49.285 [INFO] [acd_cli] - TestPlugin attached.
16-02-29 14:44:49.285 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/Danial/Library/Caches/acd_cli".
16-02-29 14:44:49.286 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-29 14:44:49.287 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-02-29 14:44:49.371 [DEBUG] [acdcli.cache.db] - Set busy_timeout to 30000. Result: 30000.
16-02-29 14:44:49.372 [DEBUG] [acdcli.cache.db] - Set journal_mode to wal. Result: wal.
16-02-29 14:44:49.372 [INFO] [acd_cli] - Last sync at 2016-02-29 15:28:59.116660.
16-02-29 14:44:49.375 [CRITICAL] [acd_cli] - Could not resolve path "/Movie/Crank_".


But if I put the destination in quote, it work, just don't download it.


Danials-iMac:~ Danial$ acdcli -d dl "/Movie/Crank_ High Voltage.mkv"
16-02-29 14:46:29.338 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-02-29 14:46:29.338 [INFO] [acd_cli] - TestPlugin attached.
16-02-29 14:46:29.339 [INFO] [acdcli.api.client] - Initializing ACD with path "/Users/Danial/Library/Caches/acd_cli".
16-02-29 14:46:29.339 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-02-29 14:46:29.340 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-02-29 14:46:29.399 [DEBUG] [acdcli.cache.db] - Set busy_timeout to 30000. Result: 30000.
16-02-29 14:46:29.399 [DEBUG] [acdcli.cache.db] - Set journal_mode to wal. Result: wal.
16-02-29 14:46:29.399 [INFO] [acd_cli] - Last sync at 2016-02-29 15:28:59.116660.
16-02-29 14:46:29.402 [INFO] [acd_cli] - Resolved "/Movie/Crank_ High Voltage.mkv" to "Node('g00rE4XDSiKsAhcZJBFpJg', 'Crank_ High Voltage.mkv')"
16-02-29 14:46:29.402 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x10374fcf8>, action='dl', cache=<acdcli.cache.db.NodeCache object at 0x10373ba58>, check=0, color=2, debug=1, exclude_fe=[], exclude_re=[], func=<function download_action at 0x103725c80>, log=True, max_connections=1, max_retries=0, no_wait=False, node='g00rE4XDSiKsAhcZJBFpJg', node_path='/Movie/Crank_ High Voltage.mkv', path=None, remove_source_files=False, times=False, utf=False, verbose=None)
16-02-29 14:46:29.402 [INFO] [acdcli.utils.threading] - 1 jobs in queue.
16-02-29 14:46:29.403 [INFO] [acd_cli] - Downloading "Crank_ High Voltage.mkv".
16-02-29 14:46:29.403 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.064067s
16-02-29 14:46:29.403 [INFO] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content"
16-02-29 14:46:29.826 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): content-na.drive.amazonaws.com
send: b'GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAccept: */*\r\nAuthorization: Bearer Atza|IQEBLzAtAhUAkp2fCzOyVtNVrcBET-LI3VNtTPMCFHkyFfMr9LDBCcr17KhcBgmv21OGZsikUQpdHk0T003zoeXGhtoxemekvAvevjDTmJpGjWgbElVmiU3HakY0bpN9LzPFGFKlHL4oTL17Y_SxtQ67CE_It-O81kigrzWG82V2RBB6fwhm648xQQecpkd-TY8dJurf5t4QfOlS_yWZPfy-w-h7Rdq1QVSbEef1Jibaw6Yd2mYQGOHGJwltX8hc37rcGxv5auSv7UmdBkP5sEYrMyXaKBRMqnH4Y-lPjnjsBjFLoejXQhkrE82nI9_bmlRIYUjRL9rItnlGB30_W1dvhJrQJS9V-B01rC4_as6cO9uElg7UIRi2j-remzO2D6kCTacQuBKV-zs07LMFtpomgoqdzhpJi6U3pg_jB-YB8pvokl4bajaiqT8CW5yLPinElQ\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nConnection: keep-alive\r\nRange: bytes=0-524287999\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'0/1     0.0B/s       0s
header: Content-Type header: Date header: Server header: x-amzn-RequestId header: Content-Length header: Connection 16-02-29 14:46:30.479 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1" 500 30
16-02-29 14:46:30.480 [DEBUG] [acdcli.api.content] - Range 0-524287999
16-02-29 14:46:30.480 [DEBUG] [root] - Chunk [0-524287999], retry 1.
16-02-29 14:46:30.480 [DEBUG] [acdcli.api.backoff_req] - Retry 1, waiting 1.775176s
16-02-29 14:46:32.257 [DEBUG] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content"
16-02-29 14:46:32.259 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (2): content-na.drive.amazonaws.com
send: b'GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAccept: */*\r\nAuthorization: Bearer Atza|IQEBLzAtAhUAkp2fCzOyVtNVrcBET-LI3VNtTPMCFHkyFfMr9LDBCcr17KhcBgmv21OGZsikUQpdHk0T003zoeXGhtoxemekvAvevjDTmJpGjWgbElVmiU3HakY0bpN9LzPFGFKlHL4oTL17Y_SxtQ67CE_It-O81kigrzWG82V2RBB6fwhm648xQQecpkd-TY8dJurf5t4QfOlS_yWZPfy-w-h7Rdq1QVSbEef1Jibaw6Yd2mYQGOHGJwltX8hc37rcGxv5auSv7UmdBkP5sEYrMyXaKBRMqnH4Y-lPjnjsBjFLoejXQhkrE82nI9_bmlRIYUjRL9rItnlGB30_W1dvhJrQJS9V-B01rC4_as6cO9uElg7UIRi2j-remzO2D6kCTacQuBKV-zs07LMFtpomgoqdzhpJi6U3pg_jB-YB8pvokl4bajaiqT8CW5yLPinElQ\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nConnection: keep-alive\r\nRange: bytes=0-524287999\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'0/1     0.0B/s       0s
header: Content-Type header: Date header: Server header: x-amzn-RequestId header: Content-Length header: Connection 16-02-29 14:46:33.017 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1" 500 30
16-02-29 14:46:33.019 [DEBUG] [acdcli.api.content] - Range 0-524287999
16-02-29 14:46:33.019 [DEBUG] [root] - Chunk [0-524287999], retry 2.
16-02-29 14:46:33.020 [DEBUG] [acdcli.api.backoff_req] - Retry 2, waiting 0.057130s
16-02-29 14:46:33.082 [DEBUG] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content"
16-02-29 14:46:33.084 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (3): content-na.drive.amazonaws.com
send: b'GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAccept: */*\r\nAuthorization: Bearer Atza|IQEBLzAtAhUAkp2fCzOyVtNVrcBET-LI3VNtTPMCFHkyFfMr9LDBCcr17KhcBgmv21OGZsikUQpdHk0T003zoeXGhtoxemekvAvevjDTmJpGjWgbElVmiU3HakY0bpN9LzPFGFKlHL4oTL17Y_SxtQ67CE_It-O81kigrzWG82V2RBB6fwhm648xQQecpkd-TY8dJurf5t4QfOlS_yWZPfy-w-h7Rdq1QVSbEef1Jibaw6Yd2mYQGOHGJwltX8hc37rcGxv5auSv7UmdBkP5sEYrMyXaKBRMqnH4Y-lPjnjsBjFLoejXQhkrE82nI9_bmlRIYUjRL9rItnlGB30_W1dvhJrQJS9V-B01rC4_as6cO9uElg7UIRi2j-remzO2D6kCTacQuBKV-zs07LMFtpomgoqdzhpJi6U3pg_jB-YB8pvokl4bajaiqT8CW5yLPinElQ\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nConnection: keep-alive\r\nRange: bytes=0-524287999\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'0/1     0.0B/s       0s
header: Content-Type header: Date header: Server header: x-amzn-RequestId header: Content-Length header: Connection 16-02-29 14:46:34.041 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1" 500 30
16-02-29 14:46:34.043 [DEBUG] [acdcli.api.content] - Range 0-524287999
16-02-29 14:46:34.044 [DEBUG] [root] - Chunk [0-524287999], retry 3.
16-02-29 14:46:34.044 [DEBUG] [acdcli.api.backoff_req] - Retry 3, waiting 0.613841s
16-02-29 14:46:34.659 [DEBUG] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content"
16-02-29 14:46:34.661 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (4): content-na.drive.amazonaws.com
send: b'GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAccept: */*\r\nAuthorization: Bearer Atza|IQEBLzAtAhUAkp2fCzOyVtNVrcBET-LI3VNtTPMCFHkyFfMr9LDBCcr17KhcBgmv21OGZsikUQpdHk0T003zoeXGhtoxemekvAvevjDTmJpGjWgbElVmiU3HakY0bpN9LzPFGFKlHL4oTL17Y_SxtQ67CE_It-O81kigrzWG82V2RBB6fwhm648xQQecpkd-TY8dJurf5t4QfOlS_yWZPfy-w-h7Rdq1QVSbEef1Jibaw6Yd2mYQGOHGJwltX8hc37rcGxv5auSv7UmdBkP5sEYrMyXaKBRMqnH4Y-lPjnjsBjFLoejXQhkrE82nI9_bmlRIYUjRL9rItnlGB30_W1dvhJrQJS9V-B01rC4_as6cO9uElg7UIRi2j-remzO2D6kCTacQuBKV-zs07LMFtpomgoqdzhpJi6U3pg_jB-YB8pvokl4bajaiqT8CW5yLPinElQ\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nConnection: keep-alive\r\nRange: bytes=0-524287999\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'0/1     0.0B/s       0s
header: Content-Type header: Date header: Server header: x-amzn-RequestId header: Content-Length header: Connection 16-02-29 14:46:35.023 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1" 500 30
16-02-29 14:46:35.026 [DEBUG] [acdcli.api.content] - Range 0-524287999
16-02-29 14:46:35.026 [DEBUG] [root] - Chunk [0-524287999], retry 4.
16-02-29 14:46:35.027 [DEBUG] [acdcli.api.backoff_req] - Retry 4, waiting 1.592500s
16-02-29 14:46:36.624 [DEBUG] [acdcli.api.backoff_req] - GET "https://content-na.drive.amazonaws.com/cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content"
16-02-29 14:46:36.626 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (5): content-na.drive.amazonaws.com
send: b'GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1\r\nHost: content-na.drive.amazonaws.com\r\nAccept: */*\r\nAuthorization: Bearer Atza|IQEBLzAtAhUAkp2fCzOyVtNVrcBET-LI3VNtTPMCFHkyFfMr9LDBCcr17KhcBgmv21OGZsikUQpdHk0T003zoeXGhtoxemekvAvevjDTmJpGjWgbElVmiU3HakY0bpN9LzPFGFKlHL4oTL17Y_SxtQ67CE_It-O81kigrzWG82V2RBB6fwhm648xQQecpkd-TY8dJurf5t4QfOlS_yWZPfy-w-h7Rdq1QVSbEef1Jibaw6Yd2mYQGOHGJwltX8hc37rcGxv5auSv7UmdBkP5sEYrMyXaKBRMqnH4Y-lPjnjsBjFLoejXQhkrE82nI9_bmlRIYUjRL9rItnlGB30_W1dvhJrQJS9V-B01rC4_as6cO9uElg7UIRi2j-remzO2D6kCTacQuBKV-zs07LMFtpomgoqdzhpJi6U3pg_jB-YB8pvokl4bajaiqT8CW5yLPinElQ\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: acdcli.api/0.8.9 python-requests/2.9.1\r\nConnection: keep-alive\r\nRange: bytes=0-524287999\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'0/1     0.0B/s       0s
header: Content-Type header: Date header: Server header: x-amzn-RequestId header: Content-Length header: Connection 16-02-29 14:46:36.876 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/g00rE4XDSiKsAhcZJBFpJg/content HTTP/1.1" 500 30
16-02-29 14:46:36.878 [DEBUG] [acdcli.api.content] - Range 0-524287999
16-02-29 14:46:36.878 [DEBUG] [root] - Chunk [0-524287999], retry 5.
16-02-29 14:46:36.879 [ERROR] [acd_cli] - Downloading "Crank_ High Voltage.mkv" failed. RequestError: 1002, [acd_api] Downloading chunk failed multiple times.
[                         ]   0.0% of    4GiB  0/1     0.0B/s       0s
1 file(s) failed.

**Comment by dany20mh** [comment]
Let me know if you want me to test anything else.

**Comment by dany20mh** [comment]
Sorry, I just I missed on more space in the last comment.

It will work if use this 
`acdcli -d dl /Movie/Crank_\ High\ Voltage.mkv`
But still not download and getting error 500.

**Comment by yadayada** [comment]
>Let me know if you want me to test anything else.

Please don't make so many comments; rather edit them if you must.

Can you access/download that file in the web interface? If not, please delete it and other files that are inaccessible.

**Comment by dany20mh** [comment]
Sorry,

From web interface, you can see the size of it, it won't play it cause it saying it's more 20 minutes, but if I hit the download button, it will download a file with a random name **-OdzHjmKs1RFKnkpsSw2pb2MFLRUHbCoC-MwNsiZRj0LAYspN** and it's just 30 bytes.

So I try to delete those files I get error 500 for them.

**Comment by cmeka** [comment]
Same issue, all my files are accessible

`16-03-04 08:34:55.078 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.200053s
16-03-04 08:34:55.794 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.760617s
16-03-04 08:34:56.900 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.693053s
16-03-04 08:34:57.884 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.169660s
16-03-04 08:34:58.942 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.485486s
16-03-04 08:34:59.905 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.142413s
16-03-04 08:35:00.548 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.340169s
16-03-04 08:35:01.505 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.435146s
16-03-04 08:35:03.201 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.618423s
16-03-04 08:35:03.553 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.204479s
16-03-04 08:35:04.299 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.332806s
16-03-04 08:35:05.258 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.478311s
16-03-04 08:35:06.715 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.143172s
16-03-04 08:35:08.074 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.653791s
16-03-04 08:35:08.542 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.389603s
16-03-04 08:35:09.559 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.453135s
16-03-04 08:35:10.578 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.584646s
16-03-04 08:35:11.680 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.103296s
16-03-04 08:35:12.250 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.149053s
16-03-04 08:35:13.185 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.211202s
16-03-04 08:35:13.714 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.132574s
16-03-04 08:35:16.271 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.074299s
16-03-04 08:35:16.834 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.364041s
16-03-04 08:35:17.630 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.635384s
16-03-04 08:35:18.826 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.736724s
16-03-04 08:35:20.143 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -0.006651s
16-03-04 08:35:20.627 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.219952s
16-03-04 08:35:21.225 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.867637s
16-03-04 08:35:22.635 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.201796s
16-03-04 08:35:23.517 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.211512s
16-03-04 08:35:24.230 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.804602s
16-03-04 08:35:25.490 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.321867s
16-03-04 08:35:26.410 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.459665s
16-03-04 08:35:27.360 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.773921s
16-03-04 08:35:28.756 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting 0.606460s`

**Comment by yadayada** [comment]
>From web interface, you can see the size of it, it won't play it cause it saying it's more than 20 minutes, but if I hit the download button, it will download a file with a random name -OdzHjmKs1RFKnkpsSw2pb2MFLRUHbCoC-MwNsiZRj0LAYspN and it's just 30 bytes.

@dany20mh Please contact Amazon's support team.

> Same issue 

Nope, it's not, you don't get any errors. The wait is mandatory.

**Comment by dany20mh** [comment]
@yadayada So far I haven't had the problem anymore, and I deleted those file and download them again, and now I haven't got any shutdown so far.
But I keep you update if anything else happened.
Thanks.

**Comment by yadayada** [comment]
> But I keep you update if anything else happened.

Please don't.
