### ISSUE TITLE
Allow upload --remove-source-files to remove file if already present

### ISSUE THREAD

**Issue by JustinGrote** [yadayada/acd_cli#284]
Hello,

If I'm doing upload --remove-source-files, if it finds the file is present and "skips" the upload, it then doesn't remove the source file.

I understand this is probably a safety check, so perhaps allow to override this behavior by requiring --deduplicate and --force? That way the system will check the hash if a dupe file exists and be absolutely sure it exists correctly remotely before deleting it.

**Comment by yadayada** [comment]
I'm closing this issue because it seems to be a roughly the same as #235. Please object if it is not.

**Comment by JustinGrote** [comment]
Looking at the commit I'm pretty sure this solves the same problem. Will test and report back but yes, it appears to be a dupe of #235 . Thanks very much!
