### ISSUE TITLE
[Non-issue] I'm watching files be deleted from ACD using rm command

### ISSUE THREAD

**Issue by metalgeekstl** [yadayada/acd_cli#285]
I know it's stated under the API Restrictions section that you cannot delete files from ACD via acd_cli, but I'm running the rm command from my mounted ACD directory, and watching them appear in the "Deleted" section of the ACD page in real-time.

Perhaps the API has been updated to allow this?  Either way I'm happy it's working. 

If this belongs somewhere else please notify me. 

Thanks.

**Comment by yadayada** [comment]
You'll notice that that kind of *deletion* is called 'trashing' in the [official API description](https://developer.amazon.com/public/apis/experience/cloud-drive/content/restful-api).

Please use the Gitter.
