### ISSUE TITLE
Some days ago, no auto sync

### ISSUE THREAD

**Issue by vampywiz17** [yadayada/acd_cli#286]
Hello there,

I update the app some days ago (via github), but now its not auto-update the ACD.

If i create a new folder in ACD web interface, it not show automatically in the mounted fuse filesystem.

The only way, if i unmount and run the sync and mount again....

I don't know what happened, it was working well last week...

I use the latest lubuntu version.

Little other info: If i create like a folder in mounted system i see it in web interface.

If you need log or something else, please write it.

Thanks!

**Comment by breunigs** [comment]
try passing `--interval 60` to the command line you mount your folder with, e.g.
```
acd_cli -v mount --foreground --interval 60 /media/acd
```

I guess you are affacted by 02c1120d3e307c0a which was made to fix #231.

**Comment by vampywiz17** [comment]
Working thanks!

I only edit my crontab from `@reboot /bin/sleep 30; /usr/local/bin/acdcli mount /home/vamp/amazon/ --allow-other`

to

`@reboot /bin/sleep 30; /usr/local/bin/acdcli mount -i60 /home/vamp/amazon/ --allow-other `

Now working well.

Thanks again!
