### ISSUE TITLE
Log Files and Upload Overwrite

### ISSUE THREAD

**Issue by 2marshall** [yadayada/acd_cli#287]
I'm running this command to upload data and it's working great but I can't find seem to find a certain file thats being uploaded continuously to verify it's upload was successful. When a file is being --overwritten what kind of string appears in the log files proving it's being overwritten? 

I've done a grep on all the acd_cli.log* files but it doesn't appear.

/usr/local/bin/acd_cli -v upload --overwrite -x 2 /freebacky/Applications /

**Comment by yadayada** [comment]
There's no dedicated message that indicates the beginning of an overwrite. You'll get the hash and size comparison messages.

**Comment by 2marshall** [comment]
ok add this to feature list :)

thanks

**Comment by 2marshall** [comment]
yah it's definately a feature request than because when I run this daily
and do a grep for the specific file I want to see uploaded within the log
files in this job  it would be nice to see that it was successful in
uploading.
