### ISSUE TITLE
oauth_data File Becomes Corrupted

### ISSUE THREAD

**Issue by owlboy** [yadayada/acd_cli#294]
**Environment/Command Used:**
```Mac OS X 10.11.3```
```acd_cli 0.3.1, api 0.8.8```

python3 -c 'import platform as p; print("%s\n%s" % (p.python_version(), p.platform()))' gives me:
```
3.5.1
Darwin-15.3.0-x86_64-i386-64bit
```
Mounted using the command: ```env no_proxy='*' acd_cli mount -ro ~/acd/```

**Issue:**
The following has happened a couple times now for me. I'll return to my server, find the acd_cli drive is not working, and upon attempting remount the following happens:
* First I get an error saying the mount point is in use (```~/acd/``` for me). 
* Then I force an unmount. (```acd_cli umount```)
* Next I attempt to remount and I get an error telling me the ```oauth_data``` file is missing or incorrect.

Here is an example of the "corrupted" ```oauth_data``` file. (I removed large middle chunks of the keys for my privacy. Otherwise structure is the same as I found it):
```
{
    "access_token": "Atza|IQEBLjAsAhR_d_2GufCLL31jnGQq_EIIgIUDgKQluhbRKMpOgR66trUaSLpWHzI32CHkL-MZAf4GIhLmaphkHGbye3q1c6eksY_dMGl_XVcQ81mkBgwonWGZrTmAZugbbbZWd99cPA3bAxcRmMkt6oqSUBPk-uKroXEiaS-PWF3wc3GPNuXuG907pOsdFr8rQPtajJ5R3m1SP7lp6ArP",
    "exp_time": 1455389409.62625,
    "expires_in": 3600,
    "refresh_token": "Atzr|IQEBLjAsACZiDsVco6rSsjUbhLEtBqY00Icv2T7X-89wAzgiM1CL1tL4O9dx0-xGfzt4vVvy-DuwLI2_ta9MxMmtyfFiJEIaYlfoOJWGfOEBs8sIJajlrtFpQzKj",
    "token_type": "bearer"
}token_type": "bearer"
}
```

The first time it happened the "corrupted" oauth_data file looked like this:
```
{
    "access_token": "Atza|IQEBLzAtAhRaWaw1ByNQIVAI9yCgSV-MHnQL_3I7A7sbSuIgOIg2OHeeU9dMUshok0wqVX2Xo3I5xu-DlKrnUqOFJ3wGJR7PrLbyTgP0QVg-sczBN7mVY5K0MruTLZ1NRpH_WmmRJSNK4_W2ASimulJIdCjcL1lWgKIFWCh5dUX6kFfj1n-xjjxX4mhJfT-pAaD_dMTr87xkaF4SXUbcs_Adho6iTiKWFsFoR-LESap5QEaoaiGCw_sCxsXFroy5ttP3wILIiO-z0XI4FMOyAv8HiBFrJpBe7rteO-0g6xCzrbLM1tbwa4HqElK4LBTsiNZh4dlc3o6iDxLix4",
    "exp_time": 1457830740.933467,
    "expires_in": 3600,
    "refresh_token": "Atzr|IQEBLIEyEq8gKv6b6q7Ou0ZFAgdUCIynFaMMLiBF30dszCtn8e3m-3hL6686eT2_4dESnL-MC9gKSW6M0G-_4FtfhGu-iDCpcKVnoX-Mw-SD_WDwXDlP0XoYWAS3t-ettNOHn5Sl2pJTAt8oJz1ih10kP8E14tZvpmi21zcKosDj4BsygylkU7sYlgyNqehQ0ad1sUgLiwo8G3iT202r-pyUfzTZeW2veZ_P9TpN0S2gr4FRH4_R_7Xnffw",
    "token_type": "bearer"
}}
```

**Comment by msh100** [comment]
I have seen this happen before on an OpenVZ container, as I didn't have control to the host assumed there was some outdated filesystem module or such but assume not now.

I noticed this back in July maybe so this problem has existed for some time.

The `oauth_data` file becomes corrupt when it is overwritten by data which is smaller than before, I suspect that the previous content is not wiped beforehand and simply written on top so if you have a file which is smaller, you end up with the trailing parts of the larger (older) file.

A quick fix I used was to simply run a cron to remove all contents after the first `}` in the file, as this should only occur once. I never digged any deeper into the cause and I no longer have information of the host where this happened - sorry.

**Comment by msh100** [comment]
Hey @owlboy to answer what you asked on Twitter, I don't have the script I used before but quickly put something together like this:

```
JSON=`cut -f1 -d"}" oauth_data`; echo "${JSON}}" > oauth_data
```

This would set `$JSON` to the content of `oauth_data` up until `}`, then it would write that content + an additional `}` back to `oauth_data`. I think this should work fine, replace the paths obviously.

For a more permanent solution - I guess the config writer should be repaired :smile:
