### ISSUE TITLE
Add Xattr Support

### ISSUE THREAD

**Issue by segator** [yadayada/acd_cli#296]
I think it will be very interesting to add xattr support to use it for sync purposals.
I see in the API  of amazon and it's possible using metadata LABEL tag or properties.
https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes

**Comment by yadayada** [comment]
Is this the same as #58? 

If not, is there a specific software you indent to use or a specific extended attribute that's needed?

**Comment by segator** [comment]
yes it's the same but xattr it's not only the atime and mtime setting it's for more uses but one of them is for set the date yes.
I'm  never used python but just right know I'm trying to debug your application with pycharm to now how works and see if I can help.

I have thought a solution for this and we have 2 possibilties use metadata fields (we could only use description or label field, it's the only modificable values) or we can use the properties API that i think it's more correct but I don't know when you get a dir files information of a directory you will see all the properties or you will need to get a request for every file to get the information. if is the second option I would choose the metadata API rather than property API. I saw in your api you have implemented the both requests so I think it's not a big deal to implement xattr.
