### ISSUE TITLE
Amazon Cloud unlimited now in Canada. Canadian Amazon drive server support?

### ISSUE THREAD

**Issue by ecchi** [yadayada/acd_cli#297]
Apparently Amazon Canada now has unlimited drive (not just photo). Just came out in the last 24 hours?
Presently I'm using US amazon cloud storage with a vpn. But it would be nice to stop breaking the ToS, and just use the new Canadian Amazon Drive servers.

**Comment by microSCOPED** [comment]
I wonder how hard it would be to switch.

Mike

On Mar 25, 2016 5:24 PM, ecchi <notifications@github.com> wrote:

Apparently Amazon Canada now has unlimited drive (not just photo). Just came out in the last 24 hours?
Presently I'm using US amazon cloud storage with a vpn. But it would be nice to stop breaking the ToS, and just use the new Canadian Amazon Drive servers.

**Comment by ecchi** [comment]
enabling support for it? or copying content? 
Enabling? I can't really comment on. Maybe a configuration step.

Copying?I imagine copying shouldn't be too difficult. Worst case I download locally, then re-upload to the new servers. Maybe rent a VPS with a high speed connection if I'm impatient.

**Comment by microSCOPED** [comment]
I meant moving my content over.

I guess if acd_cli had support for that region I could just mount them both and copy the data across.

Mike

On Mar 25, 2016 5:41 PM, ecchi <notifications@github.com> wrote:

enabling support for it? or copying content? 
Enabling? I can't really comment on. Maybe a configuration step.

Copying?I imagine copying shouldn't be too difficult. Worst case I download locally, then re-upload to the new servers. Maybe rent a VPS with a high speed connection if I'm impatient.

**Comment by yadayada** [comment]
While I only have tested with a US and an EU account, I would assume it just works™ with a Canadian endpoint. You should contact Amazon's support to get your data moved (see #181).
