### ISSUE TITLE
acdcli now gives an error on mount/sync

### ISSUE THREAD

**Issue by rizjuan1** [yadayada/acd_cli#299]
I noticed a transfer was going very slow via fuse mounted acdcli. I canceled it and tried to unmount via `acdcli umount /home/plex/amazon` but received the error `fusermount: failed to unmount /home/plex/amazon: Device or resource busy` so i unmounted via `sudo umount -l /home/plex/amazon` .

That did the trick but now when I try to mount I get the following:

> plex@plex-onra:~$ acdcli mount /home/plex/amazon
> Traceback (most recent call last):
>   File "/usr/local/bin/acdcli", line 9, in <module>
>     load_entry_point('acdcli==0.3.1', 'console_scripts', 'acdcli')()
>   File "/usr/local/bin/acd_cli.py", line 1498, in main
>     cache = db.NodeCache(CACHE_PATH, args.check)
>   File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/db.py", line 49, in                    __init__
>     self.init()
>   File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/schema.py", line 91,                    in init
>     self.create_tables()
>   File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/schema.py", line 107                   , in create_tables
>     self._conn.executescript(_CREATION_SCRIPT)
> sqlite3.DatabaseError: file is encrypted or is not a database

Any ideas? I also get the same error when I try to run `acdcli sync` .

**Comment by judhat2** [comment]
Try `acdcli clear-cache` before syncing. If that doesn't work then delete /.cache/acd_cli/nodes.db in your home directory.  That has worked for me before.

**Comment by rizjuan1** [comment]
@judhat2 `acdcli clear-cache` gave the same error. Deleting the nodes.db file seems to have fixed the issue for me thoguh. Thanks!

**Comment by seb206** [comment]
Hello all,

I have installed acdcli on debian and I have the issue quoted... "sqlite3.DatabaseError: file is encrypted or is not a database". Removing the ~/.cache/acd_cli/nodes.db is working fine!

However, I have an issue on MacOS, I did the same setup, acd_cli was working fine, and I have the "sqlite3.DatabaseError: file is encrypted or is not a database" while syncing. Unfortunately, I'm not able to find where is located the nodes.db database !
"locate" is returning nothing, I checked /User/myuser/.cache there's no drawer....
I launch acd_cli with a sudo, and there's no root folder on mac :(
Could you please help to find the issue, the error log is the following:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/acd_cli.py", line 1584, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/db.py", line 59, in __init__
    self.integrity_check(check)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/acdcli/cache/db.py", line 124, in integrity_check
    r = c.execute('PRAGMA integrity_check;')
sqlite3.DatabaseError: file is encrypted or is not a database

**Comment by putty182** [comment]
On OS X, the cache folder will be `~/Library/Caches/acd_cli`

**Comment by AiMAnsarie** [comment]
I'm using ACD_CLI for an always on PLEX MEDIA SERVER so on Ubuntu this did the trick for me, thanks to all of you guys commented above:

1) $ sudo service plexmediaserver stop
2) $ rm root/.cache/acd_cli/nodes.db
3) $ acd_cli clear-cache
4) $ acd_cli sync
5) $ acd_cli mount <your mount path. for me it was "/home/plex/amazon" without quotes>

Hope that helps a noob like me out there!
