### ISSUE TITLE
FUSE crashes randomly

### ISSUE THREAD

**Issue by rizjuan1** [yadayada/acd_cli#301]
Every now and then FUSE will crash on my system. It seems random but it might be either correlated to when I'm deleting files (maybe via WinSCP?) or have multiple things accessing it at the same time (Plex, Sonarr, Sabnzbd, etc). When it crashes Plex no longer sees the files, WinSCP starts throwing out permission errors, and a ls command in terminal gives the following:

> plex@plex-onra:/home/plex/amazon$ ls
> ls: reading directory .: Bad address

The logs show the following over and over:

> 16-03-30 11:26:25.502 [DEBUG] [acdcli.acd_fuse] - <- getattr '[Unhandled Exception]'
> 16-03-30 11:26:25.503 [DEBUG] [acdcli.acd_fuse] - -> getattr / (None,)
> 16-03-30 11:26:25.504 [DEBUG] [acdcli.acd_fuse] - <- getattr '[Unhandled Exception]'
> 16-03-30 11:26:25.504 [DEBUG] [acdcli.acd_fuse] - -> getattr /Temp (None,)

Here is a complete version of the logs showing the error/crash as it first happened. This one seemed to be immediately triggered by a delete action I took in WinSCP: [http://pastebin.com/8vap4WyC](http://pastebin.com/8vap4WyC)

Edit: A friend suggested mounting with the -ao switch and seeing if that helps. I'm going try that but am not sure why it would help.

**Comment by judhat2** [comment]
This looks similar to #290

**Comment by yadayada** [comment]
I think so, too. I suggest mounting with `-i0` since the errors begin to occur after an autosync call.

**Comment by rizjuan1** [comment]
@yadayada Thanks I will try that! Just for clarification `-i0` disables autosync? I also have a crontab entry of `* * * * * /usr/local/bin/acd_cli sync` which syncs acd_cli every minute. Would you advise removing that? Could that have been causing the issue in the first place?

**Comment by yadayada** [comment]
I was assuming you had autosync enabled. See the output of `acdcli mount -h` to check whether your acd_cli version still uses autosync.

>Would you advise removing that? 

Yes.

>Could that have been causing the issue in the first place?

Looks like it.

**Comment by rizjuan1** [comment]
D'oh. That's what I get for following a random online tutorial. ([link](http://makeshift.ninja/unlimited-plex-media-server-using-amazons-unlimited-storage-backend-pt1.html))

I was using the latest master version when I had that error. I have since downgraded to the PyPI version but just to test some things- I will upgrade back to master shortly and test it out. Thanks again!

**Comment by saqebakhter** [comment]
What is a good way to update the fuse mount - with autosync diabled ?

On Wed, Mar 30, 2016 at 12:30 PM, rizjuan1 <notifications@github.com> wrote:

> D'oh. That's what I get for following a random online tutorial. (link
> <http://makeshift.ninja/unlimited-plex-media-server-using-amazons-unlimited-storage-backend-pt1.html>
> )
>
> I was using the latest master version when I had that error. I have since
> downgraded to the PyPI version but just to test some things- I will upgrade
> back to master shortly and test it out. Thanks again!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/yadayada/acd_cli/issues/301#issuecomment-203514137>
>



-- 
- Saqeb Akhter
