### ISSUE TITLE
raise EnvironmentError('Unable to find libfuse')

### ISSUE THREAD

**Issue by thesatman** [yadayada/acd_cli#302]
Found some similar issues, but assumed it was better to open my own issue.

My setup: 
XPenology running as a VM on VMware. HP N54L AMD Athlon II x4 260. 
DS3612xs, DSM 5.04458

Installed Python 3.4 with included pip3.+ acd_cli 0.3.1 and API 0.8.7

Can run acd_cli ls, that part is working. Created new folder called "amazon_cloud".

`XPEnDiskStation> /volume3/@appstore/py3k/usr/local/bin/acdcli mount /volume3/NAS-data2/Media\ Server\ content\ 3/amazon_cloud
Traceback (most recent call last):
  File "/volume3/@appstore/py3k/usr/local/bin/acd_cli", line 11, in <module>
    sys.exit(main())
  File "/volume3/@appstore/py3k/usr/local/bin/acd_cli.py", line 1366, in main
    sys.exit(args.func(args))
  File "/volume3/@appstore/py3k/usr/local/bin/acd_cli.py", line 904, in mount_action
    import acdcli.acd_fuse
  File "/volume3/@appstore/py3k/usr/local/lib/python3.4/site-packages/acdcli/acd_fuse.py", line 15, i
n <module>
    from acdcli.bundled.fuse import FUSE, FuseOSError as FuseError, Operations
  File "/volume3/@appstore/py3k/usr/local/lib/python3.4/site-packages/acdcli/bundled/fuse.py", line 7
6, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse`

It looks like libfuse is already on my system from when I installed VMware-tools ::
`XPEnDiskStation> find / -name libfuse*
/volume1/@appstore/open-vm-tools/lib/libfuse.so.2
/volume1/@appstore/open-vm-tools/lib/libfuse.so.2.9.3
/volume1/@appstore/open-vm-tools/lib/libfuse.so`

I have both ipkg and opkg installed. Ipkg did not offer the download for libfuse. But I found it from a x86 version from QNAPware. Tried that as well, without any success.

When I do 
`umount
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH"/volume1/@appstore/open-vm-tools/lib/libfuse.so.2"`

I still get the same error. So after 2 days of trial and error, I'm kind of stumped in what to try next. I've been reading the howto on the latest bundled/fuse.py and the option to define your own path, but I don't understand where that needs to be done, or at what point.

Any advice would be welcome. Thank you in advance for what looks to be a great solution.

**Comment by yadayada** [comment]
You need to `export LIBFUSE_PATH="/volume1/@appstore/open-vm-tools/lib/libfuse.so.2.9.3"` before mounting.

But even if that works, you may need to compile (or to somehow obtain) a 64bit libfuse. See #263.

**Comment by thesatman** [comment]
OK, for what it's worth it, I did a check:

XPEnDiskStation> ./python3 <<EOF
> with open('/volume1/@appstore/open-vm-tools/lib/libfuse.so.2.9.3',
'rb') as libfuse:
>     libfuse.seek(4)
>     arch = 32 if libfuse.read(1) == b'1' else 64
>     print(arch)
> EOF
64

Looks like this is the correct version? What do you suggest?

**Comment by yadayada** [comment]
There was an error in the code snippet, so please re-check

```
python3 <<EOF
with open('/volume1/@appstore/open-vm-tools/lib/libfuse.so.2.9.3) as libfuse:
    libfuse.seek(4)
    arch = 32 if libfuse.read(1) == b'\x01' else 64     
    print(arch)
EOF
```

**Comment by thesatman** [comment]
Same result :)    >>  64

**Comment by yadayada** [comment]
>Same result :)    >>  64

That's encouraging. Does it mount now after exporting LIBFUSE_PATH?
