### ISSUE TITLE
Moving to another server

### ISSUE THREAD

**Issue by microSCOPED** [yadayada/acd_cli#304]
So, I want to move my connection to another server, I use acd_cli and encfs.

Is there a proper way to do so? Or a better place to ask?

Thanks.

**Comment by msh100** [comment]
This is quite an odd place to ask.

Anyway, you can copy `~/.cache/acd_cli` to your new node to get the oauth credentials and a copy of your objects on acd. As for encfs, maybe also copy your encfs configuration file? That really depends on your setup.

The thing about storing data on Amazon is that you don't really need to do anything to migrate. All your data is remote regardless.
