### ISSUE TITLE
Error syncing

### ISSUE THREAD

**Issue by chesterdkat** [yadayada/acd_cli#305]
I am getting the following error when I sync:

pi@aws_server:~ $ acdcli sync
Syncing...
RequestError: 504, [acd_api] no body received.
16-04-03 21:42:16.858 [CRITICAL] [acd_cli] - Sync failed.

Note, once the sync command is issued this error keeps reappearing every 2 minutes or so.

Thanks!

Now I am getting this after issuing the sync command:

pi@aws_server:~ $ acdcli sync
Syncing...
RequestError: 1000, HTTPSConnectionPool(host='cdws.us-east-1.amazonaws.com', port=443): Read timed out. (read timeout=60)
16-04-03 22:13:33.764 [CRITICAL] [acd_cli] - Sync failed.

**Comment by yadayada** [comment]
See #259.
