### ISSUE TITLE
Sync failing

### ISSUE THREAD

**Issue by SullyTheUnusual** [yadayada/acd_cli#308]
Getting this message when I try running `acdcli sync`.  I ran `acdcli cc` first, and it still happens.

Syncing...
RequestError: 1003, [acd_api] reading changes terminated prematurely.
16-04-10 13:29:07.871 [CRITICAL] [acd_cli] - Sync failed.

**Comment by calisro** [comment]
Wish I would have seen this before I opened a new one...  FYI, I bet the old-sync option works as a work around.

https://github.com/yadayada/acd_cli/issues/310

**Comment by yadayada** [comment]
@SullyTheUnusual Could you please try if the same error occurs using the  762dd0c14ce6f07158e703765547b8f40ae772d7 commit or older, e.g. by installing the PyPI version?

@calisro clearing the cache is equivalent to using the ``--full`` flag.
