### ISSUE TITLE
Stuck progress indicator

### ISSUE THREAD

**Issue by Issam2204** [yadayada/acd_cli#31]
Hello! Thank you for the beautiful and useful software :)

I have the latest version and it looks like this time to trigger a time out I have to press CTRL + C. This way acd_cli  doesn't stop completely, but it simply skips the stuck upload.

My previous experience was that timeout generally "activates" without manual intervention (perhaps after 1 minute?). In a scenario with long uploads, manual intervention is not handy.

Here is what happened (I waited 10 minutes before pressing CTRL + C, no % change during these 10 minutes - TMUX environment):
```
>Current directory: EXAMPLE
Current file: EXAMPLE1.mp4
[#######################          ]  69.3% of    1.4GiB,    1.1MB/s
15-05-06 10:37:20.704 [acd_cli] [WARNING] - Timeout while uploading "EXAMPLE1".
Current file: EXAMPLE2.jpg
[#################################] 100.0% of  203.5KiB,
```
This happened in a Kimsufi (OVH) server with Ubuntu 14.04. I don't understand if this is Kimsufi's fault, since timeouts mainly happens with this server. No issues with other servers/VPSs.

I'm still heavily testing acd_cli. Right now I'm uploading 120 GB.

Again, thank you!

**Comment by yadayada** [comment]
Your upload may still be going on even if the percentage indicator stalls... albeit very slowly. Currently, the low-speed timeout is 60s with 0Bytes transferred.

**Comment by Issam2204** [comment]
Thank you for your answer!

Now that you mention it, when I press CTRL + C I notice that the % changes: it is a bit higher than before. We can say that there is certainly a transfer.

The question becomes: why does it get graphically stuck when the transfer rate becomes very low (from being initially high)?

I have this idea, please tell me if you find it feasible: acd_cli could check the file size of an uploading file and when such a file is big (say 500 MB+) and when the transfer rate becomes too slow (say 10 KB/s -) it drops the current transfer, and it re-starts the upload. 
Now, this could have many implications: what is a big file size? What is a slow rate transfer (for someone is 5 KB/s, for others 1MB/s)? Should acd_cli drop a transfer that reached 95% just because it's going slow?

When I'll have the next stuck file I'll make sure to check if acd_cli actually transfers data or not.

Thank you!

**Comment by yadayada** [comment]
>why does it get graphically stuck when the transfer rate becomes very low
I haven't looked into how curl determines when/how often to trigger the progress callback.

Implementing a (static) minium upload rate as an argument would be trivial. But as it is I'm using two different libraries for uploading (curl) and everything else (requests) and I was planning on removing the curl dependency.

**Comment by Issam2204** [comment]
That's what I thought regarding the static minimum upload.

Thanks yadayada!

**Comment by yadayada** [comment]
Does this still happen? The progress indicator should refresh every 0.3 seconds now.

If it still happens, could you try pressing the enter key? If it doesn't, please cose the issuel

**Comment by dansku** [comment]
One quick question, how do I update the software to an new version. Just download and pip install . and it will be updated?

**Comment by Issam2204** [comment]
I tested it on 100 GB files. I'd like to make an another test with a faster network so to push at least 500GB.

I let you know tomorrow. Sorry for keeping this open.
