### ISSUE TITLE
Unable to sync 504, [acd_api] no body received.

### ISSUE THREAD

**Issue by calisro** [yadayada/acd_cli#310]
I have been unable to sync for some time (months).  I've deleted the database and started from scratch and it works initially but then fails again because there are a lot of changes between syncs.  I think it is just timing out because of the number of changes in between syncs.  Between each sync, there are tens of thousands of changed/new/deleted files.

acd_cli sync
Syncing... 
RequestError: 504, [acd_api] no body received.

I tried the 'old-sync' and that seems to work but (  very very very slowly :)  )   is there an option to potentially increase the timeout for the regular sync to let it complete?  Any other ideas?  Any other data I can drop into this issue to help?  What's interesting is that it works on the initial sync to create the database.  Perhaps an option that simple just recreates the database from scratch gracefully instead rather than applying deltas (which is how I *think* it works).

**Comment by yadayada** [comment]
>is there an option to potentially increase the timeout for the regular sync to let it complete? 

There's nothing I can do about a 504 gateway timeout.

>Perhaps an option that simple just recreates the database from scratch gracefully instead rather than applying deltas (which is how I think it works).

``acdcli sync --full`` will do.

**Comment by calisro** [comment]
Thanks, I tried the --full and it did complete faster than the 'old-sync' did.  Do you think there could be some enhancements in the 'old-sync' option?  The old-sync I believe does a pagination of 200 entries (I may be mistaken).  Perhaps if that was configurable, we could use the old-sync but make it more aggressive with a higher pagination to complete a bit faster (before the ACD timeouts the request that is).

**Comment by yadayada** [comment]
>Do you think there could be some enhancements in the 'old-sync' option? 

No.

>The old-sync I believe does a pagination of 200 entries 

That's already the maximum. 

>I suppose if the periodic sync wasn't disabled, I would not have this problem because i'd never have that many changes queued up anyway to sync.

Re-enable it and see if it works. Hint: there is a command line argument for that.
