### ISSUE TITLE
Updates not appearing in FUSE mount

### ISSUE THREAD

**Issue by munrotm** [yadayada/acd_cli#311]
I am not seeing new files coming into my mounted fuse drive as of a couple days ago. I am uploading a bunch of stuff from my NAS using RCLONE, whilst simultaneously mounting the drive on a VPS.

ACD is mounted to /media/amazon. ls on this folder shows:
xxxx@xxxxxx:/media/amazon# ls
Plex Cloud Sync  backup

However there are more folders here, as can be seen when I run acdcli ls:
xxxx@xxxxxx:/media/amazon# acdcli ls
[dCeX00ClRLq-Kd5031owsQ] [A] Plex Cloud Sync/
[25S6Rf-QRcmwW_-Y5-DeWg] [A] backup/
[wIUniWIbSr-KLe3QAk7aJg] [A] seed/

This is directly after running acdcli sync. Is the automatic syncing supposed to work, or am I required to unmount and mount to see changes?

xxxx@xxxxxx:/media/amazon# acdcli version
acd_cli 0.3.1, api 0.8.9

xxxx@xxxxxx:/media/amazon# uname -a
Linux xxxxxx 2.6.32-042stab113.11 #'1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

Cheers

**Comment by yadayada** [comment]
>Is the automatic syncing supposed to work, or am I required to unmount and mount to see changes?

You can enable autosync by e.g. adding the mount option ``-i 60 `` to see whether it causes problems for you or not.

**Comment by munrotm** [comment]
Is it possible to add this variable to fstab if mounting that way at boot?
