### ISSUE TITLE
authorization with a headless server

### ISSUE THREAD

**Issue by magicalbanana** [yadayada/acd_cli#313]
Just wondering if what the approach is when authorizing with a headless server?

**Comment by EldonMcGuinness** [comment]
@magicalbanana If you're referring to the capturing the oauth file, I believe the docs mention that the setup will try to open a lynx (cli browser) to get the oauth bits. Though you could always scp/ftp the oauth file from a machine with a traditional desktop to the headless box, that is what I did.

**Comment by magicalbanana** [comment]
@EldonMcGuinness no, I mean when you run the authorization on the headless browser by an ssh session, I wanted to know if the browser that needs to be opened has to be forwarded to the client connecting. But I think I'll just do your second suggestion. Thanks @EldonMcGuinness!
