### ISSUE TITLE
Reusing already opened https connection

### ISSUE THREAD

**Issue by karbowiak** [yadayada/acd_cli#315]
Hi there.

From the log it seems that it's constantly reopening new https connections, not that they're super time consuming to setup, doing it a lot (as is happening with file requests apparently) do end up slowing it all down.

Probably an idea to reuse the already opened connection? :)

**Comment by yadayada** [comment]
Commit 25b559b49946750d642321caf4b3856440ea096f put a session into use.

When downloading, I get one message
```
[INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): content-na.drive.amazonaws.com
```

From the dozens of messages following like that

```
[DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/FOOBAR/content HTTP/1.1" 206 
```

I gather the connection gets reused...

**Comment by karbowiak** [comment]
Hm, might have missed that - i just saw a bunch of "Starting new HTTPS connection" lines - and went with the feeling that it was spawning new connections for every part of a file /o\

My bad - i'll close this again :)
