### ISSUE TITLE
Type mismatch error in pulling settings.

### ISSUE THREAD

**Issue by surfrock66** [yadayada/acd_cli#319]
Ubuntu Server 16.04, was working fine in 15.10.  Using Python 5.3.1+.  Freshly updated acd_cli from git.  When trying to mount an amazon drive, I get a crash.

Output:
```
surfrock66@sr66-blade:~/.sources$ /usr/local/bin/acd_cli mount /mnt/amazon-drive/
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1345, in main
    cache = db.NodeCache(CACHE_PATH, args.check)
  File "/home/surfrock66/.local/lib/python3.5/site-packages/acdcli/cache/db.py", line 65, in __init__
    self._conf = _get_conf(settings_path)
  File "/home/surfrock66/.local/lib/python3.5/site-packages/acdcli/cache/db.py", line 30, in _get_conf
    conffn = os.path.join(path, _SETTINGS_FILENAME)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'
```

I'm a noob to python, but looks like something goes wrong in setting the "settings_path" variable from /cache/db.py

**Comment by yadayada** [comment]
>  File "/usr/local/bin/acd_cli.py", line 1345, in main
>  File "/home/surfrock66/.local/lib/python3.5/site-packages/acdcli/cache/db.py"

Different versions?!

**Comment by surfrock66** [comment]
Huh...good catch, not sure.  I've followed the install and update procedures...lemme purge and re-setup.

I installed with:
`sudo pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git`

and I re-run that every week or so.

Also, this may be relevant:
```
surfrock66@sr66-blade:~/.sources/acd_cli$ pip3 list | grep acd
acdcli (0.3.1)
```

**Comment by surfrock66** [comment]
Yea, did a search on my system, blew away anything with acd in /usr, (there was stuff in /usr/local/lib/python3.4/dist-packages), then reinstalled and it worked.  I wonder if artifacts left over from the Ubuntu upgrade broke it.

Either way, working now.
