### ISSUE TITLE
(Very) Large file split.

### ISSUE THREAD

**Issue by chrisidefix** [yadayada/acd_cli#32]
Maybe `acd_cli` isn't really the tool to do this, but what do you think about splitting very large files before uploading them?

### Why do we need this?
`acd_cli` makes uploading files to amazon a lot easier.
With the *unlimited* file storage capacity, people will want to store *very large files* there.
It would be great if `acd_cli` could become the tool to allow this in a smarter fashion than doing it manually.

### When do you really need this?
For example, I have some old, encrypted backup images that I would like to backup to ACD - they are over 100 GB in size. I tried uploading them through the official app, but after waiting for a while `...` and reaching `100%` in the upload view, it simply gives an error and the file doesn't show up online. This is frustrating and annoying.

### It doesn't work without this?
I tried to upload such large files (> 100 GB) through `acd_cli` and while it appeared to work fine, I received a time-out at the very end and the file didn't show up ACD.
The largest file I managed to upload was just over 40GB, which is already pretty good.

### How should this work?
Probably by means of split-rar archive creation. Note that you need not to compress anything, but simply split the file (which makes it faster and will mostly be limited by disk read/write speeds).

### What other advantages does this have?
Well, if the file is split - each part could be uploaded / downloaded in parallel as discussed here #7 (ok, maybe for uploading this doesn't make too much sense, but I think for downloading might very well be worth it). This would very much improve the speed everybody could use ACD at.

**Comment by Issam2204** [comment]
Hi!

I like this idea but I'd not really consider it as a high priority implementation. What you need can be easily achieved with two commands (to make your life easier you can use an alias in your .bash_aliases file, or even better if you use a simple script that once called will split the file and upload it with acd_cli).

You have all the tools there: split, gnupg and acd_cli. Call them with a script :)

**Comment by yadayada** [comment]
There is a project called [splitviewfuse](https://github.com/seiferma/splitviewfuse) which might do the trick if - or once - the FUSE write support is implemented.

**Comment by ShapeShifter499** [comment]
@yadayada I'm a bit confused, why would write support be needed?

**Comment by yadayada** [comment]
I don't remember why I wrote that. The splitview should point to the original directory (containing large files) and the unionview should point at the FUSE mount point.

**Comment by yadayada** [comment]
I'm not implementing it.

**Comment by 0xFEEDC0DE64** [comment]
I implemented a small c++ application that splits any file into small pictures (for free unlimited photo storage). I can also reassemble the pictures to a file again. It does work on folders and on files. I hope this helps in any way handling huge files!
