### ISSUE TITLE
mount breaks on sync operation sporatically

### ISSUE THREAD

**Issue by shushry** [yadayada/acd_cli#325]
I have several independent servers mounting the same ACD, and in order for each to see changes to the ACD filesystem from the others, it's necessary to run an acd_cli sync on occasion.   Currently, I'm doing this on a scheduled basis.

Sometimes when an acd_cli sync is run, it breaks the mount on the server this is run on.  Attempts to access the mount point result in "Bad address - transport endpoint not connected".   The only way to recover is to unmount and remount ACD.   

I haven't tested this extensively but I'm suspicious that this happens if an operation is underway that uses the mountpoint, and a scheduled "acd_cli sync" is run.

Any insight into this?  Is there a better way to keep the mountpoint in sync?

**Comment by tobyboreham** [comment]
I also have this issue - I've experienced it on both OS X and Linux.

**Comment by be8weyq6** [comment]
I have this same issue too.  I can recreate it everytime with the following:

1. Have acd_cli mounted to a directory, such as /mnt/acd
2. Upload a file using the ACD web interface to a directory under ACD, for example "Temp".
3. acd_cli sync
4. cd /mnt/acd/Temp
5. ls

I get:

ls: cannot open directory '.': Bad address

**Comment by SchnorcherSepp** [comment]
sounds like this:   https://github.com/yadayada/acd_cli/issues/290
it happens sometime
I am also affected

**Comment by yadayada** [comment]
Don't have multiple acd_cli instances access the same cache. 

You can try autosyncing, but if that doesn't work, you're out of luck.

**Comment by shushry** [comment]
Thanks for chiming in.   Note that these are NOT multiple acd_cli instances accessing the same cache.   Original report at the top indicates "independent servers" accessing the same acd account.   Completely different servers.     Standard sync operation (to collect changes made by other, independent instances on other servers), seems to cause the mount break issue.

**Comment by shushry** [comment]
Scratch that.  I'll try the autosync.

**Comment by EldonMcGuinness** [comment]
For what it is worth, I have noticed that mounting the acd share as read-only seems to help this issue. If you are in need of syncing to account for multiple devices accessing the same acd account then you could always whip up a script to unmount, sync, remount the share. I do this once an hour on my box to account for this and all is fine. However, all writes are done via "acdcli ul" and not via the fuse module.

**Comment by shushry** [comment]
Thanks Eldon -   I was running an acd_cli sync command independent of the mount, and this "mostly" works, but occasionally creates the breakage and apparently this is an unsupported process.

At my end I essentially do a healthcheck and then remount if there is a problem, but if there is an operation in place (like moving data) in a bad case, it'll break that operation.

I wasn't aware of the autosync feature - or moreso that it had been repaired in the past, so I'll give that a go and see if it actually works.   I had implemented regular acd_cli sync operations early on when independent changes weren't showing up.

**Comment by EldonMcGuinness** [comment]
shushry, indeed, the remount would break it, what I do is use lsof to check and see if anything is accessing a file in that directory and then postpone the remount until that condition goes away.

acdremount
```
echo "Remount Initiated $(date)"

if [ $(ps -Al | grep acdremount | wc -l) -gt 2 ]; then
        echo "Already Running! Count $(ps -Al | grep acdremount | wc -l)"
        exit
fi

while [ $(lsof | grep '/mnt/.acd' | wc -l) -gt 0 ]; do
        echo "File in use, waiting $(date)"
        sleep 300
done

echo "Remounting $(date)"
        umount /mnt/.acd
        acdcli sync
        mount /mnt/.acd
echo "Remount Done $(date)"
```
