### ISSUE TITLE
AttributeError: 'NodeCache' object has no attribute 'resolve_path'

### ISSUE THREAD

**Issue by sjpotter** [yadayada/acd_cli#327]
So I'm trying to set it up, and it I did an init and a sync.  usage shows information, but ls fails with the error

```
$ acd_cli usage
Documents:       1,    5.6 KiB
Other:          19,   97.0 MiB
Photos:          0,    0.0 B  
Videos:          0,    0.0 B  
Total:          20,   97.0 MiB
```

but

```
$ acd_cli  ls /
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1361, in main
    incl_trash=args.action not in no_autores_trash_actions)
  File "/usr/local/bin/acd_cli.py", line 935, in resolve_remote_path_args
    v = cache.resolve_path(val, trash=incl_trash)
AttributeError: 'NodeCache' object has no attribute 'resolve_path'
```

this is on an ubuntu 16.04 box with it installed via pip3

```
pip3 install --upgrade --pre acdcli
```

**Comment by yadayada** [comment]
Mea culpa. I forgot to put in a method to resolve paths and you're the first one to notice.

**Comment by sjpotter** [comment]
I'm confused.  based on your comment then labels?

**Comment by yadayada** [comment]
Since you installed the PyPI package dating back to October, it's unlikely you've spotted an error there, especially a missing function. I think you somehow got files mixed from different versions.
