### ISSUE TITLE
Getting changesRequestError: 401, [acd_api] no body received.

### ISSUE THREAD

**Issue by rafaelferreirapt** [yadayada/acd_cli#328]
```
root@ubuntu:/home/gipmon# acd_cli -v sync
16-05-22 13:30:59.624 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-05-22 13:30:59.624 [INFO] [acd_cli] - TestPlugin attached.
16-05-22 13:30:59.624 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-05-22 13:30:59.624 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-05-22 13:31:00.107 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Getting changes16-05-22 13:31:00.108 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "***".
16-05-22 13:31:00.108 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
16-05-22 13:31:00.111 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): cdws.us-east-1.amazonaws.com
RequestError: 401, [acd_api] no body received.
16-05-22 13:31:00.720 [CRITICAL] [acd_cli] - Sync failed.
```

**Comment by lloydie11** [comment]
I'm also getting this since last night.

reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Server header: Date header: Content-Type header: Content-Length header: Connection header: x-amzn-RequestId header: Content-Encoding header: x-amzn-ErrorType header: Cache-Control header: Pragma header: Vary 16-05-22 14:44:55.059 [DEBUG] [requests.packages.urllib3.connectionpool] - "POST /drive/v1/changes HTTP/1.1" 401 75
RequestError: 401, [acd_api] no body received.
16-05-22 14:44:55.060 [CRITICAL] [acd_cli] - Sync failed.

I rolled back my box toca few weeks prior, it connected for a few moments and the sane happened again.

Sounds like an ACD thing..

**Comment by SchnorcherSepp** [comment]
amazon has problems: https://github.com/yadayada/acd_cli/issues/326

**Comment by epemetheus** [comment]
Also getting the same issues.  I even wiped the entire server and set it all up with latest updates.

Still same problem everyone has -

acdcli.api.common.RequestError: RequestError: 401, {"message":"Token has expired"}
plex@Evang:/home/plex$ acd_cli sync
Getting changesRequestError: 401, [acd_api] no body received.
16-05-21 20:37:43.938 [CRITICAL] [acd_cli] - Sync failed.

**Comment by zenjabba** [comment]
It's happening with ALL applications that use ACD API (but not it seems cloud.amazon.com). I guess we just hope and pray somebody at amazon has figured it out.

**Comment by icenine9** [comment]
I'm pretty sure this is amazon cutting everyone off.  I hope I'm wrong, but acdcli did enable a lot of people to put large multimedia libraries on their servers. I'm pretty sure amazon never intended for their service to be used for that purpose.

**Comment by zenjabba** [comment]
I don’t think so, we are but a blip on the S3 bucket storage area they have available. Amazon Cloud Drive brought me to using AWS EC2 and S3 and we now spend about $40k a month in services with them.

**Comment by icenine9** [comment]
I hope you're right - I just get this darned nagging feeling...

**Comment by tmanka** [comment]
@zenjabba I hope you are right too...the amazon api for acd is saying everything is 100%: https://developer.amazon.com/public/apis/experience/cloud-drive/content/status

There is a new thread o there about this problem:
https://forums.developer.amazon.com/questions/27740/401-messagetoken-has-expired.html

I would assume it would be good for people to like or comment that this is a problem for them too?
