### ISSUE TITLE
401 Token Issue

### ISSUE THREAD

**Issue by lloydie11** [yadayada/acd_cli#330]
Sorry to post this as a duplicate however aw the others are closed, I wanted to get some feedback.

The token issue is still happening for me using ACDCLI and was also happening with netdrive, netdrive released a new version of their software which did in fact worm without any drops or token issues (dev build released today). I'm not sure what they did bit if NetDrive have managed to work around it, I'd assume there must be some way of acdcli doing the same?

#326 & #328

Thank

**Comment by nonissue** [comment]
This is reassuring:

https://forums.developer.amazon.com/answers/27995/view.html
