### ISSUE TITLE
DatabaseError: file is encrypted or is not a database

### ISSUE THREAD

**Issue by tracebell2000** [yadayada/acd_cli#333]
When trying to mount my ACD with acd_cli mount, I get the following error. 
`Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1532, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/db.py", line 70, in __init__
    self.integrity_check(check)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/db.py", line 135, in integrity_check
    r = c.execute('PRAGMA integrity_check;')
sqlite3.DatabaseError: file is encrypted or is not a database
`

I have used pip to remove and reinstall acd_cli, as well as removing and reinstalling python, but am still having the same error.
Any help would be greatly appreciated, thank you.

**Comment by chauffer** [comment]
Try removing your `~/.cache/acd_cli` directory.

**Comment by tracebell2000** [comment]
That solved it, I'll have to remember that as a troubleshooting step in the future. Thanks for the help!

**Comment by andrewlorien** [comment]
Or if you want to keep your log files and authentication just delete `~/.cache/acd_cli/nodes.db`
I had to run `acd_cli sync` a few times after that - i have many thousands of files, and i think the database error was because a previous sync had failed.
