### ISSUE TITLE
bad redirect url when using security profile to authorize

### ISSUE THREAD

**Issue by quantileconsulting** [yadayada/acd_cli#334]
The redirect url I got after opeing the browser tab

http://localhost/?error_description=An+unknown+scope+was+requested&error=invalid_scope

It is in no way close to what is described in the instruction.

I am using acd_cli 0.3.1, api 0.8.7 and chrome  49.0.2623.112

**Comment by yadayada** [comment]
This may be the result of an API/security profile mismatch, i.e. it can happen if ones tries to request the new "clouddrive:read_all" scope for an old security profile (created prior to June 2015) or the "clouddrive:read" scope for a new security profile.

**Comment by quantileconsulting** [comment]
I created the security file yesterday just like what the instruction says and got the wrong redirect url. 

`{
    "CLIENT_ID": "amzn1.application-oa2-client.0123456789abcdef0123456789abcdef",
    "CLIENT_SECRET": "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
}`


Then I added 

`"SCOPE": "clouddrive:write"`

and still ended up with the wrong url. 

Would you  please update the authorization section of the doc?

**Comment by Daaaam** [comment]
Wait, it may not be advisable !!!..

**Comment by yadayada** [comment]
>Then I added

>``"SCOPE": "clouddrive:write"``

>and still ended up with the wrong url.

That's a strange thing to do in the first place and it would not have fixed your problem, anyway.

I can't be bothered to create another security profile just to test this. So it would be nice if someone else could provide confirmation whether something is broken or not.

**Comment by breunigs** [comment]
Registering a security profile alone is not enough to gain access to the API. You also need to whitelist this profile. This can be done through a form somewhere in the Amazon Developer Area. @quantileconsulting have you whitelisted your profile *and* have heard back from Amazon?

I registered a security profile for the native duplicity backend and am still waiting on their answer. I can reply here once they whitelist mine.

**Comment by justincathcart** [comment]
From Amazon:

> The new Amazon Drive API and SDKs for Android and iOS are available by invitation only, starting August 2nd, 2016

> Visit this page to request an invitation:
> https://developer.amazon.com/public/apis/experience/cloud-drive
