### ISSUE TITLE
Files are corrupted after download

### ISSUE THREAD

**Issue by iliakan** [yadayada/acd_cli#336]
Hi,

I uploaded and then downloaded about 2TB of 2GB files.
Several of them are corrupted after download by acd_cli.

When I try to redownload, it says all is up to date, but several files are corrupted, wrong md5. Is there a safe way to "resync" the files?

The remote file is good, the local file is bad, but acd_cli does not redownload it.

**Comment by yadayada** [comment]
Does this occur on resumed files (see issue #57) or when downloading normally? 
Have you double-checked the MD5 checksums, e.g. using `md5sum`?

> Is there a safe way to "resync" the files?

If only a few files are affected, you can get temporary links for them using the `metadata` action and download them manually with a download manager.

**Comment by iliakan** [comment]
@yadayada yes, I used m5sum to check. 

I did not stop/resume acd_cli.

I understand that I can check/redownload things manually. And probably I can write my own clouddrive client for that. But I guessed the issue is very serious, and I like your tool that's why I reported.

**Comment by yadayada** [comment]
I would be eternally grateful if you could get a clean download of a failed file, compare the clean and failed binary files and see if you could find something out about what went wrong where.

>But I guessed the issue is very serious

It seems to be. I'm just not sure whether it is a common issue.

Soo... I guess you want completed files to be deleted if a hash mismatch occurs?

**Comment by iliakan** [comment]
@yadayada guess that's the only way? I'm not sure why the mismatch occures, it seems to be scattered across the files.

**Comment by iliakan** [comment]
P.S. I used a web-browser to download the file and compare. You want me to use acd_cli to redownload it to a different location and then compare right?

**Comment by iliakan** [comment]
I changed directory and redownloaded the file, it is correct.

**Comment by yadayada** [comment]
> I'm not sure why the mismatch occures, it seems to be scattered across the files.

How many files would that be in total and how many are affected?

>P.S. I used a web-browser to download the file and compare. You want me to use acd_cli to redownload it to a different location and then compare right?

No, it doesn't really matter where the clean file came from. I just really would like to know what kind of error occured and at what byte range(s) in the file(s) it was.

Alternatively, if you somehow could give me access to the clean and erroneous file, that woul also be great. But as the files are quite large, that doesn't seem feasible...

**Comment by iliakan** [comment]
@yadayada yep, I tried binary diff, but the files are 2GB. I compared them line-by-line, lots of mismatches. 

md5 mismatch in 37 files of 1253

**Comment by iliakan** [comment]
P.S. I can try to redownload all stuff again, with some kind of advanced debugging logging enabled.

**Comment by iliakan** [comment]
So that if I see md5 error again, we can check the logs and see what happened during the download of that file.

**Comment by yadayada** [comment]
>yep, I tried binary diff, but the files are 2GB. I compared them line-by-line, lots of mismatches.

Is there any more info you can give me on that? E.g. are there any observable patterns, what's the starting offset, is a chunk of bytes missing/a chunk of bytes included that's not in the original file, do the errors just go on until the end of the file or do they have boundaries?

>P.S. I can try to redownload all stuff again, with some kind of advanced debugging logging enabled.

> So that if I see md5 error again, we can check the logs and see what happened during the download of that file.
 
I doubt there is much to see. But if you have the debug mode enabled while you are downloading, you can at least check if errors start at a chunk offset. [Files are downloaded in 500MiB chunks.]

You'll see the byte ranges printed like below.
``
16-06-04 08:58:53.048 [DEBUG] [acdcli.api.content] - Range 1048576000-1572863999
``

PS: Please don't create so many separate comments in such a short timespan.

**Comment by iliakan** [comment]
I examined the files. The corruption starts at some place and then continues all the way through the file. 

It's not like a byte or two.

The starting offset is around 1488519168 (in 2GB file)

**Comment by iliakan** [comment]
I tried to redownload all again, with maximal debug. So I have logs now, they say that md5 matches, but files are corrupted again.

How can I open acd_cli database to see the actual md5sums?

**Comment by iliakan** [comment]
Here's what I've found:
```

16-06-05 03:59:01.821 [ERROR] [acd_cli] - Downloading "2011-2012-APPLE.part4.rar" failed. RequestError: 1003, [acd_api] download incomplete.
16-06-05 03:59:01.838 [INFO] [acd_cli] - Downloading "2011-2012-APPLE.part4.rar".
...

16-06-05 04:00:42.557 [ERROR] [acd_cli] - Hash mismatch between local and remote file for "2011-2012-APPLE.part4.rar".
16-06-05 04:00:42.573 [DEBUG] [acd_cli] - Local and remote sizes match for "./old/foto/2011-2012-APPLE/2011-2012-APPLE.part4.rar".
```

So acd_cli detects the mismatch! But somehow it leaves the corrputed file on the drive and considers it valid.

**Comment by iliakan** [comment]
I'll retry with the new version, thanks.

**Comment by iliakan** [comment]
I put a new overnight download. There's a bunch of failures, and somewhy the change didn't help.

Here's the log (I grepped only the lines containing filename):
```
acdcli -dd download -r 4 -x 1 /archive/aes/MobileSync-20160117.tgz.aes/MobileSync-20160117.tgz.aes.part07.rar16-06-13 04:07:11.801 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-06-13 04:07:12.109 [INFO] [acd_cli] - Resolved "/archive/aes/MobileSync-20160117.tgz.aes/MobileSync-20160117.tgz.aes.part07.rar" to "Node('pHfaLrEBMMazG_ROmu7OhQ', 'MobileSync-20160117.tgz.aes.part07.rar')"
16-06-13 04:07:12.109 [DEBUG] [acd_cli] - Namespace(acd_client=<acdcli.api.client.ACDClient object at 0x7fa88e872208>, action='download', cache=<acdcli.cache.db.NodeCache object at 0x7fa88eae5550>, check=0, color=2, debug=2, exclude_fe=[], exclude_re=[], func=<function download_action at 0x7fa88eacd1e0>, log=True, max_connections=1, max_retries=4, no_wait=False, node='pHfaLrEBMMazG_ROmu7OhQ', node_path='/archive/aes/MobileSync-20160117.tgz.aes/MobileSync-20160117.tgz.aes.part07.rar', path=None, print_progress=True, remove_source_files=False, times=False, utf=False, verbose=None)
16-06-13 04:07:12.110 [INFO] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar".
16-06-13 04:14:29.232 [ERROR] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar" failed. RequestError: 1003, [acd_api] download incomplete.
16-06-13 04:14:29.233 [INFO] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar".
16-06-13 04:20:01.485 [ERROR] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar" failed. RequestError: 1003, [acd_api] download incomplete.
16-06-13 04:20:01.767 [INFO] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar".
16-06-13 04:22:30.343 [ERROR] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar" failed. RequestError: 1003, [acd_api] download incomplete.
16-06-13 04:22:30.344 [INFO] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar".
16-06-13 04:24:25.267 [ERROR] [acd_cli] - Hash mismatch between local and remote file for "MobileSync-20160117.tgz.aes.part07.rar".
16-06-13 04:24:26.743 [DEBUG] [acd_cli] - Deleted "MobileSync-20160117.tgz.aes.part07.rar".
16-06-13 04:24:26.755 [INFO] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar".
16-06-13 04:34:11.905 [ERROR] [acd_cli] - Downloading "MobileSync-20160117.tgz.aes.part07.rar" failed. RequestError: 1003, [acd_api] download incomplete.
Error code 8
```

At morning, I run the same command at my home Mac and the server, it downloaded the file flawlessly.

**Comment by yadayada** [comment]
Well, it deletes the mismatching file and redownloads, at least. But it seems to run into the same issue again.
It would be great if you could further investigate the incomplete download (turn off retries and have a look whether the requested byte ranges are correct).

**Comment by yadayada** [comment]
Would you please retry with the latest commit?
