### ISSUE TITLE
Partial synchronization

### ISSUE THREAD

**Issue by Intensity** [yadayada/acd_cli#338]
It seems that I need to do an `acd_cli sync` command before doing anything (even an `ls`). That would be fine in itself but I have a lot of data already in Amazon Cloud Drive. And yet there are only five top level folders. When I began the sync command it's started to download a gigabyte and is still going - I'm preferring to `Library/Caches/acd_cli/nodes.db` in particular. I don't see a progress indicator, and I don't know how well the sync process resumes upon TCP/IP interruption.

But the main issue is: is such an expensive operation a strict requirement to be able to perform top-level commands? I would understand if my top level root directory had many files. However, I have this arranged so that there are only a few at the top level, and I intend to restrict my attention to only one or two of those folders - leaving the rest alone. I'd prefer to only download metadata pertaining to those other directories on demand - and to keep the initial barrier to entry to a sync minimal with verbose indication of progress.

**Comment by yadayada** [comment]
>I don't see a progress indicator, 

There is no way to know in advance how many changes there are to be fetched, nor is there a way to guesstimate. [BTW, I disagree semantically with your definition of "progress indicator".]

>but I have a lot of data already in Amazon Cloud Drive.

How many nodes? A few 100K?

>and I don't know how well the sync process resumes upon TCP/IP interruption.

It should do fine™. There are intermediate checkpoint IDs which are used to resume syncing. If there is a connection loss, just wait until it's done inserting the nodes into the database, then run the sync again until it's able to successfully complete the download of all (incremental) changes once.

> is such an expensive operation a strict requirement to be able to perform top-level commands?

No, but it's the easiest and fastest way to cache the whole node hierarchy and that's what it's supposed to do. 

> I would understand if my top level root directory had many files.

Well, the synchronization process is not recursive (folder/children-based) or partial.

>I'd prefer to only download metadata pertaining to those other directories on demand

If you would want to selectively synchronize a few folders, the alternative is to fetch the contents of directories in pages of 200 nodes, which would be even slower in your case, I suppose. If someone else needs this kind of partial synchronization, please upvote @Intensity's comment.

>with verbose indication of progress.

That's simply not possible.

**Comment by losvald** [comment]
I'm also voting up for partial metadata sync. This particularly makes sense with the Amazon's unlimited photos / storage options, as most of user's data will be kept cold, i.e. archived and (almost) never looked again. Please consider adding an option to only sync the metadata of the toplevel (`--shalow`) or specified directory (`--shallow=DIR`). For us who (intend to) store millions of files, this would make this promising tool actually usable.

**Comment by jrwr** [comment]
I could see this working well with the FUSE subsystem as well, that what only a subdir is only pulled and not the entire node set
