### ISSUE TITLE
Invalid Range

### ISSUE THREAD

**Issue by fantom-x** [yadayada/acd_cli#342]

**Comment by fantom-x** [comment]
I am trying to download a file from a FUSE mount, but the download always fails: the file I get is always smaller. Unfortunately, Multiple files are affected. I enabled debug logging and according to the logs, there is always a request for a range beyond the end of the file and ACD replies with `RequestError: 416, {"message":"Invalid Range"}`
The file size is 215,696. Here is a last good request:
```
16-06-11 20:07:05.987 [DEBUG] [acdcli.acd_fuse] - <- read ''
16-06-11 20:07:06.007 [DEBUG] [acdcli.acd_fuse] - -> read /Documents/easychair.docx (86016, 131072, 3)
16-06-11 20:07:06.117 [DEBUG] [acdcli.acd_fuse] - s: 131072-215695; r: 131072-217087
16-06-11 20:07:06.122 [DEBUG] [acdcli.api.content] - chunk o 131072 l 524288000
```
And `Range: bytes=131072-524419071` for this request above
The next ask is beyond the file size:
```
16-06-11 20:07:07.536 [DEBUG] [acdcli.acd_fuse] - <- read ''
16-06-11 20:07:07.567 [DEBUG] [acdcli.acd_fuse] - -> getattr /Documents/easychair.docx (None,)
16-06-11 20:07:07.684 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_ctime': 1461414156.14, 'st_nlink': 1, 'st_mtime': 1461414182.7, 'st_mode': 33206, 'st_size': 215696, 'st_atime': 1465675627.6576135}
16-06-11 20:07:07.694 [DEBUG] [acdcli.acd_fuse] - -> read /Documents/easychair.docx (4096, 274432, 3)
16-06-11 20:07:07.817 [DEBUG] [acdcli.acd_fuse] - s: 215696-215695; r: 274432-278527
16-06-11 20:07:07.822 [DEBUG] [acdcli.acd_fuse] - s: 131072-215695; r: 274432-278527
16-06-11 20:07:07.827 [DEBUG] [acdcli.api.content] - chunk o 274432 l 524288000
```
As a result `Range: bytes=274432-524562431` is now beyond the end of the file.

**Comment by fantom-x** [comment]
Did a bit more debugging and also tried single threaded mode with no avail. According to the code acd_fuse seems to be using a cache of chunks, but the logs do not confirm that. 

First request (file size is 215,696):
```
16-06-11 21:26:58.244 [DEBUG] [acdcli.acd_fuse] - -> open /Documents/easychair.docx ('0x20000',)
16-06-11 21:26:58.249 [DEBUG] [acdcli.acd_fuse] - <- open 3
16-06-11 21:26:58.260 [DEBUG] [acdcli.acd_fuse] - -> read /Documents/easychair.docx (131072, 0, 3)
16-06-11 21:26:58.362 [DEBUG] [acdcli.api.content] - chunk o 0 l 524288000
Range: bytes=0-52428799
GET 206 215696
```

Second request:
```
16-06-11 21:26:59.299 [DEBUG] [acdcli.acd_fuse] - <- read ''
16-06-11 21:26:59.319 [DEBUG] [acdcli.acd_fuse] - -> read /Documents/easychair.docx (86016, 131072, 3)
16-06-11 21:26:59.428 [DEBUG] [acdcli.acd_fuse] - s: 131072-215695; r: 131072-217087
16-06-11 21:26:59.433 [DEBUG] [acdcli.api.content] - chunk o 131072 l 524288000
Range: bytes=131072-524419071
GET 206 84624
```
Third and subsequent requests are beyond the end of file:
```
16-06-11 21:27:00.505 [DEBUG] [acdcli.acd_fuse] - <- read ''
16-06-11 21:27:00.533 [DEBUG] [acdcli.acd_fuse] - -> getattr /Documents/easychair.docx (None,)
16-06-11 21:27:00.649 [DEBUG] [acdcli.acd_fuse] - <- getattr {'st_size': 215696, 'st_ctime': 1461414156.14, 'st_atime': 1465680420.623794, 'st_mode': 33206, 'st_nlink': 1, 'st_mtime': 1461414182.7}
16-06-11 21:27:00.659 [DEBUG] [acdcli.acd_fuse] - -> read /Documents/easychair.docx (4096, 274432, 3)
16-06-11 21:27:00.778 [DEBUG] [acdcli.acd_fuse] - s: 215696-215695; r: 274432-278527
16-06-11 21:27:00.783 [DEBUG] [acdcli.acd_fuse] - s: 131072-215695; r: 274432-278527
16-06-11 21:27:00.788 [DEBUG] [acdcli.api.content] - chunk o 274432 l 524288000
Range: bytes=274432-524562431
get: RequestError: 416, {"message":"Invalid Range"}
```
Is there anything else I could/should try?

**Comment by yadayada** [comment]
Sorry, my fault. The read implementation was slightly off. I've fixed that in the newest commit.

I presumed that applications would always read the last chunk, get fewer bytes than expected and then try to read only at the offset that's the file's length rather than beyond that.
Which operating are you using, btw?

>```
16-06-11 20:07:06.007 [DEBUG] [acdcli.acd_fuse] - -> read /Documents/easychair.docx (86016, 131072, 3)
16-06-11 20:07:06.117 [DEBUG] [acdcli.acd_fuse] - s: 131072-215695; r: 131072-217087
16-06-11 20:07:06.122 [DEBUG] [acdcli.api.content] - chunk o 131072 l 524288000
```

The chunk that has the correct offset should be read until its end, ideally. I'll also have to check that.

**Comment by fantom-x** [comment]
Thx for looking into this. I get this behaviour with this set-up below. I can never download any file and would get a permission error at the end. A "cp/mv" work fine off of the same mount.

&nbsp;&nbsp;Nautilus via "Connect to Server" in the menu (Ubuntu 16.04); I think this is using GVFS under the hood
&nbsp;&nbsp;&nbsp;&nbsp;Samba
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ACD mount

**Comment by fantom-x** [comment]
I have manually applied your first commit and it fixed the downloads for me. Thx for fixing it promptly. Looking forward to you releasing the other fixes so that I can get them all with pip3.

**Comment by fantom-x** [comment]
I noticed that the first get is out with `Range: bytes=0-52428799` that is way more than the file size was, but then there was a second get for `Range: bytes=131072-524419071`. Is that an expected behaviour? The entire file was already downloaded the first time.

**Comment by yadayada** [comment]
Please see the setup section in the documentation on how to install from the repository.

>I noticed that the first get is out with Range: bytes=0-52428799

The default chunk size is 500MiB, even for smaller files.

>16-06-11 21:26:58.362 [DEBUG] [acdcli.api.content] - chunk o 0 l 524288000
Range: bytes=0-52428799
GET 206 215696

The chunk object will recognize that the response is only 215696 bytes long.

>but then there was a second get for Range: bytes=131072-524419071.

That second request should no longer be issued with the latest commit.

**Comment by fantom-x** [comment]
That confuses me: `chunk o 0 l 524288000` is 500M but the "get" request has `Range: bytes=0-52428799` which is 50M. Unless the chunk object consists internally of ten 50M chunks...

**Comment by yadayada** [comment]
>That confuses me: chunk o 0 l 524288000 is 500M but the "get" request has Range: bytes=0-52428799 which is 50M. Unless the chunk object consists internally of ten 50M chunks...

I assume it's really 524287999 because that's what shows up in my logs.

**Comment by fantom-x** [comment]
My bad: somehow I did not see the last digit in the `Range` specification. 

I have updated to the latest and the greatest and there are no redundant reads any more. This latest version is also much faster and is using much less CPU than the one I was using prior.

Thx again for the quick fix.
