### ISSUE TITLE
ACD_FUSE Chunk size configuration

### ISSUE THREAD

**Issue by fantom-x** [yadayada/acd_cli#343]
This is a feature request: can you pls add the ability to configure the chunk size? It is currently set at 500M and quite suitable for sequential file access. It would help some of us if we could configure it to much smaller values in the range to several megabytes or less so that we could try and optimize the set-up to handle random access to different parts of the file.

**Comment by yadayada** [comment]
You may already configure it by setting the download chunk size in `acd_client.ini`, as that's also used by the FUSE module.

But there will be no difference in random access time if you lower the chunk size below the current value of 500M. If there is no (possibly partially read) request that begins at the specified read `offset` and has at least `length` bytes remaining, a new HTTP request will be issued. It's not lengthily "fast-forwarding" through a chunk if it so happens to satisfy the neccessary byte range.

**Comment by fantom-x** [comment]
Thx; that takes care of it then.
