### ISSUE TITLE
acd_fuse does not start if there is no Internet connection

### ISSUE THREAD

**Issue by fantom-x** [yadayada/acd_cli#344]
On a few occasions now the mount would not start because the internet connection would not fully come up until a few moments later. Any chance you could add support for this? The mount could come up and be empty and read-only and every on fuse refresh interval it could check if the connection is up or not.

**Comment by chauffer** [comment]
I'd suggest properly fixing the issue; such as mounting only after being sure internet is accessible.

**Comment by fantom-x** [comment]
@chauffer, that is not a fix: that is a workaround. The use case here is a laptop with a wireless connection. The fuse capability in acd_cli is truly unique and has an enormous potential if it did not rely on having an Internet connection up all the time. The connection  might not be up when a mount is created or when it is unmounted or it can go up and down while it is already mounted. The laptop itself can go to sleep or hibernate. Actually, even stationary computers could have connectivity issues.
A fuse mount is refreshed every 60s by default and I am hoping that could be used to refresh the connections so that the mount is always up whether or not the Internet connection is up. It is ok for any transfers in flight to fail if there is no connectivity and all the new ones be blocked, but it would be great if the mount would stay up and heal itself soon after the connectivity is back up.

**Comment by fantom-x** [comment]
Thanks for the fix, but something is off: when a connection is down `acd_cli` starts, but `df -h` does not display the mount, even though according to the output of `mount` it is mounted. An attempt to use it results in `Communication error on send`, which is expected.

Once the connectivity is restored I am able to copy files to and from it, but `df -h` output remains wrong :

df -h /amazon_cloud_drive/
Filesystem      Size  Used Avail Use% Mounted on
ACDFuse            0     0     0    - /amazon_cloud_drive

In addition to that `df -h` is still missing the acd mount (maybe because it is zero size?). 

I can run more tests is needed and provide more info; let me know.
