### ISSUE TITLE
proxy only for refresh authentication token

### ISSUE THREAD

**Issue by Cologler** [yadayada/acd_cli#346]
In Chinese, `appspot.com` was blocked, but amazon cloud drive was not blocked.
Is there possible to use proxy only for refresh authentication token?

**Comment by yadayada** [comment]
The authentication does ignore the proxy config, so it might work if you set the `HTTPS_PROXY` environment variable whilst unsetting the https proxy in `acd_client.ini`
```
 [proxies]
https=
```

If it does not work, register your own security profile.
