### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'reset'

### ISSUE THREAD

**Issue by paede81** [yadayada/acd_cli#347]
First sync fails.  After I download and copy the oauth_data to the right right directory I try to execute:

```
acd_cli sync
Getting changes..
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1554, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 680, in sync_action
    return sync_node_list(full=args.full)
  File "/usr/local/bin/acd_cli.py", line 129, in sync_node_list
    if changeset.reset or (full and first):
AttributeError: 'bytes' object has no attribute 'reset'
```

**Comment by yadayada** [comment]
Your acd_cli.py and the client API do not match. Reinstall.

**Comment by paede81** [comment]
I tried it but no success. What I did:
- acd_cli delete-everything
- pip3 uninstall acdcli
- pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git
- installed oauth_data file

Successfully uninstalled acdcli-0.3.1
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git
Collecting git+https://github.com/yadayada/acd_cli.git
  Cloning https://github.com/yadayada/acd_cli.git to /tmp/pip-t07o7sjt-build
Collecting appdirs (from acdcli===0.3.1)
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting colorama (from acdcli===0.3.1)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting fusepy (from acdcli===0.3.1)
Collecting python_dateutil (from acdcli===0.3.1)
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting requests!=2.9.0,>=2.1.0 (from acdcli===0.3.1)
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting requests_toolbelt!=0.5.0 (from acdcli===0.3.1)
  Using cached requests_toolbelt-0.6.2-py2.py3-none-any.whl
Collecting six>=1.5 (from python_dateutil->acdcli===0.3.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: appdirs, colorama, fusepy, six, python-dateutil, requests, requests-toolbelt, acdcli
  Running setup.py install for acdcli ... done
Successfully installed acdcli-0.3.1 appdirs-1.4.0 colorama-0.3.7 fusepy-2.0.4 python-dateutil-2.5.3 requests-2.10.0 requests-toolbelt-0.6.2 six-1.10.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

But I still got the same:
acd_cli sync
Getting changes..
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.1', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1554, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 680, in sync_action
    return sync_node_list(full=args.full)
  File "/usr/local/bin/acd_cli.py", line 129, in sync_node_list
    if changeset.reset or (full and first):
AttributeError: 'bytes' object has no attribute 'reset'

**Comment by yadayada** [comment]
You need to check manually that everything was uninstalled. You can also use a virtualenv otherwise.
