### ISSUE TITLE
FUSE Crash on outside sync

### ISSUE THREAD

**Issue by jrwr** [yadayada/acd_cli#356]
So, I keep getting Fuse mount crashes (Bad Address when accessing the mount) after syncing the database out of band (interval is off and there is a Unhanded Exception in the logs -- Log: http://hastebin.com/mecivugado.coffee

More details: Looks like it might be a ACD issue, this was always happening right after a rclone upload, I added a 120s sleep right after dowing a upload and it has seemed to stop this crash

Mount Command: acd_cli mount --read-only --allow-other --umask 000 /mnt/acd/

Version: acd_cli 0.3.1, api 0.9.0 
fusermount version: 2.9.4
Ubuntu 16.04
Python 3.5.1+ 
Linux 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by a5m0** [comment]
I often got a acd_cli fuse crash in this same situation, I will try with a pause between rclone upload and acd_cli sync.

**Comment by teddy6565** [comment]
Hi I also get a crash after rclone upload and then a sync. I tried delaying for a few minutes but this still happens regularly. Any solutions?

**Comment by a5m0** [comment]
I only have a workaround, wrote a python script to monitor if the FUSE mount is accessible and if not does an unmount and remount.

**Comment by sbcrumb** [comment]
@a5m0 care to share your script?

**Comment by a5m0** [comment]
@sbcrumb here you go https://gist.github.com/a5m0/5090c42f16c39c8a34876bfcc7b3703d

**Comment by KaMoS69** [comment]
I got the error after `acd_cli sync` this morning. This is the log:

> 16-07-26 09:36:05.954 [DEBUG] [acdcli.acd_fuse] - -> getattr /Encrypted/ (None,)
16-07-26 09:36:05.954 [DEBUG] [acdcli.acd_fuse] - <- getattr '[Unhandled Exception]'
16-07-26 09:36:06.081 [DEBUG] [acdcli.acd_fuse] - -> getattr /Encrypted/ (None,)
16-07-26 09:36:06.081 [DEBUG] [acdcli.acd_fuse] - <- getattr '[Unhandled Exception]'
16-07-26 09:36:06.082 [DEBUG] [acdcli.acd_fuse] - -> statfs /Encrypted/ ()
16-07-26 09:36:06.082 [DEBUG] [acdcli.acd_fuse] - <- statfs {'f_frsize': 524288, 'f_namemax': 256, 'f_bavail': 209373534, 'f_blocks': 209715200, 'f_bfree': 209373534, 'f_bsize': 524288}
16-07-26 09:36:06.083 [DEBUG] [acdcli.acd_fuse] - -> statfs /Encrypted/ ()
16-07-26 09:36:06.083 [DEBUG] [acdcli.acd_fuse] - <- statfs {'f_frsize': 524288, 'f_namemax': 256, 'f_bavail': 209373534, 'f_blocks': 209715200, 'f_bfree': 209373534, 'f_bsize': 524288}
16-07-26 09:36:06.083 [DEBUG] [acdcli.acd_fuse] - -> statfs /Encrypted/ ()
16-07-26 09:36:06.083 [DEBUG] [acdcli.acd_fuse] - <- statfs {'f_frsize': 524288, 'f_namemax': 256, 'f_bavail': 209373534, 'f_blocks': 209715200, 'f_bfree': 209373534, 'f_bsize': 524288}
16-07-26 09:36:06.084 [DEBUG] [acdcli.acd_fuse] - -> getattr /Encrypted/ (None,)
16-07-26 09:36:06.084 [DEBUG] [acdcli.acd_fuse] - <- getattr '[Unhandled Exception]'

I appreciate the workaround a5m0 but is there a fix for this?

**Comment by teddy6565** [comment]
I had the issue but now I am mountain with the interval update command i 60 - I no longer have issues with any rcloud or sync issues.

**Comment by KaMoS69** [comment]
Thanks @teddy6565. Please would you share more details about your solution.

**Comment by teddy6565** [comment]
Mounting the drive with an interval sync command means rather than me having to run sync it checks every x seconds. Just add i 60 ( 60 being seconds ) to the mount command. In Linux this seems to require an open session so best running from 'screen'

Let know if this still doesn't make sense

**Comment by yadayada** [comment]
If that happens, you need to unmount, sync and re-mount.
