### ISSUE TITLE
Documentation: Packages with FPM

### ISSUE THREAD

**Issue by jbuchbinder** [yadayada/acd_cli#36]
This is just a placeholder for generating easy packages with [FPM](https://github.com/jordansissel/fpm). All instructions were successfully executed under Ubuntu 15.04:

## Debian/Ubuntu packages (.deb)

```
fpm -s python -t deb --python-pip /usr/bin/pip3 --python-bin /usr/bin/python3 ./setup.py
```

## Redhat/CentOS packages (.rpm)

```
fpm -s python -t rpm --python-pip /usr/bin/pip3 --python-bin /usr/bin/python3 ./setup.py
```

**Comment by yadayada** [comment]
Looks nice.

**Comment by yadayada** [comment]
Unfortunately, fpm suffers from problems that arise when a certain dependency is not available as a package for the current distro, e.g. requests-toolbelt for Debian.

**Comment by jbuchbinder** [comment]
It's always possible to use its simple python packaging to create the deb/rpm packages in question. That's not a panacea, but should allow using fpm for packaging. :)

**Comment by yadayada** [comment]
Ok, in the next commit I'll put a Makefile in the assets directory.
```Makefile
deb: 
	fpm -s python -t deb requests-toolbelt
	fpm -s python -t deb --python-pip /usr/bin/pip3 --python-bin /usr/bin/python3 ../setup.py

rpm:
	fpm -s python -t rpm requests-toolbelt
	fpm -s python -t rpm --python-pip /usr/bin/pip3 --python-bin /usr/bin/python3 ../setup.py
```
