### ISSUE TITLE
Slow directory creation when you have a large database - add an index to fix.

### ISSUE THREAD

**Issue by gerph** [yadayada/acd_cli#363]
Hiya,

I have what appears to be a large database for the files on ACD. This means that trying to upload a new area to the server with the `acdcli upload` takes an incredibly long time. The first stage is creating all the directories. This appears to be single threaded, for a start, so everything blocks on the directories having been created. That's frustrating but not a huge problem.

However, the directory creation seems to spend ~12 seconds between creating each directory. This is more frustrating. Using strace on a running python process indicated that it was continually reading, and reading a lot. Using gdb to look at the stack trace indicated that it was commonly sitting in the `FIND_FIRST_PARENT_SQL` query.

```
Traceback (most recent call first):
  File "/usr/local/lib/python3.4/dist-packages/acdcli/cache/query.py", line 272, in first_path
    c.execute(FIND_FIRST_PARENT_SQL, (node_id,))
  File "/usr/local/bin/acd_cli.py", line 424, in traverse_ul_dir
    logger.info('Created folder "%s"' % (cache.first_path(parent.id) + short_nm))
  File "/usr/local/bin/acd_cli.py", line 391, in create_upload_jobs
    rsf, exclude, exclude_paths, jobs)
...
```

Using the sqlite3 tool to look at this query showed that it required a full scan of every node, which it shouldn't need for the query. The reason is that the `parentage` table's compound index of `parent, child` is used to look up the values, and the database has decided that in doing so, the nodes table should be scanned for the matching nodes.

The `EXPLAIN QUERY PLAN` may make this clearer:

``` sql
sqlite> EXPLAIN QUERY PLAN SELECT n.* FROM nodes n JOIN parentage p ON n.id = p.parent WHERE p.child = (?) ORDER BY n.status, n.id;
0|0|0|SCAN TABLE nodes AS n
0|1|1|SEARCH TABLE parentage AS p USING COVERING INDEX sqlite_autoindex_parentage_1 (parent=? AND child=?)
0|0|0|USE TEMP B-TREE FOR ORDER BY
```

The `SCAN TABLE` is a massive red flag.

Creating a new, dedicated, index for the child, can be done easily:

``` sql
sqlite> CREATE INDEX ix_parentage_child ON parentage(child);
```

And then another `EXPLAIN QUERY PLAN` shows that this has improved to be only searches using indexes, rather than a full scans:

``` sql
sqlite> EXPLAIN QUERY PLAN SELECT n.* FROM nodes n JOIN parentage p ON n.id = p.parent WHERE p.child = (?) ORDER BY n.status, n.id;
0|0|1|SEARCH TABLE parentage AS p USING INDEX ix_parentage_child (child=?)
0|1|0|SEARCH TABLE nodes AS n USING INDEX sqlite_autoindex_nodes_1 (id=?)
0|0|0|USE TEMP B-TREE FOR ORDER BY
```

Having done this, the preparation of the files to upload and directory creation is massively faster for me.

**Comment by jrwr** [comment]
Good 'ol Sqlite indexes Great find

**Comment by zenjabba** [comment]
for us sqlite numpties, how do we do this via the command line. I need every trick to get performance increases from acd_cli.

One thing I would like to see if having the sqlite completely in memory, as I think that will speed up a lot of things as well.

**Comment by gerph** [comment]
If you want to do this from the command line...

```
sqlite3 nodes.db 'CREATE INDEX ix_parentage_child ON parentage(child);'
```

is all you need - `nodes.db` is the filename of the nodes database for acd_cli, and `sqlite3` is the command line sqlite3 tool.

OR update to pep1's acd_cli repository which seems to have been updated with this change.

**Comment by vb0** [comment]
Adding the index increased my speed for just going through the files more than 50x!

Just one caveat (to be expected I guess) I had to run also ANALYZE; - without there was no change!

That is doing rsync backups from local -> "local" (encfs -> acd-cli fuse mounted), despite doing size-only and no timestamps for folders still it would take some perceptible time to do each "getattr {'st_ctime'.." in the destination. Under one second but still adding up, it would take many minutes just to get a listing of pictures I've done this year... Also one core would go to 100%. Now it's much, much faster (50-100x).

**Comment by gerph** [comment]
PR raised to add the index the parentage table.

**Comment by vb0** [comment]
Because of recent events (to put it like this) I nuked my nodes.db (actually the whole .cache/acd_cli) and started from scratch. It seems that the index still isn't implemented (I can't read github very well but I assume so from "All checks have failed" on the pull request).

For me the index it's making a huge difference, without it even "sync" was hogging a CPU core completely (and I think by how the system was behaving killing the I/O on the SSD where nodes.db is located too, but did not check that at the time). After adding the index it's just spiking at 15% of one core from now and then.
