### ISSUE TITLE
acd_cli init and amazon captcha?

### ISSUE THREAD

**Issue by scriptzteam** [yadayada/acd_cli#366]
when i did acd_cli init on a fresh new server, amazon want from me captcha to fill which i can not see in terminal :D whats now?

**Comment by msh100** [comment]
You can authenticate on a machine with a gui and use that oauth file.

**Comment by scriptzteam** [comment]
how to do that?

**Comment by msh100** [comment]
Just go to the url which you're directed to from the terminal in your desktop web browser

**Comment by scriptzteam** [comment]
Got it works thx :)
