### ISSUE TITLE
Amazon Unlimited Cloud Drive finally arrived in Germany

### ISSUE THREAD

**Issue by ErAzOr2k** [yadayada/acd_cli#369]
Amazon Unlimited Cloud Drive finally arrived in Germany :)
Are changes in acd_cli needed for using in germany? Or should it work "out of the box"?

**Comment by seppi91** [comment]
It's free for the first 3 months. So why not just go ahead and give it a try?

**Comment by msh100** [comment]
The endpoints are provided by the Amazon Cloud Drive API. I am fairly sure it will "just work".

**Comment by KaMoS69** [comment]
My dedi-server is hosted in Germany, so it'd be better to use .de instead of .com. Speeds to .com have been poor.

How would I have to change acd_cli so that it points to the German ACD? Would I just delete the oauth_data file and re-run acd_cli -v init? When I look at the appspot source it points to:

```
AMAZON_OA_LOGIN_URL = 'https://amazon.com/ap/oa'
AMAZON_OA_TOKEN_URL = 'https://api.amazon.com/auth/o2/token'
```

Should these URL's be changed to .de instead of .com?

**Comment by msh100** [comment]
You need a new account.

**Comment by KaMoS69** [comment]
@msh100 I assumed that. I've already created a new .de account.

**Comment by msh100** [comment]
You should just login to the new account and it should just direct you to German servers (I'd imagine, I have not tried it out). You shouldn't need to change any settings.

**Comment by seppi91** [comment]
fyi, i've already asked amazon customer service to transfer my files from US to Germany. This is their reply:

> Our marketplace data centers operate independently, hence we are unable to transfer your files from one website to another.
In this case, we request you to download and re-upload to your account on the Amazon Germany Drive website.
I understand that you have huge amount of data stored on Drive account and I apologize for the inconvenience.
Considering the situation, I've forwarded this issue to Amazon Drive development team requesting for "transfer files" option for better experience.
Your cooperation in this matter will be highly appreciated.
Also I would like to inform you that once you back up your data, we will cancel your subscription on Amazon.com and issue refund for the recent charge.

**Comment by msh100** [comment]
@seppi91 they're refunding you on a service in their terms only for Americans so you can switch to their German version? That's amazingly good support 😄

**Comment by KaMoS69** [comment]
Ok, got it working but upload speeds were the same :/ Weird, I thought it'd be MUCH faster, I guess I was wrong :-(

**Comment by ErAzOr2k** [comment]
@KaMoS69 have you changed login and tokel URL to '.de' ?

**Comment by KaMoS69** [comment]
@ErAzOr2k No. I just re-authed using my new .de account.

I was able to see the files uploaded on the .de ACD. I was getting 10MB/s on .com, got the same on .de

**Comment by crack00r** [comment]
Same here
******** .eu-west-1.compute.amazonaws.com 25.2MB
i dont get over 25/28MB/s

BUUTTT
With more simultan transfers i get over 120MB Upload / s

so is it possible to speed up the upload for 1 transfer in any way?
Maybe more connections ore someting like this

**Comment by crack00r** [comment]
Right now i already note this Problem here
https://www.filebot.net/forums/viewtopic.php?f=6&t=4028&p=22526#p22526

i use Filebot to rename and transfer the file to the cloud... my server has 1gig speed, in DL i get around 150mb/sec, but in upload to cloud not over 25-30mb/sec.

any help in this?

**Comment by crack00r** [comment]
Manual transfer over the mountet cli 8 connections at the same time i get around 120mb/s, so it seams amazon cap at 30mb/s/transfer over cli

**Comment by crack00r** [comment]
i tryd now this way

```
#!/bin/bash
FOLDER="/root/toupload"
inotifywait -m $FOLDER -e create -e moved_to |
        while read path action file; do
                echo "The file '$file' appeared in directory '$path' via '$action'"
                acd_cli ul -x 20 $FOLDER/"$file" /Daten/
                rm -rf $FOLDER/"$file"
        done
```

but it seams, still seams to upload 1 file at once... why not all what -x stands for... should it upload then 20 files at once?

**Comment by KaMoS69** [comment]
OK, so I've done some more testing over the last few days and it seems if you increase the max number of connections the upload speed increases as well. This only applies where multiple files are being uploaded. I've been averaging 50 MB/s up with -x set to 10. On single files, it slows down to as little as 4.4 MB/s or 35 mb/s.

This is pretty much the same as what I get to the .com ACD, so I'm going to stick to .com

**Comment by yadayada** [comment]
acd_cli should work with German accounts out of the box.  I tested it with my free 100GB account at the end of last year.
