### ISSUE TITLE
acd_cli stalls then fails

### ISSUE THREAD

**Issue by sixstringsg** [yadayada/acd_cli#379]
I start an upload with 
`.local/bin/acd_cli upload -x 2 -r 4 --deduplicate`
It starts to upload at a reasonable speed, then drops to 0.0B/s. It does this a few times, then eventually the transfer fails. I've gotten 
`[WARNING] [acd_cli] - Return value error code: 512.`
`[WARNING] [acd_cli] - Return value error code: 768.`
`[WARNING] [acd_cli] - Return value error code: 792.`

**Comment by yadayada** [comment]
The overall return value isn't much to go by. You should investigate the errors at the file level. 512 means there was at least one remote duplicate; but you also seem to have an outdated cache warning, a timeout error and a failed transfer.
