### ISSUE TITLE
Question: Can acd_cli make a read/write key without permission to delete?

### ISSUE THREAD

**Issue by ShapeShifter499** [yadayada/acd_cli#388]
When acd_cli requests access to my Amazon account it requests full permissions and this is fine for normal usage. However if I wanted to set up acd_cli on a personal file server I'd be worried someone might remotely break in and be able to delete everything off my Amazon cloud. So I'm wondering if it's possible to create a auth key for acd_cli that only gives access to read and write but not access to delete?  Or a better question is, does acd_cli do "permanent deletion" as mentioned in the following link?  https://www.amazon.com/gp/help/customer/display.html?nodeId=201376770

The goal is to be able to quickly recover in the event that some one gains access to the computer with acd_cli running and ruins all my files.

**Comment by yadayada** [comment]
The Cloud API does not permit permanent deletion, just trashing. However, there is a risk that your files may be overwritten or zero out with the standard write permission.

**Comment by ShapeShifter499** [comment]
@yadayada Oh I hadn't even thought of that.  Googling for this and I don't find any way to restore overwritten files. SO this is one caveat of Amazon cloud.

**Comment by ShapeShifter499** [comment]
I guess I'll just have to keep the server as secure as I can and hope a offline backup doesn't get ruined in the event it becomes my only backup left.
