### ISSUE TITLE
Cygwin compatibility?

### ISSUE THREAD

**Issue by john3voltas** [yadayada/acd_cli#389]
Hello.
Unfortunately I can't run Python natively on some of our computers (boss orders) but we are allowed to run cygwin and cygwin has a python package.
The problem is, when I try to set up acd_cli under cygwin using AppSpot, it opens Amazon's website on lynx web browser and then it fails to download the JSON file even though I input username and password correctly. It seems more like a browser issue than username/password issue because if I really mess up inputting the password it gives me the bad username or password.
So, I am using the proper username/password but lynx can't download the file. Could you please allow download using the native web browser (FF or Chrome)? Some guy down at #cygwin told me that we should use something like 'export BROWSER=cygstart' but I wouldn't really know what that is. Sounds like an environment configuration...
Would be really great to run acd_cli under cygwin. Hope you can help us out.
Thanks in advance.

**Comment by john3voltas** [comment]
Hello again.
I'm sorry but I just noticed that I can just copy the whole URL that acd_cli uses for init (https://tensile-runway-92512.appspot.com/src) to my native browser, input username, password, download the JSON file and then copy/paste it into my cygwin user account folder, which in my case is "C:\cygwin64\home\my_windows_user_account_name\.cache\acd_cli".
That's it. It's already working. Brilliant stuff. Thanks a bunch :-)

PS: I wonder if I can take this JSON file with me and copy it to another computer of mine instead of having to go through the registration again.

**Comment by msh100** [comment]
Yes, you can move that file around.

**Comment by john3voltas** [comment]
Cool. This way I can just copy the file to my 2 other PC's.
Thanks :-)
