### ISSUE TITLE
Generate / retrieve sharable links ?

### ISSUE THREAD

**Issue by wdenx** [yadayada/acd_cli#39]
One of the major drawbacks of ACD is that you cannot share a folder,
not even several files at once.  Sharing any larger number of files is
a major annoyance.

It would be nice if acd_cli would support sharing of files, like:
- print sharable links for shared files in the ACD
- make files in the ACD shared (and print the sharable links for
  these)
- make files in the ACD unshared

Would this be possible?

**Comment by yadayada** [comment]
Unfortunately with the Cloud Drive API, it is not possible to share a file or even get the permanent links of files that are already shared.

Temporary links, however, can be generated. These last for maybe 24 or 48 hours. It is already possible to get these by using the metadata action.

I'm considering adding an action to generate links for a whole folder.

**Comment by wdenx** [comment]
By "action to generate links for a whole folder" you mean temporary links, right?

So we have no chance to mimic that action of creating a permanent sharable link as on the web interface?  What a pity...

**Comment by yadayada** [comment]
Yes, I meant temporary links. I take it from your response that temporary links aren't useful to you.

If Amazon decides to lift the restriction on sharing, I would be happy to implement this. But it seems they are not intent on doing it for security reasons.
https://forums.developer.amazon.com/forums/thread.jspa?threadID=4510
