### ISSUE TITLE
HTTPException: Deadline exceeded while waiting for HTTP response from URL: https://api.amazon.com/auth/o2/token

### ISSUE THREAD

**Issue by jerblack** [yadayada/acd_cli#391]
Today I started getting the error below when I try to use acd_cli. I tried a sync and an init and they both give the same error.
```
HTTPException: Deadline exceeded while waiting for HTTP response from URL: https://api.amazon.com/auth/o2/token
```
I remove the oauth_data file in my cache and still get the same error. I am dead in the water at the moment. Any suggestions?

Also, I heard that Amazon switched over to make their Drive API invite only. I assume that affects acd_cli as well. Did you receive an invite, or is acd_cli shutting down now?

---
from https://tensile-runway-92512.appspot.com/?code=***********&scope=clouddrive%3Aread+clouddrive%3Awrite

```
Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~tensile-runway-92512/2.387559670694189735/main.py", line 88, in get
    resp = urllib.urlopen(AMAZON_OA_TOKEN_URL, urllib.urlencode(params))
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 88, in urlopen
    return opener.open(url, data)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 205, in open
    return getattr(self, name)(url, data)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 433, in open_https
    errcode, errmsg, headers = h.getreply()
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/gae_override/httplib.py", line 623, in getreply
    response = self._conn.getresponse()
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/gae_override/httplib.py", line 526, in getresponse
    raise HTTPException(str(e))
HTTPException: Deadline exceeded while waiting for HTTP response from URL: https://api.amazon.com/auth/o2/token

```

**Comment by jerblack** [comment]
I'm getting a new error now from https://tensile-runway-92512.appspot.com/
```
Error
    Over Quota
    This application is temporarily over its serving quota. Please try again later. 
```

**Comment by Synopis** [comment]
I've been getting the same error too.

**Comment by sergiopatino** [comment]
+1

**Comment by maiaftv** [comment]
+1 here.

**Comment by cashman04** [comment]
Getting the same right now.  Found an issue from September 2015 here where the same thing happened and it was due to something being down on amazon's end.  Best bet now is to just wait.

**Comment by sergiopatino** [comment]
Lets hope that's it.

**Comment by okiwoki** [comment]
Ditto, getting the same thing.

**Comment by JustinGrote** [comment]
Bump. If you try to do a re-initialization or browse to the page manually you get the same error. I'm now getting "over quota" instead of deadline exceeded so obviously something is broken on the Amazon side and they're probably fixing it?

Any chance they changed the system and https://tensile-runway-92512.appspot.com/ is not the correct address to get? That seems like a very specific server address and not something like acdthirdpartyauth.appspot.com that would go to a load balancer or something.

**Comment by dollabi11z** [comment]
Same error good god lol this is crashing my whole system

**Comment by dollabi11z** [comment]
Simply change it to an app that isnt rate limited acdcli

**Comment by epemetheus** [comment]
yea, same error https://tensile-runway-92512.appspot.com/ is overloaded.  So our tokens are expiring and losing all ties to the back-end :/

**Comment by thenoahcomputer** [comment]
Happening for me as well.  Storage went down before the authentication page did.  The authentication page after entering credentials was DDoS for awhile as everyone using acd_cli simultaneously tried to reauthenticate.  Message switched to the quota exceeded after a few minutes.

**Comment by jerblack** [comment]
The https://tensile-runway-92512.appspot.com/ is part of the acd_cli app, and is used to act as a go-between for handling oauth for ACD_CLI with Amazon. That's why it's not a familiar looking URL, or being load-balanced as was asked earlier.

Is anyone familiar with the process for creating a personal security profile on the Amazon developer portal to bypass this? I [found documentation here](http://acd-cli.readthedocs.io/en/latest/authorization.html), but it looks like that portal was updated and the documentation is no longer correct. If we could make this process work, then we could bypass the need to connect to the tensile-runway server.

**Comment by epemetheus** [comment]
Figured it out!!!

Load up this website - https://drivesink.appspot.com/

Click on "Or you can just get your access token right here."

Delete your oauth_data token and replace it with that Token Key 
{
    "access_token"
******************
}

Run acd_cli sync
than acd_cli mount /yourshitson!@#!@#

**Comment by thenoahcomputer** [comment]
epemetheus solution confirmed working for me

**Comment by JustinGrote** [comment]
Did the work around by epemetheus till this gets sorted.

**Comment by jerblack** [comment]
Back in business thanks to epemetheus! Thanks!

**Comment by nonissue** [comment]
Cool, thanks for the work around @epemetheus. it is a little worrying though, does this mean amazon plans to ban (or has banned) acd_cli?

**Comment by maiaftv** [comment]
With this solution, you're enabling CloudSync, a third-part application not related to ACD to both:
- Ability to read your Cloud Drive content.
- Ability to modify your Cloud Drive content.

@epemetheus, @jerblack, @thenoahcomputer, @nonissue
Are you sure you all want to do this?

**Comment by JustinGrote** [comment]
I think it's more that there is just a bug on the intermediary server and
yadayada hasn't seen this yet to go look and fix it. I wouldn't worry too
much.

**Comment by epemetheus** [comment]
Sure why not, all my shit is in AES-256bit encryption?

**Comment by JustinGrote** [comment]
Yeah #1 I don't care it's all encrypted, #2 this is a desktop applications,
and his processing looks like it doesn't save the API keys on his server
(in fact the nature that he doesn't "get the key automatically" for you
means he probably can't, the same reason why you have to do it for acdcli)

**Comment by zmwangx** [comment]
The title of this issue is misleading considering developments since its creation. What about changing it to a more fitting description for discoverability?

**Comment by thenoahcomputer** [comment]
So it would appear epemetheus solution only works for 1 hour until the token needs to be refreshed

**Comment by epemetheus** [comment]
Nutz, yeah it broke after an hour :/

**Comment by isleshocky77** [comment]
@jerblack Unless I'm missing something, it appears that access to the Amazon Drive API is now invite-only.  I went through the process of setting up the security profile but kept getting an invalid_scope error. With a little more digging I found an issue where @yadayada goes off on someone for not thoroughly reading the docs and whitelisting the app. However, on my profile I have no way of doing that. 

> Whitelisting Your App
> 
> You must be invited into the Amazon Drive API service to whitelist your app for Amazon Drive or you will not be able to send any node-related requests. 

Source: https://developer.amazon.com/public/apis/experience/cloud-drive/content/getting-started

https://developer.amazon.com/cloud-drive
https://news.ycombinator.com/item?id=12273150

**Comment by dany20mh** [comment]
Can we setup a automatic script that get the oauth from that site and replace it in the cache?

Like this 

curl https://drivesink.appspot.com/config?c=xxxxxx -fo ~/yourcachfolder/oauth_data

**Comment by yadayada** [comment]
I suggest to wait 3 hours till the quota is reset. Again, a note to the desperate: I think the backup authentication Appspot app may still be working, see https://github.com/yadayada/acd_cli/issues/147#issuecomment-141811192.

**Comment by jerblack** [comment]
Things have started working again! I can now authenticate again.
