### ISSUE TITLE
files not showing - acd_cli sync reports over quota

### ISSUE THREAD

**Issue by a5m0** [yadayada/acd_cli#393]
Suddenly all my files aren't showing up and acd_cli sync reports "This application is temporarily over its serving quota.  Please try again later."

**Comment by zmwangx** [comment]
Same here. I guess someone's abusing the service.

For the moment you could switch to your own security profile. See https://acd-cli.readthedocs.io/en/latest/authorization.html#advanced-users-security-profile. It does take a few (kind of confusing) steps to set up, and IIRC there were past reports of personal security profiles not being as fast as @yadayada's one for production, but I've been using my profile for a while on one of my machines and didn't notice any speed drop (upload speed goes up to ~300Mbps which is good enough for me). Now I'm switching the profile across the board.

**Comment by zmwangx** [comment]
Actually #391 is the same issue.

**Comment by isleshocky77** [comment]
@zmwangx Am I seeing this wrong or did Amazon change access to the Amazon Drive API 20 days ago to be invite-only?  Meaning you now can't create your own security profile unless you pass through the invite process.

https://developer.amazon.com/cloud-drive
https://news.ycombinator.com/item?id=12273150

**Comment by zmwangx** [comment]
> Am I seeing this wrong or did Amazon change access to the Amazon Drive API 20 days ago to be invite-only?

Wow, the heck? Guess that's why I can't figure out how to whitelist just now (#392). Glad I have a working profile that predates this bullshit.

To be clear, I think you can still create security profiles, but maybe you need an invitation to get it whitelisted for ACD's API.

**Comment by KarmaPoliceT2** [comment]
Not trying to be "one of those people"... but just thought it interesting that rclone (http://rclone.org/) works fine right now... so not sure what they are doing differently, but it might be worth looking into for acd_cli

**Comment by JustinGrote** [comment]
Duplicate of #391. The problem is that there's an intermediary server that yadayada runs to do the app token refreshing and it's busted. We have to wait until he fixes it.

**Comment by sergiopatino** [comment]
@KarmaPoliceT2 Amazon's whitelisting process for access to their API is application specific and traffic is tagged accordingly. If usage for one service (acd_cli vs rclone) spikes Amazon may start to throttle or deny access. It's happened before.

**Comment by zmwangx** [comment]
> If usage for one service (acd_cli vs rclone) spikes Amazon may start to throttle or deny access.

What's happening here is the GAE app being throttled. It's not Amazon's problem.

**Comment by a5m0** [comment]
looks like it's working again
