### ISSUE TITLE
RequestError: 504, [acd_api] no body received

### ISSUE THREAD

**Issue by CharlesErickT** [yadayada/acd_cli#397]
Hey guys,

I'm not sure if the issue I have is related to ACD, Acd_cli or either my setup. Here's what I get when I try to run 
```
acd_cli sync

Getting changesTraceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1601, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 721, in sync_action
    return sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/local/bin/acd_cli.py", line 140, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/metadata.py", line 51, in get_changes
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 504, [acd_api] no body received.
```

I tried to search if ACD currently have any issues but it doesn't seems like it.

This is on Ubuntu 16.04. Anyone else is having the same issue ?

Thanks

**Comment by yadayada** [comment]
I think you will find similar closed issues. acd_cli cannot do anything if it fails with a HTTP 504 status. Rinse and repeat. If you find you cannot sync at all, try the deprecated and slower `old-sync` command.

**Comment by CharlesErickT** [comment]
Thanks for the reply. I was able to make it work using `old-sync`
