### ISSUE TITLE
Question:  What makes "security profile" more secure?

### ISSUE THREAD

**Issue by ShapeShifter499** [yadayada/acd_cli#404]
I'm looking at https://acd-cli.readthedocs.io/en/latest/authorization.html and I read the following quote. "There is a fast and simple way and a secure way."  What makes one way more secure than the other?

**Comment by msh100** [comment]
Using the public oauth_handler you're relying on an application hosted by @yadayada to provide you with the data in the oauth_data, so if for whatever reason you don't trust @yadayada's handling of your secrets to the ACD API, then it could be considered insecure. Handling your own oauth requests however do not have this issue as you communicate directly with Amazon oauth services.

**Comment by ShapeShifter499** [comment]
@msh100 Thanks for the quick reply. Maybe this info should be added to the manual/wiki page somewhere.
