### ISSUE TITLE
Regular crash on mac using FUSE

### ISSUE THREAD

**Issue by BoxOfSnoo** [yadayada/acd_cli#410]
I am trying to use encfs and acd_cli together to host some Plex items on my Mac (El Capitan, for a few days more at least!)

It seems to work perfectly for about 24 hours (or so?), and then as soon as I try to access it through Plex, the acd_cli process crashes.  My Console.app shows that Python is the task that crashes.  It seems to be after a passage of some hours, before that I can access the videos easily, I tested a few videos, a few times yesterday and it works great.  Something happens after time though, maybe you can help.

The console crashlog is here: http://pastebin.com/Yu9TdUs5

Due to the number of overlapping bits of software, I hope I am targeting the right project... you know how it is, please let me know if otherwise, or if you need more info.

encfs 1.8.1
FUSE For macOS 3.5.0 (I was using 2.x until yesterday, same issue)

I am also using unionfs 0.26 but I am not accessing that mount point at all when it crashes, so I doubt that has anything to do with it (does it?)

Thank you.

**Comment by yadayada** [comment]
Did you have a look at the FAQs?

**Comment by BoxOfSnoo** [comment]
Yes, but apparently I totally didn't see that one.  Thanks.  I guess it would have been more obvious if it threw the error *right* after I executed acd_cli but I guess that's the nature of debugging daemons and stuff.
