### ISSUE TITLE
sqlite3.DatabaseError: file is encrypted or is not a database

### ISSUE THREAD

**Issue by kuuhakuu** [yadayada/acd_cli#414]
I'm getting this all of a sudden:
`Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/bin/acd_cli.py", line 1574, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/db.py", line 59, in __init__
    self.integrity_check(check)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/db.py", line 124, in integrity_check
    r = c.execute('PRAGMA integrity_check;')
sqlite3.DatabaseError: file is encrypted or is not a database`

**Comment by EldonMcGuinness** [comment]
This sounds like corruption of the nodes.db file. Last time I seen it I deleted the file and did another sync.

**Comment by jmelton98** [comment]
I have the same problem. Where is the nodes.db file located?
Thanks

**Comment by EldonMcGuinness** [comment]
@jmelton98 Supposedly you can run `acdcli cc` to fix the issue as well. But the nodes.db file can be found by using `acdcli -v i`

```
16-11-15 11:59:58.162 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-11-15 11:59:58.162 [INFO] [acd_cli] - TestPlugin attached.
16-11-15 11:59:58.162 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
16-11-15 11:59:58.163 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-11-15 11:59:58.164 [INFO] [acdcli.api.oauth] - LocalOAuthHandler initialized.
16-11-15 11:59:58.822 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-11-15 11:59:58.823 [INFO] [acd_cli] - Last sync at 2016-11-15 13:00:20.924850.
```

Note the acdcli.api.client line, that is where you will look.
