### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Axcy** [yadayada/acd_cli#418]
Hello,

Just installed Acd_cli on a fresh OVH server, but recieving a TypeError: float() argument must be a string or a number, not 'NoneType' when I try to sync after placement of the oauth file.
```

Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1608, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 728, in sync_action
    return sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/local/bin/acd_cli.py", line 134, in sync_node_list
    lst = float(lst)
TypeError: float() argument must be a string or a number, not 'NoneType'

```

**Comment by kuuhakuu** [comment]
Having the same problem, also on an ovh server. Though mine isn't fresh but reinstalled. Had it running on the same setup 2 or 3 days ago.

**Comment by Postremus** [comment]
same problem here on a fresh install

**Comment by Postremus** [comment]
So, did some further investigation:
this problem is related to https://github.com/yadayada/acd_cli/commit/b2b75dc6b7742099668e0d8c253c2902ff42cf6a
The cache seems to be empty on a fresh install for this key.
Adding  
```
    if not lst:
        lst = 0
    lst = float(lst)
```
after line 133 solved this problem for me.
