### ISSUE TITLE
Support sparse files?

### ISSUE THREAD

**Issue by docbill** [yadayada/acd_cli#419]
I don't know if Amazon Cloud Drive supports sparse files.   But if it does, it would be really helpful if acd_cli supported it.   Here are few failure cases:

[briemers@media1 ~]$ dd if=/dev/zero of=pv01.img bs=1M seek=9999 count=1
1+0 records in
1+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 0.00185389 s, 566 MB/s
[briemers@media1 ~]$ cp pv01.img acd/.
cp: error writing 'acd/./pv01.img': Illegal seek
cp: failed to close 'acd/./pv01.img': Remote I/O error
[briemers@media1 ~]$ cd acd
[briemers@media1 acd]$ dd if=/dev/zero of=pv01.img bs=1M seek=9999 count=1
dd: failed to truncate to 10484711424 bytes in output file 'pv01.img': Function not implemented

If acd_cli supported sparse files, then loopback file systems on acd_cli would become an extremely useful use case.

**Comment by docbill** [comment]
BTW.  Another use case that fails if rsync attempts to copy a sparse file, with our without the -S flag rsync seems to simply freeze.   It took a long time to realize that is why rsync was not working for mirror my data.   I thought acd_cli was losing connection with amazon or something.

**Comment by bgemmill** [comment]
@docbill looking at the drive API, it's not clear that we can store sparse files directly on amazon since the resource model looks like blobs of bytes with discreet size:
https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes

Truncation to non-zero lengths is also hard because the API doesn't support partial writes; we'd need to upload the entire non-truncated file again. You can imagine this would be bad if the call was to truncate one byte off the end of a huge file.

You'll probably have better luck backing up sparse files inside duplicity or borg using acdcli as the target, which will preserve the files internally and just expose binary blobs to amazon.

**Comment by docbill** [comment]
Thanks.  That is a very helpful link.   I was looking at the code, and I see writes are basically implemented as if we have a tape drive.   One can create a new file, or append to an existing file.  Attempting to say replace a block in the middle simply is not possible.   As such something like truncating a file to add in holes definitely is beyond the scope of the current driver.   A cursory look at the API it seems that functionality is simply not included in the offering.  One can do resumable uploads to append to a file but that is it.   It is always possible Amazon would interpret resuming an upload past the EOF as a command to insert a filesystem hole, but unlikely.  I'll have to try it anyway, just because I'll want to know.   But the standard does indicate clearly if one simply tried re-uploading an earlier part of the file, the chunk would simply be ignored.   Pitty.

**Comment by bgemmill** [comment]
There are some workarounds we can do; I have a PR branch that stores files locally in memory (or disk if they get too big) and then upload fully to amazon on flush or file handle release. This allows some more flexibility in how the blob is formed than the tape drive model, but we still have to send it to amazon all at once and it can't have any holes.

**Comment by docbill** [comment]
I see I was wrong about being able to append files.   In the current implementation it is only possible to append while the session is in progress.   Presumably feature that could be extended using a range request to do a resumable upload. 

As for the rest it seems like if it is beyond what Amazon Cloud Drive support, it is better to do the extension as an additional fuse module to layer ontop.   For example the cryfs can allow random access data.   I don't particularly like the cryfs solution because it would result in billions small files.   But it is an example of one way to do it.   A better way might be a system that adds journelling ontop of acl_cli.   So the updates could be written to ACD right away, applied locally when accessing the files, and background process could apply the journel to ACD in a efficient manner.   That however, seems to make a fairly simple fuse model and make it extremely complicated.

Your locally story and upload seems like a reasonably simple solution that probably would make sense to add as option that could be enabled or disabled.   So in usage scenarios where buffering makes sense it could be used.   When another solution is layered ontop that adds functionality ontop more efficiently it could be disabled.

In anycase, it is quite clear filesystem holes is well beyond what is possible, so I will close this issue.

**Comment by docbill** [comment]
Ah.  I found the issue.  3.8 GB is exactly the size of my tmpfs.   The process is filling up my tmp volume, and then giving a disk full error.   After that acd_cli is just starts sort of faking it.  None of the data actually gets sent to amazon.
