### ISSUE TITLE
Some error messages when uploading a huge directory of subfolders and files

### ISSUE THREAD

**Issue by procmail** [yadayada/acd_cli#43]
Here are some errors. If helpful, I'll paste different ones as I encounter them.

This was after a sync has been done.

```
15-05-20 08:42:41.859 [ERROR] [acd_cli] - Uploading "DSC03681-Edit.tif" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
15-05-20 08:52:55.102 [ERROR] [acd_cli] - Uploading "DSC04718.ARW" failed. Code: 500, msg: {"logref":"6ef2915c-fe8a-11e4-91ae-1f772ce1db15","message":"Internal failure","code":""}
15-05-20 09:32:14.355 [ERROR] [acd_cli] - Uploading "IMG_3942.JPG" failed. Code: 500, msg: {"message":"Internal failure"}
```

There was another one about a token yesterday, but I lost that log.

**Comment by yadayada** [comment]
The name collisions can still happen after syncing because the synced data is not always up to date.

The other error messages aren't very useful by themself. Could you post the errors with the verbose option enabled?

**Comment by procmail** [comment]
I will try again, but using the verbose option with that many number of files makes it hard to spot the errors.

Can I use the 2> error.log to redirect the errors?

**Comment by yadayada** [comment]
Redirecting the standard error stream like you suggested will redirect all log messages, including the skipping info.
