### ISSUE TITLE
mount: corrupted database

### ISSUE THREAD

**Issue by ladude626** [yadayada/acd_cli#430]
Sorry I'm a noob, don't know where to find the log for this issue. But I often get this error I'm trying to access the folders:

ls: cannot access 'acd_decrypted': Bad address
ls: cannot access 'acd_encrypted': Bad address 

I believe it's database corruption issue. Because if I delete /root/.cache/acd_cli/nodes.db and run "acd_cli sync", everything works again. Don't have to unmount/remount anything, and don't have to make any changes to encfs.

I'm using encfs 1.8.1 + acd_cli 0.3.2.

**Comment by ncorder** [comment]
I seem to get this error more often when I run "acd_cli sync" while also having ACD mounted to a folder...

**Comment by metalgeekstl** [comment]
@ncorder Same here. I run it before my nightly upload cron job. I'll remove 'acdcli sync' it and see if it dismounts again.

**Comment by yadayada** [comment]
Please test  the pull request #436.

**Comment by madmanali93** [comment]
Has anyone tested that pull request  yet? I have the same issue and I have been trying to fix it. Mostly happens after the acdcli sync

**Comment by ladude626** [comment]
According the PR discussion, looks like it's not ready for general use yet. Looks like you have to configure the database manually.
