### ISSUE TITLE
Intermitent very low upload speeds

### ISSUE THREAD

**Issue by maiaftv** [yadayada/acd_cli#433]
I am facing very low speeds when uploading files after some time. It's totally inconsistent. Sometimes I can upload as much as 30 Gb with the full upstream and then drops for an unknown reason. Syncing, remounting and removing the cache nodes don't help.

Does anybody have a clue in how to solve this?

```
$ rsync -avrhP --inplace *.img ~/Backup/
sending incremental file list
221000.img
          4.55M   0%  101.69kB/s   61:56:19 
```

**Comment by Joost1991** [comment]
I have the same problem. Once in a while it just uploads a file with 100kb/s, most of the time it uploads with full speed. If I cancel the upload and try it again it goes back to full speed again.

**Comment by maiaftv** [comment]
Mounting with or without -i0 doesn't influence, also.

**Comment by asabla** [comment]
I've seen this behavior on my end as well. Think it has more todo with ACD then the mount it self, but im not sure

**Comment by El-Fitz** [comment]
What do you mean by and how do you get "full upstream" ? Is it full speed ?
Personally, moving a file to an acd_cli mount has, at best, 500kb/s.

While acd_cli upload -x 10 went as fast as 12Mb/s (and I couldn't find what the 'x' option does, or what '10' stands for. But thanks reddit anyway)

**Comment by maiaftv** [comment]
Hello @El-Fitz. I meant, by "full upstream", taking the whole available speed in my connection here: 25 MB/s for upload. Is it wrong to use the term "full upstream"? ESL learner here, always trying to improve.

Unfortunately, I can't upload files with your method, as I'm using an encrypted fs (encfs) that is mounted on top of the acd's folder. I'm basically rsyncing my files with the --inplace option to avoid the creation of hidden files. Apart from the speed issues, which has been improved, everything works fine.

**Comment by El-Fitz** [comment]
I'm also using encfs
It's quite simple actually.

Have a look at this: https://amc.ovh

**Comment by maiaftv** [comment]
Thank you for the link, @El-Fitz. Doesn't it implies that you need to have a mirror copy in your local drive? In my scenario here, the encrypted folder at ACD is larger than all my local disks combined.

**Comment by El-Fitz** [comment]
@maiaftv Nope. That's the beauty of it. Just have to mirror the structure (path to the file).

Would be quite useless if you had to make a mirror copy. The union-fs part isn't what you need. It just enables to "display" the local mount and the remote one as a single volume, a whole other matter.

**Comment by maiaftv** [comment]
This sounds really good, @El-Fitz! I will try it here. Thank you very much.

**Comment by maiaftv** [comment]
I finally managed some time to read the articles thoroughly. Issue has been solved. Thanks, @El-Fitz . Full speed now,
