### ISSUE TITLE
Writing to acd_cli fuse mount breaks on partially uploaded files when using rsync.

### ISSUE THREAD

**Issue by gordan-bobic** [yadayada/acd_cli#435]
Specifically, the following rsync options manifest the problem:
```
--append
--append-verify
--no-whole-file
```

rsync reports it couldn't write.

Unfortunately, without these options, resuming uploads on large files is impractical.

Additionally, mtimes preservation doesn't appear to work, which breaks metadata based checking, so the checks have to be relaxed to use --size-only rsync option. I don't know if this is a limitation of ACD or acd_cli.

**Comment by tintop2k** [comment]
You can't do partial writes to ACD. It's object based storage.

Take a look at rclone. You can upload direct to your ACD without pushing
through an acd_cli mount. I use acd_cli as a read only fuse mount and
rclone to upload data (which acd_cli sees when it syncs). They work very
well together.

**Comment by gordan-bobic** [comment]
If there is no way to append, how does rclone work around it?

The specific case I am trying to address is where the connection drops or gets reset for whatever reason during the upload of a large file.

**Comment by tintop2k** [comment]
As I understand it, rclone does a low level retry in that instance. It's
still uploading the same file, in the same ACD upload object, but
reestablishes the HTTP connection. If the low level retry attempts don't
work, then rclone will do a full retry which is an upload from scratch.

It's not something you can compare to rsync retries which, I believe, try
and establish a new file handle to the partially copied file and append to
it.

Only when a file is fully uploaded does it gain persistence in ACD. There
is no concept of partial files. Files either finish uploading and get an
object ID or fail to upload, are discarded and cease to exist.

When you write into the fuse mount of acd_cli, it opens a session to ACD
and starts streaming the file to it. If you cancel the write, lose internet
connection briefly, the source disappears or anything else occurs to fail
out rsync then the operation fails. Rsync can't resume as there is no data
to resume to. A new, full write must be attempted.

If you are uploading large files, you'll have more success using out of
band rclone uploads or acd_cli upload commands. Small files will be fine
through the fuse mount as there is less chance of a minor disruption
causing the entire file to fail.

**Comment by gordan-bobic** [comment]
I see, so there is no way to make this work due to ACD limitations. Thank you for the explanation and apologies for the noise. Closing the issue.
