### ISSUE TITLE
Slow read of File Stream / Upload.

### ISSUE THREAD

**Issue by timliesenhoff** [yadayada/acd_cli#438]
Hey all,
first of all, my configuration:
Server with 1Gbit connection
ACD Drive mounted
(by fstab or acd_cli mounted to /media/acd/ , same issue)
My Wan Connection is about 100 mbit. (most times 140 mbit)

When i want to view 720P Videos, the stream is lagging.
I download a ubuntuimage from this server (apache)  its downloaded with fuss speed (140 mbit/ or 14mb/s), so it cannot be cause of WAN connection from Server to me.
When i start Up/Download to/from ACD, noproblems, 30 mb/sec

> `[##                       ]  11.7% of   26GiB   0/13   27.9MB/s   14:47m`

i tryed to change buffes size, like this [description](http://acd-cli.readthedocs.io/en/latest/configuration.html), but no changes: (changed it to: 2000, 231072,331072)

> 16-10-07 16:50:35.507 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
> 16-10-07 16:50:35.508 [DEBUG] [acdcli.utils.conf] - configuration resulting from merging default and acd_cli.ini: {'download': {'keep_corrupt': 'False', 'keep_incomplete': 'True'}, 'DEFAULT': {}}
> 16-10-07 16:50:35.508 [DEBUG] [acdcli.utils.conf] - configuration resulting from merging default and acd_client.ini: {'endpoints': {'validity_duration': '259200', 'filename': 'endpoint_data'}, 'proxies': {}, 'DEFAULT': {}, 'transfer': {'idle_timeout': '60', 'connection_timeout': '30', 'chunk_retries': '1', 'fs_chunk_size': '2000', 'dl_chunk_size': '524288000'}}
> 16-10-07 16:50:35.508 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
> 16-10-07 16:50:35.508 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
> 16-10-07 16:50:35.509 [DEBUG] [acdcli.utils.conf] - configuration resulting from merging default and cache.ini: {'sqlite': {'filename': 'nodes.db', 'journal_mode': 'wal', 'busy_timeout': '30000'}, 'DEFAULT': {}, 'blacklist': {'folders': '[]'}}
> 16-10-07 16:50:35.515 [INFO] [acdcli.cache.schema] - DB schema version is 2.
> 16-10-07 16:50:35.516 [DEBUG] [acdcli.cache.db] - Set busy_timeout to 30000. Result: 30000.
> 16-10-07 16:50:35.541 [DEBUG] [acdcli.cache.db] - Set journal_mode to wal. Result: wal.
> 16-10-07 16:50:35.542 [INFO] [acd_cli] - Last sync at 2016-10-07 13:50:35.290139.

But read did not changing.
> `16-10-07 16:47:48.155 [DEBUG] [acdcli.acd_fuse] - s: 213319680-487400055; r: 213319680-213450751
> 16-10-07 16:47:48.156 [DEBUG] [acdcli.acd_fuse] - <- read 131072`

Any suggestions? Or maybe more data / information needed?

**Comment by yadayada** [comment]
Try to increase the buffer in your video player.

>i tryed to change buffes size

...
>But read did not changing.

That's because `buffer_size` only changes the length of the write queue.

**Comment by timliesenhoff** [comment]
sorry but it is not solved for me,
even not every player is able to change buffer size, or is able to buffer >100mb
if i have 30 mb/s connection to cloud,
why the fuse mount is having this bad connection.
CPU 99% idle. 
Memory 600 mb of 4 GB used.
its not the hardware :/

i checked speed by pv now.
its copying with a speed of 1 mb/s up to ~ 4 mb/s

> pv /media/acd/4k-bspl.mp4 > /home/test/testfile.mpg
>  465MB 0:02:32 [3.05MB/s] [========================....=====>] 100%

but i can up/download vom acd with:

> [## ] 11.7% of 26GiB 0/13 27.9MB/s 14:47m

so why is fuse so slow :(
