### ISSUE TITLE
Error on (re)mount

### ISSUE THREAD

**Issue by tolotos-rgu** [yadayada/acd_cli#440]
Hi,
I get an error if try to mount the amazon drive:

16-10-08 22:51:22.906 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-10-08 22:51:22.906 [INFO] [acd_cli] - TestPlugin attached.
16-10-08 22:51:22.906 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
16-10-08 22:51:22.907 [DEBUG] [acdcli.utils.conf] - configuration resulting from merging default and acd_cli.ini: {'DEFAULT': {}, 'upload': {'timeout_wait': '10'}, 'download': {'keep_corrupt': 'False', 'keep_incomplete': 'True'}}
16-10-08 22:51:22.907 [DEBUG] [acdcli.utils.conf] - configuration resulting from merging default and acd_client.ini: {'DEFAULT': {}, 'proxies': {}, 'endpoints': {'filename': 'endpoint_data', 'validity_duration': '259200'}, 'transfer': {'idle_timeout': '60', 'fs_chunk_size': '131072', 'dl_chunk_size': '524288000', 'connection_timeout': '30', 'chunk_retries': '1'}}
16-10-08 22:51:22.908 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-10-08 22:51:22.908 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-10-08 22:51:22.909 [DEBUG] [acdcli.utils.conf] - configuration resulting from merging default and cache.ini: {'DEFAULT': {}, 'blacklist': {'folders': '[]'}, 'sqlite': {'journal_mode': 'wal', 'busy_timeout': '30000', 'filename': 'nodes.db'}}
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1584, in main
    cache = db.NodeCache(CACHE_PATH, SETTINGS_PATH, args.check)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/db.py", line 59, in __init__
    self.integrity_check(check)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/cache/db.py", line 124, in integrity_check
    r = c.execute('PRAGMA integrity_check;')
sqlite3.DatabaseError: file is encrypted or is not a database

**Comment by tintop2k** [comment]
Delete nodes.db and run acdcli sync to create a new database.

**Comment by tolotos-rgu** [comment]
Thanks it works now. 
I found a remount script in issue #290 and will add this in the next days to my server.
