### ISSUE TITLE
Identify the file being uploaded

### ISSUE THREAD

**Issue by jscottdouglas** [yadayada/acd_cli#445]
How can I identify the file being uploaded at the time? I am uploading folders with alot of different files, seems to be failing on one file but I can't identify which one.

**Comment by yadayada** [comment]
If you use the `-verbose` flag, you'll see which file is being uploaded in the logging output, e.g. 
```
16-10-15 06:17:48.029 [INFO] [acd_cli] - Uploading foo.bar
```
