### ISSUE TITLE
Windows: Download hangs after first file

### ISSUE THREAD

**Issue by sasotepina** [yadayada/acd_cli#45]
Verison 03a5e3a5819711e41e0085c49ce5c1bc8c4574b3
Windows XP, Windows 7
When downloading a file, the download stops after 100%, the speed goes to 0, and nothing else happens.
When downloading a folder, the download stops at 100% of the first file.
The file is downloaded ok, but it keeps the `.__incomplete` extension.

**Comment by yadayada** [comment]
This is because the fi

**Comment by yadayada** [comment]
Will be fixed in the next commit.
