### ISSUE TITLE
Download chunk size (Not configurable?)

### ISSUE THREAD

**Issue by karbowiak** [yadayada/acd_cli#452]
Hi there, i just installed ACDCLI (again) but i've noticed that i can at most get around 1MB/s in download speed, even if my connection is capable of several times that.

I've looked at the logs, and noticed the the download chunk size is always 131072 (~128KB)
Is there any way to up this to say 256, 512, 1024KB blocks?
This should speed up the transfer speed by a lot -but i've tried every conceivable configuration option, and gotten nowhere.

**Comment by yadayada** [comment]
It's [`fs_chunk_size`](http://acd-cli.readthedocs.io/en/latest/configuration.html#acd-client-ini). I increased the value to 1 gigabyte and even that didn't negatively affect my transfer rate.

**Comment by karbowiak** [comment]
Hi @yadayada

I've now tried adding ```[transfer]
fs_chunk_size = 16777216```

In acd_client.ini under `/root/.config/acd_cli` and `/root/.cache/acd_cli` both times it reverts back to 131072 according to the log.

```16-10-22 19:34:44.089 [DEBUG] [acdcli.acd_fuse] - -> open /Win10_1607_EnglishInternational_x64.iso ('0x8000',)
16-10-22 19:34:44.091 [DEBUG] [acdcli.acd_fuse] - <- open 2
16-10-22 19:34:44.091 [DEBUG] [acdcli.acd_fuse] - -> read /Win10_1607_EnglishInternational_x64.iso (131072, 0, 2)
16-10-22 19:34:44.092 [DEBUG] [acdcli.api.content] - chunk o 0 l 524288000
16-10-22 19:34:44.092 [DEBUG] [acdcli.api.backoff_req] - Retry 0, waiting -18.796028s
16-10-22 19:34:44.092 [INFO] [acdcli.api.backoff_req] - GET "https://content-eu.drive.amazonaws.com/cdproxy/nodes/-xxxx/content"
16-10-22 19:34:44.095 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): content-eu.drive.amazonaws.com
16-10-22 19:34:44.703 [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /cdproxy/nodes/-xxxx/content HTTP/1.1" 206 524288000
16-10-22 19:34:44.704 [DEBUG] [acdcli.api.backoff_req] - x-amzn-RequestId: xxxx
16-10-22 19:34:44.952 [DEBUG] [acdcli.acd_fuse] - <- read 131072
16-10-22 19:34:44.953 [DEBUG] [acdcli.acd_fuse] - -> read /Win10_1607_EnglishInternational_x64.iso (131072, 131072, 2)
16-10-22 19:34:44.953 [DEBUG] [acdcli.acd_fuse] - s: 131072-524287999; r: 131072-262143```

So no idea what i'm doing wrong at this point :\

Could it be because i'm running it as a fuse mount (with the acdcli mount /mnt/acd command) ?

**Comment by karbowiak** [comment]
After some more digging, it is indeed Fuse that sets the 128KB block size.

Is there any chance you can ignore that in acdcli @yadayada and download whatever blocksize the user defines ?

Because fuse limiting the download block size to 128KB blocks, severely limits the download speed when using acdcli with the mount option.
