### ISSUE TITLE
--overwrite function

### ISSUE THREAD

**Issue by jscottdouglas** [yadayada/acd_cli#453]
If the --overwrite (-o) argument is specified, the remote file will be overwritten if it exists.

How is this handled with folders, does the overwrite overwrite the entire folder or only file content example i recreate file paths in my local drive remove source but another file goes into one of the folders and now the path gets recreated, if i do an upload of folder to folder will it overwrite the entire folder or just the files within the folder if it finds a match from the local.  The read me isn't exactly clear on how it is handled. My concern is that I add the overwrite flag and it will clear the contents of the remote folder and replace it with the new local folder.

**Comment by yadayada** [comment]
The `--overwrite` flag does not affect whole folders, just files with matching file names.

```
  --overwrite, -o       overwrite if local modification time is higher or
                        local ctime is higher than remote modification time
                        and local/remote file sizes do not match.
```
