### ISSUE TITLE
Feature request: Sync only a "folder" on ACD

### ISSUE THREAD

**Issue by imagesafari** [yadayada/acd_cli#454]
Perhaps this is already possible and I just can't find it. I've got 2TB+ of backup data on ACD, but I'd like to mount only one top level directory, and not sync the whole thing.

If there is already a way to do this, please let me know! :)

Thanks.

**Comment by vb0** [comment]
--modules="subdir,subdir=/myfolder"

**Comment by imagesafari** [comment]
vb0: I know that works for mounting, but does it work for sync as well?

**Comment by vb0** [comment]
Brain freeze sorry, I read only " I'd like to mount only one top level directory" :-)

I don't know how/if that can be done - and especially with sync becoming throttled/getting interrupted this could be a very useful feature if you have tons and tons of files outside your normal acd_cli fuse mount.

**Comment by tintop2k** [comment]
Yes, the command is detailed here
https://acd-cli.readthedocs.io/en/latest/FUSE.html

A non-root folder may be mounted similarly, by

acd_cli -nl mount --modules="subdir,subdir=/folder" path/to/mountpoint

**Comment by imagesafari** [comment]
Again, I know I can _mount_ a subfolder. The question is can I limit what acd_cli _syncs_ to a subfolder?

**Comment by philipp-spiess** [comment]
The initial syncing takes forever if you have a lot of data on ACD that you don't want to access via the CLI. I use Arq to backup my devices which results in a lot of files. 

I think this can be avoided by only syncing part of the files that are on ACD into the cache. I would love to see this happen.

**Comment by yadayada** [comment]
This has already been requested in #338.
