### ISSUE TITLE
OSError: Unable to find libfuse

### ISSUE THREAD

**Issue by kmain4** [yadayada/acd_cli#461]
Getting the following error when running `acdcli -v mount /mnt/.acd` after init and sync on my tiny Ubuntu 16.04 VM...

```
root@offsite:~/Downloads/complete# acdcli -v mount /mnt/.acd
16-10-27 10:14:52.754 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-10-27 10:14:52.754 [INFO] [acd_cli] - TestPlugin attached.
16-10-27 10:14:52.754 [INFO] [acd_cli] - Settings path is "/root/.config/acd_cli".
16-10-27 10:14:52.756 [INFO] [acdcli.api.client] - Initializing ACD with path "/root/.cache/acd_cli".
16-10-27 10:14:52.756 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
16-10-27 10:15:00.727 [INFO] [acdcli.cache.schema] - DB schema version is 2.
16-10-27 10:15:00.728 [INFO] [acd_cli] - Last sync at 2016-10-27 14:14:48.856160.
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1611, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 1089, in mount_action
    import acdcli.acd_fuse
  File "/usr/local/lib/python3.5/dist-packages/acdcli/acd_fuse.py", line 29, in <module>
    from fuse import FUSE, FuseOSError as FuseError, Operations
  File "/usr/local/lib/python3.5/dist-packages/fuse.py", line 69, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse
```

**Comment by EpicnessTwo** [comment]
This error usually happens when you don't have the fuse package installed. You can install this with:

`sudo apt-get update && sudo apt-get install fuse`

After this, it should work. :)

**Comment by kmain4** [comment]
@EpicnessTwo Looks like its an issue because I'm being hosted on OpenVZ. I tried that and still no go, now I get another error..

**Comment by kmain4** [comment]
```
fuse: device not found, try 'modprobe fuse' first
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/bin/acd_cli.py", line 1601, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 1088, in mount_action
    allow_root=args.allow_root, allow_other=args.allow_other)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/acd_fuse.py", line 716, in mount
    FUSE(ACDFuse(**args), path, subtype=ACDFuse.__name__, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/fuse.py", line 480, in __init__
    raise RuntimeError(err)
RuntimeError: 1
```

**Comment by EpicnessTwo** [comment]
Not 100% guaranteed to work but have you tried mounting as a non-root user? 

I've not personally tested running this as root and the practice of running things as root is sometimes frowned upon.,

**Comment by bgemmill** [comment]
If you're mounting as non-root, make sure your user account in the 'fuse' group.

**Comment by jerblack** [comment]
Try using `modprobe fuse` to verify that fuse is enabled on your VM.

On a VM where FUSE is enabled, `modprobe fuse` won't display anything.
On a VM where FUSE is not enabled, it will look something like this:
```
modprobe fuse
modprobe: ERROR: ../libkmod/libkmod.c:507 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab102.9/modules.builtin.bin'
modprobe: FATAL: Module fuse not found.
```

If it's not enabled, you should look in the web control panel for the VM provided by the host, and see if there is an option to enable it. If not, you may need to contact their support to get it turned on. A lot of OpenVZ VMs don't have it turned on by default, and some provide no way of turning it on, meaning you would just need to find another provider that supports FUSE on their OpenVZ VMs. Or just bypass the problem entirely and get a KVM VM or a dedicated server.
