### ISSUE TITLE
NO_ACTIVE_SUBSCRIPTION_FOUND

### ISSUE THREAD

**Issue by crack00r** [yadayada/acd_cli#465]
Hi, since today, i get for all my uploads

16-10-30 06:33:37.014 [ERROR] [acd_cli] - Uploading "moviestars-stardust-1080p.nfo" failed. RequestError: 403, {"logref":"67efc816-9e62-11e6-87a4-552dfff0c61c","message":"File size exceeds account allowance.","code":"NO_ACTIVE_SUBSCRIPTION_FOUND"}.

**Comment by anhydro** [comment]
Have you checked to see if you still have a plan with ACD?

**Comment by crack00r** [comment]
lol, thx :D
