### ISSUE TITLE
RequestError:1000 / Broken Pipe

### ISSUE THREAD

**Issue by Razzala** [yadayada/acd_cli#466]
When running the upload command I am getting the following error:

16-10-30 12:59:24.720 [ERROR] [acd_cli] - Uploading "bP71D36Dfj3494tn6wvMrkdsSmVWtec0GshAPoJMCMTBY," failed. RequestError: 1000, ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')).

It was working just fine previously.

**Comment by yadayada** [comment]
How can I reproduce this error?
