### ISSUE TITLE
RequestError: 500, {"message":"Internal failure"}.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [yadayada/acd_cli#472]
My uploading command

```
acd_cli upload --remove-source-files \
/mnt/user/Amazon/.local/* \
/encfs/ 
```

The error that I get.

```
  File "/usr/lib64/python3.5/site-packages/acdcli/api/backoff_req.py", line 149, in paginated_get
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 429, {"logref":"ca4dbfe6-a25d-11e6-b614-2fcfa11e422b","message":"System unavailable. Please back off for a while and try again later"}

16-11-04 16:28:03.830 [ERROR] [acd_cli] - Uploading "nmQRxj2iyWfN9l6hoajq2D,jy337vK4ea0cTTZ9C5X0EIxmQydpxXk6u" failed. RequestError: 500, {"message":"Internal failure"}.
16-11-04 16:56:16.193 [ERROR] [acd_cli] - Uploading "vjpFrdweVhj2CVnWLwh1BrAMaG1PeZUgodmhKraGnNnVV95P9DaU5rPA" failed. RequestError: 500, {"message":"Internal failure"}.
16-11-04 17:50:47.191 [ERROR] [acd_cli] - Uploading "qjRwlNXfvXlTSkSH-pjhcz71bwFD58Vsc-F0IjCzExPLu6SdrE69fNqo" failed. RequestError: 500, {"message":"Internal failure"}.
16-11-04 18:33:35.410 [ERROR] [acd_cli] - Uploading "AbXuUCPDnydt2jgHNBmDr7M,hE49RdlyuXuVA1Qm1OR2p-" failed. RequestError: 500, {"message":"Internal failure"}.
16-11-04 18:59:21.753 [ERROR] [acd_cli] - Uploading "QP-sxaMzmvo,fw9fqh7bSSqbEpexZZKMOyeaOq5bdjWCAVEdH3YzO4xEWCLtt5YLNb5" failed. RequestError: 500, {"message":"Internal failure"}.

```

What does that means? Is there a reference for error codes? How do I know its an error on my side or on Amazon side? What actions that I should do on such errors? Are there any forum for inquiring error codes? Can I confirm that the uploaded file are exact to the source before acdcli delete the source file(Does it compare checksum?)?

Thanks.

**Comment by bgemmill** [comment]
500s are issues on Amazon's side. In their reply, you can see:
"System unavailable. Please back off for a while and try again later"

There's not too much to be done other than wait when they have issues.

**Comment by syaifulnizamyahya** [comment]
Thanks. Ill just try again later.

By the way, can I confirm that the uploaded file are exact to the source before acdcli delete the source file(Does it compare checksum?)?

**Comment by yadayada** [comment]
A backoff algorithm is already in place, so if you get an 429 error, you just need to repeat the failed upload later. The remaining uploads in the queue should succeed after the backoff time, but in your case they unfortunately do not.

As for the status 500, that is generally the catch-all error status and there is not much I can infer from it.

> Are there any forum for inquiring error codes?

https://forums.developer.amazon.com/spaces/87/Cloud+Drive.html

>By the way, can I confirm that the uploaded file are exact to the source before acdcli delete the source file(Does it compare checksum?)?

Yes, size and hash are compared before deleting the source file.

**Comment by syaifulnizamyahya** [comment]
Thanks for the answer.
