### ISSUE TITLE
Upload Error Code 400

### ISSUE THREAD

**Issue by dcplaya** [yadayada/acd_cli#48]
Some of the files I try to upload report a error code 400 on upload. The exact error is below. What is the cause of this?

15-05-22 09:12:45.772 [ERROR] [acd_cli] - Uploading "Super secrete video file name.nfo" failed. Code: 400, msg: {"message":"{\"name\":\"content\",\"Content-Type\":\"application/octet-stream\"}"}

I am syncing before each time I try to upload but I am uploading a large list of files. 95% of theses files are already uploaded so I get a "Skipping Upload" message. I also see 

15-05-22 09:16:19.738 [WARNING] [acdcli.api.common] - Waiting 154.651692s because of error(s).

Not sure if that is due to the "errors" skipping files or not though.

**Comment by yadayada** [comment]
Possible duplicate of https://github.com/yadayada/acd_cli/issues/40.
Using the latest version?

**Comment by dcplaya** [comment]
I just pulled your commits from today. I am retesting. I will close this is I dont get any of those errors.

**Comment by dcplaya** [comment]
Issue fixed after pulling the newest commits
