### ISSUE TITLE
How to install latest version from git

### ISSUE THREAD

**Issue by ajkis** [yadayada/acd_cli#495]
I assume that version get changed 
at iam running acd_cli 0.3.2, api 0.9.0 and installed it with 
sudo pip3 install git+https://github.com/yadayada/acd_cli.git and tried the 
sudo pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git

**Comment by yadayada** [comment]
There is not necessarily a version change. 0.3.2 is the current version.
