### ISSUE TITLE
Traceback Errors when doing anything

### ISSUE THREAD

**Issue by geekcroft** [yadayada/acd_cli#496]
Hi there,

Been running acd_cli for about 8 months on my Ubuntu server and other than having to run it in Foreground mode 24/7 its been rock solid.

Today noticed that my syncs were throwing an error, so unmounted and figured I would clear-cache (and remove the DB if I thought necessary) to do a new init/sync. However no matter what I can no longer do init/sync/mount - I just get an error similar to the below;

`# acd_cli -v init
16-12-02 11:07:52.624 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
16-12-02 11:07:52.624 [INFO] [acd_cli] - TestPlugin attached.
16-12-02 11:07:52.624 [INFO] [acd_cli] - Settings path is "/home/user/.config/acd_cli".
16-12-02 11:07:52.624 [INFO] [acd_cli] - Cache path is "/home/user/.cache/acd_cli".
16-12-02 11:07:52.625 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/user/.cache/acd_cli".
16-12-02 11:07:52.625 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1645, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 46, in __init__
    self._load_endpoints()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 66, in _load_endpoints
    self._endpoint_data = json.load(ep)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 6 column 2 - line 6 column 3 (char 202 - 203)
# acd_cli v
acd_cli 0.3.2, api 0.9.2 

`

I have tried upgrading acd_cli (though not to the dev branch), removed my oath and re-generated it and nothing is working still. I also havent upgraded any other packages since it was working 24 hours ago.

Any ideas what is going wrong?

**Comment by yadayada** [comment]
You need to fix or delete the file named `endpoint_data` in the cache path.

**Comment by geekcroft** [comment]
Fix how?

Or should I just delete

**Comment by geekcroft** [comment]
Hi yadayada,

Deleted endpoint_data (and nodes.db) and did a re-sync, and now get a "Root node not Synced" whenever I try to do the initial sync.

Obviously this causes it to break.
