### ISSUE TITLE
Performance issues with sqlalchemy / sqlite cache backend

### ISSUE THREAD

**Issue by jbuchbinder** [yadayada/acd_cli#50]
Dealing with a large number of files seems to cause a very long journaling backup in the sqlalchemy / sqlite backend.

```
Documents: 6107,   16.5 GiB
Other:     54512,  101.0 GiB
Photos:    91785,  668.0 GiB
Videos:     977,  294.0 GiB
Total:     153381,    1.1 TiB
```

The last error messages I see when sync is called with ```--debug``` are:

```
15-05-24 11:25:25.723 [INFO] [acdcli.cache.sync] - 587 duplicate folders not inserted.
15-05-24 11:25:25.723 [INFO] [acdcli.cache.sync] - 1 folder(s) updated.
```

and after an hour and a half in ```~/.local/acd_cli/```:

```
 67084288 May 24 13:48 nodes.db
  9943440 May 24 13:48 nodes.db-journal
```

The journal file grows very slowly as it attempts to insert / update records. I'm not sure if the bottleneck has to do with indexing in the sqlite database or is just a performance limitation of the backend, but it seems as though re-syncing isn't going to be logistically scalable for hundreds of thousands of files otherwise. (I'm using a 3-4 year old machine with an SSD drive and plenty of memory, if it makes any difference.)

**Comment by jurecotic** [comment]
Would using Mysql help? Mysql would also be great if you are using multiple computers to upload files.

**Comment by yadayada** [comment]
You can try the dev branch
https://github.com/yadayada/acd_cli/tree/dev
There aren't any tests yet, but the syncing should take a 10th of the time it used to for an empty cache and should speed up updates two orders of magnitude.

And here's the benchmark I used
https://gist.github.com/yadayada/c0ee0576075331ca2bd3

**Comment by jbuchbinder** [comment]
I'm around 170k files, and with the dev branch code:

```
real    0m0.720s
user    0m0.511s
sys     0m0.051s
```

(It took 17 seconds the first time, but that still beats sitting around for an hour without it.)
