### ISSUE TITLE
how does find-md5 work?

### ISSUE THREAD

**Issue by 3fey3ugf** [yadayada/acd_cli#504]
I want verify the integrity of files when I upload them to an Amazon Drive. How does find-md5 work? Does it get the the remote file's MD5 checksum value and then match it local file checksum value?

**Comment by yadayada** [comment]
Your local files are automatically hashed on-the-fly while they are being uploaded (via the CLI). On successful upload, Amazon sends back metadata of the freshly created node, which contain a checksum that was calculated on the remote side. These two hashes are compared and when they mismatch, you'll get an error message.

``find-md5`` will look for files (in the cache) that match a given MD5 sum and print the remote paths of the files.
