### ISSUE TITLE
Moving files in ACD Web UI does not reflect in ACD_CLI mount after sync

### ISSUE THREAD

**Issue by kingkork** [yadayada/acd_cli#505]
Hello, I'm having an issues that I hope someone may be able to assist with.  My ACD has a folder within it that contains 4 subfolders.  Each subfolder contains files.

Everything was properly reflected in my local ACD_CLI fuse mounts.  I have the mounts pointed to /.acd folder and then have an encfs decrypted view of that folder pointing to /acd.

I realized a file was uploaded to folder A on ACD (using rclone) when I wanted it in folder B.  I moved it using Amazon's WebUI.  After doing so, and resyncing with ACD_CLI, I no longer see the file in folder A on my local /.acd mount, which is correct behavior, but it's not showing in folder B.  I uploaded two additional files to folder B using rclone, and they are showing correctly, but this first file won't appear in folder B in /.acd.

i am verifying it exists in folder b on Amazon's WebUI.

I'm on macOS.  I tried clear-cache and seperately deleted nodes.db and did another sync.  It still won't show.  Am I doing something wrong?

**Comment by jlarson82** [comment]
Since it is a single file, try renaming the file with a single character change and then right afterwards rename it again back to the name it was.  I've had multiple cases of uploads to ACD via a different app that sometimes certain files are not visible in my ACD mount nor in Amazon's own Cloud Drive app.  Simply renaming the file has always resolved the invisible to certain apps related issues for me at least the last few months.

**Comment by kingkork** [comment]
Thanks, although I made a mistake.  It's actually a file contained within a folder.  The folder (and obviously, the file) are both not showing.  Would you recommend changing the name of the folder, the file, or both?  Just figured i'd ask before doing.

**Comment by jlarson82** [comment]
I should have stated to rename the file via the web interface so as to not have rsync upload the file again.

**Comment by jlarson82** [comment]
Renaming just the folder first in this case via the Amazon's Cloud Drive website since at least in my experience did fix a missing folder on the iOS app that was visible on the website.  Then after syncing ACD you can find out if all of the underlying files also showed up.

**Comment by kingkork** [comment]
Thanks, unfortunately changing the name to something else in the web ui and then changing it back, and then syncing, it shows in .acd.  Unfortunately, it isn't showing in the ecfs decrypted version.  That doesn't appear to be acd_cli's fault though.  I will close this out and look further.  Thanks.
