### ISSUE TITLE
Create entire path to final folder when using create

### ISSUE THREAD

**Issue by dcplaya** [yadayada/acd_cli#51]
It would be nice to have subfolders create automatically. For example, if I do

```
./acd_cli.py create /test/folder
```

And I do not have a folder called test already, the command would create "test" as well as "folder" inside of test.

**Comment by yadayada** [comment]
This will be possible with FUSE and an OS command, so I think it's not strictly necessary for me to implement.

**Comment by dcplaya** [comment]
No problem then. I will just make my scripts check for entire paths then for now until FUSE support gets better (and faster).

**Comment by yadayada** [comment]
Ok, then.

**Comment by yadayada** [comment]
Finally implemented in #146.
