### ISSUE TITLE
[Question]Constant downloading even when plex is not in use?

### ISSUE THREAD

**Issue by chris243** [yadayada/acd_cli#510]
I was going over my stats on my providers page and notice 6tb of downloads but only 800gb of upload. I installed a network monitor and notice acd_cli was downloading like 100mbps even though no one is watching anything on plex. I killed my mount and it stopped. Is this supposed to happen? It's not a big deal since I have 20tb of transfers but just wanted to make sure there wasnt anything wrong with my set up.

**Comment by odarriba** [comment]
Maybe you have Plex configured to autodiscover new media/download new subtitles/etc?This can cause Plex reading your files frequently, and since they are media files (and most of them shouldn't be able to be cacheable) they will be downloaded every time.

**Comment by bgemmill** [comment]
@chris243 `less +F ~/.cache/acd_cli/acd_cli.log` during one of these times of inactivity and it'll show you exactly which files are being read. Match that up with `lsof` and you'll be able to find which programs are doing the reading.

**Comment by yadayada** [comment]
>just wanted to make sure there wasnt anything wrong with my set up.

I don't use Plex, but there seems to be an option for debugging/logging. You should look that up and maybe take this question to the pertinent Plex support thingy.
