### ISSUE TITLE
Resume aborted upload

### ISSUE THREAD

**Issue by philipp-spiess** [yadayada/acd_cli#511]
How would one resume an aborted upload? There seems to be logic in place to resume uploads when the connection interrupts but this does not work for interrupting the upload (i.e. SIGKIILL).

I'm building a scheduled uploader that runs 8hrs/day to keep my home internet snappy during the day and I have a file that takes more than 8hours to download. I'd like to abort the upload and continue it on the next day.

Based on the documentation website:

> Incomplete file downloads will be resumed automatically. Aborted file uploads are not resumable at the moment.

Does this mean that there is a special logic involved in the exit trap that will clear the interim state? Could we add an option to `acd_cli upload` to skip this? e.g. `acd_cli upload --resumeable`?

**Comment by yadayada** [comment]
>There seems to be logic in place to resume uploads when the connection interrupts but this does not work for interrupting the upload (i.e. SIGKIILL).

I have not investigated in which cases files are lost or appear as partial uploads. There is no client-side logic involved that controls the behavior.

Resumable uploads were announced by Amazon (last year?), but I think that feature has not been implemented.

>> Incomplete file downloads will be resumed automatically. Aborted file uploads are not resumable at the moment.

>Does this mean that there is a special logic involved in the exit trap that will clear the interim state? Could we add an option to acd_cli upload to skip this? e.g. acd_cli upload --resumeable?

I see no good reason for changing the interrupt handling to prematurely and cleanly end uploads since there is no possibility to resume them later.

**Comment by philipp-spiess** [comment]
@yadayada Thank you for your input :) Not having resume logic inside the code dos explain why I can't find any :)

So, to summarize, the Amazon Drive API does not allow a resumable multipart upload similar to the S3 API right now but it was announced and we can build something like this as soon as the API is released?

**Comment by yadayada** [comment]
>So, to summarize, the Amazon Drive API does not allow a resumable multipart upload similar to the S3 API right now but it was announced and we can build something like this as soon as the API is released?

Let's say I will eat my hat if upload resumption ever gets implemented.

**Comment by philipp-spiess** [comment]
Hahaha! Thank you so much for the insight. I will close this issue and wait for you to eat your hat 😆
