### ISSUE TITLE
constant acdcli.api.backoff_req

### ISSUE THREAD

**Issue by theholyherb** [yadayada/acd_cli#512]
The last two days ive been getting constant Requesterror: 1000 messages and warnings for acdcli.api.backoff_req. It seems about half the time the files actually do upload even though it is errored out and stops before 100% and the other half of the time nothing uploads at all. Any suggestions?

**Comment by yadayada** [comment]
There is nothing that could be done about this, unfortunately. Please wait a bit, sync and re-execute the upload command.
