### ISSUE TITLE
Syntax Error:invalid syntax

### ISSUE THREAD

**Issue by Synopis** [yadayada/acd_cli#513]
python 3.5.2. Tried a couple of other things but nothing worked.

Ubuntu-1604-xenial-64-minimal:~# pip install --upgrade git+https://github.com/yadayada/acd_cli.git
Collecting git+https://github.com/yadayada/acd_cli.git
  Cloning https://github.com/yadayada/acd_cli.git to /tmp/pip-7tkrbz-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-7tkrbz-build/setup.py", line 8
        def read(fname: str) -> str:
                      ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-7tkrbz-build/

**Comment by yadayada** [comment]
You need to use the Python 3 version of pip, presumably pip3.
