### ISSUE TITLE
Initializing ACD with path "/home/pi/.cache/acd_cli".

### ISSUE THREAD

**Issue by Elfrederiko** [yadayada/acd_cli#515]
Hi Guys,

Can you change the directory where the "oauth_data" needs to be?
For example,    '/root/.cache/acd_cli/oauth_data'
<img width="353" alt="root directory" src="https://cloud.githubusercontent.com/assets/25183039/22036270/31a092c4-dcf3-11e6-8c08-0828e04a0db0.PNG">

In the documentation is "ACD_CLI_CACHE_PATH" mentioned, 
I tried ACD_CLI_SETTINGS_PATH=$/home/pi/.cache, but this did not work.
Any suggestions ?
Thanks in advance.

**Comment by yadayada** [comment]
Look up how to set an environment variable.
