### ISSUE TITLE
Errors mounting ACD drive

### ISSUE THREAD

**Issue by DerekLee13** [yadayada/acd_cli#520]
Getting this error trying to mount my ACD drive.  Really appreciate any help!

Traceback (most recent call last):
  File "/home/plex/.local/bin/acd_cli", line 7, in <module>
    from acd_cli import main
  File "/home/plex/.local/bin/acd_cli.py", line 24, in <module>
    from acdcli.cache import format, db
ImportError: cannot import name 'db'
Traceback (most recent call last):
  File "/home/plex/.local/bin/acd_cli", line 7, in <module>
    from acd_cli import main
  File "/home/plex/.local/bin/acd_cli.py", line 24, in <module>
    from acdcli.cache import format, db
ImportError: cannot import name 'db'

**Comment by yadayada** [comment]
Please test whether installing acd_cli into a virtualenv makes this error disappear.

**Comment by DerekLee13** [comment]
I have since determined that someone hacked into my box and started running a python based password cracker.  I'm going to do some work on this machine and figure out exactly what they did, but based on the logs when they hacked in, it coincides with the time that acd_cli stopped working.  If I have to, I'll wipe and reinstall the whole system to get back up and running again.  

FYI - here are the commands they used, if this helps give any ideas as to how to easily restore acd_cli when I can get back to this workstation later in the week:

python crack.py 10k.txt 200 0
cd smtp
chmod +x *

Thanks, yadayada.
