### ISSUE TITLE
Requests: make file size for s3 temporary download link configurable

### ISSUE THREAD

**Issue by scoopydude2002** [yadayada/acd_cli#521]
I notice my speed is much after when downloading from s3 temporary link (for me via s3-1-w.amazonaws.com) than regular downloads (via ec2-XXX-XXX-XXX-XXX.compute-1.amazonaws.com). I believe the current file size is set at >10GB for files to be downloaded via s3 temporary link. Can this size be made into a configurable variable?

**Comment by yadayada** [comment]
>I believe the current file size is set at >10GB for files to be downloaded via s3 temporary link.

I am fairly sure the acd_client does not choose to generate temp links and download from them.
