### ISSUE TITLE
cronjob

### ISSUE THREAD

**Issue by elPerstin** [yadayada/acd_cli#524]
Hi there
can't get my cronjob tu work, maybe any1 can help?

crontab -e:
`30 04 * * * bash /home/plex/acdsync.sh`

/home/plex/acdsync.sh:
```
acd_cli umount
acd_cli psync -r /
acd_cli mount /home/plex/encrypted
```

If I run the acdsync.sh by myself it works, not in cron.

**Comment by Grimeton** [comment]
Wrong user or ACD_CLI environment variables missing. 

Acdcli sync every five minutes anyway. Check the ini configuration docs for more information. 

Cu

**Comment by elPerstin** [comment]
shouldn't change the date of the nodes.db every 5 minutes?
![08-02-_2017_10-54-07](https://cloud.githubusercontent.com/assets/1962479/22732040/0caae69e-eded-11e6-858b-de27163530c9.png)

I will have a look into the ini-docs, thx anyway.

**Comment by Grimeton** [comment]
Hi,

Depends on the time you're looking at. Is this ctime, atime, mtime? Also keep in mind there's a write ahead log and SQLite does not always flush the log immediately. So a change to the main file mustn't necessarily happen. 

Also a sync from the outside gives you a high chance of a broken cache/bad address at the mount point. I don't recommend that. Bad experience ...

Cu

**Comment by elPerstin** [comment]
Well, if I'm running the mentioned script manually, the mtime is the same as my system time. but nevermind, only 1-2TB to go until updates on the acd-side will occur only ocassionally. I'll update manually, No big deal.

btw: couldn't ind any useful information in the docs (I think you're refering to [http://acd-cli.readthedocs.io/en/latest/configuration.html](url)?)

**Comment by Grimeton** [comment]
I'm refering to these docs: https://github.com/yadayada/acd_cli/blob/master/docs/configuration.rst

There's a "timeout_wait" mentioned which represents the time acdcli waits for the new file to appear on the aws side before it gets imported... It takes it's time until it's visible on aws.

And - my mistake - there's a minimum sync interval shown here: https://github.com/yadayada/acd_cli/blob/master/acd_cli.py#L77. Not sure if that's just the internal setting for times between manual syncs or if it's also the automatic syncing interval. But it looks a lot like it having a look at https://github.com/yadayada/acd_cli/blob/master/acd_cli.py#L260

Cu

**Comment by acs-ferreira** [comment]
Try
`30 04 * * */bin/bash /home/plex/acdsync.sh`

and
````
/usr/local/bin/acd_cli umount
/usr/local/bin/acd_cli psync -r /
/usr/local/bin/acd_cli mount /home/plex/encrypted
````

**Comment by elPerstin** [comment]
You saved me, good Sir! 

Thank you very much. :)

 

Von: Carlos Ferreira [mailto:notifications@github.com] 
Gesendet: Dienstag, 14. Februar 2017 08:11
An: yadayada/acd_cli <acd_cli@noreply.github.com>
Cc: Manuel Sychold <manuel@syccon.ch>; Author <author@noreply.github.com>
Betreff: Re: [yadayada/acd_cli] cronjob (#524)

 

Try
30 04 * * */bin/bash /home/plex/acdsync.sh

and

/usr/local/bin/acd_cli umount
/usr/local/bin/acd_cli psync -r /
/usr/local/bin/acd_cli mount /home/plex/encrypted
