### ISSUE TITLE
A lot of writes to the drive containing / and the mount point when copying a file

### ISSUE THREAD

**Issue by inquam** [yadayada/acd_cli#525]
Not actually an issue as much as a question.
If I mount the Amazon drive and copy a file to it. Will the file get streamed or will it be written locally first and then transferred? I tried copying a file of a few GB and using nmon I saw a lot of activity on my system drive containing / which is an SSD. I'd like to avoid that.
If this is actually happening and is not some anomaly due to the Amazon drive beeing located under /mnt/amazon, is there any way to choose the path of where to temporarily store the file?

**Comment by yadayada** [comment]
The data is streamed to Amazon Drive. 

Which command did you use to mount?

**Comment by inquam** [comment]
acdmount    /mnt/amazon    fuse    _netdev    0    0

in fstab

Might have been some other process that just happened to write at the same time that confused me then. Does this support resuming uploads of a file, appending to file etc?

**Comment by inquam** [comment]
p.s.

Also, there seems to be an error in the documentation.
https://acd-cli.readthedocs.io/en/latest/FUSE.html#automatic-remount

Claims the needed script for the mount to work is

```
#!/bin/bash

acd_cli mount -nl $1
```

I think it should be

```
#!/bin/bash

acd_cli -nl mount $1
```
