### ISSUE TITLE
Missing folders/files

### ISSUE THREAD

**Issue by shadycuz** [yadayada/acd_cli#530]
I just recently added a new host and want to upload to amazon cloud drive. I installed acdcli and uploaded 1 file as a test. I could see the file on both machines. I then proceeded to upload 100gb. I also used the -rsf flag =/ . Now my files were uploaded I can see them in the web gui but I can not see them on my other host. I have tried downgrading acd_cli and after  doing that I couldn't sync "no root node" so I ran old-sync. Which worked but still I can not find my files.

**Comment by yadayada** [comment]
I think if it spews out the "no root node found" you need to sync again until it succeeds.

**Comment by shadycuz** [comment]
Its something else, I'm using ENCFS to encrypt my files. I'm uploading from hosta and hostb to cloud drive and reading back the files on hosta. So sometimes I upload files from hostb and hosta can decrypt them and other times the files make it to the cloud drive but hosta can't decrypt them. I'm not sure what is going on. Something going wrong with the acd_cli upload that causing the files to change slightly and making the decryption fail with encfs? Haven't figured it out but I got about 6-8 hours of troubleshooting in to get this far.

**Comment by yadayada** [comment]
>Something going wrong with the acd_cli upload that causing the files to change slightly and making the decryption fail with encfs?

Let me report back when I have checked the files on your machines.

**Comment by shadycuz** [comment]
Oh that's really comforting, you need my private keys or do you already have that?
