### ISSUE TITLE
Mount two or more accounts 

### ISSUE THREAD

**Issue by esturniolo** [yadayada/acd_cli#538]
Hi.
There is a way to mount in different folders, differents accounts?

Example:
ACD Account
**_foo@mail.com_**
Mount Point
**_/mnt/foo_**

ACD Account
**_bar@anothermail.com_**
Mount Point
**_/mnt/bar_**

Sorry @yadayada if you answered this before, but I don't found any documentation with this.

Thanks

**Comment by yadayada** [comment]
You can utilize the [enviroment variables](https://acd-cli.readthedocs.io/en/latest/setup.html#environment-variables) for this purpose.

**Comment by esturniolo** [comment]
Thanks, but I can't realize where or how change the variable.

**Comment by yadayada** [comment]
Life is hard.

**Comment by esturniolo** [comment]
And you're are a winner.

**Comment by SchnorcherSepp** [comment]
example

ACD_CLI_SETTINGS_PATH=/etc/acd_cli ACD_CLI_CACHE_PATH=/var/cache/acd_cli /usr/local/bin/acd_cli -v init
ACD_CLI_SETTINGS_PATH=/etc/acd_cli ACD_CLI_CACHE_PATH=/var/cache/acd_cli /usr/local/bin/acd_cli psync /
ACD_CLI_SETTINGS_PATH=/etc/acd_cli ACD_CLI_CACHE_PATH=/var/cache/acd_cli /usr/local/bin/acd_cli mount --allow-other --interval 330 $MOUNTPOINT

**Comment by esturniolo** [comment]
Thanks @SchnorcherSepp!
