### ISSUE TITLE
Problem with downloading files

### ISSUE THREAD

**Issue by nonsindeads** [yadayada/acd_cli#547]
Version and System: Python 3.5.2
Linux-4.4.0-71-generic-x86_64-with-Ubuntu-16.04-xenial
Its a dedicated server with 1Gigabit bandwith
Firewall is not running atm

I am trying to download a folder with
sudo acd_cli download /Servers/ /mnt/
very often I become a message that downloading file XYZ is failed with request error connection aborted remote disconnected
and some time the download ist stopping with 0.0/s and needs a few seconds to go on.

Atm the download is running with --verbose an it looks like its running without problems... but the last 2 days without verbose mode it doesn't work.

Screenshot:
https://postimg.org/gallery/1mlqlrgf8/

**Comment by yadayada** [comment]
Sorry, I can't help you there.
