### ISSUE TITLE
RequestError 429 "Rate Exceeded"

### ISSUE THREAD

**Issue by drgroot** [yadayada/acd_cli#550]
#74 (same issue)

```
Syncing...
17-04-19 08:41:10.959 [ERROR] [acdcli.api.backoff_req] - Error getting node list.
17-04-19 08:41:10.966 [ERROR] [acd_cli] - RequestError: 429, {"message":"Rate exceeded"}
17-04-19 08:41:10.966 [CRITICAL] [acd_cli] - Sync failed.
```

I'm noticing this issue again. I have tried to register my security profile (but not respsonse from amazon)
I also cannot figure out how to install the 'google.appengine.api' module.

any tips?

**Comment by thenoahcomputer** [comment]
I'm fairly certain something is broken on Amazon's end.  I noticed this yesterday along with a variety of other unusual errors:
-"bad address" when writing to a mount (write access has been broken since yesterday for me)
-"url not found" and "rate exceeded" when syncing or doing anything with acd_cli
-some message about it being unable to get my quota and usage when mounting
-random dismounts
-sometimes syncing takes 3-4 attempts to complete
-clear-cache, re-auth, re-sync doesn't resolve it

**Comment by josefolhaoliveira** [comment]
same problem, since yesterday, 
and some uploaded files after upload became with 0 bytes in size
i even formated a new debian comuter, but same problem

**Comment by kelek-** [comment]
Same issue here as well. That has to be something on Amazons side. Let's all be patient and wait 👍

**Comment by 0x4D616E75** [comment]
Looks like you're right.
There are two entries in the amazon developer forum from today, which describe the same problem.

https://forums.developer.amazon.com/questions/67668/error-429-rate-exceeded-when-uploading-or-download.html

https://forums.developer.amazon.com/questions/67393/anyone-else-having-problems-uploading-stuff-i-keep.html

**Comment by drgroot** [comment]
so has this been resolved?

**Comment by 0x4D616E75** [comment]
Looks like amazon has fixed it. I get no "Rate exceeded" error since the last 40 minutes, but I get some "Connection reset by peer" errors.

Before this my Arq backup was also not working and this is now working.

**Comment by kelek-** [comment]
Its working for me for at least 4 hours again - can be closed 👍

**Comment by thenoahcomputer** [comment]
Confirmed working for me again as well

**Comment by kelek-** [comment]
Here we go again with:
`acd_cli sync
17-05-13 20:57:23.850 [CRITICAL] [acdcli.api.client] - Error getting endpoint data. Response: {"message":"Rate exceeded"}
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1646, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 46, in __init__
    self._load_endpoints()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 69, in _load_endpoints
    self._endpoint_data = self._get_endpoints()
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/client.py", line 80, in _get_endpoints
    raise Exception
Exception`

Amazon issues again? Can somebody confirm?

**Comment by thenoahcomputer** [comment]
Yep I'm getting this again when autosync runs:

`Getting changes17-05-13 15:00:36.986 [ERROR] [acd_cli] - Traceback (most recent call last):
  File "/usr/local/bin/acd_cli.py", line 273, in autosync
    sync_node_list(full=False)
  File "/usr/local/bin/acd_cli.py", line 149, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/metadata.py", line 51, in get_changes
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 429, [acd_api] no body received.
`
Given that #549 came up again at the same time just like the last time this happened, I think Amazon is having the similar issues again.

**Comment by kelek-** [comment]
Thanks for the confirmation!
So we can leave this closed I guess :)

**Comment by marekmkmk** [comment]
I've got the same issue

**Comment by ChoosenEye** [comment]
same here!

**Comment by devtrf** [comment]
Same here:

17-05-13 21:45:15.247 [CRITICAL] [acdcli.api.client] - Error getting endpoint data. Response: {"message":"Rate exceeded"}
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1582, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)

**Comment by HirschSt** [comment]
Same here ... seems to be an Amazon issue because I can't connect with the Android Amazon Drive App either

**Comment by tmanka** [comment]
Same here :-(

17-05-13 17:22:11.284 [CRITICAL] [acdcli.api.client] - Error getting endpoint data. Response: {"message":"Rate exceeded"}
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1645, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/client.py", line 46, in __init__
    self._load_endpoints()
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/client.py", line 69, in _load_endpoints
    self._endpoint_data = self._get_endpoints()
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/client.py", line 80, in _get_endpoints
    raise Exception
Exception

**Comment by qbert** [comment]
Same here
[ERROR] [acd_cli] - RequestError: 429, {"message":"Rate exceeded"}

**Comment by nycatelos** [comment]
I'm also having that issue.
17-05-13 22:49:12.708 [CRITICAL] [acdcli.api.client] - Error getting endpoint data. Response: {"message":"Rate exceeded"}

**Comment by gdragotto** [comment]
same

**Comment by petvas** [comment]
+1

**Comment by M0V3** [comment]
It's only acd_cli.
rclone for example works flawless

**Comment by yadayada** [comment]
See #416.
