### ISSUE TITLE
acd_cli upload error

### ISSUE THREAD

**Issue by Clefss** [yadayada/acd_cli#556]
This happened when I was trying to upload:

~$acd_cli upload motivos-influenciar-mudar-imagem-profissional-noticias.jpg /
17-05-12 13:32:34.044 [ERROR] [acd_cli] - Uploading "motivos-influenciar-mudar-imagem-profissional-noticias.jpg" failed. RequestError: 1000, HTTPSConnectionPool(host='content-na.drive.amazonaws.com', port=443): Read timed out. (read timeout=30).
[                         ]   0.0% of   28KiB  0/1     0.0B/s       0s
1 file(s) failed.

This error happens with all files.

**Comment by pink-mist** [comment]
Stop that. This isn't an issue with acd_cli, it clearly says that the error was that the *.drive.amazonaws.com timed out. Complain to Amazon.
