### ISSUE TITLE
Can't seem to be successful in authorising acd_cli again

### ISSUE THREAD

**Issue by Originn** [yadayada/acd_cli#559]
I have been trying to mount acd_cli on 16.04 ubuntu headless EC2. I have been successful on the first attempt, and the computer froze after trying to upload. I have created a new instance and tried to reinstall acd_cli, but now I get the following message after moving the oauth file to .cache/acd_cli.-

Press a key if you have saved the "oauth_data" file into "/root/.cache/acd_cli".

17-05-13 20:54:24.508 [CRITICAL] [acdcli.api.client] - Error getting endpoint data. Response: {"message":"Rate exceeded"}
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1646, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/client.py", line 46, in __init__
    self._load_endpoints()
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/client.py", line 63, in _load_endpoints
    self._endpoint_data = self._get_endpoints()
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/client.py", line 80, in _get_endpoints
    raise Exception
Exception

re installation does not help.

**Comment by emreuenal** [comment]
it is an amazon issue #550

**Comment by Boecki83** [comment]
yep same for me

**Comment by M0V3** [comment]
Wait some hours, maybe a day.
We had this the last time about 24 days ago and it is and amazon api problem.

**Comment by cpare** [comment]
Same here - this appears to be an Amazon issue as my setup has been working for weeks:
cpare@raspberrypi:~$ /usr/local/bin/acd_cli -v sync
17-05-13 18:56:29.567 [INFO] [acd_cli] - Plugin leaf classes: TestPlugin
17-05-13 18:56:29.569 [INFO] [acd_cli] - TestPlugin attached.
17-05-13 18:56:29.570 [INFO] [acd_cli] - Settings path is "/home/cpare/.config/acd_cli".
17-05-13 18:56:29.571 [INFO] [acd_cli] - Cache path is "/home/cpare/.cache/acd_cli".
17-05-13 18:56:29.579 [INFO] [acdcli.api.client] - Initializing ACD with path "/home/cpare/.cache/acd_cli".
17-05-13 18:56:29.588 [INFO] [acdcli.api.oauth] - AppspotOAuthHandler initialized
17-05-13 18:56:34.844 [INFO] [acdcli.cache.schema] - DB schema version is 2.
Getting changes17-05-13 18:56:34.849 [INFO] [acdcli.api.metadata] - Getting changes with checkpoint "CLKBx5fAKxoA".
17-05-13 18:56:34.850 [INFO] [acdcli.api.backoff_req] - POST "https://cdws.us-east-1.amazonaws.com/drive/v1/changes"
Traceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1680, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 774, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/local/bin/acd_cli.py", line 149, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/metadata.py", line 51, in get_changes
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 429, [acd_api] no body received.

**Comment by spuniun** [comment]
I am able to mount my ACD with rclone just fine so it doesn't appear to be an API issue one Amazon's end.

**Comment by M0V3** [comment]
Confirmed, rclone works.

**Comment by Harrdy** [comment]
same here, get "no body received." and "Rate exceeded" errors with acd but rclone still works

**Comment by ethanfel** [comment]
Hello, i can confirm the issue too.

"acdcli.api.common.RequestError: RequestError: 429, [acd_api] no body received.
17-05-14 09:34:06.223 [WARNING] [acdcli.acd_fuse] - Error getting account quota data. Cannot determine total and available disk space."

**Comment by scream88** [comment]
Same issues since yesterday evening :( Does everyone know, how to fix it? Maybe with a workaround?
Or do we really have to wait that Amazon fix it?

**Comment by madyoda** [comment]
It almost sounds like acd_cli got revoked. @yadayada ?

![image](https://cloud.githubusercontent.com/assets/5332144/26032589/e18d1d00-388e-11e7-87af-eff3c3467277.png)

**Comment by SchnorcherSepp** [comment]
maybe it's amazon reaction to 
https://github.com/yadayada/acd_cli/issues/549#issuecomment-301234895

**Comment by chrisgavin** [comment]
I wonder if you are right @SchnorcherSepp. It's possible they believe it to be an issue specific to acd_cli (I wonder if it could even be a caching bug in App Engine), and have cut off access. Either way, the fact they still aren't giving open access to the API makes this a bit of a pain. I'd be happy to use my own security profile if they'd damn well let me.

**Comment by madyoda** [comment]
@chrisgavin I guess we can ask @yadayada if they see anything in the Amazon console or w/e regarding the tensile-runway-92512.appspot.com.

**Comment by tintop2k** [comment]
rclone still appears to be working fine. It does look like Amazon have
suspended acdcli access while they look into the issue.

**Comment by Harrdy** [comment]
@tintop2k yea but not work so smooth like acd and i have a small issue with rclone. sometimes (mostly long videos, rarely tv series) i can't jump to other scene because plex tell me connection lost. Can you show me your mount command?

**Comment by zenjabba** [comment]
<style></style>

</head>
<body text=#000000 bgcolor=#ffffff>
<table border=0 cellpadding=2 cellspacing=0 width=100%>
<tr><td bgcolor=#3366cc><font face=arial,sans-serif color=#ffffff><b>Error</b></td></tr>
<tr><td>&nbsp;</td></tr></table>
<blockquote>
<H1>Over Quota</H1>
This application is temporarily over its serving quota.  Please try again later.

<p>
</blockquote>
<table width=100% cellpadding=0 cellspacing=0><tr><td bgcolor=#3366cc><img alt="" width=1 height=4></td></tr></table>
</body></html>

**Comment by AiMAnsarie** [comment]
Confirming the acd_cli error.

**Comment by Em31Et** [comment]
acd_cli used cache to minimize api call, but rclone spam API.
It is no sense to ban acd_cli.

**Comment by madyoda** [comment]
@Em31Et It does make sense to, atleast, temporarily ban acd_cli. See #549

**Comment by chrisgavin** [comment]
@Em31Et It seems likely the ban was due to the recently reported security concern (okay it was reported a while ago but it seems Amazon is only now paying attention). I can't really blame Amazon for protecting customer data first and asking questions later.

**Comment by tintop2k** [comment]
screen -d -m -S ACDMOUNT bash -c 'rclone mount --read-only --allow-other
--acd-templink-threshold 0 --stats 1s --buffer-size 1G --timeout 5s
--contimeout 5s -v --log-file=/home/plex/acdmount.log acd_remote:Media
/home/plex/.acd-sorted'

**Comment by zmwangx** [comment]
> It does make sense to, atleast, temporarily ban acd_cli.

My personal security profile, which should have nothing to do with acd_cli, also appears to be banned. Which makes no sense at all.

**Comment by madyoda** [comment]
@zmwangx Huh. This is interesting, because rclone isn't revoked. Does your security profile make any references to acd_cli?

**Comment by zmwangx** [comment]
The name is unfortunately acd_cli... But banning profiles based on the name sounds incredibly stupid.

**Comment by madyoda** [comment]
@zmwangx I agree, but maybe it's a blanket ban type situation until they figure out what exactly is causing #549 (possibly related) ?

**Comment by zmwangx** [comment]
It's my security profile used only for myself. They can easily verify who's signed in with that profile, so cross-contamination is impossible unless intentionally look into owning other people's files.

Also, anyone unaware of this project could have called their security profile acd_cli. It's not exactly an imaginative name.

**Comment by chrisgavin** [comment]
They can probably check which software was used to access ACD anyway given that acd_cli sets a custom user agent. It's possible they banned based on that. Seems stupid though, given that the method for using a custom security profile should prevent any access tokens or refresh tokens from leaving your machine.

**Comment by zmwangx** [comment]
Not a user agent issue. I commented out the user agent patching part. Same thing.

I'll try to manually issue authorization requests after lunch to make sure that my security profile is indeed banned. I'll report back (sorry about the spam in advance).

**Comment by zmwangx** [comment]
Oh I just realized @chrisgavin was talking about software that *was* used to access ACD with the custom user agent. Yeah that's possible.

**Comment by yadayada** [comment]
Please delete your oauth data and try again.
