### ISSUE TITLE
acd_cli does not link to the new authorisation site

### ISSUE THREAD

**Issue by nitschkecm** [yadayada/acd_cli#564]
Upgraded the stack on the computer but when running acd_cli init it still links to the previous site.

**Comment by beam** [comment]
you have to install from GH, or update site manualy

**Comment by giacomofabbri** [comment]
What does it mean exactly upgrade from GH?? 
I'm sorry I'm not an expert and I'm still trying to update ccdcli also to the latest revision as of today but with no success. If you can help me that would be greatly appreciated.
P.S. I'm on Ubuntu Server

**Comment by beam** [comment]
http://acd-cli.readthedocs.io/en/latest/setup.html
``pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git``

**Comment by giacomofabbri** [comment]
That's what I did! But then if I launch ccdcli init I get this error `acdcli init
Traceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1646, in main
    acd_client = client.ACDClient(CACHE_PATH, SETTINGS_PATH)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/client.py", line 43, in __init__
    self.handler = oauth.create_handler(cache_path)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 28, in create_handler
    return AppspotOAuthHandler(path)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 167, in __init__
    self.load_oauth_data()
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 99, in load_oauth_data
    self.get_auth_token(reload=False)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 117, in get_auth_token
    self.refresh_auth_token()
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/oauth.py", line 210, in refresh_auth_token
    'Error refreshing authentication token: %s' % response.text)
acdcli.api.common.RequestError: RequestError: 1004, Error refreshing authentication token: {
    "error": "HTTP Error 500: Internal Server Error", 
    "request:": "POST / HTTP/1.1\r\nAccept: */*\r\nContent-Length: 604\r\nContent-Type: application/x-www-form-urlencoded\r\nContent_Length: 604\r\nContent_Type: application/x-www-form-urlencoded\r\nHost: acd-api-oa.appspot.com\r\nUser-Agent: acdcli.api/0.9.3 python-requests/2.14.2\r\nX-Appengine-Country: ZZ\r\nX-Cloud-Trace-Context: b56c1ebb6f38d2c0993230cec0bfefad/15414710026851875428\r\n\r\nrefresh_token=Atzr%7CIwEBIB2J4Tycx1NX-s8WeUj--6aoFtelE-ORSB2wq25Bih7vzVKI0No_PSavX5naYsZbnw3HXCQ6D7w5SGzdw4qkPsC6nxqhYtMq6wBzab88TY37f-gjy22_Om6WxZJ4v5JkIO2bbuLp9ZKHGTa7oPd-Nb10Ij2hg6YnOg6vbWbnqg18H12jqdqVauEijbrOWT6dXzHzGLIQxqpc9DJdz94pSk7q2B9jrbIO8UfUG5VaUwVxoZZJgdEQ08mBELgxKQteJMLc4qPn8Eizx0NQdjn2nhLOmJpoir6FR9mbZMiSIOLlurwxAZb5Oms6i13kQ-dQOG6BzJwvzapTCMCEJEABd9fhIQbnoM6o5U5U3gtysEp7sIhvNc1KzCiO3NV07E9chWZE-4o4m-1H18o3vI41rqKVnJA3ejRK8BiAS4Zq5ixmNIWhamE3zZJ9iA6HfqNdKRBE5jO2f4YeakwYH0HLhvdfjO1vg6kj1CgasKmPeIssoQK5eNQuAl7DC-1k9xpIb16hgA5LeBVxfpRkAW2_LSL8jH4P44b3-ylB0UKc6HdPcVaDjkOEVV8SGsNVoYGNji4"
}`

**Comment by giacomofabbri** [comment]
I'm running headless if that may help!!

**Comment by beam** [comment]
I thinks Host: acd-api-oa.appspot.com is a new site, so refresh_token just doesn't work at this time.

**Comment by Tangoes** [comment]
@giacomofabbri

You must uninstall and then reinstall acdcli.

Pip upgrade does not work.

**Comment by Tangoes** [comment]
@giacomofabbri:

Please run `acd_cli delete-everything` first to delete your authentication and node data in the cache path. Then, use pip to uninstall

`pip3 uninstall acdcli`

and then, reinstall again from master branch using

`pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git`

and then run the authorization:

`acd_cli init`

**Comment by giacomofabbri** [comment]
I was finally able to install correctly the latest update! Thanks so much for all your help!

**Comment by D3473R** [comment]
Hi, is https://tensile-runway-92512.appspot.com/ down again?
![2017-06-07 13_35_53-error 404 page not found 1](https://user-images.githubusercontent.com/10356892/26876408-4efc4e2e-4b86-11e7-8c28-99e17d8c9cc5.png)
