### ISSUE TITLE
[ERROR] [acd_cli] - Root node not found. Sync may have been incomplete.

### ISSUE THREAD

**Issue by jxer** [yadayada/acd_cli#567]
after moving to the new auth and updating acd cli i now get this error on every initial sync

my scripting used to remove everything in .cache prior to a sync minus the auth file. this worked fine for months.
if i rerun the sync command without deleting anything it then syncs very quickly with no error.

anyone?

**Comment by jxer** [comment]
now getting this without deleting just syncing.

Getting changesTraceback (most recent call last):
  File "/usr/local/bin/acdcli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acdcli')()
  File "/usr/local/bin/acd_cli.py", line 1680, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 774, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/local/bin/acd_cli.py", line 149, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/local/lib/python3.4/dist-packages/acdcli/api/metadata.py", line 51, in get_changes
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 401, [acd_api] no body received.

**Comment by tintop2k** [comment]
Why would you delete your database before every sync?

The oauth_data file has been renamed to oauth.json. Are you taking that
into account when deleting?

**Comment by jxer** [comment]
and now 

17-05-26 11:18:58.969 [CRITICAL] [acdcli.api.client] - Error getting endpoint data. Response: {"message":"Token has expired"}

**Comment by jxer** [comment]
@tintop2k 
it use to be a cleaner way back when acd cli wouldn't always see all the files rclone uploaded

**Comment by Tangoes** [comment]
@jxer start with this:

Please run `acd_cli delete-everything` first to delete your authentication and node data in the cache path. Then, use pip to uninstall

`pip3 uninstall acdcli`

and then, reinstall again from master branch using

`pip3 install --upgrade git+https://github.com/yadayada/acd_cli.git`

and then run the authorization:

`acd_cli init`

To ensure that everything is OK, if you type

`acd_cli version`

you should get:

`acd_cli 0.3.2, api 0.9.3 
`

Then, sync.

`acdcli sync`

After No root node found error, sync again:

`acdcli sync`

And wait 5 minutes if asked.

Every time you delete database, the no root node error will raise up.

**Comment by jxer** [comment]
@Tangoes
"Then, sync.

acdcli sync

After No root node found error, sync again:

acdcli sync

And wait 5 minutes if asked.

Every time you delete database, the no root node error will raise up."

is this new behavior? it never use to do this

and it cleared up all the other errors on its own

**Comment by jxer** [comment]
is it no longer recommend to delete the db anymore before sync? this use to be standard practice

**Comment by Tangoes** [comment]
@jxer I´ve never deleted the DB before sync. I had this "missing root node" months ago, and now, every time I need to delete db. If you don´t, no errors are shown.

**Comment by jxer** [comment]
@Tangoes why are you needing to delete the db?

**Comment by Tangoes** [comment]
@jxer Well, I told it a bad way. I never need to delete de DB. I just wanted to say:

I had this "missing root node" months ago, and now, every time I delete the db. If you don´t, no errors are shown.

**Comment by yadayada** [comment]
>is it no longer recommend to delete the db anymore before sync? this use to be standard practice

Please don't delete your node cache when the sync is incomplete, that just puts you at risk for another incomplete sync. Just re-issue the sync action (without the -f flag) once or twice.

**Comment by fnkr** [comment]
First time user here. Same problem. Running current master (d7a9a3b8372316df3563507b499e10394eb34ce0).
```
$ env/bin/acd_cli mount ~/acd
17-05-27 11:16:23.404 [CRITICAL] [acd_cli] - Root node not found. Please sync.
$ env/bin/acd_cli sync
Getting changes..............................................................................................................................
Inserting nodes.............................................................................................................................
17-05-27 11:19:31.574 [ERROR] [acd_cli] - Root node not found. Sync may have been incomplete.
```

**Comment by Tangoes** [comment]
@fnkr as said before, just type 

acdcli sync

And problem solved.

**Comment by fnkr** [comment]
@Tangoes Uhm, that's what I've been doing. The result was getting this error message. Did you read the log I've posted (especially the last 4 lines)? :)

**Comment by tintop2k** [comment]
Keep running the sync command until it completes. You don't need to remove
the database just sync.
