### ISSUE TITLE
Difficulties for initial configuration of Acd_cli

### ISSUE THREAD

**Issue by ricardoclaus** [yadayada/acd_cli#570]
Dear,
I'm setting up the ACD_CLI for the first time in Centos7.
When I run the command below, it tells me that it is necessary to authenticate via browser. But the URL that appears does not open anything (https://tensile-runway-92512.appspot.com).
Then I arrived at this URL and managed to generate the token: https://acd-api-oa.appspot.com/
An oauth.json file has been generated. I copied in /root/.cache/acd_cli/
However, every time I run the command "acd_cli init", it displays the message saying that it needs to authenticate via browser.

What am I doing wrong ?

**Comment by yadayada** [comment]
If you are using the PyPI variant, you need switch to use the GitHub one. If not, you need to upgrade.

**Comment by ricardoclaus** [comment]
I just renamed the file:
# mv oauth.json oauth_data

The message requesting token no longer appears.
Apparently it's working

I installed acd_cli like this:
# pip3 install --upgrade --pre acdcli

# acd_cli version
acd_cli 0.3.2, api 0.9.0

Am I using the correct version?
How do I know if I'm using the PyPI variant?
