### ISSUE TITLE
No Body Received

### ISSUE THREAD

**Issue by danyderigon** [yadayada/acd_cli#573]
Hi !

Since a few hours I've got this error when I do "acd_cli sync"
`Getting changesTraceback (most recent call last):
  File "/usr/local/bin/acd_cli", line 9, in <module>
    load_entry_point('acdcli==0.3.2', 'console_scripts', 'acd_cli')()
  File "/usr/local/bin/acd_cli.py", line 1691, in main
    ret = args.func(args)
  File "/usr/local/bin/acd_cli.py", line 785, in sync_action
    ret = sync_node_list(args.full, args.to_file, args.from_file)
  File "/usr/local/bin/acd_cli.py", line 149, in sync_node_list
    file=to_file if to_file else None)
  File "/usr/local/lib/python3.5/dist-packages/acdcli/api/metadata.py", line 51, in get_changes
    raise RequestError(r.status_code, r.text)
acdcli.api.common.RequestError: RequestError: 429, [acd_api] no body received.`

Do you know how to fix it ?
I try to refresh my token, acd_cli init, ... nothing works.

**Comment by Kuchenpirat** [comment]
Same here...

**Comment by triwing** [comment]
Same error here. Seems to be related with this error: https://github.com/yadayada/acd_cli/issues/572

**Comment by Kedryn** [comment]
Expandrive is also getting this error and not working.

**Comment by kkna9877** [comment]
Seems to be an annual issue originating with Amazon, see https://github.com/yadayada/acd_cli/issues/328

**Comment by solracsf** [comment]
More probably related to https://github.com/yadayada/acd_cli/issues/572#issuecomment-305517129

**Comment by yadayada** [comment]
Same as #572.
