### ISSUE TITLE
404 after acd_cli init

### ISSUE THREAD

**Issue by ikrai** [yadayada/acd_cli#575]
Hi,

I am not sure whether this is to be reported here, but the page [https://tensile-runway-92512.appspot.com](https://tensile-runway-92512.appspot.com) displayed by `acd_cli init` gives me a 404 error.
I understand acd_cli is working again, but could not find anyone reporting the same issue after a fresh install. I am on Ubuntu 16.04 using acd_cli 0.3.2 and api 0.9.0.

Thanks in advance for your help!

**Comment by Jomenvisst** [comment]
I have the same issue. All I get when opening https://tensile-runway-92512.appspot.com  at first init, is a 404 page.

**Comment by ebouda33** [comment]
Acdcli doesn t work anymore 
It Was end
