### ISSUE TITLE
Mounting hangs

### ISSUE THREAD

**Issue by alex036** [yadayada/acd_cli#60]
Just want to preface this by saying amazing job with acd_cli yadayada. It's working great and the addition of FUSE will be amazing. I also understand it's very experimental so if this isn't fully implemented yet I understand.

While playing around trying to mount it somewhere, it's hanging right after
` [DEBUG] [requests.packages.urllib3.connectionpool] - "GET /drive/v1/account/quota HTTP/1.1" 200 135`
I'm getting a `reply: 'HTTP/1.1 200 OK\r\n'` right before it.

I'm using Ubuntu 14.04. Please let me know if you need any more logs.

**Comment by yadayada** [comment]
Have you checked it is actually hanging? It is supposed to block.

![ub1404](https://cloud.githubusercontent.com/assets/4608955/7952356/9db0009e-09b4-11e5-831d-894301c03344.png)

**Comment by alex036** [comment]
I wasn't putting python3 in front of acd_cli.py which fixed it. Looks like my mnt dir is in read-only mode, but I'm able to delete files.

`ubuntu@ip-xxx:~/mnt/Documents$ cp ~/100mb.file .`
`cp: cannot create regular file ‘./100mb.file’: Read-only file system`

**Comment by yadayada** [comment]
That is the expected behaviour for now.
