### ISSUE TITLE
Upload problems with Python 3.2.3

### ISSUE THREAD

**Issue by jwanglof** [yadayada/acd_cli#61]
I'm trying to upload a folder containing a lot of RAW (.pef) picture files (the folder is about 4GB in total size) and I keep getting error messages like these:
```
15-06-05 11:27:03.136 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:27:40.610 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:28:20.238 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:28:20.252 [WARNING] [acdcli.api.common] - Waiting 6.502539s because of error(s).
15-06-05 11:28:27.088 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:29:08.401 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:29:11.714 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:29:11.719 [WARNING] [acdcli.api.common] - Waiting 12.377117s because of error(s).
15-06-05 11:30:02.016 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:30:02.022 [WARNING] [acdcli.api.common] - Waiting 41.907783s because of error(s).
15-06-05 11:30:44.474 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:31:17.511 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:31:17.525 [WARNING] [acdcli.api.common] - Waiting 233.880961s because of error(s).
15-06-05 11:35:11.969 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:35:11.980 [WARNING] [acdcli.api.common] - Waiting 230.623471s because of error(s).
15-06-05 11:39:26.844 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:39:26.858 [WARNING] [acdcli.api.common] - Waiting 72.633123s because of error(s).
15-06-05 11:40:39.908 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:40:39.917 [WARNING] [acdcli.api.common] - Waiting 228.244669s because of error(s).
15-06-05 11:45:01.570 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
15-06-05 11:45:01.582 [WARNING] [acdcli.api.common] - Waiting 173.578258s because of error(s).
```

**Comment by yadayada** [comment]
It seems like you did not use pip to install.
Please tell me your
* operating system and its version,
* Python version,
* requests version
* urllib3 version

Does this happen on this directory only? I also would like to see a debug log for a single failed file.

**Comment by jwanglof** [comment]
That's true, I installed the packages via apt-get.

Info about the server:
* Debian 7.6
* Python 3.2.3
* Python3-requests: According to "apt-cache showpkg python3-requests": 2.0.0.1
* Python3-urllib3: According to "apt-cache showpkg python3-urllib3": 1.7.1.1

This is what I get when I try to upload a file:
15-06-05 15:02:42.703 [ERROR] [acd_cli] - data should be a bytes-like object or an iterable, got <class 'acdcli.bundled.encoder.MultipartEncoder'>
[#################################] 100.0% of    7MiB  1/1  290.4KB/s
1 file(s) failed.

**Comment by yadayada** [comment]
There seems to be some strange issue with requests-toolbelt and the Python 3.2.6 httplib (https://github.com/sigmavirus24/requests-toolbelt/issues/88).

If you can upgrade to Python 3.4, you might want to try that first.

Alternatively, there is an old version still uses curl that should work
https://github.com/yadayada/acd_cli/tree/f13aaa90c199e8be5bd5285430297035dffc9f7a

**Comment by sigmavirus24** [comment]
So requests-toolbelt has a lower-limit set on the version of requests that it accepts. That version is `2.0.1` further, `2.0.0.1` is not a version that requests ever installed.

**Comment by yadayada** [comment]
I can reproduce this on a Debian wheezy live CD with requests 2.7.0. But it is Python 3.2.3, actually.

**Comment by yadayada** [comment]
I think this will be a permanent issue.
