### ISSUE TITLE
Upgrade error (windows cp1252)

### ISSUE THREAD

**Issue by sasotepina** [yadayada/acd_cli#64]
version a116bee7c6ebdd089a627b3c4938165ed742c489
windows 7

```
C:\acd_cli-master>pip3 install --upgrade .
Processing c:\acd_cli-master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\stepina\AppData\Local\Temp\pip-9u835hhy-build\setup.py", li
ne 19, in <module>
        long_description=read('README.rst'),
      File "C:\Users\stepina\AppData\Local\Temp\pip-9u835hhy-build\setup.py", li
ne 8, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5819:
 character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\stepina\
AppData\Local\Temp\pip-9u835hhy-build
```
also similar error on "tree" or "children" when file or folder contains unicode character
```
Traceback (most recent call last):
  File "C:\acd_cli-master\acd_cli.py", line 1065, in <module>
    main()
  File "C:\acd_cli-master\acd_cli.py", line 1061, in main
    sys.exit(args.func(args))
  File "C:\acd_cli-master\acd_cli.py", line 675, in children_action
    print(entry)
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u010d' in position 44: character maps to <undefined>
```
upload and download works fine.

**Comment by yadayada** [comment]
The first error is easily fixable.

Regarding the second problem, after much consideration, I came to the conclusion that it is not the script's or Python's resposibility to set the proper output encoding.  (As it is, the encoding should have been set to UTF-8 and there should be erroneous replacement characters. Why this does not work on your installation, I don't know. I only test [irregularly] on Windows 8.1.)
 
Your system's default encoding is set to CP1252. Yet, there is no _č_ in CP1252. Your locale should have been set to CP1250.

If you want to set all consoles to CP65001 (which sort of corresponds to UTF-8) by default, put the following code in a `.reg` file and execute it. This will change your console font and default codepage.
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
"FaceName"="Lucida Console"
"CodePage"=dword:0000fde9

```
[Again, tested on Windows 8.1 only. Works for me™.]

**Comment by sasotepina** [comment]
Ok, thanks. Changed the locale. Works fine now.
