### ISSUE TITLE
Upload time out

### ISSUE THREAD

**Issue by Issam2204** [yadayada/acd_cli#68]
This happened when I was trying to upload a snapshot of 2.2 GB : 

```
issam@HP250G3:~/Backups$ acd_cli.py upload HP250G3-13-06-15_09-44.tar.gpg /Snapshots/'HP 250 G3'

Syncing...
Done.

15-06-13 11:38:38.844 [ERROR] [acd_cli] - Uploading "HP250G3-13-06-15_09-44.tar.gpg" failed. Code: 1000, msg: ('Connection aborted.', timeout('The write operation timed out',))
[                                 ]   0.0% of    2GiB  0/1 -492.3MB/s
1 file(s) failed.
```

The upload reached 40% .ca before timing out. My current upload bandwidth is 2.5 Mbits/s. The upload is not present on Amazon Cloud Drive.

**Comment by yadayada** [comment]
Well, that is an connection error and out of my sphere of influence. This can happen if the internet connection goes down, the IP address changes or, less likely, if a server error occurs.

**Comment by jbuchbinder** [comment]
I've been seeing issues like this intermittently with files over 8-9GB in size uploading at about 1.0 MB/s. The connection definitely isn't dropping. I'm getting something like this:

```
15-08-26 17:30:58.317 [ERROR] [acd_cli] - Uploading "BMPC4k01_1_2015-04-07_1503_C0001.mov" failed. Code: 1000, msg: HTTPSConnectionPool(host='content-na.drive.amazonaws.com', port=443): Read timed out. (read timeout=60)
```

(I'm reading this over a CIFS mounted share on a Linux box, if that makes any difference.)

**Comment by kiding** [comment]
I believe this is an actual issue. It has been impossible for me to upload any _considerably big_ (>1GB) files. It probably is simple network error; given my packets should travel across the Pacific ocean. I reckon we need a way to _continue_ uploading, rather than wait-and-retries which also fail.

**Comment by kiding** [comment]
I’ve tested a little bit more on this, with the settings as below.
```
[transfer]
connection_timeout = 172800
idle_timeout = 172800
```
```
[upload]
timeout_wait = 2880
```

After around 10 minutes of upload, the process _hangs_ at 0B/s. Might need to dig deep into the stack.
```
16-10-11 16:05:36.028 [INFO] [acd_cli] - Uploading /Volumes/4TB/test.mp4
16-10-11 16:05:36.113 [INFO] [acdcli.api.backoff_req] - POST "https://content-na.drive.amazonaws.com/cdproxy/nodes"
16-10-11 16:05:36.137 [INFO] [requests.packages.urllib3.connectionpool] - Starting new HTTPS connection (1): content-na.drive.amazonaws.com
[#######################  ]  95.2% of    2GiB  0/1     0.0B/s       0s
```

**Comment by kiding** [comment]
Making the same request with cURL shows the server returns `504 GATEWAY_TIMEOUT` after 10m of continuous write. Without an API support, maybe chunk, it would probably very difficult to solve this issue.

```
*   Trying 52.6.157.183...
* Connected to content-na.drive.amazonaws.com (52.6.157.183) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: content-na.drive.amazonaws.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=Washington,L=Seattle,O=Amazon.com\, Inc.,CN=content-na.drive.amazonaws.com
* 	 start date: Thu, 08 Sep 2016 00:00:00 GMT
* 	 expire date: Sat, 21 Oct 2017 23:59:59 GMT
* 	 issuer: C=US,O=Symantec Corporation,OU=Symantec Trust Network,CN=Symantec Class 3 Secure Server CA - G4
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> POST /cdproxy/nodes HTTP/1.1
> Host: content-na.drive.amazonaws.com
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer ...
> Content-Length: 9359589701
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------5a850fa8679a311c
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 504 GATEWAY_TIMEOUT
< Content-Length: 0
< Connection: keep-alive
* HTTP error before end of send, stop sending
< 
* Closing connection 0

real	11m2.427s
user	6m38.976s
sys	1m55.816s
```

**Comment by ianling** [comment]
It looks like some people working on rclone have found a way to resume uploads. I can confirm that when this 504 timeout error occurs, the file DOES at least partially exist on my ACD, the filename just gets a dot prepended to it, which causes it to appear to be hidden in Linux, and then it also appears to get a random string appended to the end of the file name. I'm not sure if this string can be found in the request. You can also view these temporary files in the ACD web interface.

From what I can tell, this is the whole file, I'm trying to download it now, and then I will compare an MD5 hash of this hidden file with the MD5 hash of the original file to see if they match.

This temporary file disappears at some point. I'm not sure if this occurs after a sync or what, but they do disappear after some time.

Anyway, see https://github.com/ncw/rclone/issues/87

**Comment by ianling** [comment]
Also, just as an example, I tried to upload a large file, and it failed several times with the same timeout error being discussed in this thread. This left 3 of those hidden files in my upload directory:

    -rwxrwxrw- 1 ianl ianl   794340157 Sep  2  2016 .file.1IjFeS
    -rwxrwxrw- 1 ianl ianl   794340157 Sep  2  2016 .file.6m1CSR
    -rwxrwxrw- 1 ianl ianl   794340157 Sep  1  2016 .file.sxyYyB

And when it finally successfully uploaded:

    -rwxrwxrw- 1 ianl ianl 794340157 Sep  2  2016 file

Each of those temporary files is the full file.

I think acd_cli could easily be updated to at least detect that the file has been fully uploaded, despite the timeout error, and then simply rename the temporary file.

**Comment by yadayada** [comment]
@ianling Is this an issue with FUSE or rsync, specifically?

**Comment by ianling** [comment]
Oh, duh, I was using rsync to transfer the files to the FUSE mount. That explains the randomized file extensions; rsync does that!

I'm not sure how the `acd_cli upload` command handles transfers on the backend. Does it just POST the files to the API? That would explain why I don't see these temporary files on my ACD when I use that command.

Just to be very clear as to how I'm uploading:

1. acd_cli mount ~/acd
2. rsync --progress ~/my_file ~/acd/

rsync never reports any kind of timeouts or errors, but will very frequently leave behind these temporary files, indicating that the transfer didn't complete for some reason. I did just confirm that these files are complete and match my hashes of the originals though, so I'm not sure why only the very end of the transfer, where the temporary file gets renamed to the real file name, is failing to happen.

**Comment by yadayada** [comment]
I think the --inplace flag will stop rsync from creating these hidden files in the first place.

**Comment by ianling** [comment]
Just tried that, and it looks like instead of leaving behind the full temporary files when something goes wrong, now it leaves behind an empty file with the correct file name, so I'm not sure where all the data I just uploaded went...

**Comment by ianling** [comment]
Interestingly, it looks like rsync does report some errors, I just wasn't seeing them because I wasn't logging rsync output, and I was running it in a screen, so the screen would die as soon as rsync finished.

rsync will give one of two errors (sometimes both):

    rsync: open "/home/ianl/acd/file" failed: Connection timed out (110)
    rsync: ftruncate failed on "/home/ianl/acd/file": Function not implemented (38)

However, these errors appear to be meaningless, because sometimes, even if a file successfully transfers, I'll still get an error, and when a file fails to transfer for some reason, sometimes it will only get the ftruncate error. There doesn't seem to be any pattern to the errors.

Anyway, running rsync with the --inplace flag doesn't seem to have helped, and may have actually made it worse because it doesn't leave behind the temporary files anymore when an upload fails, so I can't manually rename them. If an upload failed while I'm using the --inplace flag, it simply leaves an empty file with the correct name on ACD.

I'm going to verify that a temporary file is ALWAYS created when an upload fails and you are not using the --inplace flag. If that is the case, then at least I will have a workaround for failed rsync uploads.
