### ISSUE TITLE
stream data to ACD?

### ISSUE THREAD

**Issue by wdenx** [yadayada/acd_cli#75]
is there some way to stream data to the ACD, i. e. something like

tar -cf - * | acd_cli upload --filename myfiles.tar.gz

Thanks in advance,

wd

**Comment by yadayada** [comment]
After a lot of fiddling, I put something up https://github.com/yadayada/acd_cli/tree/dev

The syntax is as follows ``cat furchtbar | acdcli stream actualname /path/``, similar to a single-file upload.
