### ISSUE TITLE
acd_cli vs acd_fuse

### ISSUE THREAD

**Issue by cpare** [yadayada/acd_cli#78]
What are the differences between acd_cli and acd_fuse?
  From what I am seeing:
     - acd_fuse allows r/w access to acd while acd_cli is r/o
     - acd_cli is still being actively developed, while acd_fuse seems a little stale

Is there value in merging these two?

**Comment by karloluiten** [comment]
acd_cli works

**Comment by cpare** [comment]
I am confused about the R/W or R/O functionality, I see lots of information about uploading data but the description still reads "acd_cli provides a command line interface to Amazon Cloud Drive and allows mounting your cloud drive using FUSE for read access. It is currently in beta stage." - is this just in need of an update?

**Comment by karloluiten** [comment]
Fuse was just added to acd_cli. The purpose of acd_cli is *command line* access to acd. So you can do `./acd_cli ul file`. See USAGE in the readme.

Fuse is an addition to the acd_cli module. It is expirimental. And yes, at this moment it does not allow uploading. But FUSE is just an extra interface to your data, not the main interface.

**Comment by cpare** [comment]
gotcha - thanks for the extra information - I have a 1.5tb volume I want to rsync with acd to have an off-site replica.  I will certainly be installing it tonight and watching for the fuse activity!

**Comment by karloluiten** [comment]
Yeah that is what you would want then. Let's wait together ;)
