### ISSUE TITLE
Ability to permanently delete 

### ISSUE THREAD

**Issue by Linwood-F** [yadayada/acd_cli#79]
This is a question, or maybe a request for confirmation, not a bug.

I installed this last night on ubuntu 15.04 and it installed and worked fine - kudos. 

My intent was to use this to archive security camera  footage stills, but a part of that would be to periodically purge them so they do not grow infinitely.  

In brief experimenting, and looking in the SDK, it would appear there is no support for a permanent delete, is that correct?   I tried remove a few times and could not actually see that it did anything. 

This would mean manually deleting (emptying the trash) from a web browser, which (at least at first glance) can only be done 1000 images at a time, wait, manually delete some more.

Am I correct that Amazon is imposing this limitation? 

The only workaround I can see is to (outside of your tool, or maybe I can use the same sync'd database) keep track of everything uploaded, and instead of deleting do an update instead of new upload.  Or update and rename perhaps. 

Thank you for doing this tool , very helpful.

**Comment by yadayada** [comment]
That's correct, it is not possible to empty the trash or delete nodes using the REST API.

You may want to contact the Cloud Drive API support at clouddrive-api-support@amazon.com to let them know you want the ability to purge nodes added.

For easier deletion, I recommend that you use folders.

**Comment by Linwood-F** [comment]
Thanks, I rather thought it was an amazon issue.

**Comment by yadayada** [comment]
Some day, if I ever get bored, I might add a webscraper that uses the web interface to implement a purge action.

**Comment by neumachen** [comment]
What's the news on this? It's stupid. My storage space consumption is like 80% because of the trash node and I can only delete 3000 items at any given time while having 213K items in trash.
