### ISSUE TITLE
10GB file size limit

### ISSUE THREAD

**Issue by pimodege** [yadayada/acd_cli#8]
Failure:
```
root@linux:~/.acd# ./acd_cli.py upload /root/12.9GB.file /
Current file: /root/12.9GB.file
[##################################################] 100.00% of 12.9GiB
Uploading "12.9GB.file" failed. Code: 504, msg: {"message": "[acd_cli] no body received."}
```
Success:
```
root@linux:~/.acd# ./acd_cli.py upload 10GB.file /                           
Current file: /root/10GB.file
[##################################################] 100.00% of 10.0GiB
```
I've repeated the experiment several times. Is this a client or service limitation?

**Comment by yadayada** [comment]
It seems that the files get stored anyway; just an internal timeout occurs while Amazon processes the uploaded file for the node metadata that normally would get sent after the upload is finished.

I've uploaded a 17.4GB file, got a 504 error, then synced, compared the local and remote hash and they matched.
So there appears to be no real limitation on the upload file size.

Have you tried immediately uploading a large file twice? E.g.
``./acd_cli.py upload /root/12.9GB.file /; ./acd_cli.py upload /root/12.9GB.file /``
This should (hopefully) skip on the second upload attempt.

**Comment by smehernosh** [comment]
I'm facing this same issue and I'm unable to download files that have had this error shown while uploading.

I tried downloading from the web UI but couldn't download the file, tried downloading using acd_cli.py  and I got,

    Downloading [node id] failed.
    Downloading "file" failed. Code: 500, msg: {"message":"Internal failure"}

    Hash mismatch between local and remote file for "file"    

I tried listing metadata for the file and got the templink, when I tried opening the templink I got the same error, "{"message":"Internal failure"}"

**Comment by yadayada** [comment]
I believe Amazon is currently working on these issues.

**Comment by yadayada** [comment]
**Update**: There seems to be a way to access large files, because [NetDrive](http://www.netdrive.net) can do it.

**Comment by smehernosh** [comment]
Nope I'm facing problems with Netdrive also when downloading large files.

http://support.netdrive.net/forums/251857-bug-or-error/suggestions/7599042-2-5-beta-7-i-o-device-error-on-almost-file-copy-co

I guess we'll have to wait for Amazon to fix this

**Comment by yadayada** [comment]
I was able to stream a >10GiB file using NetDrive, so it should theoretically be possible to download them as well.

**Comment by smehernosh** [comment]
I think the limit is 14gb as mentioned here:

https://forums.developer.amazon.com/forums/thread.jspa?threadID=5034&tstart=0

**Comment by Issam2204** [comment]
Also for me:

>issam@localhost:~/Files$ du -ch output.dat 
15G	output.dat
15G	total
issam@localhost:~/Files$ acdu upload output.dat /
Current file: output.dat
[#################################] 100.0% of   14.6GiB,   19.5MB/s
15-05-05 11:35:42.632 [acd_cli] [WARNING] - Timeout while uploading "%s".
issam@localhost:~/Files$ acdu upload output.dat /
Current file: output.dat
[                                 ]   0.0% of   14.6GiB,  169.2KB/s
15-05-05 11:41:32.862 [acd_cli] [ERROR] - Uploading "output.dat" failed. Name collision with non-cached file. If you want to overwrite, please sync and try again.
issam@localhost:~/Files$

I tried, as you can see, to re-upload the file and indeed it gives me an error (which is good). If I look at the webapp the file is there.

**Comment by chrisidefix** [comment]
To add my experience - so far the largest file I managed to upload was sized 40.8 GB.
I tried with 100 GB and 142 GB - both failed with time-out messages. For other files with this error, usually the file was uploaded anyway, but for these admittedly very large files, it didn't work and I am not too keen on trying this over and over.

I guess I could split them, which should also make the download easier again.

**Comment by yadayada** [comment]
It was briefly possible to download files >10GiB using ranged requests. I did implement this and it worked. But apparently, Amazon deliberately put an end to this. NetDrive also cannot stream such files anymore.

I think it is time to look for another web storage.

**Comment by procmail** [comment]
So this isn't a bug serverside, but perhaps a policy restriction?

**Comment by chrisidefix** [comment]
I contacted them through phone support and was directed towards the "technical team" as the support person did not know of any such restrictions. I am waiting to hear back from them, but so far there is no "file size limitation" policy to be found on the website. The funny part is that I now cannot download files I previously was able to upload. Hopefully, this is a temporary problem as the error message suggests:
`{"message":"Currently unsupported file size."}`

**Comment by Issam2204** [comment]
Thanks chrisidefix!

Please let us know ;)

**Comment by chrisidefix** [comment]
Official Amazon Customer Service response:

> We've worked with developers from the Cloud Drive Web team and the Cloud Drive Service team to figure out what's going on. Presently there is an issue with downloading large file sizes. We are actively pursuing a resolution to this issue. In the meantime, you should try to keep your file sizes less than 10GB. Files that you have uploaded that are larger than the current limitation will continue to be kept safely in storage, but are not able to be downloaded until we are able to resolve the underlying issue. 

> As soon as we have an idea on a time frame for this problem to be fixed we'll be sure to let know.

**Comment by HazCod** [comment]
Any updates on this matter?

**Comment by yadayada** [comment]
The current limit is somewhat above 9GiB, I believe. It is unknown whether this limit is final or not; hopefully, we'll know more next month.

https://forums.developer.amazon.com/forums/thread.jspa?threadID=5240&tstart=0
>Currently, we are actively working on improving our upload/download limits, and we should have a fix in place by early next month. Regardless, we are currently verifying what our new limits will be, so please hang tight.

>Regards,

>Jamie

**Comment by karloluiten** [comment]
As a workaround I split all my uploads into 9GB parts, that works well.

**Comment by procmail** [comment]
I have 33GB, 21GB and 19GB zip files uploaded by the official client.



-- 
Eric Boo

**Comment by HazCod** [comment]
The official client is not limited by the API file size limit.

**Comment by yadayada** [comment]
@procmail 
It's possible (and pretty likely) you won't be able to download your large files later. Even if the upload file size limit is higher, it is not advisable to upload large files (as stated by Amazon's customer service) until there is no official statement about size limitations.

@HazCod 
The last time I checked (in May), it was not possible to download files larger than 10GiB using the official client; but at that time it was possible to access them using NetDrive or download them using acd_cli. The necessary chunked download feature was consequently removed in early May, reinstated a week later and then removed again in June. 

So, based on my prior test, I assume the official client is subject to the same limitations. Did you verify that it isn't?

**Comment by HazCod** [comment]
@yadayada I was always told this, but i'm afraid I have not tested this myself yet.

**Comment by procmail** [comment]
It wasn't possible for me to upload big files the last time I tested the official client, which was a month ago I think. 

I will test downloading a big file when I have time, and report back.

**Comment by Issam2204** [comment]
I've tested uploading 1TB file and the upload went smooth until 100%. It took me almost 24h and I was fairly impressed to discover no issues during the upload time. However, (as expected) upon reaching 100% it failed giving me "Code: 400, msg: {"message":"Cannot complete upload"}".

![untitled1](https://cloud.githubusercontent.com/assets/8282518/8397012/36a1d482-1dbd-11e5-94da-162fea026700.png)

**Comment by smehernosh** [comment]
They've increased the file size limit. I was able to download a 32gb archive and extract it successfully. 

Guess you can close this now.

**Comment by yadayada** [comment]
I've noticed the change. But there still is no official comment on this matter. I also was able to download a large file using the web interface. But surely, there still must be some size limit. It would be nice if someone could ascertain the new limit.

**Comment by chrisidefix** [comment]
I did receive a customer support mail 5 days ago, but they didn't specify any specific limit either - only that I should now be able to download large files. Guess it's time for a large file test-run :o:

**Comment by Issam2204** [comment]
I tried yesterday to upload a 15GB, 50GB and 100GB files. All failed because of internal failure (error code 500). I tried this with 2 different dedicated servers located in different datacenters. The failures happens at the end of the upload.

Has anyone been able to upload large files?

**Comment by smehernosh** [comment]
I uploaded a 32gb archive and I did get the same error but I was able to download the file and extract it  successfully.

**Comment by chrisidefix** [comment]
Yes, I was able to upload archives at 42 GB size. I also see the same error, but the files still show up on my cloud drive. However, when I tried much larger files, it also didn't work. I might try again, though, in case Amazon improved anything on their end.

**Comment by ShapeShifter499** [comment]
Hmm weird issue guys, so is it advisable to chunk the files that are to be uploaded, maybe with chunkfs?

**Comment by chrisidefix** [comment]
@Issam2204 I remember you telling me to use "split, gnupg and acd_cli" and "Call them with a script", maybe that will solve your problems :-1: 

@ShapeShifter499 I suggest we take another look at issue #32, where I proposed splitting very large files for upload ...

**Comment by ShapeShifter499** [comment]
@chrisidefix alright

**Comment by yadayada** [comment]
Soooo... the actual limit is 50G(i)B.
https://forums.developer.amazon.com/forums/thread.jspa?threadID=4610

**Comment by Sunako** [comment]
Well, at least it is sorta defined now. 50G seems reasonable enough IMO.

**Comment by yadayada** [comment]
Since the limit is now know and the timeout errors are documented in the README.rst, I will close this issue.
