### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by msh100** [yadayada/acd_cli#80]
I have quite erratic throughput with acd_cli and suspect it is as I am using it from within Europe. I would like to attempt to proxy traffic through a US server I know I have a reliable connection to.

Is there any proxy support currently implemented? If not, this would be a nice feature - also because of:

> The Service is offered in the United States. We may restrict access from other locations.

I can understand their reasoning and I am sure many people would be willing to pay for the traffic between the US and elsewhere.

**Comment by msh100** [comment]
I took at look at http://docs.python-requests.org/en/latest/user/advanced/#proxies and seems like the `HTTP_PROXY` environment variable can be defined. When I try to do this with `acd_cli sync` though there's no effect.

```
$ HTTP_PROXY="http://xxx.xxx.xxx.xxx:8888/" acd_cli sync
Syncing...
Done.
$ export HTTP_PROXY="http://xxx.xxx.xxx.xxx:8888/"
$ acd_cli sync
Syncing...
Done.
```

Watching tcpdump on `xxx.xxx.xxx.xxx` shows absolutely no traffic. I guess this method simple does not work in the way I am trying it.

**Comment by yadayada** [comment]
Please try again with the HTTPS_PROXY environment variable set.

Alternatively, you might want to try adding your proxy setting directly to
https://github.com/yadayada/acd_cli/blob/master/acdcli/api/common.py#L222

**Comment by msh100** [comment]
fwiw I am now writing at 20MBps with a proxy. It improved the throughput substantially.
