### ISSUE TITLE
Trouble installing to virtualenv

### ISSUE THREAD

**Issue by elonen** [yadayada/acd_cli#87]
I'm trying to install acd_cli to a python virtualenv, so I don't have to fix it every time the system (Debian) updates Python packages. Unfortunately, it terminates to the followin error: `error: could not create '/usr/lib/python3.4/site-packages': Permission denied`

Is this a bug with acd_cli's pip packagin(?) or with my system? (Sorry, I'm not very familiar with inner working of pip / virtualenv.)

The commands I've been running to get the error are (as a regular user, not root):

    $ source bin/activate
    $ pip3 install --upgrade acdcli

**Comment by elonen** [comment]
The complete log:


    source bin/activate
    # This file must be used with "source bin/activate" *from bash*
    # you cannot run it directly

    deactivate () {
        unset pydoc

        # reset old environment variables
        if [ -n "$_OLD_VIRTUAL_PATH" ] ; then
            PATH="$_OLD_VIRTUAL_PATH"
            export PATH
            unset _OLD_VIRTUAL_PATH
        fi
        if [ -n "$_OLD_VIRTUAL_PYTHONHOME" ] ; then
            PYTHONHOME="$_OLD_VIRTUAL_PYTHONHOME"
            export PYTHONHOME
            unset _OLD_VIRTUAL_PYTHONHOME
        fi

        # This should detect bash and zsh, which have a hash command that must
        # be called to get it to forget past commands.  Without forgetting
        # past commands the $PATH changes we made may not be respected
        if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
            hash -r 2>/dev/null
        fi

        if [ -n "$_OLD_VIRTUAL_PS1" ] ; then
            PS1="$_OLD_VIRTUAL_PS1"
            export PS1
            unset _OLD_VIRTUAL_PS1
        fi

        unset VIRTUAL_ENV
        if [ ! "$1" = "nondestructive" ] ; then
        # Self destruct!
            unset -f deactivate
        fi
    }

    # unset irrelevant variables
    deactivate nondestructive

    VIRTUAL_ENV="/home/jarno/bin/acd_cli"
    export VIRTUAL_ENV

    _OLD_VIRTUAL_PATH="$PATH"
    PATH="$VIRTUAL_ENV/bin:$PATH"
    export PATH

    # unset PYTHONHOME if set
    # this will fail if PYTHONHOME is set to the empty string (which is bad anyway)
    # could use `if (set -u; : $PYTHONHOME) ;` in bash
    if [ -n "$PYTHONHOME" ] ; then
        _OLD_VIRTUAL_PYTHONHOME="$PYTHONHOME"
        unset PYTHONHOME
    fi

    if [ -z "$VIRTUAL_ENV_DISABLE_PROMPT" ] ; then
        _OLD_VIRTUAL_PS1="$PS1"
        if [ "x" != x ] ; then
            PS1="$PS1"
        else
        if [ "`basename \"$VIRTUAL_ENV\"`" = "__" ] ; then
            # special case for Aspen magic directories
            # see http://www.zetadev.com/software/aspen/
            PS1="[`basename \`dirname \"$VIRTUAL_ENV\"\``] $PS1"
        else
            PS1="(`basename \"$VIRTUAL_ENV\"`)$PS1"
        fi
        fi
        export PS1
    fi
    basename "$VIRTUAL_ENV"
    basename "$VIRTUAL_ENV"

    alias pydoc="python -m pydoc"

    # This should detect bash and zsh, which have a hash command that must
    # be called to get it to forget past commands.  Without forgetting
    # past commands the $PATH changes we made may not be respected
    if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
        hash -r 2>/dev/null
    fi

    #Disabled - currently fails to compile/install?
    #pip install --upgrade git+https://github.com/yadayada/acd_cli.git

    pip3 install --upgrade acdcli
    Downloading/unpacking acdcli
      Running setup.py (path:/tmp/pip-build-ywdnnu52/acdcli/setup.py) egg_info for package acdcli
        
    Downloading/unpacking appdirs (from acdcli)
      Downloading appdirs-1.4.0-py2.py3-none-any.whl
    Downloading/unpacking python-dateutil from https://pypi.python.org/packages/any/p/python-dateutil/python_dateutil-2.4.2-py2.py3-none-any.whl#md5=c817289a1d95a355cc088e2292791a77 (from acdcli)
    Requirement already up-to-date: requests>=2.1.0 in /usr/lib/python3/dist-packages (from acdcli)
    Downloading/unpacking requests-toolbelt (from acdcli)
      Downloading requests_toolbelt-0.4.0-py2.py3-none-any.whl
    Downloading/unpacking sqlalchemy (from acdcli)
      Running setup.py (path:/tmp/pip-build-ywdnnu52/sqlalchemy/setup.py) egg_info for package sqlalchemy
        
        warning: no files found matching '*.jpg' under directory 'doc'
        warning: no files found matching '*.mako' under directory 'doc'
        warning: no files found matching 'distribute_setup.py'
        warning: no files found matching 'sa2to3.py'
        warning: no files found matching 'ez_setup.py'
        no previously-included directories found matching 'doc/build/output'
    Requirement already up-to-date: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->acdcli)
    Installing collected packages: acdcli, appdirs, python-dateutil, requests-toolbelt, sqlalchemy
      Running setup.py install for acdcli
        changing mode of build/scripts-3.4/acd_cli.py from 644 to 755
        error: could not create '/usr/lib/python3.4/site-packages': Permission denied
        Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-ywdnnu52/acdcli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nhdma3qe-record/install-record.txt --single-version-externally-managed --compile:
        running install

    running build

    running build_py

    creating build

    creating build/lib

    creating build/lib/acdcli

    copying acdcli/fuse.py -> build/lib/acdcli

    copying acdcli/__init__.py -> build/lib/acdcli

    creating build/lib/acdcli/utils

    copying acdcli/utils/threading.py -> build/lib/acdcli/utils

    copying acdcli/utils/progress.py -> build/lib/acdcli/utils

    copying acdcli/utils/hashing.py -> build/lib/acdcli/utils

    copying acdcli/utils/__init__.py -> build/lib/acdcli/utils

    creating build/lib/acdcli/plugins

    copying acdcli/plugins/template.py -> build/lib/acdcli/plugins

    copying acdcli/plugins/__init__.py -> build/lib/acdcli/plugins

    creating build/lib/acdcli/cache

    copying acdcli/cache/sync.py -> build/lib/acdcli/cache

    copying acdcli/cache/query.py -> build/lib/acdcli/cache

    copying acdcli/cache/format.py -> build/lib/acdcli/cache

    copying acdcli/cache/db.py -> build/lib/acdcli/cache

    copying acdcli/cache/__init__.py -> build/lib/acdcli/cache

    creating build/lib/acdcli/bundled

    copying acdcli/bundled/fuse.py -> build/lib/acdcli/bundled

    copying acdcli/bundled/encoder.py -> build/lib/acdcli/bundled

    copying acdcli/bundled/__init__.py -> build/lib/acdcli/bundled

    creating build/lib/acdcli/api

    copying acdcli/api/trash.py -> build/lib/acdcli/api

    copying acdcli/api/oauth.py -> build/lib/acdcli/api

    copying acdcli/api/metadata.py -> build/lib/acdcli/api

    copying acdcli/api/content.py -> build/lib/acdcli/api

    copying acdcli/api/common.py -> build/lib/acdcli/api

    copying acdcli/api/account.py -> build/lib/acdcli/api

    copying acdcli/api/__init__.py -> build/lib/acdcli/api

    running build_scripts

    creating build/scripts-3.4

    copying and adjusting acd_cli.py -> build/scripts-3.4

    changing mode of build/scripts-3.4/acd_cli.py from 644 to 755

    running install_lib

    creating /usr/lib/python3.4/site-packages

    error: could not create '/usr/lib/python3.4/site-packages': Permission denied

    ----------------------------------------
    Cleaning up...
    Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-ywdnnu52/acdcli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nhdma3qe-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-ywdnnu52/acdcli
    Storing debug log for failure in /home/jarno/.pip/pip.log

**Comment by elonen** [comment]
Turns out the culprit was a an old version of `virtualenv`. I created one with `/usr/bin/pyvenv-3.5 acd_cli` and now it works with both pip repository version and the github version.

**Comment by yadayada** [comment]
Maybe I'm just reiterating what you just said, but I had to specify the correct python3 executable for virtualenv like so:

```bash
virtualenv -p /usr/bin/python-3.4 acd_dir
```
