### ISSUE TITLE
Pipe data for upload

### ISSUE THREAD

**Issue by hongkongkiwi** [yadayada/acd_cli#88]
im really keen to use something like the dd (along with GZip) and pipe the output directly to Amazon Cloud Drive. This way I can create weeks clones of my hard drive and take advantage of the unlimited space.

It would be great if I could do this, right now I have to pipe it to a file and when the file is finished then upload that. It's definitely not ideal since I require a lot of space to do it this way. If I could simply pipe it to the upload feature that would be amazing! 

For example:

cat dog.jpg > acd_cli upload /dog.jpg

**Comment by yadayada** [comment]
This is very similar to feature request #75.
