### ISSUE TITLE
Upload only new files

### ISSUE THREAD

**Issue by kylehayes** [yadayada/acd_cli#9]
If I run the upload command a second time on the same set of directories, will all the uploads be replaced or will only new and changed files be updated?

**Comment by yadayada** [comment]
Folder syncing is not yet implemented. If the upload command is run a second time, only new local files will be uploaded. 
There is an `--overwrite` option which allows overwriting of smaller remote files. As this is not very sensible, I will change it in the next commit to overwrite remote files with a lower modification time.
For the meantime, the `--force` option should overwrite everything.

**Comment by kylehayes** [comment]
Sounds good. I just started using it a few days ago and its working great so far for what I need it. Thank you for starting this project.

**Comment by yadayada** [comment]
The upload overwriting should now (218a39268385677039e11639202d3f7192a163f3) work if a local file has a) a higher modification date or b) a higher ctime and different file size.

Case b should hopefully catch file movements (in UNIX) where a local file is overwritten with a file that has a lower modification date.

Note that the system clock should be accurate so the file system's timestamps are accurate.

**Comment by kylehayes** [comment]
:+1: thank you!

**Comment by chrisidefix** [comment]
Relating to my question #21 wouldn't it make sense to compare the file-hash value? And then compare the file name. For example, if I rename a 10GB file, it would be great to detect that it only was renamed and thus doesn't need to be uploaded again.
