### ISSUE TITLE
Re-mount on boot?

### ISSUE THREAD

**Issue by hongkongkiwi** [yadayada/acd_cli#90]
Is it possible to use fstab to automount the fuse filesystem on boot?

If not I have a shell script which can do it automatically (run it as an init.d script), but it seems much more elegant to have it from fstab. I'm just not exactly clear how fuse works in the low level compared to normal filesystems such as NFS.

**Comment by HazCod** [comment]
Could you just not put it in a crontab with `@reboot` ?

**Comment by hongkongkiwi** [comment]
That's definitely possible. I've tried Init scripts but not crontab.

Thanks for the suggestion.

On Thursday, July 16, 2015, HazCod <notifications@github.com> wrote:

> Could you just not put it in a crontab with @reboot ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yadayada/acd_cli/issues/90#issuecomment-121896656>.
>


-- 
Sent from Gmail Mobile

**Comment by LtRipley36706** [comment]
@reboot /usr/local/bin/acd_cli mount /path/to/mount/to

worked for me on Ubuntu 14.04.2, crontab -e

**Comment by yadayada** [comment]
I'm closing this if nobody minds.

**Comment by vampywiz17** [comment]
Hello,

I try to 

@reboot /usr/local/bin/acd_cli mount /home/nsuto/amazon --allow-other

but not working... any idea?

**Comment by seppi91** [comment]
@vampywiz17 unfortunately i've got no solution for this but I'm also faced with this issue when running the mount command with --allow-other

**Comment by yadayada** [comment]
@vampywiz17, @seppi91 My guess is that it fails because your network interface isn't yet up. You should try to prepend a sleep command and append a redirect for the script's output to a logfile.
```
@reboot /bin/sleep 30; /usr/local/bin/acdcli mount /mount/path >> /path/to/log/log.txt 2>&1
```

**Comment by seppi91** [comment]
@yadayada Thx, that's it :+1:

**Comment by vampywiz17** [comment]
Now is working well!!

I mount it `sudo crontab` so i copy the acd_cli folder to `/root/.cache`.

**Comment by hongkongkiwi** [comment]
Hi there, I wanted to re-open this.

Why do I want to mount via fstab? Because I have other fstab mounts which rely on acd_cli to be up and running, so by putting it in fstab I can put them in order.

My solution is ofcourse to put all the mounts in crontab, but that relies on the connection being up and other factors first, whereas in fstab that's all handled for me.

Is it straight forward to allow mounting via fstab?

**Comment by yadayada** [comment]
The easiest way is with a simple shell script, placed into /usr/bin/acdmount:
```bash
#!/bin/sh
acd_cli mount $1
```

You'll have to add the options to the command in the script because there is no support for options via ``-o`` (#173).

Then, add to your fstab
```
acdmount	/mount/point	fuse	defaults	0	0
```

**Comment by hongkongkiwi** [comment]
That's absolutely perfect thanks!!

**Comment by sedlund** [comment]
Suggest the fstab line be like below so systemd will have networking started before attempting to mount.

acdmount    /mount/point    fuse    _netdev   0   0
