### ISSUE TITLE
Adding ACD_CLI to the Arch Linux User Repository

### ISSUE THREAD

**Issue by ShapeShifter499** [yadayada/acd_cli#91]
Hi,

This issue is more of a convenience issue and not a issue with the program itself. I'm wondering if this package could be added to the Arch Linux User Repository, you or I could create the package.

**Comment by yadayada** [comment]
I am not an Arch user. Anyway, since I have no experience in packaging for any distro, feel free to create a package for the AUR.

**Comment by ShapeShifter499** [comment]
Ok I finally uploaded a copy of the package to the AUR https://aur4.archlinux.org/packages/acd_cli-git/      It installs everything under /usr/bin if that's alright.   The URL I provided will change after August 8th because they are migrating from AUR3 to AUR4, in which the URL should be  https://aur.archlinux.org/packages/acd_cli-git/  

```
[lance@Arch-Chromebook ~]$ which acd_cli
/usr/bin/acd_cli
[lance@Arch-Chromebook ~]$ which acdcli 
/usr/bin/acdcli
[lance@Arch-Chromebook ~]$ which acd_cli.py 
/usr/bin/acd_cli.py
[lance@Arch-Chromebook ~]$ 
```

**Comment by ShapeShifter499** [comment]
If you look on that AUR page you will see the dependencies I added to the package, any that shouldn't really be included?  I noticed you said dateutils and requests-toolbox are recommended but optional, I wasn't sure if I should too make those two packages optional on the AUR.

**Comment by yadayada** [comment]
Thanks for creating the package. Regarding the dependencies, keep them if they are already there. I might remove the bundled modules at some point. 

AUR even has a requests-toolbelt; color me impressed.

**Comment by ShapeShifter499** [comment]
I'm glad everything looks ok. FYI the python-requests-toolbelt is already a officially approved package in the default repo. So it's better than a AUR package.

**Comment by yadayada** [comment]
Seems like this can be closed. I will include information on the AUR package once I write up a few lines in a separate document on packaging/installation.
