### ISSUE TITLE
Follow softlinks

### ISSUE THREAD

**Issue by Stapper** [yadayada/acd_cli#95]
acd_cli doesn't seem to follow softlinks, it just uploads the link file.
As hard links are not possible to direct to a directory, and mounting the folders in a centralised folder seems like an ugly hack.

Is it possible to let acd_cli follow softlinks, this way I can create a folder "AmazonTransfer" and just link files I want to have uploaded there.

**Comment by msh100** [comment]
I guess the solution here would be to run [realpath](https://docs.python.org/2/library/os.path.html#os.path.realpath) on each file. However some people may want to upload symlinks so it may be worth adding this as a flag.

**Comment by chrisidefix** [comment]
What about recursive self-including links? Will `realpath` deal with this sufficiently or would we also have to safeguard against endless recursion?

I can see the appeal of having an "AmazonTransfer" folder, but you could also just write a script that runs `acd_cli.py` a couple of times for each folder pair you would like to upload.

Example bash-script:

```bash
python3 acd_cli.py s
python3 acd_cli.py ul -x 4 /mnt/external_drive/foo /Backup
python3 acd_cli.py ul -x 4 ~/Documents/bar /Documents
python3 acd_cli.py ul -x 4 ~/Pictures /
```

**Comment by yadayada** [comment]
For me, it follows symbolic links, but doesn't seem to preserve the link name for directories.

So, with a dir structure
```
bar/
bar/foo -> ../baz
baz/
baz/gorgonzola -> ../cheddar
cheddar
```

``acdcli ul bar /`` will create ``/bar``, ``/bar/baz`` and ``/bar/baz/gorgonzola``

Which operating system are you using?

**Comment by Stapper** [comment]
I was using Debian 7 with python 3.2.
I have since updated, and cannot recreate the issue.
